# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(
      app_identifier: ["pro.vocably.Vocably"],
      platform: "macos",
      additional_cert_types: "mac_installer_distribution"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    certificates
    increment_build_number(xcodeproj: "Vocably.xcodeproj")
    build_app(scheme: "Vocably")
    upload_to_testflight
  end
end
