import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'QYQDj',
    created: 1736995234809,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: 'naˈzaːhatun',
      example: 'احترامُ المرءِ مقرونٌ بنزاهتِهِ.',
      definition: 'الابتعادُ عنِ السّوءِ والأعمالِ الدّنيئةِ',
      translation: 'ईमानदारी',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kTJGD',
    created: 1736995254068,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: 'sˤuˈmuːdun',
      example: 'يُعرفُ القويُّ بصمودِهِ أمام المصاعبِ.',
      definition: 'ثباتٌ وعدمُ التّحرّكِ',
      translation: 'स्थिरता, अडिगता',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-Z2N-',
    created: 1736995282326,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: 'ʕaˈtabatun',
      example: 'عتبَةُ البيتِ عاليةٌ.',
      definition: 'خشبةُ البابِ الّتي يوطأُ عليها',
      translation: 'दरवाज़े की चौखट',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'YiQmK',
    created: 1736995292768,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: 'taˈsˤarrafa',
      example: 'تصرّفَ الموظّفُ بصورةٍ لائقةٍ.',
      definition: 'قامِ بفعلِ ما يشاءُ',
      translation: 'व्यवहार करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HKc7Z',
    created: 1736995311916,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: 'inʕiˈkaːsun',
      example: 'كانَ لرحيلها انعكاسٌ كبيرٌ على حياتهِ.',
      definition: 'إرتدادٌ إلى الوراءِ أو بزاويةٍ ما',
      translation: 'परावर्तन',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ng_Gz',
    created: 1736995331074,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: 'ħaˈsˤiːlatun',
      example: 'حصيلةُ أرباحِ الفنادقِ قليلةٌ.',
      definition: 'ما بقيَ وثبتَ منَ الشّيءِ بعدَ ذهابِ ما سواهُ',
      translation: 'बचत, निष्कर्ष',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3w-cN',
    created: 1736995359254,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: 'ˈqarra',
      example: 'قرَّ رأيُ اللّجنةِ على إعادةِ الانتخاباتِ.',
      definition: 'ثبتَ واستقرَّ على قرارٍ',
      translation: 'स्थिर होना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0ESPc',
    created: 1736995378457,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: 'iʕˈtabara',
      example:
        '* يعتبرُ الحكيمُ مكانةَ العلماءِ.\n* يعتبرُ العاقلُ منْ أخطاءِ غيرهِ.',
      definition:
        '* إِعتدَّ بالأمرِ واحترمهُ\n* إِتّعَظَ منَ التّجربةِ وأخذها عبرةً',
      translation: 'मानना, गंभीरता से लेना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tJqGQ',
    created: 1736995389638,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: 'kurˈsijjun',
      example: 'جلسَ المتعبُ على الكرسيِّ.',
      definition: 'مقعدٌ لجلوسِ شخصٍ واحدٍ مصنوعٌ منْ خشبٍ أوْ نحوِهِ',
      translation: 'कुर्सी',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'uZkKq',
    created: 1736995408856,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: 'ˈbarrara',
      example: 'برّرتِ التّلميذةُ عدمَ تقدّمها للاختباراتِ السّنويّةِ.',
      definition: 'أعطى تفسيرًا وشرحًا لما قامَ بهِ',
      translation: 'व्याख्या करना, स्पष्टीकरण देना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'frZ0R',
    created: 1736995428130,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: 'ˈʔahmala',
      example: 'أهملَ الكسولُ واجباتهِ.',
      definition: 'تركَ الأمرَ ولم يهتمَّ فيهِ',
      translation: 'उपेक्षा करना, अनदेखा किया',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_J0vO',
    created: 1736995456130,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: 'ˈʔaqnaʕa',
      example: 'أقنَعتُهُ بالحِوارِ.',
      definition: 'جعلَ فلانًا يسلّمُ بالأمرِ عنْ رضًا',
      translation: 'राजी करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3WgHa',
    created: 1736995457054,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'क्रमशः',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_dZIE',
    created: 1736995466807,
    data: {
      language: 'ar',
      source: 'ضَمْنًا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'शामिल',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CCMBi',
    created: 1736995476479,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'विशेष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Q-Nh0',
    created: 1736995495730,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: 'ˈħaːlan',
      example: 'سأتناولُ غرضًا منَ السَّيَّارةِ وأَعودُ حَالًا.',
      definition: 'تَوًّا وَدُونَ تَأْخِيرٍ',
      translation: 'तुरंत, अभी',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HcoiC',
    created: 1736995505213,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लगभग',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SS8cY',
    created: 1736995515002,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'पर्याप्त रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RDqdV',
    created: 1736995525986,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: 'muˈθaːbirun',
      example: 'لكي تنجحَ عليكَ أن تكونَ مثابِرًا.',
      definition: 'من يعملُ بنشاطٍ',
      translation: 'परिश्रमी',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'f-H0i',
    created: 1736995545084,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: 'ˈʃaːmilun',
      example: 'حقّقَ المحقّقُ بالجريمةِ بشكلٍ شاملٍ.',
      definition: 'محيطٌ بجميعِ النّواحي',
      translation: 'समग्र, व्यापक, समावेशी',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FS-TQ',
    created: 1736995564341,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: 'ˈmumtiʕun',
      example: 'شاهدْتُ فيلمًا ممتعًا في السّينما.',
      definition: 'يبعثُ الفرحَ والتّسليّةَ في النّفسِ',
      translation: 'मनोरंजक',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-rb6X',
    created: 1736995592567,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: 'ˈħaðarun',
      example: 'يجبُ الحذرُ من لمسِ الكهرباءِ.',
      definition: 'حرصٌ وانتباهٌ تجاهَ الأمورِ',
      translation: 'सावधानी, चेतावनी',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Jf1KR',
    created: 1736995602765,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'आलसी',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9w1D8',
    created: 1736995621967,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: 'ˈbaːrizun',
      example: 'ابنُ خلدونِ عالمٌ بارزٌ في علمِ الاجتماعِ.',
      definition: 'واضحٌ للعيانِ',
      translation: 'स्पष्ट, उजागर',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
