import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Y53LC',
    created: 1736998904760,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: 'naˈzaːhatun',
      example: 'احترامُ المرءِ مقرونٌ بنزاهتِهِ.',
      definition: 'الابتعادُ عنِ السّوءِ والأعمالِ الدّنيئةِ',
      translation: 'uczciwość, integralność',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BK1k9',
    created: 1736998906032,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: 'sˤuˈmuːdun',
      example: 'يُعرفُ القويُّ بصمودِهِ أمام المصاعبِ.',
      definition: 'ثباتٌ وعدمُ التّحرّكِ',
      translation: 'stałość, wytrwałość',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IuLqF',
    created: 1736998907278,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: 'ʕaˈtabatun',
      example: 'عتبَةُ البيتِ عاليةٌ.',
      definition: 'خشبةُ البابِ الّتي يوطأُ عليها',
      translation: 'progu',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KBM6m',
    created: 1736998908752,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: 'taˈsˤarrafa',
      example: 'تصرّفَ الموظّفُ بصورةٍ لائقةٍ.',
      definition: 'قامِ بفعلِ ما يشاءُ',
      translation: 'zachować się, postępować',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'j38D0',
    created: 1736998910157,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: 'inʕiˈkaːsun',
      example: 'كانَ لرحيلها انعكاسٌ كبيرٌ على حياتهِ.',
      definition: 'إرتدادٌ إلى الوراءِ أو بزاويةٍ ما',
      translation: 'odbicie',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0SCBd',
    created: 1736998911308,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: 'ħaˈsˤiːlatun',
      example: 'حصيلةُ أرباحِ الفنادقِ قليلةٌ.',
      definition: 'ما بقيَ وثبتَ منَ الشّيءِ بعدَ ذهابِ ما سواهُ',
      translation: 'wynik',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7IA-X',
    created: 1736998913048,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: 'ˈqarra',
      example: 'قرَّ رأيُ اللّجنةِ على إعادةِ الانتخاباتِ.',
      definition: 'ثبتَ واستقرَّ على قرارٍ',
      translation: 'osiedlić się, ustanowić się',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1OHBr',
    created: 1736998914346,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: 'iʕˈtabara',
      example:
        '* يعتبرُ الحكيمُ مكانةَ العلماءِ.\n* يعتبرُ العاقلُ منْ أخطاءِ غيرهِ.',
      definition:
        '* إِعتدَّ بالأمرِ واحترمهُ\n* إِتّعَظَ منَ التّجربةِ وأخذها عبرةً',
      translation: 'uważać, brać pod uwagę',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zXHwy',
    created: 1736998915627,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: 'kurˈsijjun',
      example: 'جلسَ المتعبُ على الكرسيِّ.',
      definition: 'مقعدٌ لجلوسِ شخصٍ واحدٍ مصنوعٌ منْ خشبٍ أوْ نحوِهِ',
      translation: 'krzesło',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0tGF9',
    created: 1736998917422,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: 'ˈbarrara',
      example: 'برّرتِ التّلميذةُ عدمَ تقدّمها للاختباراتِ السّنويّةِ.',
      definition: 'أعطى تفسيرًا وشرحًا لما قامَ بهِ',
      translation: 'uzasadnił',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ISyv4',
    created: 1736998919255,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: 'ˈʔahmala',
      example: 'أهملَ الكسولُ واجباتهِ.',
      definition: 'تركَ الأمرَ ولم يهتمَّ فيهِ',
      translation: 'zaniedbać',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H-PQK',
    created: 1736998921198,
    data: {
      language: 'ar',
      source: 'قنع',
      ipa: 'ˈqannaʕa',
      example: 'قنّعَ المحقّقُ الشّاهدَ على قولِ ما رأى.',
      definition: '* جعلَ فلانًا يقتنعُ\n* رضيَ بما لَهُ ولوْ كانَ قليلًا',
      translation: 'przekonać, zadowolić się',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_IokE',
    created: 1736998922320,
    data: {
      language: 'ar',
      source: 'تدريجياً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'stopniowo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vWAsv',
    created: 1736998923871,
    data: {
      language: 'ar',
      source: 'ضمنا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'włącznie',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3B_kv',
    created: 1736998924894,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'w szczególności',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yPT3q',
    created: 1736998926385,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: 'ˈħaːlan',
      example: 'سأتناولُ غرضًا منَ السَّيَّارةِ وأَعودُ حَالًا.',
      definition: 'تَوًّا وَدُونَ تَأْخِيرٍ',
      translation: 'natychmiast, teraz',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'brtpu',
    created: 1736998927491,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prawie',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'j3XMR',
    created: 1736998928484,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'wystarczająco',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'j2IDj',
    created: 1736998929965,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: 'muˈθaːbirun',
      example: 'لكي تنجحَ عليكَ أن تكونَ مثابِرًا.',
      definition: 'من يعملُ بنشاطٍ',
      translation: 'pracowity, wytrwały',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C3irM',
    created: 1736998931479,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: 'ˈʃaːmilun',
      example: 'حقّقَ المحقّقُ بالجريمةِ بشكلٍ شاملٍ.',
      definition: 'محيطٌ بجميعِ النّواحي',
      translation: 'wszechstronny, kompleksowy',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'A9oAj',
    created: 1736998933110,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: 'ˈmumtiʕun',
      example: 'شاهدْتُ فيلمًا ممتعًا في السّينما.',
      definition: 'يبعثُ الفرحَ والتّسليّةَ في النّفسِ',
      translation: 'zabawny, przyjemny, ciekawy',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TPX_t',
    created: 1736998936912,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: 'ˈħaðarun',
      example: 'يجبُ الحذرُ من لمسِ الكهرباءِ.',
      definition: 'حرصٌ وانتباهٌ تجاهَ الأمورِ',
      translation: 'ostrożność, czujność',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pa2Nd',
    created: 1736998937762,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'leniwy',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iob6s',
    created: 1736998939222,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: 'ˈbaːrizun',
      example: 'ابنُ خلدونِ عالمٌ بارزٌ في علمِ الاجتماعِ.',
      definition: 'واضحٌ للعيانِ',
      translation: 'wyraźny',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
