import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'xL2Ex',
    created: 1736993764130,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: 'naˈzaːhatun',
      example: 'احترامُ المرءِ مقرونٌ بنزاهتِهِ.',
      definition: 'الابتعادُ عنِ السّوءِ والأعمالِ الدّنيئةِ',
      translation: 'чистота, недоступность',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'YGQ2f',
    created: 1736993765365,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: 'sˤuˈmuːdun',
      example: 'يُعرفُ القويُّ بصمودِهِ أمام المصاعبِ.',
      definition: 'ثباتٌ وعدمُ التّحرّكِ',
      translation: 'стойкость',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'uOonm',
    created: 1736993767108,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: 'ʕaˈtabatun',
      example: 'عتبَةُ البيتِ عاليةٌ.',
      definition: 'خشبةُ البابِ الّتي يوطأُ عليها',
      translation: 'порог',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pa6Gc',
    created: 1736993768488,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: 'taˈsˤarrafa',
      example: 'تصرّفَ الموظّفُ بصورةٍ لائقةٍ.',
      definition: 'قامِ بفعلِ ما يشاءُ',
      translation: 'действовать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dqJPz',
    created: 1736993770169,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: 'inʕiˈkaːsun',
      example: 'كانَ لرحيلها انعكاسٌ كبيرٌ على حياتهِ.',
      definition: 'إرتدادٌ إلى الوراءِ أو بزاويةٍ ما',
      translation: 'отражение',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IC9a5',
    created: 1736993771609,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: 'ħaˈsˤiːlatun',
      example: 'حصيلةُ أرباحِ الفنادقِ قليلةٌ.',
      definition: 'ما بقيَ وثبتَ منَ الشّيءِ بعدَ ذهابِ ما سواهُ',
      translation: 'остаток',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zo5C2',
    created: 1736993774094,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: 'ˈqarra',
      example: 'قرَّ رأيُ اللّجنةِ على إعادةِ الانتخاباتِ.',
      definition: 'ثبتَ واستقرَّ على قرارٍ',
      translation: 'утвердился, остановился',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ytu5Q',
    created: 1736994675595,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: 'iʕˈtabara',
      example:
        '* يعتبرُ الحكيمُ مكانةَ العلماءِ.\n* يعتبرُ العاقلُ منْ أخطاءِ غيرهِ.',
      definition:
        '* إِعتدَّ بالأمرِ واحترمهُ\n* إِتّعَظَ منَ التّجربةِ وأخذها عبرةً',
      translation: 'считать, принимать во внимание',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'O1IJu',
    created: 1736994676915,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: 'kurˈsijjun',
      example: 'جلسَ المتعبُ على الكرسيِّ.',
      definition: 'مقعدٌ لجلوسِ شخصٍ واحدٍ مصنوعٌ منْ خشبٍ أوْ نحوِهِ',
      translation: 'стул',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kgzYF',
    created: 1736994678857,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: 'ˈbarrara',
      example: 'برّرتِ التّلميذةُ عدمَ تقدّمها للاختباراتِ السّنويّةِ.',
      definition: 'أعطى تفسيرًا وشرحًا لما قامَ بهِ',
      translation: 'объяснил, оправдал',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'n7lXJ',
    created: 1736994680460,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: 'ˈʔahmala',
      example: 'أهملَ الكسولُ واجباتهِ.',
      definition: 'تركَ الأمرَ ولم يهتمَّ فيهِ',
      translation: 'игнорировать, пренебрегать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZYiCt',
    created: 1736994684238,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: 'ˈʔaqnaʕa',
      example: 'أقنَعتُهُ بالحِوارِ.',
      definition: 'جعلَ فلانًا يسلّمُ بالأمرِ عنْ رضًا',
      translation: 'убедить',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wZDPq',
    created: 1736994687547,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Vh02I',
    created: 1736994688336,
    data: {
      language: 'ar',
      source: 'ضَمْنًا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'включая',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '47Fa0',
    created: 1736994688934,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'в частности',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UK8_M',
    created: 1736994690615,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: 'ˈħaːlan',
      example: 'سأتناولُ غرضًا منَ السَّيَّارةِ وأَعودُ حَالًا.',
      definition: 'تَوًّا وَدُونَ تَأْخِيرٍ',
      translation: 'сейчас, немедленно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HzHAj',
    created: 1736994692456,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'примерно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qlOI1',
    created: 1736994693127,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'достаточно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'heMec',
    created: 1736994694586,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: 'muˈθaːbirun',
      example: 'لكي تنجحَ عليكَ أن تكونَ مثابِرًا.',
      definition: 'من يعملُ بنشاطٍ',
      translation: 'усердный',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'm1lqR',
    created: 1736994696645,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: 'ˈʃaːmilun',
      example: 'حقّقَ المحقّقُ بالجريمةِ بشكلٍ شاملٍ.',
      definition: 'محيطٌ بجميعِ النّواحي',
      translation: 'всеобъемлющий',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ha71q',
    created: 1736994698769,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: 'ˈmumtiʕun',
      example: 'شاهدْتُ فيلمًا ممتعًا في السّينما.',
      definition: 'يبعثُ الفرحَ والتّسليّةَ في النّفسِ',
      translation: 'увлекательный',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ojicv',
    created: 1736994700589,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: 'ˈħaðarun',
      example: 'يجبُ الحذرُ من لمسِ الكهرباءِ.',
      definition: 'حرصٌ وانتباهٌ تجاهَ الأمورِ',
      translation: 'осторожность, бдительность',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vBytz',
    created: 1736994701351,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ленивый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qo5Wz',
    created: 1736994703022,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: 'ˈbaːrizun',
      example: 'ابنُ خلدونِ عالمٌ بارزٌ في علمِ الاجتماعِ.',
      definition: 'واضحٌ للعيانِ',
      translation: 'явный, заметный',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
