import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'CAP3X',
    created: 1736996054222,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: 'naˈzaːhatun',
      example: 'احترامُ المرءِ مقرونٌ بنزاهتِهِ.',
      definition: 'الابتعادُ عنِ السّوءِ والأعمالِ الدّنيئةِ',
      translation: 'ärlighet, integritet',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BAGva',
    created: 1736996073270,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: 'sˤuˈmuːdun',
      example: 'يُعرفُ القويُّ بصمودِهِ أمام المصاعبِ.',
      definition: 'ثباتٌ وعدمُ التّحرّكِ',
      translation: 'ståndfasthet, uthållighet',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0-3_9',
    created: 1736996101005,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: 'ʕaˈtabatun',
      example: 'عتبَةُ البيتِ عاليةٌ.',
      definition: 'خشبةُ البابِ الّتي يوطأُ عليها',
      translation: 'tröskel',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ruljf',
    created: 1736996129342,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: 'taˈsˤarrafa',
      example: 'تصرّفَ الموظّفُ بصورةٍ لائقةٍ.',
      definition: 'قامِ بفعلِ ما يشاءُ',
      translation: 'agera, handla',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8P2Cs',
    created: 1736996139521,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: 'inʕiˈkaːsun',
      example: 'كانَ لرحيلها انعكاسٌ كبيرٌ على حياتهِ.',
      definition: 'إرتدادٌ إلى الوراءِ أو بزاويةٍ ما',
      translation: 'reflektion',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JxhLi',
    created: 1736996158770,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: 'ħaˈsˤiːlatun',
      example: 'حصيلةُ أرباحِ الفنادقِ قليلةٌ.',
      definition: 'ما بقيَ وثبتَ منَ الشّيءِ بعدَ ذهابِ ما سواهُ',
      translation: 'resultat',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aK0HF',
    created: 1736996187438,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: 'ˈqarra',
      example: 'قرَّ رأيُ اللّجنةِ على إعادةِ الانتخاباتِ.',
      definition: 'ثبتَ واستقرَّ على قرارٍ',
      translation: 'stanna, fastna',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bO7sA',
    created: 1736996206441,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: 'iʕˈtabara',
      example:
        '* يعتبرُ الحكيمُ مكانةَ العلماءِ.\n* يعتبرُ العاقلُ منْ أخطاءِ غيرهِ.',
      definition:
        '* إِعتدَّ بالأمرِ واحترمهُ\n* إِتّعَظَ منَ التّجربةِ وأخذها عبرةً',
      translation: 'betrakta, anse',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wheSy',
    created: 1736996216776,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: 'kurˈsijjun',
      example: 'جلسَ المتعبُ على الكرسيِّ.',
      definition: 'مقعدٌ لجلوسِ شخصٍ واحدٍ مصنوعٌ منْ خشبٍ أوْ نحوِهِ',
      translation: 'stol',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4RuIp',
    created: 1736996236326,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: 'ˈbarrara',
      example: 'برّرتِ التّلميذةُ عدمَ تقدّمها للاختباراتِ السّنويّةِ.',
      definition: 'أعطى تفسيرًا وشرحًا لما قامَ بهِ',
      translation: 'förklara, motivera',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'D5DRD',
    created: 1736996255384,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: 'ˈʔahmala',
      example: 'أهملَ الكسولُ واجباتهِ.',
      definition: 'تركَ الأمرَ ولم يهتمَّ فيهِ',
      translation: 'försummade',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eqp_e',
    created: 1736996283231,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: 'ˈʔaqnaʕa',
      example: 'أقنَعتُهُ بالحِوارِ.',
      definition: 'جعلَ فلانًا يسلّمُ بالأمرِ عنْ رضًا',
      translation: 'övertala',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PF_Kj',
    created: 1736996293009,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5k4-O',
    created: 1736996302807,
    data: {
      language: 'ar',
      source: 'ضَمْنًا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'underförstått',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZFsgt',
    created: 1736996304007,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: 'särskilt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mLaPo',
    created: 1736996323227,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: 'ˈħaːlan',
      example: 'سأتناولُ غرضًا منَ السَّيَّارةِ وأَعودُ حَالًا.',
      definition: 'تَوًّا وَدُونَ تَأْخِيرٍ',
      translation: 'omedelbart, nu',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AYDoW',
    created: 1736996332893,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefär',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iHzlZ',
    created: 1736996342748,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillräckligt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'r52RN',
    created: 1736996361990,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: 'muˈθaːbirun',
      example: 'لكي تنجحَ عليكَ أن تكونَ مثابِرًا.',
      definition: 'من يعملُ بنشاطٍ',
      translation: 'flitig, ihärdig',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VqboS',
    created: 1736996372283,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: 'ˈʃaːmilun',
      example: 'حقّقَ المحقّقُ بالجريمةِ بشكلٍ شاملٍ.',
      definition: 'محيطٌ بجميعِ النّواحي',
      translation: 'omfattande',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dAQqC',
    created: 1736996391276,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: 'ˈmumtiʕun',
      example: 'شاهدْتُ فيلمًا ممتعًا في السّينما.',
      definition: 'يبعثُ الفرحَ والتّسليّةَ في النّفسِ',
      translation: 'underhållande',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WtdJY',
    created: 1736996419793,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: 'ˈħaðarun',
      example: 'يجبُ الحذرُ من لمسِ الكهرباءِ.',
      definition: 'حرصٌ وانتباهٌ تجاهَ الأمورِ',
      translation: 'försiktighet, vaktsamhet',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DNdMl',
    created: 1736996429610,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: 'slö',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'F5jcB',
    created: 1736996457580,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: 'ˈbaːrizun',
      example: 'ابنُ خلدونِ عالمٌ بارزٌ في علمِ الاجتماعِ.',
      definition: 'واضحٌ للعيانِ',
      translation: 'framträdande, tydlig',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
