import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'qKfeE',
    created: 1736992598126,
    data: {
      language: 'ar',
      source: 'نزاهة',
      ipa: 'naˈzaːhatun',
      example: 'احترامُ المرءِ مقرونٌ بنزاهتِهِ.',
      definition: 'الابتعادُ عنِ السّوءِ والأعمالِ الدّنيئةِ',
      translation: '清白, 廉洁',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kWodQ',
    created: 1736992599533,
    data: {
      language: 'ar',
      source: 'صمود',
      ipa: 'sˤuˈmuːdun',
      example: 'يُعرفُ القويُّ بصمودِهِ أمام المصاعبِ.',
      definition: 'ثباتٌ وعدمُ التّحرّكِ',
      translation: '坚定, 不动, 坚韧',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1iXYw',
    created: 1736992601883,
    data: {
      language: 'ar',
      source: 'عتبة',
      ipa: 'ʕaˈtabatun',
      example: 'عتبَةُ البيتِ عاليةٌ.',
      definition: 'خشبةُ البابِ الّتي يوطأُ عليها',
      translation: '门槛',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ml8Gc',
    created: 1736992603060,
    data: {
      language: 'ar',
      source: 'تصرف',
      ipa: 'taˈsˤarrafa',
      example: 'تصرّفَ الموظّفُ بصورةٍ لائقةٍ.',
      definition: 'قامِ بفعلِ ما يشاءُ',
      translation: '行为',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nC6vA',
    created: 1736992604846,
    data: {
      language: 'ar',
      source: 'انعكاس',
      ipa: 'inʕiˈkaːsun',
      example: 'كانَ لرحيلها انعكاسٌ كبيرٌ على حياتهِ.',
      definition: 'إرتدادٌ إلى الوراءِ أو بزاويةٍ ما',
      translation: '反射',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'd8MNn',
    created: 1736992606315,
    data: {
      language: 'ar',
      source: 'حصيلة',
      ipa: 'ħaˈsˤiːlatun',
      example: 'حصيلةُ أرباحِ الفنادقِ قليلةٌ.',
      definition: 'ما بقيَ وثبتَ منَ الشّيءِ بعدَ ذهابِ ما سواهُ',
      translation: '结果, 收获',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yLuXT',
    created: 1736992607927,
    data: {
      language: 'ar',
      source: 'قر',
      ipa: 'ˈqarra',
      example: 'قرَّ رأيُ اللّجنةِ على إعادةِ الانتخاباتِ.',
      definition: 'ثبتَ واستقرَّ على قرارٍ',
      translation: '固定, 安定',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '58YIx',
    created: 1736992609960,
    data: {
      language: 'ar',
      source: 'اعتبر',
      ipa: 'iʕˈtabara',
      example:
        '* يعتبرُ الحكيمُ مكانةَ العلماءِ.\n* يعتبرُ العاقلُ منْ أخطاءِ غيرهِ.',
      definition:
        '* إِعتدَّ بالأمرِ واحترمهُ\n* إِتّعَظَ منَ التّجربةِ وأخذها عبرةً',
      translation: '认为, 考虑',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0AmH7',
    created: 1736992611620,
    data: {
      language: 'ar',
      source: 'كرسي',
      ipa: 'kurˈsijjun',
      example: 'جلسَ المتعبُ على الكرسيِّ.',
      definition: 'مقعدٌ لجلوسِ شخصٍ واحدٍ مصنوعٌ منْ خشبٍ أوْ نحوِهِ',
      translation: '椅子',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4lpnQ',
    created: 1736992616872,
    data: {
      language: 'ar',
      source: 'برر',
      ipa: 'ˈbarrara',
      example: 'برّرتِ التّلميذةُ عدمَ تقدّمها للاختباراتِ السّنويّةِ.',
      definition: 'أعطى تفسيرًا وشرحًا لما قامَ بهِ',
      translation: '解释, 辩解',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ysvtc',
    created: 1736992618443,
    data: {
      language: 'ar',
      source: 'أهمل',
      ipa: 'ˈʔahmala',
      example: 'أهملَ الكسولُ واجباتهِ.',
      definition: 'تركَ الأمرَ ولم يهتمَّ فيهِ',
      translation: '忽视, 不重视',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '026hI',
    created: 1736992619910,
    data: {
      language: 'ar',
      source: 'أقنع',
      ipa: 'ˈʔaqnaʕa',
      example: 'أقنَعتُهُ بالحِوارِ.',
      definition: 'جعلَ فلانًا يسلّمُ بالأمرِ عنْ رضًا',
      translation: '说服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RniOL',
    created: 1736992620948,
    data: {
      language: 'ar',
      source: 'تَدْرِيجِيّاً',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐渐地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4_yNp',
    created: 1736992624379,
    data: {
      language: 'ar',
      source: 'ضَمْنًا',
      ipa: '',
      example: '',
      definition: '',
      translation: '包含在内',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6OnAy',
    created: 1736992625230,
    data: {
      language: 'ar',
      source: 'على وجه الخصوص',
      ipa: '',
      example: '',
      definition: '',
      translation: '特别是',
      partOfSpeech: 'phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QupKS',
    created: 1736992626871,
    data: {
      language: 'ar',
      source: 'حالا',
      ipa: 'ˈħaːlan',
      example: 'سأتناولُ غرضًا منَ السَّيَّارةِ وأَعودُ حَالًا.',
      definition: 'تَوًّا وَدُونَ تَأْخِيرٍ',
      translation: '立刻, 马上, 现在',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'USbXR',
    created: 1736992627913,
    data: {
      language: 'ar',
      source: 'تقريبا',
      ipa: '',
      example: '',
      definition: '',
      translation: '大约',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AjIL0',
    created: 1736992629001,
    data: {
      language: 'ar',
      source: 'بشكل كافي',
      ipa: '',
      example: '',
      definition: '',
      translation: '足够地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4e1rX',
    created: 1736992630594,
    data: {
      language: 'ar',
      source: 'مثابر',
      ipa: 'muˈθaːbirun',
      example: 'لكي تنجحَ عليكَ أن تكونَ مثابِرًا.',
      definition: 'من يعملُ بنشاطٍ',
      translation: '勤奋',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FgXr1',
    created: 1736992631989,
    data: {
      language: 'ar',
      source: 'شامل',
      ipa: 'ˈʃaːmilun',
      example: 'حقّقَ المحقّقُ بالجريمةِ بشكلٍ شاملٍ.',
      definition: 'محيطٌ بجميعِ النّواحي',
      translation: '全面的',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7kLOW',
    created: 1736992633420,
    data: {
      language: 'ar',
      source: 'ممتع',
      ipa: 'ˈmumtiʕun',
      example: 'شاهدْتُ فيلمًا ممتعًا في السّينما.',
      definition: 'يبعثُ الفرحَ والتّسليّةَ في النّفسِ',
      translation: '有趣',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zhxOx',
    created: 1736992634923,
    data: {
      language: 'ar',
      source: 'حذر',
      ipa: 'ˈħaðarun',
      example: 'يجبُ الحذرُ من لمسِ الكهرباءِ.',
      definition: 'حرصٌ وانتباهٌ تجاهَ الأمورِ',
      translation: '警惕, 小心',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9NLKa',
    created: 1736992636008,
    data: {
      language: 'ar',
      source: 'مُتَكَاسِل',
      ipa: '',
      example: '',
      definition: '',
      translation: '懒惰的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'giYL2',
    created: 1736992637515,
    data: {
      language: 'ar',
      source: 'بارز',
      ipa: 'ˈbaːrizun',
      example: 'ابنُ خلدونِ عالمٌ بارزٌ في علمِ الاجتماعِ.',
      definition: 'واضحٌ للعيانِ',
      translation: '显著',
      partOfSpeech: 'adjective',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
