import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'SlkEv',
    created: 1737089234524,
    data: {
      language: 'da',
      source: 'integritet',
      ipa: 'entəgʁiˈteˀd',
      example:
        '* den personlige integritet\n* territorial integritet\n* folketingsmedlemmernes personlige integritet',
      definition:
        '* (abstrakt) rum der omgiver nogen og adskiller vedkommende fra omgivelserne, beskytter mod krænkelser osv.\n* et lands ret til at være en uindskrænket, ukrænkelig helhed\n* en persons evne og vilje til at handle selvstændigt, ærligt og redeligt uden uvedkommende el. upassende hensyntagen til nogen el. noget',
      translation: 'integridad, integridad nacional',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dwBHf',
    created: 1737089235792,
    data: {
      language: 'da',
      source: 'modstandsdygtighed',
      ipa: 'ˈmoðsdans-',
      example: '',
      definition: '',
      translation: 'resiliencia',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'aK2ET',
    created: 1737089254352,
    data: {
      language: 'da',
      source: 'tærskel',
      ipa: 'ˈtæɐ̯sgəl',
      example: 'træde (ind) over tærsklen',
      definition: '',
      translation: 'umbral',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'w4YZf',
    created: 1737089264106,
    data: {
      language: 'da',
      source: 'disposición',
      ipa: '',
      example: '',
      definition: '',
      translation: 'disposición',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ChDf7',
    created: 1737089273823,
    data: {
      language: 'da',
      source: 'eftervirkning',
      ipa: '',
      example: 'psykiske eftervirkninger',
      definition: '',
      translation: 'efecto secundario',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ww6B1',
    created: 1737089292199,
    data: {
      language: 'da',
      source: 'resultat',
      ipa: 'ʁεsulˈtæˀd',
      example: '* det endelige resultat\n* opnå resultater',
      definition:
        '* udfald, følge el. virkning af en proces, et forløb, en indsats e.l.\n* sejr, gevinst el. anden form for positivt udfald af en kamp el. en målrettet indsats\n* samlet over- el. underskud af en økonomisk virksomhed, opgjort i et regnskab som forskellen mellem omkostninger og indtægter',
      translation:
        'resultado, consecuencia, producto, desenlace, solución, balance',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'V8-qA',
    created: 1737089310280,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: 'ˈanʌˌkεnˀə',
      example:
        '* almindeligt anerkendt\n* officielt anerkendt\n* anerkende republikken Rusland som selvstændig stat',
      definition:
        '* erkende som sandt el. berettiget\n* godkende formelt; acceptere som værende juridisk gyldigt; om offentlig myndighed\n* erklære sin folkeretlige accept af en ny stat; om stat el. international organisation',
      translation:
        'reconocer, admitir, aceptar, aprobar, validar, convalidar, reconocimiento, apreciar, valorar, acuse de recibo, confirmar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7rrWp',
    created: 1737089328329,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '-ˌvɑjˀə',
      example: 'overveje situationen',
      definition:
        'tænke over noget el. tænke på at gøre noget idet man vurderer hvad der taler for og imod',
      translation: 'sopesar, reflexionar, considerar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9OitO',
    created: 1737089346619,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: 'ˈhεli',
      example:
        '* hellige skrifter\n* hellig pligt\n* i demokratiets hellige navn',
      definition:
        '* som er forbundet med det guddommelige el. indeholder guddommelig kraft, og som derfor behandles med religiøs ærefrygt\n* som har krav på ærbødighed pga. sin betydningsfuldhed, skønhed e.l.\n* som står urokkeligt fast, er uopnåelig el. ukrænkelig',
      translation:
        'sagrado, consagrado, bendito, santo, sacro, divino, bienaventurado, fariseo, intocable',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Rhnrl',
    created: 1737089356609,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '-ˌgɶˀʌ',
      example: 'retfærdiggøre en beslutning',
      definition:
        'berettigevise at noget er retfærdigt, rigtigt el. berettiget',
      translation: 'legitimar, justificar, legalizar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'T0oE5',
    created: 1737089366602,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: 'fʌˈsœmˀə',
      example: '* indhente det forsømte\n* forsømte børn\n* forsømme skolen',
      definition:
        '* undlade at gøre noget som man bør gøre\n* undlade at tage sig af, passe el. pleje ordentligt\n* udeblive fra undervisning, arbejde e.l.; undlade at deltage i',
      translation:
        'descuidar, desatender, faltar, abandonar, postergar, ausentarse, no presentarse, no comparecer, malgastar, desperdiciar, despilfarrar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YTGHs',
    created: 1737089376464,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '-ˌtæˀlə',
      example: 'forsøge/prøve at overtale nogen',
      definition:
        'få nogen til (modstræbende) at gøre noget bestemt vha. indtrængende ord, argumenter, løfter e.l.',
      translation: 'convencer, persuadir',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'H8FtA',
    created: 1737089388141,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: 'ˈgʁɑðˌviˀs',
      example: 'gradvis udvikling',
      definition: 'som foregår lidt efter lidt el. trinvis',
      translation: 'gradual',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BbIag',
    created: 1737089397731,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: 'ˈempliˌsid',
      example: '',
      definition: '',
      translation: 'implícito',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'j1vj6',
    created: 1737089407771,
    data: {
      language: 'da',
      source: 'især',
      ipa: 'iˈsεˀɐ̯',
      example: 'især skandinaver',
      definition:
        'bruges for at fremhæve det som har særlig betydning, el. det som udsagnet særlig gælder',
      translation: 'especialmente, particularmente, sobre todo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HL-fl',
    created: 1737089408638,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: 'ˈpʁʌmdə',
      example: 'en prompte reaktion',
      definition: 'øjeblikkelig; omgående',
      translation: 'momentáneo, instantáneo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'x_QRn',
    created: 1737089418301,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: 'ˈnoːənˈlɔnə',
      example:
        '* Vejret var nogenlunde på deres førdselsdag.\n* være nogenlunde sikker på at\n* nogenlunde samtidig',
      definition:
        '* ikke perfekt, men heller ikke utilfredsstillende; ret god når man tager omstændighederne i betragtning\n* i en (efter omstændighederne) tilstrækkelig el. tilfredsstillende grad; ret godt\n* omtrent; næsten',
      translation:
        'ampliamente, razonablemente, más o menos, poco más o menos, de manera razonable, casi',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ztUpl',
    created: 1737089428092,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: 'teˈsdʁagəli',
      example: 'i tilstrækkelig grad',
      definition:
        'af et omfang el. en kvalitet der er stor nok til at opfylde et bestemt behov, krav, ønske e.l.',
      translation: 'suficiente, bastante, harto',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'vyLUn',
    created: 1737089437871,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '-ˌvɑˀɑnə',
      example: 'Vandkraft er vedvarende energi.',
      definition:
        'som består til stadighed; fx om uudtømmelige energiformer som solenergi og vindenergi',
      translation: 'contínuo, duradero, perdurable, sostenible',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'MZjNq',
    created: 1737089447817,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '-ˌfadənə',
      example: 'omfattende undersøgelser',
      definition:
        'som har et stort omfang el. kræver meget arbejde og mange resurser',
      translation: 'extenso, amplio, vasto, extensivo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4eUwV',
    created: 1737089457885,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: 'ˈdɑjli',
      example: '* dejligt vejr\n* dejlig lejlighed\n* dejlig middag',
      definition:
        '* som giver anledning til stor begejstring, glæde el. tilfredshed\n* bekvem og praktisk mht. indretning, udstyr e.l.; fx om bolig el. køretøj\n* som gør et overordentlig positivt indtryk på sanserne; æstetisk tiltalende',
      translation:
        'delicioso, agradable, encantador, cómodo, práctico, maravilloso, adorable, atractivo, hermoso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '1joQq',
    created: 1737089467858,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: 'fʌˈsegdi',
      example:
        '* forsigtige skridt\n* gå forsigtig til værks\n* forsigtig optimisme',
      definition:
        '* omhyggelig og påpasselig i sine bevægelser for at undgå at skade el. ødelægge noget\n* som stilfærdigt holder sig tilbage og nødig handler el. udtaler sig uoverlagt\n* ikke på nogen måde overdreven el. overvældende; om handling, udtalelse e.l.',
      translation:
        'cuidadoso, moderado, mesurado, cauteloso, con cuidado, controlado',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rUWuL',
    created: 1737089468853,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '-ˌsdʁεˀbənə',
      example: '',
      definition: '',
      translation: 'reacio',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'B-yoS',
    created: 1737089487602,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: 'ˈvεˀsənli',
      example: '* spille en væsentlig rolle\n* væsenlig(t) dyrere',
      definition:
        '* som udgør el. vedrører en tings inderste og egentlige væsen, og som derfor er yderst vigtig\n* meget; betydelig',
      translation:
        'fundamental, esencial, central, mucho, significativo, importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
