import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'hoi3g',
    created: 1737091984073,
    data: {
      language: 'da',
      source: 'integritet',
      ipa: 'entəgʁiˈteˀd',
      example:
        '* den personlige integritet\n* territorial integritet\n* folketingsmedlemmernes personlige integritet',
      definition:
        '* (abstrakt) rum der omgiver nogen og adskiller vedkommende fra omgivelserne, beskytter mod krænkelser osv.\n* et lands ret til at være en uindskrænket, ukrænkelig helhed\n* en persons evne og vilje til at handle selvstændigt, ærligt og redeligt uden uvedkommende el. upassende hensyntagen til nogen el. noget',
      translation: 'integrità, onestà',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'N-Rtd',
    created: 1737092003256,
    data: {
      language: 'da',
      source: 'modstandsdygtighed',
      ipa: 'ˈmoðsdans-',
      example: '',
      definition: '',
      translation: 'resilienza',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ofm9v',
    created: 1737092021926,
    data: {
      language: 'da',
      source: 'tærskel',
      ipa: 'ˈtæɐ̯sgəl',
      example: 'træde (ind) over tærsklen',
      definition: '',
      translation: 'soglia',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AigLb',
    created: 1737092058611,
    data: {
      language: 'da',
      source: 'disposition',
      ipa: 'disbosiˈɕoˀn',
      example:
        '* foretage en disposition\n* til fri disposition\n* en tilgængelig disposition af bogens stof',
      definition:
        '* det at beslutte noget\n* det at råde over noget og have ret til at bestemme hvordan det skal bruges\n* det at tilrettelægge og opbygge noget på en bestemt måde',
      translation: 'disposizione, organizzazione',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '901ky',
    created: 1737092077210,
    data: {
      language: 'da',
      source: 'eftervirkning',
      ipa: '',
      example: 'psykiske eftervirkninger',
      definition: '',
      translation: 'effetto',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iBUNL',
    created: 1737092095881,
    data: {
      language: 'da',
      source: 'resultat',
      ipa: 'ʁεsulˈtæˀd',
      example: '* det endelige resultat\n* opnå resultater',
      definition:
        '* udfald, følge el. virkning af en proces, et forløb, en indsats e.l.\n* sejr, gevinst el. anden form for positivt udfald af en kamp el. en målrettet indsats\n* samlet over- el. underskud af en økonomisk virksomhed, opgjort i et regnskab som forskellen mellem omkostninger og indtægter',
      translation: 'risultato',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ANTkM',
    created: 1737092124127,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: 'ˈanʌˌkεnˀə',
      example:
        '* almindeligt anerkendt\n* officielt anerkendt\n* anerkende republikken Rusland som selvstændig stat',
      definition:
        '* erkende som sandt el. berettiget\n* godkende formelt; acceptere som værende juridisk gyldigt; om offentlig myndighed\n* erklære sin folkeretlige accept af en ny stat; om stat el. international organisation',
      translation: 'riconoscere, approvare, dichiarare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'q6KcO',
    created: 1737092151881,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '-ˌvɑjˀə',
      example: 'overveje situationen',
      definition:
        'tænke over noget el. tænke på at gøre noget idet man vurderer hvad der taler for og imod',
      translation: 'considerare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'D9JpF',
    created: 1737092179916,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: 'ˈhεli',
      example:
        '* hellige skrifter\n* hellig pligt\n* i demokratiets hellige navn',
      definition:
        '* som er forbundet med det guddommelige el. indeholder guddommelig kraft, og som derfor behandles med religiøs ærefrygt\n* som har krav på ærbødighed pga. sin betydningsfuldhed, skønhed e.l.\n* som står urokkeligt fast, er uopnåelig el. ukrænkelig',
      translation: 'santo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ATVIC',
    created: 1737092200920,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '-ˌgɶˀʌ',
      example: 'retfærdiggøre en beslutning',
      definition:
        'berettigevise at noget er retfærdigt, rigtigt el. berettiget',
      translation: 'giustificare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PzdA3',
    created: 1737092237827,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: 'fʌˈsœmˀə',
      example: '* indhente det forsømte\n* forsømte børn\n* forsømme skolen',
      definition:
        '* undlade at gøre noget som man bør gøre\n* undlade at tage sig af, passe el. pleje ordentligt\n* udeblive fra undervisning, arbejde e.l.; undlade at deltage i',
      translation: 'trascurare, negligenza',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JDQRx',
    created: 1737092258408,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '-ˌtæˀlə',
      example: 'forsøge/prøve at overtale nogen',
      definition:
        'få nogen til (modstræbende) at gøre noget bestemt vha. indtrængende ord, argumenter, løfter e.l.',
      translation: 'persuadere, convincere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fpAUe',
    created: 1737092277473,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: 'ˈgʁɑðˌviˀs',
      example: 'gradvis udvikling',
      definition: 'som foregår lidt efter lidt el. trinvis',
      translation: 'graduale',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lnNrF',
    created: 1737092287657,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: 'ˈempliˌsid',
      example: '',
      definition: '',
      translation: 'implicito',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qmYZQ',
    created: 1737092316059,
    data: {
      language: 'da',
      source: 'især',
      ipa: 'iˈsεˀɐ̯',
      example: 'især skandinaver',
      definition:
        'bruges for at fremhæve det som har særlig betydning, el. det som udsagnet særlig gælder',
      translation: 'soprattutto, in particolare',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PBvba',
    created: 1737092335312,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: 'ˈpʁʌmdə',
      example: 'en prompte reaktion',
      definition: 'øjeblikkelig; omgående',
      translation: 'immediato, pronto',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Bm0tB',
    created: 1737092345551,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: 'ˈnoːənˈlɔnə',
      example:
        '* Vejret var nogenlunde på deres førdselsdag.\n* være nogenlunde sikker på at\n* nogenlunde samtidig',
      definition:
        '* ikke perfekt, men heller ikke utilfredsstillende; ret god når man tager omstændighederne i betragtning\n* i en (efter omstændighederne) tilstrækkelig el. tilfredsstillende grad; ret godt\n* omtrent; næsten',
      translation: 'abbastanza buono, piuttosto buono',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3QHlZ',
    created: 1737092364649,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: 'teˈsdʁagəli',
      example: 'i tilstrækkelig grad',
      definition:
        'af et omfang el. en kvalitet der er stor nok til at opfylde et bestemt behov, krav, ønske e.l.',
      translation: 'sufficiente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'EXMh6',
    created: 1737092392745,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '-ˌvɑˀɑnə',
      example: 'Vandkraft er vedvarende energi.',
      definition:
        'som består til stadighed; fx om uudtømmelige energiformer som solenergi og vindenergi',
      translation: 'permanente, sostenibile',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yxbHL',
    created: 1737092420631,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '-ˌfadənə',
      example: 'omfattende undersøgelser',
      definition:
        'som har et stort omfang el. kræver meget arbejde og mange resurser',
      translation: 'ampio, esteso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '1PeYX',
    created: 1737092448976,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: 'ˈdɑjli',
      example: '* dejligt vejr\n* dejlig lejlighed\n* dejlig middag',
      definition:
        '* som giver anledning til stor begejstring, glæde el. tilfredshed\n* bekvem og praktisk mht. indretning, udstyr e.l.; fx om bolig el. køretøj\n* som gør et overordentlig positivt indtryk på sanserne; æstetisk tiltalende',
      translation: 'delizioso, piacevole, splendido',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'oOVqO',
    created: 1737092459332,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: 'fʌˈsegdi',
      example:
        '* forsigtige skridt\n* gå forsigtig til værks\n* forsigtig optimisme',
      definition:
        '* omhyggelig og påpasselig i sine bevægelser for at undgå at skade el. ødelægge noget\n* som stilfærdigt holder sig tilbage og nødig handler el. udtaler sig uoverlagt\n* ikke på nogen måde overdreven el. overvældende; om handling, udtalelse e.l.',
      translation: 'cauto, attento',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dA_QV',
    created: 1737092469072,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '-ˌsdʁεˀbənə',
      example: '',
      definition: '',
      translation: 'riluttante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'UAN8X',
    created: 1737092488301,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: 'ˈvεˀsənli',
      example: '* spille en væsentlig rolle\n* væsenlig(t) dyrere',
      definition:
        '* som udgør el. vedrører en tings inderste og egentlige væsen, og som derfor er yderst vigtig\n* meget; betydelig',
      translation: 'essenziale, significativo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
