import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 't1b43',
    created: 1737094519556,
    data: {
      language: 'da',
      source: 'integritet',
      ipa: 'entəgʁiˈteˀd',
      example:
        '* den personlige integritet\n* territorial integritet\n* folketingsmedlemmernes personlige integritet',
      definition:
        '* (abstrakt) rum der omgiver nogen og adskiller vedkommende fra omgivelserne, beskytter mod krænkelser osv.\n* et lands ret til at være en uindskrænket, ukrænkelig helhed\n* en persons evne og vilje til at handle selvstændigt, ærligt og redeligt uden uvedkommende el. upassende hensyntagen til nogen el. noget',
      translation: '성실성, 보전, 통일성, 정직성',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'oHoQB',
    created: 1737094520698,
    data: {
      language: 'da',
      source: 'modstandsdygtighed',
      ipa: 'ˈmoðsdans-',
      example: '',
      definition: '',
      translation: '저항, 저항력',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2rcWM',
    created: 1737094521756,
    data: {
      language: 'da',
      source: 'tærskel',
      ipa: 'ˈtæɐ̯sgəl',
      example: 'træde (ind) over tærsklen',
      definition: '',
      translation: '문지방, 정도를 벗어나다, 고도가 높은 해저 지역, 문턱',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'GYusA',
    created: 1737094531437,
    data: {
      language: 'da',
      source: 'disposition',
      ipa: 'disbosiˈɕoˀn',
      example:
        '* foretage en disposition\n* til fri disposition\n* en tilgængelig disposition af bogens stof',
      definition:
        '* det at beslutte noget\n* det at råde over noget og have ret til at bestemme hvordan det skal bruges\n* det at tilrettelægge og opbygge noget på en bestemt måde',
      translation: '결정, 처분, 거래, 구성, 배치, 계획, 개요, 소인',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'suUa3',
    created: 1737094532370,
    data: {
      language: 'da',
      source: 'eftervirkning',
      ipa: '',
      example: 'psykiske eftervirkninger',
      definition: '',
      translation: '여파',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4ga3z',
    created: 1737094542034,
    data: {
      language: 'da',
      source: 'resultat',
      ipa: 'ʁεsulˈtæˀd',
      example: '* det endelige resultat\n* opnå resultater',
      definition:
        '* udfald, følge el. virkning af en proces, et forløb, en indsats e.l.\n* sejr, gevinst el. anden form for positivt udfald af en kamp el. en målrettet indsats\n* samlet over- el. underskud af en økonomisk virksomhed, opgjort i et regnskab som forskellen mellem omkostninger og indtægter',
      translation: '결과',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BBk3g',
    created: 1737094551866,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: 'ˈanʌˌkεnˀə',
      example:
        '* almindeligt anerkendt\n* officielt anerkendt\n* anerkende republikken Rusland som selvstændig stat',
      definition:
        '* erkende som sandt el. berettiget\n* godkende formelt; acceptere som værende juridisk gyldigt; om offentlig myndighed\n* erklære sin folkeretlige accept af en ny stat; om stat el. international organisation',
      translation: '인정하다, 받아들이다, 확인하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'W7fEo',
    created: 1737094564975,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '-ˌvɑjˀə',
      example: 'overveje situationen',
      definition:
        'tænke over noget el. tænke på at gøre noget idet man vurderer hvad der taler for og imod',
      translation: '고려하다, 생각하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PsSOA',
    created: 1737094574934,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: 'ˈhεli',
      example:
        '* hellige skrifter\n* hellig pligt\n* i demokratiets hellige navn',
      definition:
        '* som er forbundet med det guddommelige el. indeholder guddommelig kraft, og som derfor behandles med religiøs ærefrygt\n* som har krav på ærbødighed pga. sin betydningsfuldhed, skønhed e.l.\n* som står urokkeligt fast, er uopnåelig el. ukrænkelig',
      translation:
        '신성한, 거룩한, 신성한; 축복 받은, 신성한; 구원 받은, 독선적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2c-z2',
    created: 1737094575899,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '-ˌgɶˀʌ',
      example: 'retfærdiggøre en beslutning',
      definition:
        'berettigevise at noget er retfærdigt, rigtigt el. berettiget',
      translation: '정당화하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NnBs6',
    created: 1737094585857,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: 'fʌˈsœmˀə',
      example: '* indhente det forsømte\n* forsømte børn\n* forsømme skolen',
      definition:
        '* undlade at gøre noget som man bør gøre\n* undlade at tage sig af, passe el. pleje ordentligt\n* udeblive fra undervisning, arbejde e.l.; undlade at deltage i',
      translation: '등한시하다, 방치하다, 놓치다, 소홀히 하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'onOe9',
    created: 1737094595678,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '-ˌtæˀlə',
      example: 'forsøge/prøve at overtale nogen',
      definition:
        'få nogen til (modstræbende) at gøre noget bestemt vha. indtrængende ord, argumenter, løfter e.l.',
      translation: '설득하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'OliAW',
    created: 1737094605686,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: 'ˈgʁɑðˌviˀs',
      example: 'gradvis udvikling',
      definition: 'som foregår lidt efter lidt el. trinvis',
      translation: '점진적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'scPbK',
    created: 1737094624447,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: 'ˈempliˌsid',
      example: '',
      definition: '',
      translation: '함축된, 암시적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fAi-4',
    created: 1737094634156,
    data: {
      language: 'da',
      source: 'især',
      ipa: 'iˈsεˀɐ̯',
      example: 'især skandinaver',
      definition:
        'bruges for at fremhæve det som har særlig betydning, el. det som udsagnet særlig gælder',
      translation: '특히',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hJiIr',
    created: 1737094652413,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: 'ˈpʁʌmdə',
      example: 'en prompte reaktion',
      definition: 'øjeblikkelig; omgående',
      translation: '즉각적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Ll1BI',
    created: 1737094670619,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: 'ˈnoːənˈlɔnə',
      example:
        '* Vejret var nogenlunde på deres førdselsdag.\n* være nogenlunde sikker på at\n* nogenlunde samtidig',
      definition:
        '* ikke perfekt, men heller ikke utilfredsstillende; ret god når man tager omstændighederne i betragtning\n* i en (efter omstændighederne) tilstrækkelig el. tilfredsstillende grad; ret godt\n* omtrent; næsten',
      translation: '꽤 좋은, 꽤, 상당히, 거의, 약',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kEohW',
    created: 1737094680395,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: 'teˈsdʁagəli',
      example: 'i tilstrækkelig grad',
      definition:
        'af et omfang el. en kvalitet der er stor nok til at opfylde et bestemt behov, krav, ønske e.l.',
      translation: '적절한, 충분한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kQWQl',
    created: 1737094690287,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '-ˌvɑˀɑnə',
      example: 'Vandkraft er vedvarende energi.',
      definition:
        'som består til stadighed; fx om uudtømmelige energiformer som solenergi og vindenergi',
      translation: '지속적인; 재생가능한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '99niN',
    created: 1737094708329,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '-ˌfadənə',
      example: 'omfattende undersøgelser',
      definition:
        'som har et stort omfang el. kræver meget arbejde og mange resurser',
      translation: '포괄적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Q1-e7',
    created: 1737094726466,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: 'ˈdɑjli',
      example: '* dejligt vejr\n* dejlig lejlighed\n* dejlig middag',
      definition:
        '* som giver anledning til stor begejstring, glæde el. tilfredshed\n* bekvem og praktisk mht. indretning, udstyr e.l.; fx om bolig el. køretøj\n* som gør et overordentlig positivt indtryk på sanserne; æstetisk tiltalende',
      translation: '훌륭한, 멋진, 훌륭한; 맛있는, 사랑스러운',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'l4YmZ',
    created: 1737094745163,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: 'fʌˈsegdi',
      example:
        '* forsigtige skridt\n* gå forsigtig til værks\n* forsigtig optimisme',
      definition:
        '* omhyggelig og påpasselig i sine bevægelser for at undgå at skade el. ødelægge noget\n* som stilfærdigt holder sig tilbage og nødig handler el. udtaler sig uoverlagt\n* ikke på nogen måde overdreven el. overvældende; om handling, udtalelse e.l.',
      translation: '조심스러운; 주의하는, 조심스러운, 신중한; 온건한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pwnm7',
    created: 1737094755021,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '-ˌsdʁεˀbənə',
      example: '',
      definition: '',
      translation: '꺼리는, 저항하는',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'F5NYE',
    created: 1737094764820,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: 'ˈvεˀsənli',
      example: '* spille en væsentlig rolle\n* væsenlig(t) dyrere',
      definition:
        '* som udgør el. vedrører en tings inderste og egentlige væsen, og som derfor er yderst vigtig\n* meget; betydelig',
      translation: '중요한, 필수적인, 상당히, 두드러지게',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
