import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'U8VZo',
    created: 1737090044048,
    data: {
      language: 'da',
      source: 'integritet',
      ipa: 'entəgʁiˈteˀd',
      example:
        '* den personlige integritet\n* territorial integritet\n* folketingsmedlemmernes personlige integritet',
      definition:
        '* (abstrakt) rum der omgiver nogen og adskiller vedkommende fra omgivelserne, beskytter mod krænkelser osv.\n* et lands ret til at være en uindskrænket, ukrænkelig helhed\n* en persons evne og vilje til at handle selvstændigt, ærligt og redeligt uden uvedkommende el. upassende hensyntagen til nogen el. noget',
      translation: '完整性, 独立性',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lJ5xN',
    created: 1737090054298,
    data: {
      language: 'da',
      source: 'modstandsdygtighed',
      ipa: 'ˈmoðsdans-',
      example: '',
      definition: '',
      translation: '抗逆性',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iX6p4',
    created: 1737090064062,
    data: {
      language: 'da',
      source: 'tærskel',
      ipa: 'ˈtæɐ̯sgəl',
      example: 'træde (ind) over tærsklen',
      definition: '',
      translation: '门槛',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5NIS9',
    created: 1737090074829,
    data: {
      language: 'da',
      source: 'disposition',
      ipa: 'disbosiˈɕoˀn',
      example:
        '* foretage en disposition\n* til fri disposition\n* en tilgængelig disposition af bogens stof',
      definition:
        '* det at beslutte noget\n* det at råde over noget og have ret til at bestemme hvordan det skal bruges\n* det at tilrettelægge og opbygge noget på en bestemt måde',
      translation: '决定, 支配, 安排, 处置',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TTocU',
    created: 1737090084505,
    data: {
      language: 'da',
      source: 'eftervirkning',
      ipa: '',
      example: 'psykiske eftervirkninger',
      definition: '',
      translation: '后果',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HBJn3',
    created: 1737090103589,
    data: {
      language: 'da',
      source: 'resultat',
      ipa: 'ʁεsulˈtæˀd',
      example: '* det endelige resultat\n* opnå resultater',
      definition:
        '* udfald, følge el. virkning af en proces, et forløb, en indsats e.l.\n* sejr, gevinst el. anden form for positivt udfald af en kamp el. en målrettet indsats\n* samlet over- el. underskud af en økonomisk virksomhed, opgjort i et regnskab som forskellen mellem omkostninger og indtægter',
      translation: '结果, 成果, 收益',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 's8EKQ',
    created: 1737090122814,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: 'ˈanʌˌkεnˀə',
      example:
        '* almindeligt anerkendt\n* officielt anerkendt\n* anerkende republikken Rusland som selvstændig stat',
      definition:
        '* erkende som sandt el. berettiget\n* godkende formelt; acceptere som værende juridisk gyldigt; om offentlig myndighed\n* erklære sin folkeretlige accept af en ny stat; om stat el. international organisation',
      translation: '承认, 认可',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SweXb',
    created: 1737090151204,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '-ˌvɑjˀə',
      example: 'overveje situationen',
      definition:
        'tænke over noget el. tænke på at gøre noget idet man vurderer hvad der taler for og imod',
      translation: '考虑',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wlGkc',
    created: 1737090179546,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: 'ˈhεli',
      example:
        '* hellige skrifter\n* hellig pligt\n* i demokratiets hellige navn',
      definition:
        '* som er forbundet med det guddommelige el. indeholder guddommelig kraft, og som derfor behandles med religiøs ærefrygt\n* som har krav på ærbødighed pga. sin betydningsfuldhed, skønhed e.l.\n* som står urokkeligt fast, er uopnåelig el. ukrænkelig',
      translation: '圣',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qcekx',
    created: 1737090199860,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '-ˌgɶˀʌ',
      example: 'retfærdiggøre en beslutning',
      definition:
        'berettigevise at noget er retfærdigt, rigtigt el. berettiget',
      translation: '证明, 辩护, 辩解',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'L6-ko',
    created: 1737090228076,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: 'fʌˈsœmˀə',
      example: '* indhente det forsømte\n* forsømte børn\n* forsømme skolen',
      definition:
        '* undlade at gøre noget som man bør gøre\n* undlade at tage sig af, passe el. pleje ordentligt\n* udeblive fra undervisning, arbejde e.l.; undlade at deltage i',
      translation: '忽视, 疏忽, 缺席',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3PP42',
    created: 1737090238158,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '-ˌtæˀlə',
      example: 'forsøge/prøve at overtale nogen',
      definition:
        'få nogen til (modstræbende) at gøre noget bestemt vha. indtrængende ord, argumenter, løfter e.l.',
      translation: '说服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gO0b_',
    created: 1737090268835,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: 'ˈgʁɑðˌviˀs',
      example: 'gradvis udvikling',
      definition: 'som foregår lidt efter lidt el. trinvis',
      translation: '逐渐的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iYxp8',
    created: 1737090278522,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: 'ˈempliˌsid',
      example: '',
      definition: '',
      translation: '隐含的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'N9RxP',
    created: 1737090306593,
    data: {
      language: 'da',
      source: 'især',
      ipa: 'iˈsεˀɐ̯',
      example: 'især skandinaver',
      definition:
        'bruges for at fremhæve det som har særlig betydning, el. det som udsagnet særlig gælder',
      translation: '特别, 尤其',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0X9X0',
    created: 1737090325891,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: 'ˈpʁʌmdə',
      example: 'en prompte reaktion',
      definition: 'øjeblikkelig; omgående',
      translation: '立即, 马上',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SoLJD',
    created: 1737090344977,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: 'ˈnoːənˈlɔnə',
      example:
        '* Vejret var nogenlunde på deres førdselsdag.\n* være nogenlunde sikker på at\n* nogenlunde samtidig',
      definition:
        '* ikke perfekt, men heller ikke utilfredsstillende; ret god når man tager omstændighederne i betragtning\n* i en (efter omstændighederne) tilstrækkelig el. tilfredsstillende grad; ret godt\n* omtrent; næsten',
      translation: '还不错, 差不多',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'RoHBN',
    created: 1737090365431,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: 'teˈsdʁagəli',
      example: 'i tilstrækkelig grad',
      definition:
        'af et omfang el. en kvalitet der er stor nok til at opfylde et bestemt behov, krav, ønske e.l.',
      translation: '足够的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'McRW-',
    created: 1737090384671,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '-ˌvɑˀɑnə',
      example: 'Vandkraft er vedvarende energi.',
      definition:
        'som består til stadighed; fx om uudtømmelige energiformer som solenergi og vindenergi',
      translation: '持续的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'FfIji',
    created: 1737090412831,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '-ˌfadənə',
      example: 'omfattende undersøgelser',
      definition:
        'som har et stort omfang el. kræver meget arbejde og mange resurser',
      translation: '广泛的, 全面的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PJGhx',
    created: 1737090440786,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: 'ˈdɑjli',
      example: '* dejligt vejr\n* dejlig lejlighed\n* dejlig middag',
      definition:
        '* som giver anledning til stor begejstring, glæde el. tilfredshed\n* bekvem og praktisk mht. indretning, udstyr e.l.; fx om bolig el. køretøj\n* som gør et overordentlig positivt indtryk på sanserne; æstetisk tiltalende',
      translation: '美好, 愉快, 宜人',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Wb1Um',
    created: 1737090460412,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: 'fʌˈsegdi',
      example:
        '* forsigtige skridt\n* gå forsigtig til værks\n* forsigtig optimisme',
      definition:
        '* omhyggelig og påpasselig i sine bevægelser for at undgå at skade el. ødelægge noget\n* som stilfærdigt holder sig tilbage og nødig handler el. udtaler sig uoverlagt\n* ikke på nogen måde overdreven el. overvældende; om handling, udtalelse e.l.',
      translation: '小心, 谨慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TKdlW',
    created: 1737090470275,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '-ˌsdʁεˀbənə',
      example: '',
      definition: '',
      translation: '勉强的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'GT-rM',
    created: 1737090481132,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: 'ˈvεˀsənli',
      example: '* spille en væsentlig rolle\n* væsenlig(t) dyrere',
      definition:
        '* som udgør el. vedrører en tings inderste og egentlige væsen, og som derfor er yderst vigtig\n* meget; betydelig',
      translation: '重要的, 显著的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
