import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'PTAfA',
    created: 1737090500620,
    data: {
      language: 'da',
      source: 'integritet',
      ipa: 'entəgʁiˈteˀd',
      example:
        '* den personlige integritet\n* territorial integritet\n* folketingsmedlemmernes personlige integritet',
      definition:
        '* (abstrakt) rum der omgiver nogen og adskiller vedkommende fra omgivelserne, beskytter mod krænkelser osv.\n* et lands ret til at være en uindskrænket, ukrænkelig helhed\n* en persons evne og vilje til at handle selvstændigt, ærligt og redeligt uden uvedkommende el. upassende hensyntagen til nogen el. noget',
      translation: '完整性, 正直, 誠信',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Um_o1',
    created: 1737090510688,
    data: {
      language: 'da',
      source: 'modstandsdygtighed',
      ipa: 'ˈmoðsdans-',
      example: '',
      definition: '',
      translation: '抗逆性',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AX3FK',
    created: 1737090520317,
    data: {
      language: 'da',
      source: 'tærskel',
      ipa: 'ˈtæɐ̯sgəl',
      example: 'træde (ind) over tærsklen',
      definition: '',
      translation: '門檻',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CgzaE',
    created: 1737090531304,
    data: {
      language: 'da',
      source: 'disposition',
      ipa: 'disbosiˈɕoˀn',
      example:
        '* foretage en disposition\n* til fri disposition\n* en tilgængelig disposition af bogens stof',
      definition:
        '* det at beslutte noget\n* det at råde over noget og have ret til at bestemme hvordan det skal bruges\n* det at tilrettelægge og opbygge noget på en bestemt måde',
      translation: '決定, 支配, 安排, 處置',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'VAxaG',
    created: 1737090541033,
    data: {
      language: 'da',
      source: 'eftervirkning',
      ipa: '',
      example: 'psykiske eftervirkninger',
      definition: '',
      translation: '後遺症',
      partOfSpeech: 'noun',
      g: 'common',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rZGwd',
    created: 1737090560286,
    data: {
      language: 'da',
      source: 'resultat',
      ipa: 'ʁεsulˈtæˀd',
      example: '* det endelige resultat\n* opnå resultater',
      definition:
        '* udfald, følge el. virkning af en proces, et forløb, en indsats e.l.\n* sejr, gevinst el. anden form for positivt udfald af en kamp el. en målrettet indsats\n* samlet over- el. underskud af en økonomisk virksomhed, opgjort i et regnskab som forskellen mellem omkostninger og indtægter',
      translation: '結果, 成效, 收益',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A2dgh',
    created: 1737090579745,
    data: {
      language: 'da',
      source: 'anerkende',
      ipa: 'ˈanʌˌkεnˀə',
      example:
        '* almindeligt anerkendt\n* officielt anerkendt\n* anerkende republikken Rusland som selvstændig stat',
      definition:
        '* erkende som sandt el. berettiget\n* godkende formelt; acceptere som værende juridisk gyldigt; om offentlig myndighed\n* erklære sin folkeretlige accept af en ny stat; om stat el. international organisation',
      translation: '承認, 認可, 接受',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'j-Icd',
    created: 1737090607766,
    data: {
      language: 'da',
      source: 'overveje',
      ipa: '-ˌvɑjˀə',
      example: 'overveje situationen',
      definition:
        'tænke over noget el. tænke på at gøre noget idet man vurderer hvad der taler for og imod',
      translation: '考慮',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Sr4NA',
    created: 1737090635877,
    data: {
      language: 'da',
      source: 'hellig',
      ipa: 'ˈhεli',
      example:
        '* hellige skrifter\n* hellig pligt\n* i demokratiets hellige navn',
      definition:
        '* som er forbundet med det guddommelige el. indeholder guddommelig kraft, og som derfor behandles med religiøs ærefrygt\n* som har krav på ærbødighed pga. sin betydningsfuldhed, skønhed e.l.\n* som står urokkeligt fast, er uopnåelig el. ukrænkelig',
      translation: '聖',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wRAh7',
    created: 1737090655316,
    data: {
      language: 'da',
      source: 'retfærdiggøre',
      ipa: '-ˌgɶˀʌ',
      example: 'retfærdiggøre en beslutning',
      definition:
        'berettigevise at noget er retfærdigt, rigtigt el. berettiget',
      translation: '辯解, 合理化',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zz0Lo',
    created: 1737090683369,
    data: {
      language: 'da',
      source: 'forsømme',
      ipa: 'fʌˈsœmˀə',
      example: '* indhente det forsømte\n* forsømte børn\n* forsømme skolen',
      definition:
        '* undlade at gøre noget som man bør gøre\n* undlade at tage sig af, passe el. pleje ordentligt\n* udeblive fra undervisning, arbejde e.l.; undlade at deltage i',
      translation: '忽視, 疏忽, 缺席',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HLJBv',
    created: 1737090702757,
    data: {
      language: 'da',
      source: 'overtale',
      ipa: '-ˌtæˀlə',
      example: 'forsøge/prøve at overtale nogen',
      definition:
        'få nogen til (modstræbende) at gøre noget bestemt vha. indtrængende ord, argumenter, løfter e.l.',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tvpEd',
    created: 1737090723213,
    data: {
      language: 'da',
      source: 'gradvis',
      ipa: 'ˈgʁɑðˌviˀs',
      example: 'gradvis udvikling',
      definition: 'som foregår lidt efter lidt el. trinvis',
      translation: '逐漸, 逐漸的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0VT_F',
    created: 1737090733110,
    data: {
      language: 'da',
      source: 'implicit',
      ipa: 'ˈempliˌsid',
      example: '',
      definition: '',
      translation: '隱含的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'vAVny',
    created: 1737090761305,
    data: {
      language: 'da',
      source: 'især',
      ipa: 'iˈsεˀɐ̯',
      example: 'især skandinaver',
      definition:
        'bruges for at fremhæve det som har særlig betydning, el. det som udsagnet særlig gælder',
      translation: '特別, 尤其, 特別是',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SQ-Pi',
    created: 1737090780861,
    data: {
      language: 'da',
      source: 'prompte',
      ipa: 'ˈpʁʌmdə',
      example: 'en prompte reaktion',
      definition: 'øjeblikkelig; omgående',
      translation: '立即, 立刻',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Vxbn1',
    created: 1737090791520,
    data: {
      language: 'da',
      source: 'nogenlunde',
      ipa: 'ˈnoːənˈlɔnə',
      example:
        '* Vejret var nogenlunde på deres førdselsdag.\n* være nogenlunde sikker på at\n* nogenlunde samtidig',
      definition:
        '* ikke perfekt, men heller ikke utilfredsstillende; ret god når man tager omstændighederne i betragtning\n* i en (efter omstændighederne) tilstrækkelig el. tilfredsstillende grad; ret godt\n* omtrent; næsten',
      translation: '還可以, 差不多',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yMk4n',
    created: 1737090810657,
    data: {
      language: 'da',
      source: 'tilstrækkelig',
      ipa: 'teˈsdʁagəli',
      example: 'i tilstrækkelig grad',
      definition:
        'af et omfang el. en kvalitet der er stor nok til at opfylde et bestemt behov, krav, ønske e.l.',
      translation: '足夠',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'XBBhf',
    created: 1737090838629,
    data: {
      language: 'da',
      source: 'vedvarende',
      ipa: '-ˌvɑˀɑnə',
      example: 'Vandkraft er vedvarende energi.',
      definition:
        'som består til stadighed; fx om uudtømmelige energiformer som solenergi og vindenergi',
      translation: '持續的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'L-pUw',
    created: 1737090866583,
    data: {
      language: 'da',
      source: 'omfattende',
      ipa: '-ˌfadənə',
      example: 'omfattende undersøgelser',
      definition:
        'som har et stort omfang el. kræver meget arbejde og mange resurser',
      translation: '廣泛的, 全面的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ryHhY',
    created: 1737090886435,
    data: {
      language: 'da',
      source: 'dejlig',
      ipa: 'ˈdɑjli',
      example: '* dejligt vejr\n* dejlig lejlighed\n* dejlig middag',
      definition:
        '* som giver anledning til stor begejstring, glæde el. tilfredshed\n* bekvem og praktisk mht. indretning, udstyr e.l.; fx om bolig el. køretøj\n* som gør et overordentlig positivt indtryk på sanserne; æstetisk tiltalende',
      translation: '美好, 愉快, 舒適, 美好的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_8jqt',
    created: 1737090905621,
    data: {
      language: 'da',
      source: 'forsigtig',
      ipa: 'fʌˈsegdi',
      example:
        '* forsigtige skridt\n* gå forsigtig til værks\n* forsigtig optimisme',
      definition:
        '* omhyggelig og påpasselig i sine bevægelser for at undgå at skade el. ødelægge noget\n* som stilfærdigt holder sig tilbage og nødig handler el. udtaler sig uoverlagt\n* ikke på nogen måde overdreven el. overvældende; om handling, udtalelse e.l.',
      translation: '小心, 謹慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hl8-Z',
    created: 1737090915261,
    data: {
      language: 'da',
      source: 'modstræbende',
      ipa: '-ˌsdʁεˀbənə',
      example: '',
      definition: '',
      translation: '不情願的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'GBqb-',
    created: 1737090935817,
    data: {
      language: 'da',
      source: 'væsentlig',
      ipa: 'ˈvεˀsənli',
      example: '* spille en væsentlig rolle\n* væsenlig(t) dyrere',
      definition:
        '* som udgør el. vedrører en tings inderste og egentlige væsen, og som derfor er yderst vigtig\n* meget; betydelig',
      translation: '重要的, 本質的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
