import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'L8-rc',
    created: 1736963415066,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: 'ɪntegriˈtɛːt',
      example: 'Ihre Integrität steht außer Zweifel.',
      definition: '',
      translation: 'ინტეგრიტეტი',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WsAi0',
    created: 1736963415904,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: 'ˈviːdɐʃtanʦfɛːɪçkait',
      example: 'die Widerstandsfähigkeit eines Materials testen',
      definition: '',
      translation: 'გამძლეობა',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uH1rX',
    created: 1736963416847,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: 'ˈʃvɛlə',
      example:
        '* die Braut über die Schwelle tragen\n* Schwellen legen\n* Die Hemmschwelle, so etwas zu tun, ist hoch.',
      definition:
        '* Abschluss einer Türöffnung am Fußboden\n* eines der Stücke Holz oder Beton, auf denen die Schienen liegen\n* äußerstes Maß von etwas',
      translation: 'საფეხური',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6jzVv',
    created: 1736963417785,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: 'ˈan|ɔrdnʊŋ',
      example:
        '* eine gefällige Anordnung der Blumen in Vasen\n* eine Anordnung befolgen',
      definition: '',
      translation: 'დაწყება',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7rewv',
    created: 1736963418656,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: 'ˈausvɪrkʊŋ',
      example: 'Diese Substanz könnte Auswirkungen auf die Gesundheit haben.',
      definition: '',
      translation: 'შედეგი',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uqkYR',
    created: 1736963419799,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: 'ɛɐˈgeːpnɪs',
      example:
        '* Das Ergebnis zu Aufgabe 2 lautet 32.\n* ein gutes Wahlergebnis erzielen\n* Zu welchem Ergebnis ist der Ausschuss gekommen?',
      definition:
        '* Die Zahl, die man bekommt, wenn man etwas berechnet\n* Folge eines Ereignisses / einer Handlung\n* das, was beim Nachdenken herauskommt',
      translation: 'შედეგი',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ht2tB',
    created: 1736963420567,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: 'ˈan|ɛɐkɛnən',
      example:
        '* anerkennende Worte\n* Wird mein Führerschein in den USA anerkannt?\n* Du musst anerkennen, dass er sich bemüht hat.',
      definition:
        '* positiv beurteilen\n* offiziell als gültig akzeptieren\n* respektieren oder akzeptieren',
      translation: 'აღიარება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UlsS6',
    created: 1736963421687,
    data: {
      language: 'de',
      source: 'halten',
      ipa: 'ˈhaltən',
      example:
        '* Er hielt sich den Kopf vor Schmerzen.\n* die Arme gestreckt halten\n* Der Reifen hält die Luft nicht mehr.',
      definition:
        '* mit der Hand o. Ä. fassen und nicht loslassen\n* in eine Position bringen und in dieser Position lassen\n* bewirken, dass etwas an einer Stelle bleibt',
      translation: 'დაბრუნება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NgJ9E',
    created: 1736963422536,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: 'ˈvɪtmən',
      example:
        '* Er hat seinen ersten Roman seiner Mutter gewidmet.\n* sein Leben dem Kampf gegen die Armut widmen',
      definition:
        '* jemandem als Ausdruck der Verbundenheit etwas symbolisch schenken\n* ausschließlich für jemanden / etwas verwenden',
      translation: 'უძღვნა',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mYp1i',
    created: 1736963423520,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: 'ˈrɛçtfɛrtɪgən',
      example: '',
      definition: '',
      translation: 'მართლება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PX6u0',
    created: 1736963424559,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: 'fɛɐˈnaːxlɛsɪgʊŋ',
      example: 'die Vernachlässigung seiner Pflichten',
      definition: '',
      translation: 'მიტოვება',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2TzrP',
    created: 1736963426148,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: 'yːbɐˈreːdən',
      example: 'Er ließ sich zum Kauf des Autos überreden.',
      definition:
        'so lange mit jemandem sprechen, bis er nachgibt und etwas tut',
      translation: 'დარწმუნება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f_is2',
    created: 1736963427012,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: 'ˈʃrɪtvaizə',
      example: 'etwas wird schrittweise eingeführt / geändert',
      definition: '',
      translation: 'ნაბიჯ-ნაბიჯ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NNueW',
    created: 1736963427970,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: 'ɪmpliˈʦiːt',
      example: '',
      definition:
        'in einer Äußerung indirekt enthalten, aber nicht ausdrücklich gesagt',
      translation: 'იმპლიციტური',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8weVX',
    created: 1736963428690,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'მთავარად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gTku2',
    created: 1736963429839,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: 'zoˈfɔrt',
      example: '* Soforthilfe\n* Einen Moment, ich komme sofort!',
      definition: '* ohne Pause oder Verzögerung\n* in ganz kurzer Zeit',
      translation: 'მალევე',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'k3CGP',
    created: 1736963431438,
    data: {
      language: 'de',
      source: 'rund',
      ipa: 'rʊnt',
      example:
        '* runde und eckige Bausteine\n* Im fünften Monat wird ihr Bauch allmählich rund.\n* ein Tisch mit runden Kanten',
      definition:
        '* mit einem Kreis als Grundform\n* mit viel Fleisch, gewölbt\n* nicht kantig',
      translation: 'მრგვალი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dExMb',
    created: 1736963432545,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: 'ˈausraiçənt',
      example:
        '* in ausreichender Zahl / Menge vorhanden sein\n* ein Ausreichend bekommen',
      definition:
        '* so, dass es nicht zu wenig ist\n* relativ schlechte Note an deutschen Schulen, mit der man eine Prüfung aber noch bestanden hat',
      translation: 'კმარა',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N6EA1',
    created: 1736963433407,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: 'ˈhartnɛkɪç',
      example:
        '* trotz hartnäckiger Versuche nichts erreichen\n* Er hat eine sehr hartnäckige Akne.',
      definition:
        '* ein Ziel oder Verhalten mit Ausdauer verfolgend\n* lang anhaltend, nicht wegzubekommen',
      translation: 'მტკიცე',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9SVnF',
    created: 1736963436086,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: 'ʊmˈfasənt',
      example:
        '* umfassende Kenntnisse in einem Gebiet haben\n* ein umfassendes Geständnis ablegen',
      definition: '* sehr vieles beinhaltend, erfassend\n* vollständig',
      translation: 'მთლიანად',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ywmex',
    created: 1736963436870,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: 'ɛntˈʦʏkənt',
      example: 'Was für ein entzückendes Mädchen / Kleid!',
      definition: '',
      translation: 'მხიარული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GU5cW',
    created: 1736963437958,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: 'ʦuˈrʏkhaltənt',
      example:
        '* eine zurückhaltende Schülerin\n* eine zurückhaltende Wachstumsprognose',
      definition:
        '* ruhig und unauffällig, sich nicht um Aufmerksamkeit bemühend\n* wenig intensiv, emotional oder ausgeprägt',
      translation: 'დაბალანსებული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ng4aP',
    created: 1736963439001,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: 'ˈviːdɐvɪlɪç',
      example: 'ein widerwilliges Zugeständnis',
      definition: '',
      translation: 'მიუხედავად სურვილისა',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EVu8-',
    created: 1736963439882,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: "bə'dɔytzaːm",
      example:
        '* eine bedeutsame Entwicklung / Leistung\n* Sie warf ihm einen bedeutsamen Blick zu.',
      definition: '* bedeutend\n* ohne Worte Informationen gebend',
      translation: 'მნიშვნელოვანი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
