import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'e7wAW',
    created: 1736962639233,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: 'ɪntegriˈtɛːt',
      example: 'Ihre Integrität steht außer Zweifel.',
      definition: '',
      translation: 'integriteit',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c8F-J',
    created: 1736962640053,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: 'ˈviːdɐʃtanʦfɛːɪçkait',
      example: 'die Widerstandsfähigkeit eines Materials testen',
      definition: '',
      translation: 'weerstandsvermogen, weerstandvermogen',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FCypA',
    created: 1736962641171,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: 'ˈʃvɛlə',
      example:
        '* die Braut über die Schwelle tragen\n* Schwellen legen\n* Die Hemmschwelle, so etwas zu tun, ist hoch.',
      definition:
        '* Abschluss einer Türöffnung am Fußboden\n* eines der Stücke Holz oder Beton, auf denen die Schienen liegen\n* äußerstes Maß von etwas',
      translation: 'drempel, biels, grens',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DAV5F',
    created: 1736962642028,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: 'ˈan|ɔrdnʊŋ',
      example:
        '* eine gefällige Anordnung der Blumen in Vasen\n* eine Anordnung befolgen',
      definition: '',
      translation: 'ordening, bevel',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ik_QW',
    created: 1736962643242,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: 'ˈausvɪrkʊŋ',
      example: 'Diese Substanz könnte Auswirkungen auf die Gesundheit haben.',
      definition: '',
      translation: 'gevolg, effect',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0nJi4',
    created: 1736962644254,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: 'ɛɐˈgeːpnɪs',
      example:
        '* Das Ergebnis zu Aufgabe 2 lautet 32.\n* ein gutes Wahlergebnis erzielen\n* Zu welchem Ergebnis ist der Ausschuss gekommen?',
      definition:
        '* Die Zahl, die man bekommt, wenn man etwas berechnet\n* Folge eines Ereignisses / einer Handlung\n* das, was beim Nachdenken herauskommt',
      translation: 'resultaat',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AUgXz',
    created: 1736962645114,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: 'ˈan|ɛɐkɛnən',
      example:
        '* anerkennende Worte\n* Wird mein Führerschein in den USA anerkannt?\n* Du musst anerkennen, dass er sich bemüht hat.',
      definition:
        '* positiv beurteilen\n* offiziell als gültig akzeptieren\n* respektieren oder akzeptieren',
      translation: 'erkennen, goedkeuren, officieel als geldig accepteren',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VsIfz',
    created: 1736962645727,
    data: {
      language: 'de',
      source: 'houden',
      ipa: '',
      example: '',
      definition: '',
      translation: 'houden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_eGnj',
    created: 1736962647240,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: 'ˈvɪtmən',
      example:
        '* Er hat seinen ersten Roman seiner Mutter gewidmet.\n* sein Leben dem Kampf gegen die Armut widmen',
      definition:
        '* jemandem als Ausdruck der Verbundenheit etwas symbolisch schenken\n* ausschließlich für jemanden / etwas verwenden',
      translation: 'opdragen, wijden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0d4HK',
    created: 1736962648258,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: 'ˈrɛçtfɛrtɪgən',
      example: '',
      definition: '',
      translation: 'rechtvaardigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dxih8',
    created: 1736962649126,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: 'fɛɐˈnaːxlɛsɪgʊŋ',
      example: 'die Vernachlässigung seiner Pflichten',
      definition: '',
      translation: 'verwaarlozing',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SZXEn',
    created: 1736962650344,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: 'yːbɐˈreːdən',
      example: 'Er ließ sich zum Kauf des Autos überreden.',
      definition:
        'so lange mit jemandem sprechen, bis er nachgibt und etwas tut',
      translation: 'overhalen, overtuigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VwrY1',
    created: 1736962651172,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: 'ˈʃrɪtvaizə',
      example: 'etwas wird schrittweise eingeführt / geändert',
      definition: '',
      translation: 'geleidelijk, stapsgewijs',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'liQJl',
    created: 1736962652250,
    data: {
      language: 'de',
      source: 'impliziet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'impliciet',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eAB3S',
    created: 1736962653362,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vooral',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pburr',
    created: 1736962654570,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: 'zoˈfɔrt',
      example: '* Soforthilfe\n* Einen Moment, ich komme sofort!',
      definition: '* ohne Pause oder Verzögerung\n* in ganz kurzer Zeit',
      translation: 'onmiddellijk, ogenblikkelijk, zo',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zx86d',
    created: 1736962655524,
    data: {
      language: 'de',
      source: 'rond',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rond',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CjHSX',
    created: 1736962656577,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: 'ˈausraiçənt',
      example:
        '* in ausreichender Zahl / Menge vorhanden sein\n* ein Ausreichend bekommen',
      definition:
        '* so, dass es nicht zu wenig ist\n* relativ schlechte Note an deutschen Schulen, mit der man eine Prüfung aber noch bestanden hat',
      translation: 'genoeg, voldoende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wF1Jk',
    created: 1736962660162,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: 'ˈhartnɛkɪç',
      example:
        '* trotz hartnäckiger Versuche nichts erreichen\n* Er hat eine sehr hartnäckige Akne.',
      definition:
        '* ein Ziel oder Verhalten mit Ausdauer verfolgend\n* lang anhaltend, nicht wegzubekommen',
      translation: 'hardnekkig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SS_lW',
    created: 1736962660961,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: 'ʊmˈfasənt',
      example:
        '* umfassende Kenntnisse in einem Gebiet haben\n* ein umfassendes Geständnis ablegen',
      definition: '* sehr vieles beinhaltend, erfassend\n* vollständig',
      translation: 'omvattend, volledig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xaulB',
    created: 1736962661990,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: 'ɛntˈʦʏkənt',
      example: 'Was für ein entzückendes Mädchen / Kleid!',
      definition: '',
      translation: 'schitterend, verrukkelijk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '160r9',
    created: 1736962662945,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: 'ʦuˈrʏkhaltənt',
      example:
        '* eine zurückhaltende Schülerin\n* eine zurückhaltende Wachstumsprognose',
      definition:
        '* ruhig und unauffällig, sich nicht um Aufmerksamkeit bemühend\n* wenig intensiv, emotional oder ausgeprägt',
      translation: 'terughoudend, gematigd',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OrB3q',
    created: 1736962663836,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: 'ˈviːdɐvɪlɪç',
      example: 'ein widerwilliges Zugeständnis',
      definition: '',
      translation: 'met tegenzin, tegenstribbelend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C9tDX',
    created: 1736962664762,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: "bə'dɔytzaːm",
      example:
        '* eine bedeutsame Entwicklung / Leistung\n* Sie warf ihm einen bedeutsamen Blick zu.',
      definition: '* bedeutend\n* ohne Worte Informationen gebend',
      translation: 'belangrijk, veelzeggend, betekenisvol',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
