import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'MRC1v',
    created: 1736962932321,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: 'ɪntegriˈtɛːt',
      example: 'Ihre Integrität steht außer Zweifel.',
      definition: '',
      translation: 'integritet',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GoR4J',
    created: 1736962933474,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: 'ˈviːdɐʃtanʦfɛːɪçkait',
      example: 'die Widerstandsfähigkeit eines Materials testen',
      definition: '',
      translation: 'motstandsdyktighet, motstandskraft',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mJHWq',
    created: 1736962937302,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: 'ˈʃvɛlə',
      example:
        '* die Braut über die Schwelle tragen\n* Schwellen legen\n* Die Hemmschwelle, so etwas zu tun, ist hoch.',
      definition:
        '* Abschluss einer Türöffnung am Fußboden\n* eines der Stücke Holz oder Beton, auf denen die Schienen liegen\n* äußerstes Maß von etwas',
      translation: 'terskel, sville, grense',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6Ma_L',
    created: 1736962938334,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: 'ˈan|ɔrdnʊŋ',
      example:
        '* eine gefällige Anordnung der Blumen in Vasen\n* eine Anordnung befolgen',
      definition: '',
      translation: 'systematisering, arrangement, forordning, pålegg',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aItGC',
    created: 1736962939232,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: 'ˈausvɪrkʊŋ',
      example: 'Diese Substanz könnte Auswirkungen auf die Gesundheit haben.',
      definition: '',
      translation: 'følge, konsekvens, innvirkning, påvirkning',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'No96o',
    created: 1736962940538,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: 'ɛɐˈgeːpnɪs',
      example:
        '* Das Ergebnis zu Aufgabe 2 lautet 32.\n* ein gutes Wahlergebnis erzielen\n* Zu welchem Ergebnis ist der Ausschuss gekommen?',
      definition:
        '* Die Zahl, die man bekommt, wenn man etwas berechnet\n* Folge eines Ereignisses / einer Handlung\n* das, was beim Nachdenken herauskommt',
      translation: 'svar, resultat',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2bvFP',
    created: 1736962941332,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: 'ˈan|ɛɐkɛnən',
      example:
        '* anerkennende Worte\n* Wird mein Führerschein in den USA anerkannt?\n* Du musst anerkennen, dass er sich bemüht hat.',
      definition:
        '* positiv beurteilen\n* offiziell als gültig akzeptieren\n* respektieren oder akzeptieren',
      translation: 'anerkjenne, godta, vedkjenne seg',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZM0sQ',
    created: 1736962942295,
    data: {
      language: 'de',
      source: 'halten',
      ipa: 'ˈhaltən',
      example:
        '* Er hielt sich den Kopf vor Schmerzen.\n* die Arme gestreckt halten\n* Der Reifen hält die Luft nicht mehr.',
      definition:
        '* mit der Hand o. Ä. fassen und nicht loslassen\n* in eine Position bringen und in dieser Position lassen\n* bewirken, dass etwas an einer Stelle bleibt',
      translation:
        'holde (fast), holde, holde (tilbake), holde seg, holde ut, holde stand, forelese, undervise, stanse',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TW-k_',
    created: 1736962943089,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: 'ˈvɪtmən',
      example:
        '* Er hat seinen ersten Roman seiner Mutter gewidmet.\n* sein Leben dem Kampf gegen die Armut widmen',
      definition:
        '* jemandem als Ausdruck der Verbundenheit etwas symbolisch schenken\n* ausschließlich für jemanden / etwas verwenden',
      translation: 'tilegne, dedisere, vie, vige',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tIWEQ',
    created: 1736962944373,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: 'ˈrɛçtfɛrtɪgən',
      example: '',
      definition: '',
      translation: 'rettferdiggjøre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GyvMh',
    created: 1736962945553,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: 'fɛɐˈnaːxlɛsɪgʊŋ',
      example: 'die Vernachlässigung seiner Pflichten',
      definition: '',
      translation: 'vanskjøtting, neglisjering, forsømmelse',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ehoz9',
    created: 1736962946345,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: 'yːbɐˈreːdən',
      example: 'Er ließ sich zum Kauf des Autos überreden.',
      definition:
        'so lange mit jemandem sprechen, bis er nachgibt und etwas tut',
      translation: 'overtale',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f8A14',
    created: 1736962947233,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: 'ˈʃrɪtvaizə',
      example: 'etwas wird schrittweise eingeführt / geändert',
      definition: '',
      translation: 'trinn for trinn, trinnvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'go72J',
    created: 1736962948011,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: 'ɪmpliˈʦiːt',
      example: '',
      definition:
        'in einer Äußerung indirekt enthalten, aber nicht ausdrücklich gesagt',
      translation: 'implisitt, underforstått',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vok4S',
    created: 1736962948926,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'først og fremst',
      partOfSpeech: 'phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QqA6U',
    created: 1736962949701,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: 'zoˈfɔrt',
      example: '* Soforthilfe\n* Einen Moment, ich komme sofort!',
      definition: '* ohne Pause oder Verzögerung\n* in ganz kurzer Zeit',
      translation:
        'om et øyeblikk, straks, øyeblikkelig, med det samme, umiddelbart',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LoxCZ',
    created: 1736962950713,
    data: {
      language: 'de',
      source: 'rund',
      ipa: 'rʊnt',
      example:
        '* runde und eckige Bausteine\n* Im fünften Monat wird ihr Bauch allmählich rund.\n* ein Tisch mit runden Kanten',
      definition:
        '* mit einem Kreis als Grundform\n* mit viel Fleisch, gewölbt\n* nicht kantig',
      translation: 'rund, yppig, lubben',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SPyEu',
    created: 1736962952023,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: 'ˈausraiçənt',
      example:
        '* in ausreichender Zahl / Menge vorhanden sein\n* ein Ausreichend bekommen',
      definition:
        '* so, dass es nicht zu wenig ist\n* relativ schlechte Note an deutschen Schulen, mit der man eine Prüfung aber noch bestanden hat',
      translation:
        'tilstrekkelig, nok, firer: relativt dårlig karakter på tyske skoler, men nok til å bestå en eksamen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'x_VJa',
    created: 1736962952910,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: 'ˈhartnɛkɪç',
      example:
        '* trotz hartnäckiger Versuche nichts erreichen\n* Er hat eine sehr hartnäckige Akne.',
      definition:
        '* ein Ziel oder Verhalten mit Ausdauer verfolgend\n* lang anhaltend, nicht wegzubekommen',
      translation: 'hardnakket, fast bestemt, sta',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MbT55',
    created: 1736962954126,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: 'ʊmˈfasənt',
      example:
        '* umfassende Kenntnisse in einem Gebiet haben\n* ein umfassendes Geständnis ablegen',
      definition: '* sehr vieles beinhaltend, erfassend\n* vollständig',
      translation: 'omfattende, fullstendig, komplett',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ezKlG',
    created: 1736962955093,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: 'ɛntˈʦʏkənt',
      example: 'Was für ein entzückendes Mädchen / Kleid!',
      definition: '',
      translation: 'bedårende, deilig, fortryllende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rfSKn',
    created: 1736962956210,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: 'ʦuˈrʏkhaltənt',
      example:
        '* eine zurückhaltende Schülerin\n* eine zurückhaltende Wachstumsprognose',
      definition:
        '* ruhig und unauffällig, sich nicht um Aufmerksamkeit bemühend\n* wenig intensiv, emotional oder ausgeprägt',
      translation:
        'reservert, kjølig, avmålt, tilbakeholden, utilnærmelig, forsiktig, behersket',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PE_0K',
    created: 1736962957080,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: 'ˈviːdɐvɪlɪç',
      example: 'ein widerwilliges Zugeständnis',
      definition: '',
      translation: 'motstrebende, motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rWEwk',
    created: 1736962958230,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: "bə'dɔytzaːm",
      example:
        '* eine bedeutsame Entwicklung / Leistung\n* Sie warf ihm einen bedeutsamen Blick zu.',
      definition: '* bedeutend\n* ohne Worte Informationen gebend',
      translation: 'betydelig, viktig, betydningsfull, megetsigende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
