import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'kBQzU',
    created: 1736962904039,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: 'ɪntegriˈtɛːt',
      example: 'Ihre Integrität steht außer Zweifel.',
      definition: '',
      translation: 'integritet',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Qmfk1',
    created: 1736962905211,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: 'ˈviːdɐʃtanʦfɛːɪçkait',
      example: 'die Widerstandsfähigkeit eines Materials testen',
      definition: '',
      translation: 'motståndskraft',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'l-MaN',
    created: 1736962906142,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: 'ˈʃvɛlə',
      example:
        '* die Braut über die Schwelle tragen\n* Schwellen legen\n* Die Hemmschwelle, so etwas zu tun, ist hoch.',
      definition:
        '* Abschluss einer Türöffnung am Fußboden\n* eines der Stücke Holz oder Beton, auf denen die Schienen liegen\n* äußerstes Maß von etwas',
      translation: 'tröskel, syll, sliper',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1BVts',
    created: 1736962907306,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: 'ˈan|ɔrdnʊŋ',
      example:
        '* eine gefällige Anordnung der Blumen in Vasen\n* eine Anordnung befolgen',
      definition: '',
      translation: 'anordning, arrangemang, föreskrift, direktiv, order',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Arow8',
    created: 1736962908215,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: 'ˈausvɪrkʊŋ',
      example: 'Diese Substanz könnte Auswirkungen auf die Gesundheit haben.',
      definition: '',
      translation: 'verkan, effekt, följd, påverkan',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vHNGp',
    created: 1736962909083,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: 'ɛɐˈgeːpnɪs',
      example:
        '* Das Ergebnis zu Aufgabe 2 lautet 32.\n* ein gutes Wahlergebnis erzielen\n* Zu welchem Ergebnis ist der Ausschuss gekommen?',
      definition:
        '* Die Zahl, die man bekommt, wenn man etwas berechnet\n* Folge eines Ereignisses / einer Handlung\n* das, was beim Nachdenken herauskommt',
      translation: 'resultat, svar',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9w3Mw',
    created: 1736962910081,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: 'ˈan|ɛɐkɛnən',
      example:
        '* anerkennende Worte\n* Wird mein Führerschein in den USA anerkannt?\n* Du musst anerkennen, dass er sich bemüht hat.',
      definition:
        '* positiv beurteilen\n* offiziell als gültig akzeptieren\n* respektieren oder akzeptieren',
      translation: 'erkänna, godkänna, uppskatta, kännas vid, medge',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6STJ9',
    created: 1736962911878,
    data: {
      language: 'de',
      source: 'halten',
      ipa: 'ˈhaltən',
      example:
        '* Er hielt sich den Kopf vor Schmerzen.\n* die Arme gestreckt halten\n* Der Reifen hält die Luft nicht mehr.',
      definition:
        '* mit der Hand o. Ä. fassen und nicht loslassen\n* in eine Position bringen und in dieser Position lassen\n* bewirken, dass etwas an einer Stelle bleibt',
      translation:
        'hålla, hålla i, hålla fast, hålla kvar, behålla, hålla i sig, rädda, ha, föreläsa, stanna',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JhjTE',
    created: 1736962914110,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: 'ˈvɪtmən',
      example:
        '* Er hat seinen ersten Roman seiner Mutter gewidmet.\n* sein Leben dem Kampf gegen die Armut widmen',
      definition:
        '* jemandem als Ausdruck der Verbundenheit etwas symbolisch schenken\n* ausschließlich für jemanden / etwas verwenden',
      translation: 'tillägna, dedicera, ägna',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PHYp0',
    created: 1736962915157,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: 'ˈrɛçtfɛrtɪgən',
      example: '',
      definition: '',
      translation: 'rättfärdiga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ccI4J',
    created: 1736962916479,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: 'fɛɐˈnaːxlɛsɪgʊŋ',
      example: 'die Vernachlässigung seiner Pflichten',
      definition: '',
      translation: 'försummelse, misskötsel, vanskötsel',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zmtII',
    created: 1736962917586,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: 'yːbɐˈreːdən',
      example: 'Er ließ sich zum Kauf des Autos überreden.',
      definition:
        'so lange mit jemandem sprechen, bis er nachgibt und etwas tut',
      translation: 'övertala',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'X8tOu',
    created: 1736962918328,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: 'ˈʃrɪtvaizə',
      example: 'etwas wird schrittweise eingeführt / geändert',
      definition: '',
      translation: 'stegvis, gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lwgL5',
    created: 1736962919785,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: 'ɪmpliˈʦiːt',
      example: '',
      definition:
        'in einer Äußerung indirekt enthalten, aber nicht ausdrücklich gesagt',
      translation: 'implicita',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jC453',
    created: 1736962920644,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'framför allt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zZ_VT',
    created: 1736962921430,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: 'zoˈfɔrt',
      example: '* Soforthilfe\n* Einen Moment, ich komme sofort!',
      definition: '* ohne Pause oder Verzögerung\n* in ganz kurzer Zeit',
      translation: 'genast, med detsamma, omedelbart, strax',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GcGRe',
    created: 1736962922970,
    data: {
      language: 'de',
      source: 'rund',
      ipa: 'rʊnt',
      example:
        '* runde und eckige Bausteine\n* Im fünften Monat wird ihr Bauch allmählich rund.\n* ein Tisch mit runden Kanten',
      definition:
        '* mit einem Kreis als Grundform\n* mit viel Fleisch, gewölbt\n* nicht kantig',
      translation: 'rund, jämn',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CpVoa',
    created: 1736962924082,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: 'ˈausraiçənt',
      example:
        '* in ausreichender Zahl / Menge vorhanden sein\n* ein Ausreichend bekommen',
      definition:
        '* so, dass es nicht zu wenig ist\n* relativ schlechte Note an deutschen Schulen, mit der man eine Prüfung aber noch bestanden hat',
      translation: 'tillräcklig, fyra',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ARFm6',
    created: 1736962925178,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: 'ˈhartnɛkɪç',
      example:
        '* trotz hartnäckiger Versuche nichts erreichen\n* Er hat eine sehr hartnäckige Akne.',
      definition:
        '* ein Ziel oder Verhalten mit Ausdauer verfolgend\n* lang anhaltend, nicht wegzubekommen',
      translation: 'hårdnackad, envis, enveten',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4Wq92',
    created: 1736962926431,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: 'ʊmˈfasənt',
      example:
        '* umfassende Kenntnisse in einem Gebiet haben\n* ein umfassendes Geständnis ablegen',
      definition: '* sehr vieles beinhaltend, erfassend\n* vollständig',
      translation: 'omfattande, fullständig, uttömmande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pyk44',
    created: 1736962927402,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: 'ɛntˈʦʏkənt',
      example: 'Was für ein entzückendes Mädchen / Kleid!',
      definition: '',
      translation: 'förtjusande, hänförande, bedårande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4o1FI',
    created: 1736962928430,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: 'ʦuˈrʏkhaltənt',
      example:
        '* eine zurückhaltende Schülerin\n* eine zurückhaltende Wachstumsprognose',
      definition:
        '* ruhig und unauffällig, sich nicht um Aufmerksamkeit bemühend\n* wenig intensiv, emotional oder ausgeprägt',
      translation: 'tillbakadragen, reserverad, återhållsam, svag',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_Unl9',
    created: 1736962929637,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: 'ˈviːdɐvɪlɪç',
      example: 'ein widerwilliges Zugeständnis',
      definition: '',
      translation: 'motvillig, ovillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dZaEh',
    created: 1736962931432,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: "bə'dɔytzaːm",
      example:
        '* eine bedeutsame Entwicklung / Leistung\n* Sie warf ihm einen bedeutsamen Blick zu.',
      definition: '* bedeutend\n* ohne Worte Informationen gebend',
      translation: 'betydelsefull, meningsfull',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
