import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'iwjid',
    created: 1736962747335,
    data: {
      language: 'de',
      source: 'die Integrität',
      ipa: 'ɪntegriˈtɛːt',
      example: 'Ihre Integrität steht außer Zweifel.',
      definition: '',
      translation: 'bütünlük',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nws7a',
    created: 1736962748224,
    data: {
      language: 'de',
      source: 'die Widerstandsfähigkeit',
      ipa: 'ˈviːdɐʃtanʦfɛːɪçkait',
      example: 'die Widerstandsfähigkeit eines Materials testen',
      definition: '',
      translation: 'dayanıklılık',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Reu0K',
    created: 1736962749110,
    data: {
      language: 'de',
      source: 'die Schwelle',
      ipa: 'ˈʃvɛlə',
      example:
        '* die Braut über die Schwelle tragen\n* Schwellen legen\n* Die Hemmschwelle, so etwas zu tun, ist hoch.',
      definition:
        '* Abschluss einer Türöffnung am Fußboden\n* eines der Stücke Holz oder Beton, auf denen die Schienen liegen\n* äußerstes Maß von etwas',
      translation: 'eşik, travers, sınır',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JYtn5',
    created: 1736962749945,
    data: {
      language: 'de',
      source: 'die Anordnung',
      ipa: 'ˈan|ɔrdnʊŋ',
      example:
        '* eine gefällige Anordnung der Blumen in Vasen\n* eine Anordnung befolgen',
      definition: '',
      translation: 'düzen, tertip, nizam, emir, talimat, düzenleme',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1Vs2p',
    created: 1736962751021,
    data: {
      language: 'de',
      source: 'die Auswirkung',
      ipa: 'ˈausvɪrkʊŋ',
      example: 'Diese Substanz könnte Auswirkungen auf die Gesundheit haben.',
      definition: '',
      translation: 'etki, tesir',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vvSCL',
    created: 1736962751774,
    data: {
      language: 'de',
      source: 'das Ergebnis',
      ipa: 'ɛɐˈgeːpnɪs',
      example:
        '* Das Ergebnis zu Aufgabe 2 lautet 32.\n* ein gutes Wahlergebnis erzielen\n* Zu welchem Ergebnis ist der Ausschuss gekommen?',
      definition:
        '* Die Zahl, die man bekommt, wenn man etwas berechnet\n* Folge eines Ereignisses / einer Handlung\n* das, was beim Nachdenken herauskommt',
      translation: 'sonuç, netice, cevap',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ipe9p',
    created: 1736962752771,
    data: {
      language: 'de',
      source: 'anerkennen',
      ipa: 'ˈan|ɛɐkɛnən',
      example:
        '* anerkennende Worte\n* Wird mein Führerschein in den USA anerkannt?\n* Du musst anerkennen, dass er sich bemüht hat.',
      definition:
        '* positiv beurteilen\n* offiziell als gültig akzeptieren\n* respektieren oder akzeptieren',
      translation:
        'takdir etmek, övmek, kabul etmek, tanınmak, onanmak, tanımak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8TRTi',
    created: 1736962753918,
    data: {
      language: 'de',
      source: 'halten',
      ipa: 'ˈhaltən',
      example:
        '* Er hielt sich den Kopf vor Schmerzen.\n* die Arme gestreckt halten\n* Der Reifen hält die Luft nicht mehr.',
      definition:
        '* mit der Hand o. Ä. fassen und nicht loslassen\n* in eine Position bringen und in dieser Position lassen\n* bewirken, dass etwas an einer Stelle bleibt',
      translation:
        'tutmak, etmek, korumak, muhafaza etmek, sağlamak, olmak, ayakta tutmak, elinde tutmak, dayanmak, iyi durumda kalmak, kalmak, sürmek, devam etmek, kurtarmak, beslemek, yapmak, sunmak, işlemek, durmak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'F_2FB',
    created: 1736962754724,
    data: {
      language: 'de',
      source: 'widmen',
      ipa: 'ˈvɪtmən',
      example:
        '* Er hat seinen ersten Roman seiner Mutter gewidmet.\n* sein Leben dem Kampf gegen die Armut widmen',
      definition:
        '* jemandem als Ausdruck der Verbundenheit etwas symbolisch schenken\n* ausschließlich für jemanden / etwas verwenden',
      translation: 'adamak, vakfetmek, ithaf etmek, hasretmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vZHE4',
    created: 1736962756017,
    data: {
      language: 'de',
      source: 'rechtfertigen',
      ipa: 'ˈrɛçtfɛrtɪgən',
      example: '',
      definition: '',
      translation: 'haklı çıkarmak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lxR5h',
    created: 1736962757090,
    data: {
      language: 'de',
      source: 'die Vernachlässigung',
      ipa: 'fɛɐˈnaːxlɛsɪgʊŋ',
      example: 'die Vernachlässigung seiner Pflichten',
      definition: '',
      translation: 'ihmal, savsama, savsaklama',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QPpQM',
    created: 1736962757854,
    data: {
      language: 'de',
      source: 'überreden',
      ipa: 'yːbɐˈreːdən',
      example: 'Er ließ sich zum Kauf des Autos überreden.',
      definition:
        'so lange mit jemandem sprechen, bis er nachgibt und etwas tut',
      translation: 'ikna etmek, aklını çelmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Y9LD7',
    created: 1736962758716,
    data: {
      language: 'de',
      source: 'schrittweise',
      ipa: 'ˈʃrɪtvaizə',
      example: 'etwas wird schrittweise eingeführt / geändert',
      definition: '',
      translation: 'adım adım',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tm0I7',
    created: 1736962760856,
    data: {
      language: 'de',
      source: 'implizit',
      ipa: 'ɪmpliˈʦiːt',
      example: '',
      definition:
        'in einer Äußerung indirekt enthalten, aber nicht ausdrücklich gesagt',
      translation: 'örtük',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3pkRF',
    created: 1736962761704,
    data: {
      language: 'de',
      source: 'vor allem',
      ipa: '',
      example: '',
      definition: '',
      translation: 'özellikle',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IkXpi',
    created: 1736962762627,
    data: {
      language: 'de',
      source: 'sofort',
      ipa: 'zoˈfɔrt',
      example: '* Soforthilfe\n* Einen Moment, ich komme sofort!',
      definition: '* ohne Pause oder Verzögerung\n* in ganz kurzer Zeit',
      translation: 'hemen, derhal, anında',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fXwGJ',
    created: 1736962764246,
    data: {
      language: 'de',
      source: 'rund',
      ipa: 'rʊnt',
      example:
        '* runde und eckige Bausteine\n* Im fünften Monat wird ihr Bauch allmählich rund.\n* ein Tisch mit runden Kanten',
      definition:
        '* mit einem Kreis als Grundform\n* mit viel Fleisch, gewölbt\n* nicht kantig',
      translation: 'yuvarlak, dairesel, tombul',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NED3l',
    created: 1736962765166,
    data: {
      language: 'de',
      source: 'ausreichend',
      ipa: 'ˈausraiçənt',
      example:
        '* in ausreichender Zahl / Menge vorhanden sein\n* ein Ausreichend bekommen',
      definition:
        '* so, dass es nicht zu wenig ist\n* relativ schlechte Note an deutschen Schulen, mit der man eine Prüfung aber noch bestanden hat',
      translation: 'yeterli, kâfi, yeterli notu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eqcVg',
    created: 1736962895847,
    data: {
      language: 'de',
      source: 'hartnäckig',
      ipa: 'ˈhartnɛkɪç',
      example:
        '* trotz hartnäckiger Versuche nichts erreichen\n* Er hat eine sehr hartnäckige Akne.',
      definition:
        '* ein Ziel oder Verhalten mit Ausdauer verfolgend\n* lang anhaltend, nicht wegzubekommen',
      translation: 'inatçı, ısrarlı, serkeş, çetin',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aEd2u',
    created: 1736962897737,
    data: {
      language: 'de',
      source: 'umfassend',
      ipa: 'ʊmˈfasənt',
      example:
        '* umfassende Kenntnisse in einem Gebiet haben\n* ein umfassendes Geständnis ablegen',
      definition: '* sehr vieles beinhaltend, erfassend\n* vollständig',
      translation: 'kapsamlı, geniş kapsamlı, geniş, tam, kapsayıcı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '07C2U',
    created: 1736962898761,
    data: {
      language: 'de',
      source: 'entzückend',
      ipa: 'ɛntˈʦʏkənt',
      example: 'Was für ein entzückendes Mädchen / Kleid!',
      definition: '',
      translation: 'hoş, sevimli, güzel, büyüleyici',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pCNRf',
    created: 1736962899933,
    data: {
      language: 'de',
      source: 'zurückhaltend',
      ipa: 'ʦuˈrʏkhaltənt',
      example:
        '* eine zurückhaltende Schülerin\n* eine zurückhaltende Wachstumsprognose',
      definition:
        '* ruhig und unauffällig, sich nicht um Aufmerksamkeit bemühend\n* wenig intensiv, emotional oder ausgeprägt',
      translation: 'çekingen, suskun, sakıngan, temkinli, ihtiyatlı, ölçülü',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lbAQO',
    created: 1736962901706,
    data: {
      language: 'de',
      source: 'widerwillig',
      ipa: 'ˈviːdɐvɪlɪç',
      example: 'ein widerwilliges Zugeständnis',
      definition: '',
      translation: 'gönülsüz, isteksiz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Z5pW1',
    created: 1736962903215,
    data: {
      language: 'de',
      source: 'bedeutsam',
      ipa: "bə'dɔytzaːm",
      example:
        '* eine bedeutsame Entwicklung / Leistung\n* Sie warf ihm einen bedeutsamen Blick zu.',
      definition: '* bedeutend\n* ohne Worte Informationen gebend',
      translation: 'önemli, anlamlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
