import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ZQQnv',
    created: 1736959142985,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛgrɪti',
      example:
        '* a man of great integrity\n* the structural integrity of the bridge',
      definition:
        '* the quality of being good, honest, and trustworthy\n* the quality of working together as a whole',
      translation: 'integritet, helhed',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U3k6G',
    created: 1736959144766,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪlyəns',
      example: 'her remarkable resilience in such a terrible situation',
      definition: 'the quality of being resilient',
      translation: 'modstandsdygtighed',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hx9DM',
    created: 1736959146638,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃoʊld',
      example: 'a woman with a high pain threshold',
      definition:
        'the level at which a rule starts to take effect or a limit is reached',
      translation: 'grænse, dørtrin',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'V01ed',
    created: 1736959148043,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example: 'a friendly/nervous disposition',
      definition: 'the way somebody naturally behaves',
      translation: 'disposition',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kCKqf',
    created: 1736959150198,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpəˈkʌʃən',
      example: '',
      definition:
        '* a remote or indirect consequence of some action\n* a movement back from an impact',
      translation: 'eftervirkning, tilbageslag, repercussion',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GfPjh',
    created: 1736959152142,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example: 'a positive outcome',
      definition: 'the result of a process',
      translation: 'resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Fa8t9',
    created: 1736959154181,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'ækˈnɒlɪdʒ',
      example:
        '* She refuses to acknowledge the truth.\n* He acknowledged me with a nod.\n* I acknowledge receipt of the documents.',
      definition:
        '* to admit something to yourself or others\n* to show that you see or recognize somebody\n* to respond to a letter, email etc. that has been received',
      translation: 'anerkende, erkende, besvare',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PzTXH',
    created: 1736959156653,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example:
        '* to consider the options\n* My teacher considers it to be a good program.\n* I have to consider my family.',
      definition:
        '* to think about carefully\n* to think about something in a particular way\n* to think about how actions affect others',
      translation: 'overveje, betragte, tænke på',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Kz0xV',
    created: 1736959158918,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example: 'She devoted herself to her work.',
      definition: 'to give all your time and effort to one thing',
      translation: 'at vie, dedikere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zn2uM',
    created: 1736959164581,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstəˌfaɪ',
      example: 'Does her desperation justify her killing someone?',
      definition: 'to give a good reason for',
      translation: 'berettige, retfærdiggøre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zP_qj',
    created: 1736959166994,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈglɛkt',
      example: 'his neglect of his duties',
      definition: 'the state of being neglected',
      translation: 'forsømmelse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UcrSx',
    created: 1736959168853,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example: "I'll see if I can persuade my Dad to let me go.",
      definition: 'to make somebody believe or agree with you',
      translation: 'overbevise',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vt-4X',
    created: 1736959170785,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈgrædʒuəli',
      example: 'Gradually, they started to like each other.',
      definition: 'slowly over a long period',
      translation: 'gradvist',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VCKEz',
    created: 1736959172715,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: 'ɪmˈplɪsɪt',
      example: '',
      definition:
        '* implied though not directly expressed; inherent in the nature of something\n* being without doubt or reserve',
      translation: 'implicit, underforstået',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'il5fz',
    created: 1736959178472,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: 'The Mayor was, notably, one of the two people absent.',
      definition: '',
      translation: 'især',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-JJUD',
    created: 1736959180410,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'prɒmptli',
      example:
        '* They left promptly at 8:00.\n* She agreed and then promptly changed her mind.',
      definition:
        '* exactly at the right time, without delay\n* immediately after',
      translation: 'øjeblikkeligt, straks, hurtigt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NbF1n',
    created: 1736959182641,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* I'd say it was roughly 50 feet long.\n* They pulled her roughly up the stairs.\n* a roughly translated message",
      definition:
        '* indicates a calculation or guess that is not exact\n* using force or violence\n* in a way that is not finished or perfected',
      translation: 'omtrent, groft, ufærdigt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GXtlI',
    created: 1736959184803,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example: 'Is she sufficiently qualified to do the job?',
      definition: '',
      translation: 'tilstrækkeligt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3AqWI',
    created: 1736959186868,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example:
        '* his persistent attempts to persuade her\n* a persistent cough',
      definition:
        '* done or happening repeatedly, often with negative effects\n* continuing for a long time',
      translation: 'vedholdende, ihærdig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C9ky7',
    created: 1736959188885,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example: 'comprehensive immigration reform',
      definition: 'including all that is needed',
      translation: 'omfattende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jei25',
    created: 1736959191236,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfəl',
      example: 'a delightful person',
      definition: 'causing great pleasure',
      translation: 'dejlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mJv3m',
    created: 1736959194022,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔʃəs',
      example: 'a cautious driver',
      definition: 'using care to avoid risks',
      translation: 'forsigtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n79uk',
    created: 1736959196383,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: 'a reluctant smile',
      definition: 'unwilling to do something',
      translation: 'modvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LYztF',
    created: 1736959198325,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪgˈnɪfɪkənt',
      example: 'a significant improvement in her condition',
      definition: 'having importance and meaning',
      translation: 'betydelig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
