import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'PqtfB',
    created: 1736959621798,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛgrɪti',
      example:
        '* a man of great integrity\n* the structural integrity of the bridge',
      definition:
        '* the quality of being good, honest, and trustworthy\n* the quality of working together as a whole',
      translation: 'integriti, keseluruhan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'a91QV',
    created: 1736959623597,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪlyəns',
      example: 'her remarkable resilience in such a terrible situation',
      definition: 'the quality of being resilient',
      translation: 'daya tahan, ketahanan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EzPdz',
    created: 1736959625642,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃoʊld',
      example: 'a woman with a high pain threshold',
      definition:
        'the level at which a rule starts to take effect or a limit is reached',
      translation: 'ambang',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wBXwY',
    created: 1736959628199,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example: 'a friendly/nervous disposition',
      definition: 'the way somebody naturally behaves',
      translation: 'sikap, disposisi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fhpDu',
    created: 1736959630155,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpəˈkʌʃən',
      example: '',
      definition:
        '* a remote or indirect consequence of some action\n* a movement back from an impact',
      translation: 'reaksi, kesan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eYkVT',
    created: 1736959631785,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example: 'a positive outcome',
      definition: 'the result of a process',
      translation: 'hasil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YYPof',
    created: 1736959634040,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'ækˈnɒlɪdʒ',
      example:
        '* She refuses to acknowledge the truth.\n* He acknowledged me with a nod.\n* I acknowledge receipt of the documents.',
      definition:
        '* to admit something to yourself or others\n* to show that you see or recognize somebody\n* to respond to a letter, email etc. that has been received',
      translation: 'mengakui, menghargai, menjawab',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CI3uO',
    created: 1736959635992,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example:
        '* to consider the options\n* My teacher considers it to be a good program.\n* I have to consider my family.',
      definition:
        '* to think about carefully\n* to think about something in a particular way\n* to think about how actions affect others',
      translation: 'mempertimbangkan, menganggap, memandang',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tyCGk',
    created: 1736959638140,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example: 'She devoted herself to her work.',
      definition: 'to give all your time and effort to one thing',
      translation: 'mengabdikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xSmlb',
    created: 1736959639994,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstəˌfaɪ',
      example: 'Does her desperation justify her killing someone?',
      definition: 'to give a good reason for',
      translation: 'membenarkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0dfHD',
    created: 1736959641925,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈglɛkt',
      example:
        '* owners who neglect their pets\n* a soldier who neglects his duties',
      definition:
        '* to fail to take care of or pay attention to\n* to not do something or forget to do something',
      translation: 'abaikan, mengabaikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tuMaT',
    created: 1736959643328,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example: "I'll see if I can persuade my Dad to let me go.",
      definition: 'to make somebody believe or agree with you',
      translation: 'membujuk, memujuk',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A0nlF',
    created: 1736959645308,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈgrædʒuəli',
      example: 'Gradually, they started to like each other.',
      definition: 'slowly over a long period',
      translation: 'secara beransur, secara beransur-ansur',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dgy6g',
    created: 1736959647036,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: 'ɪmˈplɪsɪt',
      example: '',
      definition:
        '* implied though not directly expressed; inherent in the nature of something\n* being without doubt or reserve',
      translation: 'tersirat, tidak diragukan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'byAx_',
    created: 1736959648962,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: 'The Mayor was, notably, one of the two people absent.',
      definition: '',
      translation: 'terutamanya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QQijP',
    created: 1736959651078,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'prɒmptli',
      example:
        '* They left promptly at 8:00.\n* She agreed and then promptly changed her mind.',
      definition:
        '* exactly at the right time, without delay\n* immediately after',
      translation: 'segera, cepat',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HjDWV',
    created: 1736959653061,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* I'd say it was roughly 50 feet long.\n* They pulled her roughly up the stairs.\n* a roughly translated message",
      definition:
        '* indicates a calculation or guess that is not exact\n* using force or violence\n* in a way that is not finished or perfected',
      translation: 'kira-kira, kasar, secara kasar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mno0P',
    created: 1736959655613,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example: 'Is she sufficiently qualified to do the job?',
      definition: '',
      translation: 'secara mencukupi',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eDFdN',
    created: 1736959657835,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example:
        '* his persistent attempts to persuade her\n* a persistent cough',
      definition:
        '* done or happening repeatedly, often with negative effects\n* continuing for a long time',
      translation: 'berterusan, kekal',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vP26U',
    created: 1736959660358,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example: 'comprehensive immigration reform',
      definition: 'including all that is needed',
      translation: 'menyeluruh, komprehensif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YIL2s',
    created: 1736959663204,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfəl',
      example: 'a delightful person',
      definition: 'causing great pleasure',
      translation: 'menyenangkan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5SX3r',
    created: 1736959665077,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔʃəs',
      example: 'a cautious driver',
      definition: 'using care to avoid risks',
      translation: 'berhati-hati',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BPCcW',
    created: 1736959666817,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: 'a reluctant smile',
      definition: 'unwilling to do something',
      translation: 'enggan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UUZsZ',
    created: 1736959668785,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪgˈnɪfɪkənt',
      example: 'a significant improvement in her condition',
      definition: 'having importance and meaning',
      translation: 'penting, bermakna, signifikan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
