import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '35F68',
    created: 1736959103174,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛgrɪti',
      example:
        '* a man of great integrity\n* the structural integrity of the bridge',
      definition:
        '* the quality of being good, honest, and trustworthy\n* the quality of working together as a whole',
      translation: 'integritet, hederlighet, helhet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4qQs9',
    created: 1736959104331,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪlyəns',
      example: 'her remarkable resilience in such a terrible situation',
      definition: 'the quality of being resilient',
      translation: 'styrke, robusthet, motstandskraft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EHmbk',
    created: 1736959105865,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃoʊld',
      example: 'a woman with a high pain threshold',
      definition:
        'the level at which a rule starts to take effect or a limit is reached',
      translation: 'terskel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r_jfM',
    created: 1736959107260,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example: 'a friendly/nervous disposition',
      definition: 'the way somebody naturally behaves',
      translation: 'lynne, innstilling, disposisjon',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'np_Rw',
    created: 1736959109359,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpəˈkʌʃən',
      example: '',
      definition:
        '* a remote or indirect consequence of some action\n* a movement back from an impact',
      translation: 'ettervirkning, tilbakevirkning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gs6Zj',
    created: 1736959110677,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example: 'a positive outcome',
      definition: 'the result of a process',
      translation: 'utfall, resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QSs-w',
    created: 1736959111533,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'ækˈnɒlɪdʒ',
      example:
        '* She refuses to acknowledge the truth.\n* He acknowledged me with a nod.\n* I acknowledge receipt of the documents.',
      definition:
        '* to admit something to yourself or others\n* to show that you see or recognize somebody\n* to respond to a letter, email etc. that has been received',
      translation:
        'innrømme, erkjenne, innse, anerkjenne, gjenkjenne, bekrefte',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fYRuC',
    created: 1736959112620,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example:
        '* to consider the options\n* My teacher considers it to be a good program.\n* I have to consider my family.',
      definition:
        '* to think about carefully\n* to think about something in a particular way\n* to think about how actions affect others',
      translation:
        'ta i betraktning, vurdere, tenke seg om, anse, betrakte, ta hensyn til, drøfte, fundere over',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xiEsG',
    created: 1736959113738,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example: 'She devoted herself to her work.',
      definition: 'to give all your time and effort to one thing',
      translation: 'vie, tilegne',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xTRAD',
    created: 1736959115065,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstəˌfaɪ',
      example: 'Does her desperation justify her killing someone?',
      definition: 'to give a good reason for',
      translation: 'rettferdiggjøre, unnskylde',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FSFpm',
    created: 1736959116412,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈglɛkt',
      example: 'his neglect of his duties',
      definition: 'the state of being neglected',
      translation: 'forsømmelse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0VCic',
    created: 1736959117789,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example: "I'll see if I can persuade my Dad to let me go.",
      definition: 'to make somebody believe or agree with you',
      translation: 'overtale, overbevise',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GC0Lj',
    created: 1736959121505,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈgrædʒuəli',
      example: 'Gradually, they started to like each other.',
      definition: 'slowly over a long period',
      translation: 'litt etter litt, gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Qg0vL',
    created: 1736959122882,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: 'ɪmˈplɪsɪt',
      example: '',
      definition:
        '* implied though not directly expressed; inherent in the nature of something\n* being without doubt or reserve',
      translation: 'implisitt, underforstått',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1_aAq',
    created: 1736959124281,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: 'The Mayor was, notably, one of the two people absent.',
      definition: '',
      translation: 'bemerkelsesverdig nok, særlig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tJtpp',
    created: 1736959125492,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'prɒmptli',
      example:
        '* They left promptly at 8:00.\n* She agreed and then promptly changed her mind.',
      definition:
        '* exactly at the right time, without delay\n* immediately after',
      translation: 'med en gang, punktlig, presis, like etter, umiddelbart',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '92Kir',
    created: 1736959126654,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* I'd say it was roughly 50 feet long.\n* They pulled her roughly up the stairs.\n* a roughly translated message",
      definition:
        '* indicates a calculation or guess that is not exact\n* using force or violence\n* in a way that is not finished or perfected',
      translation: 'omtrent, brutalt, grovt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dYQv8',
    created: 1736959128180,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example: 'Is she sufficiently qualified to do the job?',
      definition: '',
      translation: 'tilstrekkelig, nok',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sV8XJ',
    created: 1736959129064,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example:
        '* his persistent attempts to persuade her\n* a persistent cough',
      definition:
        '* done or happening repeatedly, often with negative effects\n* continuing for a long time',
      translation: 'uavlatelig, vedvarende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZOPfp',
    created: 1736959133604,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example: 'comprehensive immigration reform',
      definition: 'including all that is needed',
      translation: 'omfattende, komplett',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gRIbX',
    created: 1736959134976,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfəl',
      example: 'a delightful person',
      definition: 'causing great pleasure',
      translation: 'herlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ycLQG',
    created: 1736959138286,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔʃəs',
      example: 'a cautious driver',
      definition: 'using care to avoid risks',
      translation: 'forsiktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tizdp',
    created: 1736959139565,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: 'a reluctant smile',
      definition: 'unwilling to do something',
      translation: 'nølende, motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kLBwd',
    created: 1736959140690,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪgˈnɪfɪkənt',
      example: 'a significant improvement in her condition',
      definition: 'having importance and meaning',
      translation: 'betydelig, betydningsfull, signifikant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
