import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'QP47T',
    created: 1736959068010,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛgrɪti',
      example:
        '* a man of great integrity\n* the structural integrity of the bridge',
      definition:
        '* the quality of being good, honest, and trustworthy\n* the quality of working together as a whole',
      translation: 'integritet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1Enha',
    created: 1736959069398,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪlyəns',
      example: 'her remarkable resilience in such a terrible situation',
      definition: 'the quality of being resilient',
      translation: '(snabb) återhämtning, förmåga att komma igen, resiliens',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bJi1j',
    created: 1736959071041,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃoʊld',
      example: 'a woman with a high pain threshold',
      definition:
        'the level at which a rule starts to take effect or a limit is reached',
      translation: 'tröskel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2yQcj',
    created: 1736959072368,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example: 'a friendly/nervous disposition',
      definition: 'the way somebody naturally behaves',
      translation: 'läggning, disposition',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vZj1p',
    created: 1736959074248,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpəˈkʌʃən',
      example: '',
      definition:
        '* a remote or indirect consequence of some action\n* a movement back from an impact',
      translation: 'återverkan, efterverkning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VLyOS',
    created: 1736959075356,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example: 'a positive outcome',
      definition: 'the result of a process',
      translation: 'resultat, utslag',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-MIYV',
    created: 1736959076505,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'ækˈnɒlɪdʒ',
      example:
        '* She refuses to acknowledge the truth.\n* He acknowledged me with a nod.\n* I acknowledge receipt of the documents.',
      definition:
        '* to admit something to yourself or others\n* to show that you see or recognize somebody\n* to respond to a letter, email etc. that has been received',
      translation: 'erkänna, medge, bekräfta, bekräfta ett mottagande',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6Agmj',
    created: 1736959077694,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example:
        '* to consider the options\n* My teacher considers it to be a good program.\n* I have to consider my family.',
      definition:
        '* to think about carefully\n* to think about something in a particular way\n* to think about how actions affect others',
      translation:
        'överväga, tånka över/igenom, anse, tycka, ta hänsyn till, tänka på, betrakta, titta på',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QNsS1',
    created: 1736959078676,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example: 'She devoted herself to her work.',
      definition: 'to give all your time and effort to one thing',
      translation: 'ägna åt',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oVVA3',
    created: 1736959080257,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstəˌfaɪ',
      example: 'Does her desperation justify her killing someone?',
      definition: 'to give a good reason for',
      translation: 'berättiga, rättfärdiga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jG8Ry',
    created: 1736959081869,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈglɛkt',
      example: 'his neglect of his duties',
      definition: 'the state of being neglected',
      translation: 'försummelse, åsidosättande',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'COy8E',
    created: 1736959083147,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example: "I'll see if I can persuade my Dad to let me go.",
      definition: 'to make somebody believe or agree with you',
      translation: 'övertala, övertyga',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sGPFe',
    created: 1736959084156,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈgrædʒuəli',
      example: 'Gradually, they started to like each other.',
      definition: 'slowly over a long period',
      translation: 'med tiden, efterhand, gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Bg9Se',
    created: 1736959086655,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: 'ɪmˈplɪsɪt',
      example: '',
      definition:
        '* implied though not directly expressed; inherent in the nature of something\n* being without doubt or reserve',
      translation: 'underförstådd, implicit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '23md5',
    created: 1736959087979,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: 'The Mayor was, notably, one of the two people absent.',
      definition: '',
      translation: 'märkligt nog, särskilt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S951k',
    created: 1736959089075,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'prɒmptli',
      example:
        '* They left promptly at 8:00.\n* She agreed and then promptly changed her mind.',
      definition:
        '* exactly at the right time, without delay\n* immediately after',
      translation: 'på minuten, omedelbart, snabbt, precis på slaget',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KgiSB',
    created: 1736959090403,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* I'd say it was roughly 50 feet long.\n* They pulled her roughly up the stairs.\n* a roughly translated message",
      definition:
        '* indicates a calculation or guess that is not exact\n* using force or violence\n* in a way that is not finished or perfected',
      translation: 'grovt räknat, på ett ungefär, hårdhänt, grovt, rått',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EnuP0',
    created: 1736959091391,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example: 'Is she sufficiently qualified to do the job?',
      definition: '',
      translation: 'tillräckligt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZEC8K',
    created: 1736959092746,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example:
        '* his persistent attempts to persuade her\n* a persistent cough',
      definition:
        '* done or happening repeatedly, often with negative effects\n* continuing for a long time',
      translation: 'ihärdig, ihållande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G0F3B',
    created: 1736959093741,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example: 'comprehensive immigration reform',
      definition: 'including all that is needed',
      translation: 'omfattande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'STBLH',
    created: 1736959095944,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfəl',
      example: 'a delightful person',
      definition: 'causing great pleasure',
      translation: 'härlig, förtjusande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1BRq0',
    created: 1736959097461,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔʃəs',
      example: 'a cautious driver',
      definition: 'using care to avoid risks',
      translation: 'aktsam, försiktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XQ2B3',
    created: 1736959099613,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: 'a reluctant smile',
      definition: 'unwilling to do something',
      translation: 'motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-JgSm',
    created: 1736959101041,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪgˈnɪfɪkənt',
      example: 'a significant improvement in her condition',
      definition: 'having importance and meaning',
      translation: 'signifikant, betydande',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
