import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'zL3DW',
    created: 1736958524536,
    data: {
      language: 'en',
      source: 'integrity',
      ipa: 'ɪnˈtɛgrɪti',
      example:
        '* a man of great integrity\n* the structural integrity of the bridge',
      definition:
        '* the quality of being good, honest, and trustworthy\n* the quality of working together as a whole',
      translation: '誠信, 完整性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NC9n3',
    created: 1736958526651,
    data: {
      language: 'en',
      source: 'resilience',
      ipa: 'rɪˈzɪlyəns',
      example: 'her remarkable resilience in such a terrible situation',
      definition: 'the quality of being resilient',
      translation: '韌性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dBAf4',
    created: 1736958528574,
    data: {
      language: 'en',
      source: 'threshold',
      ipa: 'ˈθrɛʃoʊld',
      example: 'a woman with a high pain threshold',
      definition:
        'the level at which a rule starts to take effect or a limit is reached',
      translation: '門檻',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NxDCH',
    created: 1736958530396,
    data: {
      language: 'en',
      source: 'disposition',
      ipa: 'ˌdɪspəˈzɪʃən',
      example: 'a friendly/nervous disposition',
      definition: 'the way somebody naturally behaves',
      translation: '性格, 性情',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3Xb8J',
    created: 1736958532090,
    data: {
      language: 'en',
      source: 'repercussion',
      ipa: 'ˌriːpəˈkʌʃən',
      example: '',
      definition:
        '* a remote or indirect consequence of some action\n* a movement back from an impact',
      translation: '影響, 反響, 後果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AO6Nw',
    created: 1736958534061,
    data: {
      language: 'en',
      source: 'outcome',
      ipa: 'ˈaʊtˌkʌm',
      example: 'a positive outcome',
      definition: 'the result of a process',
      translation: '結果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-X6c-',
    created: 1736958536102,
    data: {
      language: 'en',
      source: 'acknowledge',
      ipa: 'ækˈnɒlɪdʒ',
      example:
        '* She refuses to acknowledge the truth.\n* He acknowledged me with a nod.\n* I acknowledge receipt of the documents.',
      definition:
        '* to admit something to yourself or others\n* to show that you see or recognize somebody\n* to respond to a letter, email etc. that has been received',
      translation: '承認, 認可, 回覆',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DPGil',
    created: 1736958538836,
    data: {
      language: 'en',
      source: 'consider',
      ipa: 'kənˈsɪdər',
      example:
        '* to consider the options\n* My teacher considers it to be a good program.\n* I have to consider my family.',
      definition:
        '* to think about carefully\n* to think about something in a particular way\n* to think about how actions affect others',
      translation: '考慮, 認為',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r0SBK',
    created: 1736958541531,
    data: {
      language: 'en',
      source: 'devote',
      ipa: 'dɪˈvoʊt',
      example: 'She devoted herself to her work.',
      definition: 'to give all your time and effort to one thing',
      translation: '奉獻, 致力於',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RkciW',
    created: 1736958547324,
    data: {
      language: 'en',
      source: 'justify',
      ipa: 'ˈdʒʌstəˌfaɪ',
      example: 'Does her desperation justify her killing someone?',
      definition: 'to give a good reason for',
      translation: '辯解, 證明, 辯護',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_ILgy',
    created: 1736958549402,
    data: {
      language: 'en',
      source: 'neglect',
      ipa: 'nɪˈglɛkt',
      example:
        '* owners who neglect their pets\n* a soldier who neglects his duties',
      definition:
        '* to fail to take care of or pay attention to\n* to not do something or forget to do something',
      translation: '忽視, 疏忽',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G6hqY',
    created: 1736958551273,
    data: {
      language: 'en',
      source: 'persuade',
      ipa: 'pərˈsweɪd',
      example: "I'll see if I can persuade my Dad to let me go.",
      definition: 'to make somebody believe or agree with you',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yXcth',
    created: 1736958552955,
    data: {
      language: 'en',
      source: 'gradually',
      ipa: 'ˈgrædʒuəli',
      example: 'Gradually, they started to like each other.',
      definition: 'slowly over a long period',
      translation: '逐漸',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uMZic',
    created: 1736958557355,
    data: {
      language: 'en',
      source: 'implicit',
      ipa: 'ɪmˈplɪsɪt',
      example: '',
      definition:
        '* implied though not directly expressed; inherent in the nature of something\n* being without doubt or reserve',
      translation: '隱含的, 內在的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wyOHA',
    created: 1736958561120,
    data: {
      language: 'en',
      source: 'notably',
      ipa: 'ˈnoʊtəbli',
      example: 'The Mayor was, notably, one of the two people absent.',
      definition: '',
      translation: '特別是',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VzXZQ',
    created: 1736958562907,
    data: {
      language: 'en',
      source: 'promptly',
      ipa: 'prɒmptli',
      example:
        '* They left promptly at 8:00.\n* She agreed and then promptly changed her mind.',
      definition:
        '* exactly at the right time, without delay\n* immediately after',
      translation: '立即, 準時, 迅速地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XWJsK',
    created: 1736958565190,
    data: {
      language: 'en',
      source: 'roughly',
      ipa: 'ˈrʌfli',
      example:
        "* I'd say it was roughly 50 feet long.\n* They pulled her roughly up the stairs.\n* a roughly translated message",
      definition:
        '* indicates a calculation or guess that is not exact\n* using force or violence\n* in a way that is not finished or perfected',
      translation: '大約, 粗暴地, 粗糙地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Sl3aD',
    created: 1736958566954,
    data: {
      language: 'en',
      source: 'sufficiently',
      ipa: 'səˈfɪʃəntli',
      example: 'Is she sufficiently qualified to do the job?',
      definition: '',
      translation: '足夠地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eRZ3u',
    created: 1736958568849,
    data: {
      language: 'en',
      source: 'persistent',
      ipa: 'pərˈsɪstənt',
      example:
        '* his persistent attempts to persuade her\n* a persistent cough',
      definition:
        '* done or happening repeatedly, often with negative effects\n* continuing for a long time',
      translation: '持續的, 堅持的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QLosx',
    created: 1736958571404,
    data: {
      language: 'en',
      source: 'comprehensive',
      ipa: 'ˌkɒmprɪˈhɛnsɪv',
      example: 'comprehensive immigration reform',
      definition: 'including all that is needed',
      translation: '全面的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'viNaS',
    created: 1736958574828,
    data: {
      language: 'en',
      source: 'delightful',
      ipa: 'dɪˈlaɪtfəl',
      example: 'a delightful person',
      definition: 'causing great pleasure',
      translation: '愉快的, 令人愉快的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7Eb7G',
    created: 1736958576813,
    data: {
      language: 'en',
      source: 'cautious',
      ipa: 'ˈkɔʃəs',
      example: 'a cautious driver',
      definition: 'using care to avoid risks',
      translation: '謹慎, 謹慎的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N9No-',
    created: 1736958580851,
    data: {
      language: 'en',
      source: 'reluctant',
      ipa: 'rɪˈlʌktənt',
      example: 'a reluctant smile',
      definition: 'unwilling to do something',
      translation: '不情願, 不情願的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'o24m6',
    created: 1736958582673,
    data: {
      language: 'en',
      source: 'significant',
      ipa: 'sɪgˈnɪfɪkənt',
      example: 'a significant improvement in her condition',
      definition: 'having importance and meaning',
      translation: '重要的, 意義深遠的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
