import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'WAogJ',
    created: 1736961269357,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: "inteγɾi'ðað",
      example: 'Denota integridad en todos sus actos.',
      definition: 'cualidad de quien tiene entereza moral',
      translation: 'bütünlük',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'br1Ss',
    created: 1736961270112,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dayanıqlılıq',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QGLtI',
    created: 1736961272763,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: "'limite",
      example: '* los límites de un territorio\n* límite de velocidad',
      definition:
        '* línea real o imaginaria que separa dos cosas\n* punto o grado que no puede superarse',
      translation: 'sərhəd',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2hzt9',
    created: 1736961273763,
    data: {
      language: 'es',
      source: 'dispozisiya',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dispozisiya',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'txHkN',
    created: 1736961274621,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: "repeɾku'sjon",
      example:
        '* El acto tuvo repercusión en todo el globo.\n* El libro logró repercusión por su temática.',
      definition:
        '* influencia de algo en un asunto\n* difusión pública de algo',
      translation: 'təsir',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mheYS',
    created: 1736961275453,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: "resul'taðo",
      example:
        '* Sus éxitos son el resultado del trabajo bien hecho.\n* Estos zapatos me han dado muy mal resultado.',
      definition:
        '* efecto y consecuencia de una cosa\n* rendimiento que da una cosa',
      translation: 'nəticə',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f_ukY',
    created: 1736961276429,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: "rekono'θeɾ",
      example:
        '* Reconocí a mi primo en medio de la multitud.\n* reconocer el terreno\n* La acusada reconoce que vio a la víctima aquella noche.',
      definition:
        '* determinar la identidad de una persona entre otras\n* considerar cuidadosamente una cosa o persona\n* admitir algo que se había negado',
      translation: 'tanımaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3AA6W',
    created: 1736961277329,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: "konsiðe'ɾaɾ",
      example:
        '* Considero que es mejor no comprar ahora.\n* Consideraré todas las calificaciones.\n* Considero que debes aceptar el trabajo.',
      definition:
        '* reflexionar minuciosamente sobre algo\n* tener en cuenta una cosa\n* realizar una crítica o juzgar',
      translation: 'düşünmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ndQIq',
    created: 1736961278130,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: "deði'kaɾ",
      example:
        '* Este templo está dedicado a Júpiter.\n* Dedicó su último libro a sus hijos.\n* El dinero recaudado se dedicará a la restauración del edificio.',
      definition:
        '* consagrar al culto religioso o profano\n* ofrecer algo a una persona como muestra de agradecimiento, cariño, etc.\n* emplear algo a un uso determinado',
      translation: 'həsr etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4kWyt',
    created: 1736961279111,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: "xustifi'kaɾ",
      example:
        '* ¿El fin justifica los medios?\n* Justificó su denuncia con informes de espías.\n* justificar una línea a la derecha',
      definition:
        '* hacer una cosa que otra sea adecuada u oportuna\n* demostrar algo con razones convincentes\n* ajustar la alineación de un texto',
      translation: 'justifikasiya etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G67cL',
    created: 1736961280147,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: "des'kwiðo",
      example:
        '* Hiciste mal el trabajo por puro descuido.\n* Bastó un descuido para que se perdiera la niña.\n* El descuido de su aspecto mostraba su estado de ánimo.',
      definition:
        '* falta de atención de algo bajo la propia responsabilidad\n* falta de atención momentánea\n* falta de aseo o desaliño en la persona',
      translation: 'qayğısızlıq',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QqZfQ',
    created: 1736961281042,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: "peɾswa'ðiɾ",
      example: 'Me persuadieron de que era mejor rechazar el encargo.',
      definition: 'convencer con argumentos a alguien de algo',
      translation: 'inandırmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'H3fCc',
    created: 1736961282029,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: "graðwal'meNte",
      example:
        'La ola de calor se va extendiendo gradualmente por todas las provincias.',
      definition: 'de manera paulatina, constante hacia un término final',
      translation: 'tədricən',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rvXyq',
    created: 1736961282903,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: "im'pliθitamente",
      example:
        'Si bien el mensaje fue claro y contundente, implícitamente también nos explicaba los motivos de su decisón con su tono y sus gestos.',
      definition:
        'de forma indirecta, supuesta o sobreentendida, al mismo tiempo que algo que se expresa abiertamente',
      translation: 'məxfi şəkildə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Fn4XE',
    created: 1736961284125,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: "notaβle'meNte",
      example: 'Su labor al frente de la empresa fue notablemente reconocida.',
      definition:
        'de manera destacada, que se percibe con claridad y denota contundencia',
      translation: 'qeyri-adi şəkildə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RzArT',
    created: 1736961285042,
    data: {
      language: 'es',
      source: 'immediately',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dərhal',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ubsuS',
    created: 1736961286009,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* En la oscuridad apenas se veía el sendero.\n* Apenas hemos vendido unas diez revistas.',
      definition:
        '* indica que la acción casi no sucede o no se nota\n* expresa una cantidad pequeña y aproximada',
      translation: 'yalnızca',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wA7cs',
    created: 1736961288121,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: "sufiθjente'mente",
      example: 'Comieron suficientemente.',
      definition: 'en un grado o medida adecuados',
      translation: 'kifayət qədər',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6ppNC',
    created: 1736961289145,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: "peɾsis'tente",
      example: '* ideas persistentes\n* lluvia persistente',
      definition:
        '* que tiene firmeza y constancia\n* que tiene una duración prolongada',
      translation: 'davamlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'p_MJp',
    created: 1736961290248,
    data: {
      language: 'es',
      source: 'integral',
      ipa: "inte'γɾal",
      example: '* una educación integral\n* arroz integral\n* pan integral',
      definition:
        '* que comprende todos los aspectos o partes necesarias para estar completo\n* cuyo grano no ha sido desprovisto de su cáscara\n* que es elaborado con harina de cereal con cáscara',
      translation: 'integral',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0gO2A',
    created: 1736961291190,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: "enkanta'ðoɾ",
      example: 'una niña encantadora',
      definition: 'que deja muy buena impresión por ser muy agradable',
      translation: 'cazibədar',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SQDB1',
    created: 1736961292095,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: "pɾeka'βiðo",
      example:
        '* Debes ser precavido y no andar de noche por las calles.\n* Mi padre es muy precavido cuando organiza un viaje.\n* Avanzaban por la jungla con paso precavido.',
      definition:
        '* que actúa con precaución\n* que piensa y dispone las cosas con antelación\n* que implica precaución',
      translation: 'ehtiyatlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's7ON0',
    created: 1736961293008,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: "re'aθjo",
      example: 'Era reacio a ver cine extranjero.',
      definition: 'que se opone o resiste a una influencia',
      translation: 'müxalif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7Qx7n',
    created: 1736961293986,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: "siγnifika'tiβo",
      example:
        '* recibir una significativa ayuda\n* Este poemario es el más significativo del autor.',
      definition: '* que es importante\n* que comunica una cosa con propiedad',
      translation: 'mühüm',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
