import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'tEwvX',
    created: 1736961183265,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: "inteγɾi'ðað",
      example: 'Denota integridad en todos sus actos.',
      definition: 'cualidad de quien tiene entereza moral',
      translation: 'ինտեգրիտետ',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'quW7E',
    created: 1736961184197,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'կայունություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uj5-o',
    created: 1736961185012,
    data: {
      language: 'es',
      source: 'լիմիտ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'լիմիտ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6E9pb',
    created: 1736961185865,
    data: {
      language: 'es',
      source: 'դիսպոզիցիա',
      ipa: '',
      example: '',
      definition: '',
      translation: 'դիսպոզիցիա',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0aubf',
    created: 1736961186993,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: "repeɾku'sjon",
      example:
        '* El acto tuvo repercusión en todo el globo.\n* El libro logró repercusión por su temática.',
      definition:
        '* influencia de algo en un asunto\n* difusión pública de algo',
      translation: 'հետադարձ ազդեցություն',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wO4Vy',
    created: 1736961187954,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: "resul'taðo",
      example:
        '* Sus éxitos son el resultado del trabajo bien hecho.\n* Estos zapatos me han dado muy mal resultado.',
      definition:
        '* efecto y consecuencia de una cosa\n* rendimiento que da una cosa',
      translation: 'արդյունք',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Cz26O',
    created: 1736961189442,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: "rekono'θeɾ",
      example:
        '* Reconocí a mi primo en medio de la multitud.\n* reconocer el terreno\n* La acusada reconoce que vio a la víctima aquella noche.',
      definition:
        '* determinar la identidad de una persona entre otras\n* considerar cuidadosamente una cosa o persona\n* admitir algo que se había negado',
      translation: 'ճանաչել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mgQH-',
    created: 1736961190506,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: "konsiðe'ɾaɾ",
      example:
        '* Considero que es mejor no comprar ahora.\n* Consideraré todas las calificaciones.\n* Considero que debes aceptar el trabajo.',
      definition:
        '* reflexionar minuciosamente sobre algo\n* tener en cuenta una cosa\n* realizar una crítica o juzgar',
      translation: 'համարել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fx6s7',
    created: 1736961191647,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: "deði'kaɾ",
      example:
        '* Este templo está dedicado a Júpiter.\n* Dedicó su último libro a sus hijos.\n* El dinero recaudado se dedicará a la restauración del edificio.',
      definition:
        '* consagrar al culto religioso o profano\n* ofrecer algo a una persona como muestra de agradecimiento, cariño, etc.\n* emplear algo a un uso determinado',
      translation: 'նվիրել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vps8e',
    created: 1736961192662,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: "xustifi'kaɾ",
      example:
        '* ¿El fin justifica los medios?\n* Justificó su denuncia con informes de espías.\n* justificar una línea a la derecha',
      definition:
        '* hacer una cosa que otra sea adecuada u oportuna\n* demostrar algo con razones convincentes\n* ajustar la alineación de un texto',
      translation: 'արդարացնել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K_05v',
    created: 1736961194137,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: "des'kwiðo",
      example:
        '* Hiciste mal el trabajo por puro descuido.\n* Bastó un descuido para que se perdiera la niña.\n* El descuido de su aspecto mostraba su estado de ánimo.',
      definition:
        '* falta de atención de algo bajo la propia responsabilidad\n* falta de atención momentánea\n* falta de aseo o desaliño en la persona',
      translation: 'անուշադրություն',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gcMyV',
    created: 1736961195423,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: "peɾswa'ðiɾ",
      example: 'Me persuadieron de que era mejor rechazar el encargo.',
      definition: 'convencer con argumentos a alguien de algo',
      translation: 'համոզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iT9jM',
    created: 1736961196540,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: "graðwal'meNte",
      example:
        'La ola de calor se va extendiendo gradualmente por todas las provincias.',
      definition: 'de manera paulatina, constante hacia un término final',
      translation: 'հասկացողաբար',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ats-g',
    created: 1736961197576,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: "im'pliθitamente",
      example:
        'Si bien el mensaje fue claro y contundente, implícitamente también nos explicaba los motivos de su decisón con su tono y sus gestos.',
      definition:
        'de forma indirecta, supuesta o sobreentendida, al mismo tiempo que algo que se expresa abiertamente',
      translation: 'անմիջապես',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vbPnj',
    created: 1736961198714,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: "notaβle'meNte",
      example: 'Su labor al frente de la empresa fue notablemente reconocida.',
      definition:
        'de manera destacada, que se percibe con claridad y denota contundencia',
      translation: 'նշանակալի կերպով',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'emWoy',
    created: 1736961199608,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: "inmeðjata'mente",
      example:
        '* Me llamaron inmediatamente después de ocurrido el hecho.\n* La orden deberá cumplirse inmediatamente.',
      definition:
        '* con la mayor rapidez\n* en el momento y sin que medie tiempo u otra cosa',
      translation: 'միանգամից',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'F2wYA',
    created: 1736961200683,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* En la oscuridad apenas se veía el sendero.\n* Apenas hemos vendido unas diez revistas.',
      definition:
        '* indica que la acción casi no sucede o no se nota\n* expresa una cantidad pequeña y aproximada',
      translation: 'միայն',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r3vez',
    created: 1736961204268,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: "sufiθjente'mente",
      example: 'Comieron suficientemente.',
      definition: 'en un grado o medida adecuados',
      translation: 'բավարար չափով',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YQ84S',
    created: 1736961205171,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: "peɾsis'tente",
      example: '* ideas persistentes\n* lluvia persistente',
      definition:
        '* que tiene firmeza y constancia\n* que tiene una duración prolongada',
      translation: 'համառ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eU5FG',
    created: 1736961205949,
    data: {
      language: 'es',
      source: 'integral',
      ipa: "inte'γɾal",
      example: '* una educación integral\n* arroz integral\n* pan integral',
      definition:
        '* que comprende todos los aspectos o partes necesarias para estar completo\n* cuyo grano no ha sido desprovisto de su cáscara\n* que es elaborado con harina de cereal con cáscara',
      translation: 'ինտեգրալ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ce65d',
    created: 1736961207096,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: "enkanta'ðoɾ",
      example: 'una niña encantadora',
      definition: 'que deja muy buena impresión por ser muy agradable',
      translation: 'հմայիչ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YAHlD',
    created: 1736961208112,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: "pɾeka'βiðo",
      example:
        '* Debes ser precavido y no andar de noche por las calles.\n* Mi padre es muy precavido cuando organiza un viaje.\n* Avanzaban por la jungla con paso precavido.',
      definition:
        '* que actúa con precaución\n* que piensa y dispone las cosas con antelación\n* que implica precaución',
      translation: 'պատրաստակամ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'R27Hp',
    created: 1736961209109,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: "re'aθjo",
      example: 'Era reacio a ver cine extranjero.',
      definition: 'que se opone o resiste a una influencia',
      translation: 'հակառակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'azmX6',
    created: 1736961210055,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: "siγnifika'tiβo",
      example:
        '* recibir una significativa ayuda\n* Este poemario es el más significativo del autor.',
      definition: '* que es importante\n* que comunica una cosa con propiedad',
      translation: 'նշանակալի',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
