import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '1SswD',
    created: 1736961238267,
    data: {
      language: 'es',
      source: 'la integridad',
      ipa: "inteγɾi'ðað",
      example: 'Denota integridad en todos sus actos.',
      definition: 'cualidad de quien tiene entereza moral',
      translation: 'тұтастық',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZzMhl',
    created: 1736961239115,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'төзімділік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tQIkM',
    created: 1736961240288,
    data: {
      language: 'es',
      source: 'el límite',
      ipa: "'limite",
      example: '* los límites de un territorio\n* límite de velocidad',
      definition:
        '* línea real o imaginaria que separa dos cosas\n* punto o grado que no puede superarse',
      translation: 'шекара',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'J45o2',
    created: 1736961241747,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: "disposi'θjon",
      example:
        '* El general eligió una buena disposición de las defensas.\n* Las empleadas han tenido una excelente disposición todo el tiempo.\n* tener una mala disposición física',
      definition:
        '* modo de estar colocadas cosas o personas\n* cualidad que se tiene para hacer algo\n* estado de ánimo o de salud',
      translation: 'орналасу',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S2cqb',
    created: 1736961242622,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: "repeɾku'sjon",
      example:
        '* El acto tuvo repercusión en todo el globo.\n* El libro logró repercusión por su temática.',
      definition:
        '* influencia de algo en un asunto\n* difusión pública de algo',
      translation: 'әсер',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tyi6C',
    created: 1736961243747,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: "resul'taðo",
      example:
        '* Sus éxitos son el resultado del trabajo bien hecho.\n* Estos zapatos me han dado muy mal resultado.',
      definition:
        '* efecto y consecuencia de una cosa\n* rendimiento que da una cosa',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'adBn_',
    created: 1736961244750,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: "rekono'θeɾ",
      example:
        '* Reconocí a mi primo en medio de la multitud.\n* reconocer el terreno\n* La acusada reconoce que vio a la víctima aquella noche.',
      definition:
        '* determinar la identidad de una persona entre otras\n* considerar cuidadosamente una cosa o persona\n* admitir algo que se había negado',
      translation: 'тану',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hbXQt',
    created: 1736961246115,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: "konsiðe'ɾaɾ",
      example:
        '* Considero que es mejor no comprar ahora.\n* Consideraré todas las calificaciones.\n* Considero que debes aceptar el trabajo.',
      definition:
        '* reflexionar minuciosamente sobre algo\n* tener en cuenta una cosa\n* realizar una crítica o juzgar',
      translation: 'қарастыру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RnQnd',
    created: 1736961247251,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: "deði'kaɾ",
      example:
        '* Este templo está dedicado a Júpiter.\n* Dedicó su último libro a sus hijos.\n* El dinero recaudado se dedicará a la restauración del edificio.',
      definition:
        '* consagrar al culto religioso o profano\n* ofrecer algo a una persona como muestra de agradecimiento, cariño, etc.\n* emplear algo a un uso determinado',
      translation: 'арнау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GL60e',
    created: 1736961248559,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: "xustifi'kaɾ",
      example:
        '* ¿El fin justifica los medios?\n* Justificó su denuncia con informes de espías.\n* justificar una línea a la derecha',
      definition:
        '* hacer una cosa que otra sea adecuada u oportuna\n* demostrar algo con razones convincentes\n* ajustar la alineación de un texto',
      translation: 'негіздеу',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P7wCS',
    created: 1736961249821,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: "des'kwiðo",
      example:
        '* Hiciste mal el trabajo por puro descuido.\n* Bastó un descuido para que se perdiera la niña.\n* El descuido de su aspecto mostraba su estado de ánimo.',
      definition:
        '* falta de atención de algo bajo la propia responsabilidad\n* falta de atención momentánea\n* falta de aseo o desaliño en la persona',
      translation: 'абайсыздық',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i9GYA',
    created: 1736961255210,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: "peɾswa'ðiɾ",
      example: 'Me persuadieron de que era mejor rechazar el encargo.',
      definition: 'convencer con argumentos a alguien de algo',
      translation: 'сендіру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6BJ84',
    created: 1736961256845,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: "graðwal'meNte",
      example:
        'La ola de calor se va extendiendo gradualmente por todas las provincias.',
      definition: 'de manera paulatina, constante hacia un término final',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PkaUn',
    created: 1736961257564,
    data: {
      language: 'es',
      source: 'implícitamente',
      ipa: "im'pliθitamente",
      example:
        'Si bien el mensaje fue claro y contundente, implícitamente también nos explicaba los motivos de su decisón con su tono y sus gestos.',
      definition:
        'de forma indirecta, supuesta o sobreentendida, al mismo tiempo que algo que se expresa abiertamente',
      translation: 'жасырын түрде',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MkHR6',
    created: 1736961258514,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: "notaβle'meNte",
      example: 'Su labor al frente de la empresa fue notablemente reconocida.',
      definition:
        'de manera destacada, que se percibe con claridad y denota contundencia',
      translation: 'айқын түрде',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M-IBm',
    created: 1736961259493,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: "inmeðjata'mente",
      example:
        '* Me llamaron inmediatamente después de ocurrido el hecho.\n* La orden deberá cumplirse inmediatamente.',
      definition:
        '* con la mayor rapidez\n* en el momento y sin que medie tiempo u otra cosa',
      translation: 'дереу',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XEEH9',
    created: 1736961260441,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* En la oscuridad apenas se veía el sendero.\n* Apenas hemos vendido unas diez revistas.',
      definition:
        '* indica que la acción casi no sucede o no se nota\n* expresa una cantidad pequeña y aproximada',
      translation: 'тек',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DbiXX',
    created: 1736961261555,
    data: {
      language: 'es',
      source: 'suficientemente',
      ipa: "sufiθjente'mente",
      example: 'Comieron suficientemente.',
      definition: 'en un grado o medida adecuados',
      translation: 'жеткілікті',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Q78aj',
    created: 1736961262552,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: "peɾsis'tente",
      example: '* ideas persistentes\n* lluvia persistente',
      definition:
        '* que tiene firmeza y constancia\n* que tiene una duración prolongada',
      translation: 'тұрақты',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4OQYu',
    created: 1736961263728,
    data: {
      language: 'es',
      source: 'integral',
      ipa: "inte'γɾal",
      example: '* una educación integral\n* arroz integral\n* pan integral',
      definition:
        '* que comprende todos los aspectos o partes necesarias para estar completo\n* cuyo grano no ha sido desprovisto de su cáscara\n* que es elaborado con harina de cereal con cáscara',
      translation: 'интеграл',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fW7I0',
    created: 1736961264828,
    data: {
      language: 'es',
      source: 'encantador',
      ipa: "enkanta'ðoɾ",
      example: 'una niña encantadora',
      definition: 'que deja muy buena impresión por ser muy agradable',
      translation: 'сүйкімді',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pRUvj',
    created: 1736961265728,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: "pɾeka'βiðo",
      example:
        '* Debes ser precavido y no andar de noche por las calles.\n* Mi padre es muy precavido cuando organiza un viaje.\n* Avanzaban por la jungla con paso precavido.',
      definition:
        '* que actúa con precaución\n* que piensa y dispone las cosas con antelación\n* que implica precaución',
      translation: 'сақтықпен',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xxtsv',
    created: 1736961267075,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: "re'aθjo",
      example: 'Era reacio a ver cine extranjero.',
      definition: 'que se opone o resiste a una influencia',
      translation: 'қарсылық білдіретін',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GHHmB',
    created: 1736961268121,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: "siγnifika'tiβo",
      example:
        '* recibir una significativa ayuda\n* Este poemario es el más significativo del autor.',
      definition: '* que es importante\n* que comunica una cosa con propiedad',
      translation: 'маңызды',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
