import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'RdMbB',
    created: 1736961129524,
    data: {
      language: 'es',
      source: 'інтегритед',
      ipa: '',
      example: '',
      definition: '',
      translation: 'інтегритет',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6iuFx',
    created: 1736961131200,
    data: {
      language: 'es',
      source: 'resiliencia',
      ipa: '',
      example: '',
      definition: '',
      translation: 'резилієнція',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5CAQl',
    created: 1736961132563,
    data: {
      language: 'es',
      source: 'ліміт',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ліміт',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mXZi_',
    created: 1736961134105,
    data: {
      language: 'es',
      source: 'la disposición',
      ipa: "disposi'θjon",
      example:
        '* El general eligió una buena disposición de las defensas.\n* Las empleadas han tenido una excelente disposición todo el tiempo.\n* tener una mala disposición física',
      definition:
        '* modo de estar colocadas cosas o personas\n* cualidad que se tiene para hacer algo\n* estado de ánimo o de salud',
      translation: 'розташування, схильність, настрій, диспозиція',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tnPlv',
    created: 1736961135544,
    data: {
      language: 'es',
      source: 'la repercusión',
      ipa: "repeɾku'sjon",
      example:
        '* El acto tuvo repercusión en todo el globo.\n* El libro logró repercusión por su temática.',
      definition:
        '* influencia de algo en un asunto\n* difusión pública de algo',
      translation: 'вплив, резонанс, реперкусія',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pGMzt',
    created: 1736961139948,
    data: {
      language: 'es',
      source: 'el resultado',
      ipa: "resul'taðo",
      example:
        '* Sus éxitos son el resultado del trabajo bien hecho.\n* Estos zapatos me han dado muy mal resultado.',
      definition:
        '* efecto y consecuencia de una cosa\n* rendimiento que da una cosa',
      translation: 'результат, вихід',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i_Jc2',
    created: 1736961142292,
    data: {
      language: 'es',
      source: 'reconocer',
      ipa: "rekono'θeɾ",
      example:
        '* Reconocí a mi primo en medio de la multitud.\n* reconocer el terreno\n* La acusada reconoce que vio a la víctima aquella noche.',
      definition:
        '* determinar la identidad de una persona entre otras\n* considerar cuidadosamente una cosa o persona\n* admitir algo que se había negado',
      translation: 'визнати, визначити',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pIo4T',
    created: 1736961146790,
    data: {
      language: 'es',
      source: 'considerar',
      ipa: "konsiðe'ɾaɾ",
      example:
        '* Considero que es mejor no comprar ahora.\n* Consideraré todas las calificaciones.\n* Considero que debes aceptar el trabajo.',
      definition:
        '* reflexionar minuciosamente sobre algo\n* tener en cuenta una cosa\n* realizar una crítica o juzgar',
      translation: 'розглядати, враховувати, критично оцінювати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D0dE3',
    created: 1736961148801,
    data: {
      language: 'es',
      source: 'dedicar',
      ipa: "deði'kaɾ",
      example:
        '* Este templo está dedicado a Júpiter.\n* Dedicó su último libro a sus hijos.\n* El dinero recaudado se dedicará a la restauración del edificio.',
      definition:
        '* consagrar al culto religioso o profano\n* ofrecer algo a una persona como muestra de agradecimiento, cariño, etc.\n* emplear algo a un uso determinado',
      translation: 'присвячувати, посвячувати, використовувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K3E12',
    created: 1736961150519,
    data: {
      language: 'es',
      source: 'justificar',
      ipa: "xustifi'kaɾ",
      example:
        '* ¿El fin justifica los medios?\n* Justificó su denuncia con informes de espías.\n* justificar una línea a la derecha',
      definition:
        '* hacer una cosa que otra sea adecuada u oportuna\n* demostrar algo con razones convincentes\n* ajustar la alineación de un texto',
      translation: 'обґрунтувати, довести, виправдати, виправдовувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Njjfg',
    created: 1736961152834,
    data: {
      language: 'es',
      source: 'el descuido',
      ipa: "des'kwiðo",
      example:
        '* Hiciste mal el trabajo por puro descuido.\n* Bastó un descuido para que se perdiera la niña.\n* El descuido de su aspecto mostraba su estado de ánimo.',
      definition:
        '* falta de atención de algo bajo la propia responsabilidad\n* falta de atención momentánea\n* falta de aseo o desaliño en la persona',
      translation: 'неувага, недбалість, неохайність',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Vh0_s',
    created: 1736961157986,
    data: {
      language: 'es',
      source: 'persuadir',
      ipa: "peɾswa'ðiɾ",
      example: 'Me persuadieron de que era mejor rechazar el encargo.',
      definition: 'convencer con argumentos a alguien de algo',
      translation: 'переконати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yvVZA',
    created: 1736961159482,
    data: {
      language: 'es',
      source: 'gradualmente',
      ipa: "graðwal'meNte",
      example:
        'La ola de calor se va extendiendo gradualmente por todas las provincias.',
      definition: 'de manera paulatina, constante hacia un término final',
      translation: 'постепово, постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5bv0W',
    created: 1736961160425,
    data: {
      language: 'es',
      source: 'імпліцитно',
      ipa: '',
      example: '',
      definition: '',
      translation: 'імпліцитно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yaj53',
    created: 1736961165161,
    data: {
      language: 'es',
      source: 'notablemente',
      ipa: "notaβle'meNte",
      example: 'Su labor al frente de la empresa fue notablemente reconocida.',
      definition:
        'de manera destacada, que se percibe con claridad y denota contundencia',
      translation: 'помітно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3VGWt',
    created: 1736961166965,
    data: {
      language: 'es',
      source: 'inmediatamente',
      ipa: "inmeðjata'mente",
      example:
        '* Me llamaron inmediatamente después de ocurrido el hecho.\n* La orden deberá cumplirse inmediatamente.',
      definition:
        '* con la mayor rapidez\n* en el momento y sin que medie tiempo u otra cosa',
      translation: 'негайно, одразу',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NqB_o',
    created: 1736961168630,
    data: {
      language: 'es',
      source: 'apenas',
      ipa: 'aˈpenas',
      example:
        '* En la oscuridad apenas se veía el sendero.\n* Apenas hemos vendido unas diez revistas.',
      definition:
        '* indica que la acción casi no sucede o no se nota\n* expresa una cantidad pequeña y aproximada',
      translation: 'ледве, лише',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0QcQU',
    created: 1736961169645,
    data: {
      language: 'es',
      source: 'достатньо',
      ipa: '',
      example: '',
      definition: '',
      translation: 'достатньо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S5J-4',
    created: 1736961171616,
    data: {
      language: 'es',
      source: 'persistente',
      ipa: "peɾsis'tente",
      example: '* ideas persistentes\n* lluvia persistente',
      definition:
        '* que tiene firmeza y constancia\n* que tiene una duración prolongada',
      translation: 'постійний, тривалий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'usg2L',
    created: 1736961174002,
    data: {
      language: 'es',
      source: 'integral',
      ipa: "inte'γɾal",
      example: '* una educación integral\n* arroz integral\n* pan integral',
      definition:
        '* que comprende todos los aspectos o partes necesarias para estar completo\n* cuyo grano no ha sido desprovisto de su cáscara\n* que es elaborado con harina de cereal con cáscara',
      translation: 'цілісний, цільний, цільнозерновий, інтегральний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_0tXQ',
    created: 1736961176579,
    data: {
      language: 'es',
      source: 'el encanto',
      ipa: "en'kanto",
      example:
        '* Su principal encanto reside en su simpatía.\n* un encanto de alumno\n* El brujo profirió un poderoso encanto.',
      definition:
        '* conjunto de cualidades que hacen a una persona o cosa muy atractiva o agradable\n* persona o cosa que agrada por sus cualidades\n* acción de someter la voluntad de alguien mediante acciones malignas',
      translation: 'чарівність, привабливість',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RHGun',
    created: 1736961178493,
    data: {
      language: 'es',
      source: 'precavido',
      ipa: "pɾeka'βiðo",
      example:
        '* Debes ser precavido y no andar de noche por las calles.\n* Mi padre es muy precavido cuando organiza un viaje.\n* Avanzaban por la jungla con paso precavido.',
      definition:
        '* que actúa con precaución\n* que piensa y dispone las cosas con antelación\n* que implica precaución',
      translation: 'обережний, попереджувальний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kvUJI',
    created: 1736961180086,
    data: {
      language: 'es',
      source: 'reacio',
      ipa: "re'aθjo",
      example: 'Era reacio a ver cine extranjero.',
      definition: 'que se opone o resiste a una influencia',
      translation: 'опірний, негативний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MtoPH',
    created: 1736961182001,
    data: {
      language: 'es',
      source: 'significativo',
      ipa: "siγnifika'tiβo",
      example:
        '* recibir una significativa ayuda\n* Este poemario es el más significativo del autor.',
      definition: '* que es importante\n* que comunica una cosa con propiedad',
      translation: 'значущий, важливий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
