import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ZNAEy',
    created: 1737102698298,
    data: {
      language: 'fi',
      source: 'eheys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bütünlük',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '667dx',
    created: 1737102699078,
    data: {
      language: 'fi',
      source: 'joustavuutta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elastiklik',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-an7u',
    created: 1737102699859,
    data: {
      language: 'fi',
      source: 'kynnys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'eşik',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Cc9ok',
    created: 1737102700550,
    data: {
      language: 'fi',
      source: 'taipumus',
      ipa: '',
      example: '',
      definition: '',
      translation: 'meyl',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hycjv',
    created: 1737102701317,
    data: {
      language: 'fi',
      source: 'jälkivaikutusta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sonrakı təsir',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NbEoI',
    created: 1737102701858,
    data: {
      language: 'fi',
      source: 'tulokset',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nəticələr',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'MQDm1',
    created: 1737102702626,
    data: {
      language: 'fi',
      source: 'tunnustaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tanımaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DNfn7',
    created: 1737102703247,
    data: {
      language: 'fi',
      source: 'harkita',
      ipa: '',
      example: '',
      definition: '',
      translation: 'düşünmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5RgO1',
    created: 1737102712856,
    data: {
      language: 'fi',
      source: 'omistautua',
      ipa: '',
      example: '',
      definition: '',
      translation: 'özünü həsr etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Bcowr',
    created: 1737102722649,
    data: {
      language: 'fi',
      source: 'perustella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'əsaslandırmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'o-mrO',
    created: 1737102732304,
    data: {
      language: 'fi',
      source: 'laiminlyödä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sayıb çıxmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'aahCi',
    created: 1737102742150,
    data: {
      language: 'fi',
      source: 'suostutella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'razı salmaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xsGak',
    created: 1737102751644,
    data: {
      language: 'fi',
      source: 'vähitellen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tədricən',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yVHzk',
    created: 1737102769984,
    data: {
      language: 'fi',
      source: 'epəsuorasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dolayı yolla',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'q4anE',
    created: 1737102779934,
    data: {
      language: 'fi',
      source: 'erityisesti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'xüsusilə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SKTlT',
    created: 1737102780566,
    data: {
      language: 'fi',
      source: 'viipymättä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tez',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SAsyX',
    created: 1737102790172,
    data: {
      language: 'fi',
      source: 'karkeasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'təxminən',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'x4XRd',
    created: 1737102808287,
    data: {
      language: 'fi',
      source: 'riittävästi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kifayət qədər',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pvcy8',
    created: 1737102818027,
    data: {
      language: 'fi',
      source: 'jatkuvaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'davamlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Nn96w',
    created: 1737102836423,
    data: {
      language: 'fi',
      source: 'kattava',
      ipa: '',
      example: '',
      definition: '',
      translation: 'əhatə edən',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dIr-J',
    created: 1737102846035,
    data: {
      language: 'fi',
      source: 'ihana',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gözəl',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_bh6o',
    created: 1737102855713,
    data: {
      language: 'fi',
      source: 'varovainen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ehtiyatlı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AMhto',
    created: 1737102865343,
    data: {
      language: 'fi',
      source: 'vastahakoinen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'müxalif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uNbwd',
    created: 1737102874913,
    data: {
      language: 'fi',
      source: 'merkittävä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mühüm',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
