import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'b9aKL',
    created: 1737102134434,
    data: {
      language: 'fi',
      source: 'eheys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'intégrité',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lj2YK',
    created: 1737102135249,
    data: {
      language: 'fi',
      source: 'joustavuutta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'flexibilité',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hA-6F',
    created: 1737102136339,
    data: {
      language: 'fi',
      source: 'kynnys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'seuil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tOFPY',
    created: 1737102137103,
    data: {
      language: 'fi',
      source: 'taipumus',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tendance',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SweOW',
    created: 1737102137792,
    data: {
      language: 'fi',
      source: 'jälkivaikutusta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'effet secondaire',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0qRdf',
    created: 1737102138483,
    data: {
      language: 'fi',
      source: 'tulokset',
      ipa: '',
      example: '',
      definition: '',
      translation: 'résultats',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CYzQt',
    created: 1737102143870,
    data: {
      language: 'fi',
      source: 'tunnustaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reconnaître',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ujZqp',
    created: 1737102144730,
    data: {
      language: 'fi',
      source: 'harkita',
      ipa: '',
      example: '',
      definition: '',
      translation: 'envisager',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '49bXt',
    created: 1737102147447,
    data: {
      language: 'fi',
      source: 'omistautua',
      ipa: '',
      example: '',
      definition: '',
      translation: 'se consacrer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A9Wga',
    created: 1737102149879,
    data: {
      language: 'fi',
      source: 'perustella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justifier',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'oY94U',
    created: 1737102150632,
    data: {
      language: 'fi',
      source: 'laiminlyödä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'négliger',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'unppw',
    created: 1737102151332,
    data: {
      language: 'fi',
      source: 'suostutella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuader',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'XTZmF',
    created: 1737102152140,
    data: {
      language: 'fi',
      source: 'vähitellen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'petit à petit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'i4Gkd',
    created: 1737102152731,
    data: {
      language: 'fi',
      source: 'epäsuorasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'indirectement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Rdy2h',
    created: 1737102153438,
    data: {
      language: 'fi',
      source: 'erityisesti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'en particulier',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'KGKaU',
    created: 1737102154117,
    data: {
      language: 'fi',
      source: 'viipymättä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sans délai',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hLffb',
    created: 1737102154948,
    data: {
      language: 'fi',
      source: 'karkeasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'grossièrement',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'mffd3',
    created: 1737102155561,
    data: {
      language: 'fi',
      source: 'riittävästi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suffisamment',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'yh_LM',
    created: 1737102156217,
    data: {
      language: 'fi',
      source: 'jatkuvaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'continu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'IlQUu',
    created: 1737102158215,
    data: {
      language: 'fi',
      source: 'kattava',
      ipa: '',
      example: '',
      definition: '',
      translation: 'global',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6JCyQ',
    created: 1737102159680,
    data: {
      language: 'fi',
      source: 'ihana',
      ipa: '',
      example: '',
      definition: '',
      translation: 'merveilleux',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4SLYS',
    created: 1737102160337,
    data: {
      language: 'fi',
      source: 'varovainen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'prudent',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9m5C3',
    created: 1737102160931,
    data: {
      language: 'fi',
      source: 'vastahakoinen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'réticent',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'd67oH',
    created: 1737102161643,
    data: {
      language: 'fi',
      source: 'merkittävä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significatif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
