import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8gye2',
    created: 1737102575826,
    data: {
      language: 'fi',
      source: 'eheys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kesatuan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gPpTk',
    created: 1737102576494,
    data: {
      language: 'fi',
      source: 'joustavuutta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kelenturan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AvEBK',
    created: 1737102577300,
    data: {
      language: 'fi',
      source: 'kynnys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ambang',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4f3Wl',
    created: 1737102578066,
    data: {
      language: 'fi',
      source: 'taipumus',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kecenderungan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ZeeVY',
    created: 1737102578900,
    data: {
      language: 'fi',
      source: 'jälkivaikutusta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'efek lanjutan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'aafFN',
    created: 1737102579546,
    data: {
      language: 'fi',
      source: 'tulokset',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hasil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6NuLG',
    created: 1737102580354,
    data: {
      language: 'fi',
      source: 'tunnustaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengakui',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'UThah',
    created: 1737102581023,
    data: {
      language: 'fi',
      source: 'harkita',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mempertimbangkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TOWtr',
    created: 1737102581849,
    data: {
      language: 'fi',
      source: 'omistautua',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mendedikasikan diri',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '00C3W',
    created: 1737102582824,
    data: {
      language: 'fi',
      source: 'perustella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mendasarkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'i1W7E',
    created: 1737102583535,
    data: {
      language: 'fi',
      source: 'laiminlyödä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengabaikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HhYKU',
    created: 1737102584530,
    data: {
      language: 'fi',
      source: 'suostutella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'membujuk',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4ecFR',
    created: 1737102585217,
    data: {
      language: 'fi',
      source: 'vähitellen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara bertahap',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '68JrT',
    created: 1737102585830,
    data: {
      language: 'fi',
      source: 'epäsuorasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara tidak langsung',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'k58iX',
    created: 1737102586442,
    data: {
      language: 'fi',
      source: 'erityisesti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara khusus',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-_OzF',
    created: 1737102587075,
    data: {
      language: 'fi',
      source: 'viipymättä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'segera',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SWMa1',
    created: 1737102587799,
    data: {
      language: 'fi',
      source: 'karkeasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kasar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nht1u',
    created: 1737102588411,
    data: {
      language: 'fi',
      source: 'riittävästi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cukup',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zCo6T',
    created: 1737102589090,
    data: {
      language: 'fi',
      source: 'jatkuvaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berkelanjutan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zA7Jg',
    created: 1737102589882,
    data: {
      language: 'fi',
      source: 'kattava',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menyeluruh',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tgbhi',
    created: 1737102590698,
    data: {
      language: 'fi',
      source: 'ihana',
      ipa: '',
      example: '',
      definition: '',
      translation: 'indah',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ftw2R',
    created: 1737102591490,
    data: {
      language: 'fi',
      source: 'varovainen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hati-hati',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0xqyK',
    created: 1737102592443,
    data: {
      language: 'fi',
      source: 'vastahakoinen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'menentang',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '1wYJI',
    created: 1737102593107,
    data: {
      language: 'fi',
      source: 'merkittävä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'signifikan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
