import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'EmoLR',
    created: 1737102312644,
    data: {
      language: 'fi',
      source: 'eheys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integriteit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NJoeD',
    created: 1737102313421,
    data: {
      language: 'fi',
      source: 'joustavuutta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'flexibiliteit',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hPEiJ',
    created: 1737102314090,
    data: {
      language: 'fi',
      source: 'kynnys',
      ipa: '',
      example: '',
      definition: '',
      translation: 'drempel',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Yr3Yu',
    created: 1737102314643,
    data: {
      language: 'fi',
      source: 'taipumus',
      ipa: '',
      example: '',
      definition: '',
      translation: 'neiging',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'eyIot',
    created: 1737102315616,
    data: {
      language: 'fi',
      source: 'jälkivaikutusta',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nacereffect',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zhEtW',
    created: 1737102316129,
    data: {
      language: 'fi',
      source: 'tulokset',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resultaten',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3EbCg',
    created: 1737102316769,
    data: {
      language: 'fi',
      source: 'tunnustaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkennen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_OlMJ',
    created: 1737102317357,
    data: {
      language: 'fi',
      source: 'harkita',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overwegen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'mfFAu',
    created: 1737102318204,
    data: {
      language: 'fi',
      source: 'omistautua',
      ipa: '',
      example: '',
      definition: '',
      translation: 'zich wijden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TvaOy',
    created: 1737102319618,
    data: {
      language: 'fi',
      source: 'perustella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'onderbouwen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wWEsX',
    created: 1737102320427,
    data: {
      language: 'fi',
      source: 'laiminlyödä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'verwaarlozen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'seKML',
    created: 1737102321140,
    data: {
      language: 'fi',
      source: 'suostutella',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overhalen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WS3OR',
    created: 1737102321754,
    data: {
      language: 'fi',
      source: 'vähitellen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'geleidelijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'RRJO2',
    created: 1737102322376,
    data: {
      language: 'fi',
      source: 'epäsuorasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'indirect',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nhbzx',
    created: 1737102323073,
    data: {
      language: 'fi',
      source: 'erityisesti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'in het bijzonder',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wyZmj',
    created: 1737102323839,
    data: {
      language: 'fi',
      source: 'viipymättä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'onmiddellijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YwgBW',
    created: 1737102324537,
    data: {
      language: 'fi',
      source: 'karkeasti',
      ipa: '',
      example: '',
      definition: '',
      translation: 'grofweg',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lNfNf',
    created: 1737102325611,
    data: {
      language: 'fi',
      source: 'riittävästi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voldoende',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'cRRuk',
    created: 1737102326992,
    data: {
      language: 'fi',
      source: 'jatkuvaa',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voortdurend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kyMbq',
    created: 1737102327917,
    data: {
      language: 'fi',
      source: 'kattava',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omvattend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fXzGm',
    created: 1737102328450,
    data: {
      language: 'fi',
      source: 'ihana',
      ipa: '',
      example: '',
      definition: '',
      translation: 'heerlijk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'thP6m',
    created: 1737102329861,
    data: {
      language: 'fi',
      source: 'varovainen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'voorzichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CfBH6',
    created: 1737102330551,
    data: {
      language: 'fi',
      source: 'vastahakoinen',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tegenstribbelend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '8wPdP',
    created: 1737102331357,
    data: {
      language: 'fi',
      source: 'merkittävä',
      ipa: '',
      example: '',
      definition: '',
      translation: 'significant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
