import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'spGj8',
    created: 1736961445378,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: 'ɛ̃tegʀite',
      example: "* l'intégrité d'un juge\n* l'intégrité des biens",
      definition: "* grande honnêteté\n* fait d'être entier",
      translation:
        '公明正大（こうめいせいだい）, 完全（かんぜん）さ、無傷（むきず）, 誠実',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UTkFG',
    created: 1736961446493,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'レジリエンス',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NW8m_',
    created: 1736961447515,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: 'sœj',
      example:
        "* attendre sur le seuil\n* au seuil de l'année\n* le seuil de la douleur",
      definition: "* entrée d'une maison\n* commencement\n* limite",
      translation:
        '敷居（しきい）, 始（はじ）まり、初（はじ）め, 限界（げんかい）',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'p9-Ox',
    created: 1736961449502,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: 'dispozisjɔ̃',
      example:
        "* changer la disposition d'une chambre\n* avoir des dispositions pour les langues",
      definition:
        '* façon dont sont placées les choses\n* capacité, qualité nécessaire pour faire quelque chose',
      translation: '配置（はいち）, 素質（そしつ）、才能（さいのう）',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'R-Fa3',
    created: 1736961451645,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: 'ʀepɛʀkysjɔ̃',
      example:
        "* répercussion d'un bruit\n* avoir des répercussions sur quelque chose",
      definition: "* renvoi d'un son\n* conséquence",
      translation: '反響（はんきょう）, 影響（えいきょう）、結果（けっか）',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fflkY',
    created: 1736961452405,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: 'ʀezylta',
      example:
        "* C'est le résultat qui compte !\n* les résultats d'un sondage\n* le résultat d'une addition",
      definition:
        "* ce qui se produit, ce que l'on obtient\n* information donnée par quelque chose\n* solution d'un calcul",
      translation:
        '成果（せいか）, 結果（けっか）, 計算（けいさん）の結果、答（こた）え, 成績（せいせき）',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jBRk1',
    created: 1736961453372,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: 'ʀəkɔnɛtʀ',
      example:
        "* reconnaître un morceau de musique\n* reconnaître ses torts\n* reconnaître l'autorité d'un souverain",
      definition:
        "* identifier quelqu’un ou quelque chose que l'on connaît\n* avouer\n* admettre comme légitime",
      translation:
        '見覚（みおぼ）え／聞（き）き覚（おぼ）えがある、それと分（わ）かる, 認（みと）める, ＜政府（せいふ）・国家（こっか）を＞承認（しょうにん）する, 偵察（ていさつ）する, 認識する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mFszZ',
    created: 1736961454372,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: 'kɔ̃sideʀe',
      example: '',
      definition: '',
      translation: '考慮する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Olfdu',
    created: 1736961455304,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: 'kɔ̃sakʀe',
      example: '* consacrer du temps à quelque chose\n* consacrer une église',
      definition: '* employer quelque chose dans un but\n* rendre sacré',
      translation: '捧（ささ）げる, 聖別（せいべつ）する, 捧げる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jk16J',
    created: 1736961456373,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: 'ʒystifie',
      example: 'justifier des dépenses',
      definition: 'prouver, expliquer quelque chose',
      translation: '釈明（しゃくめい）する、説明（せつめい）する, 正当化する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7hPri',
    created: 1736961457923,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: 'negliʒɑ̃s',
      example:
        '* oublier quelque chose par négligence\n* La panne est due à une négligence.',
      definition:
        '* manque de soin, de vigilance\n* faute commise par manque de soin',
      translation: '怠慢, 不注意',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'po-9u',
    created: 1736961458994,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: 'pɛʀsɥade',
      example: 'persuader quelqu’un de quelque chose',
      definition: 'convaincre',
      translation: '納得（なっとく）させる、説得（せっとく）する, 説得する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5pBTh',
    created: 1736961459792,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: 'pʀɔgʀesivmɑ̃',
      example: 'diminuer progressivement',
      definition: 'petit à petit',
      translation: '徐々（じょじょ）に、次第（しだい）に, 徐々に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jKlWk',
    created: 1736961461421,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: 'ɛ̃plisitmɑ̃',
      example: 'Il a implicitement reconnu son erreur.',
      definition: 'de façon implicite, sans le dire',
      translation: '暗黙的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qpGsy',
    created: 1736961462562,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: 'nɔtamɑ̃',
      example: '',
      definition: 'en particulier',
      translation: '特（とく）に、とりわけ, 特に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NfHhC',
    created: 1736961463558,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: 'ʀapidmɑ̃',
      example: 'faire quelque chose rapidement',
      definition: 'très vite',
      translation: '速（はや）く、すぐに, 速やかに',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8gEjS',
    created: 1736961464243,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'おおよそ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jfgAo',
    created: 1736961465315,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: 'syfizamɑ̃',
      example: 'avoir suffisamment de place',
      definition: 'assez',
      translation: '十分（じゅうぶん）に, 十分に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C7y0y',
    created: 1736961466734,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: 'pɛʀsistɑ̃',
      example: 'une inquiétude persistante',
      definition: 'qui dure toujours',
      translation: '持続的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tms30',
    created: 1736961467915,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: 'kɔ̃plɛ',
      example: '* une liste complète\n* hôtel complet',
      definition: "* entier, total\n* où il n'y a plus de place",
      translation: '完全（かんぜん）な, 満員（まんいん）の, 完全な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MTExS',
    created: 1736961468672,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: 'delisjø',
      example: 'un repas délicieux',
      definition: 'qui est très bon, très agréable',
      translation:
        'とても美味（おい）しい、非常（ひじょう）に快（こころよ）い, 美味しい',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XCoWt',
    created: 1736961469443,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: 'pʀydɑ̃',
      example: '* une conduite prudente\n* un choix prudent',
      definition:
        "* qui a pour but d'éviter les dangers\n* provoqué, déterminé par la prudence",
      translation: '慎重（しんちょう）な、用心深（ようじんぶか）い, 慎重な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AYql5',
    created: 1736961470619,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: 'ʀetisɑ̃',
      example: 'Il était réticent concernant ce mariage.',
      definition: 'qui hésite à faire quelque chose',
      translation: 'ためらいがちな',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NpZ2U',
    created: 1736961471463,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: 'siɲifikatif',
      example: 'un geste significatif',
      definition: 'qui indique ou exprime quelque chose',
      translation: '意味（いみ）のある, 重要な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
