import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8l8fk',
    created: 1736962238124,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: 'ɛ̃tegʀite',
      example: "* l'intégrité d'un juge\n* l'intégrité des biens",
      definition: "* grande honnêteté\n* fait d'être entier",
      translation: 'ინტეგრიტეტი',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QOFtn',
    created: 1736962239172,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'რეზილენცია',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9tB2q',
    created: 1736962240328,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: 'sœj',
      example:
        "* attendre sur le seuil\n* au seuil de l'année\n* le seuil de la douleur",
      definition: "* entrée d'une maison\n* commencement\n* limite",
      translation: 'საფეხური',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D-0vZ',
    created: 1736962241480,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: 'dispozisjɔ̃',
      example:
        "* changer la disposition d'une chambre\n* avoir des dispositions pour les langues",
      definition:
        '* façon dont sont placées les choses\n* capacité, qualité nécessaire pour faire quelque chose',
      translation: 'დისპოზიცია',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yurj-',
    created: 1736962243583,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: 'ʀepɛʀkysjɔ̃',
      example:
        "* répercussion d'un bruit\n* avoir des répercussions sur quelque chose",
      definition: "* renvoi d'un son\n* conséquence",
      translation: 'რეპერკუსია',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QdFuh',
    created: 1736962245243,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: 'ʀezylta',
      example:
        "* C'est le résultat qui compte !\n* les résultats d'un sondage\n* le résultat d'une addition",
      definition:
        "* ce qui se produit, ce que l'on obtient\n* information donnée par quelque chose\n* solution d'un calcul",
      translation: 'შედეგი',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G3cHf',
    created: 1736962246434,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: 'ʀəkɔnɛtʀ',
      example:
        "* reconnaître un morceau de musique\n* reconnaître ses torts\n* reconnaître l'autorité d'un souverain",
      definition:
        "* identifier quelqu’un ou quelque chose que l'on connaît\n* avouer\n* admettre comme légitime",
      translation: 'აღიარება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W5cCe',
    created: 1736962247328,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: 'kɔ̃sideʀe',
      example: '',
      definition: '',
      translation: 'გადაწყვეტილება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Vslgu',
    created: 1736962248561,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: 'kɔ̃sakʀe',
      example: '* consacrer du temps à quelque chose\n* consacrer une église',
      definition: '* employer quelque chose dans un but\n* rendre sacré',
      translation: 'დაათმო',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W0wKU',
    created: 1736962249620,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: 'ʒystifie',
      example: 'justifier des dépenses',
      definition: 'prouver, expliquer quelque chose',
      translation: 'მხარდაჭერა',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Fe6wr',
    created: 1736962250856,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: 'negliʒɑ̃s',
      example:
        '* oublier quelque chose par négligence\n* La panne est due à une négligence.',
      definition:
        '* manque de soin, de vigilance\n* faute commise par manque de soin',
      translation: 'გაუფრთხილებლობა',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O_zYo',
    created: 1736962251965,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: 'pɛʀsɥade',
      example: 'persuader quelqu’un de quelque chose',
      definition: 'convaincre',
      translation: 'დაარწმუნო',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zI44h',
    created: 1736962253478,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: 'pʀɔgʀesivmɑ̃',
      example: 'diminuer progressivement',
      definition: 'petit à petit',
      translation: 'პროგრესულად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7HUTe',
    created: 1736962254563,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: 'ɛ̃plisitmɑ̃',
      example: 'Il a implicitement reconnu son erreur.',
      definition: 'de façon implicite, sans le dire',
      translation: 'იმპლიციტურად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's_nxF',
    created: 1736962255438,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: 'nɔtamɑ̃',
      example: '',
      definition: 'en particulier',
      translation: 'მათ შორის',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wp7VG',
    created: 1736962256774,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: 'ʀapidmɑ̃',
      example: 'faire quelque chose rapidement',
      definition: 'très vite',
      translation: 'სწრაფად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j5oPF',
    created: 1736962258171,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'დაახლოებით',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cqf4I',
    created: 1736962258961,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: 'syfizamɑ̃',
      example: 'avoir suffisamment de place',
      definition: 'assez',
      translation: 'საკმარისად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KuRa3',
    created: 1736962260320,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: 'pɛʀsistɑ̃',
      example: 'une inquiétude persistante',
      definition: 'qui dure toujours',
      translation: 'მუდმივი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ofO6X',
    created: 1736962261139,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: 'kɔ̃plɛ',
      example: '* une liste complète\n* hôtel complet',
      definition: "* entier, total\n* où il n'y a plus de place",
      translation: 'სრული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nKhS8',
    created: 1736962262006,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: 'delisjø',
      example: 'un repas délicieux',
      definition: 'qui est très bon, très agréable',
      translation: 'გემრიელი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'q5Fg-',
    created: 1736962262754,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: 'pʀydɑ̃',
      example: '* une conduite prudente\n* un choix prudent',
      definition:
        "* qui a pour but d'éviter les dangers\n* provoqué, déterminé par la prudence",
      translation: 'გონივრული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Be3rT',
    created: 1736962263647,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: 'ʀetisɑ̃',
      example: 'Il était réticent concernant ce mariage.',
      definition: 'qui hésite à faire quelque chose',
      translation: 'დაბრკოლებული',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FMGo5',
    created: 1736962264534,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: 'siɲifikatif',
      example: 'un geste significatif',
      definition: 'qui indique ou exprime quelque chose',
      translation: 'მნიშვნელოვანი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
