import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'QXLZ3',
    created: 1736961472441,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: 'ɛ̃tegʀite',
      example: "* l'intégrité d'un juge\n* l'intégrité des biens",
      definition: "* grande honnêteté\n* fait d'être entier",
      translation:
        'че́стность, неподку́пность, це́лостность, полнота́, целостность',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KWgtp',
    created: 1736961473754,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'резилиентность',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2CCi7',
    created: 1736961474655,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: 'sœj',
      example:
        "* attendre sur le seuil\n* au seuil de l'année\n* le seuil de la douleur",
      definition: "* entrée d'une maison\n* commencement\n* limite",
      translation: 'поро́г, нача́ло, преде́л, порог',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v1Rbn',
    created: 1736961476159,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: 'dispozisjɔ̃',
      example:
        "* changer la disposition d'une chambre\n* avoir des dispositions pour les langues",
      definition:
        '* façon dont sont placées les choses\n* capacité, qualité nécessaire pour faire quelque chose',
      translation: 'расположе́ние, предрасположе́ние, расположение',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YvqCV',
    created: 1736961477009,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: 'ʀepɛʀkysjɔ̃',
      example:
        "* répercussion d'un bruit\n* avoir des répercussions sur quelque chose",
      definition: "* renvoi d'un son\n* conséquence",
      translation: 'о́тзвук, после́дствие, последствие',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6a6t7',
    created: 1736961478014,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: 'ʀezylta',
      example:
        "* C'est le résultat qui compte !\n* les résultats d'un sondage\n* le résultat d'une addition",
      definition:
        "* ce qui se produit, ce que l'on obtient\n* information donnée par quelque chose\n* solution d'un calcul",
      translation: 'результа́т, ито́г, результат',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Utd2H',
    created: 1736961478872,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: 'ʀəkɔnɛtʀ',
      example:
        "* reconnaître un morceau de musique\n* reconnaître ses torts\n* reconnaître l'autorité d'un souverain",
      definition:
        "* identifier quelqu’un ou quelque chose que l'on connaît\n* avouer\n* admettre comme légitime",
      translation:
        'узнава́ть, признава́ть, признавать, сознаваться, узнавать, исследовать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'z6n_r',
    created: 1736961479887,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: 'kɔ̃sideʀe',
      example: '',
      definition: '',
      translation: 'рассматривать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cOVtg',
    created: 1736961480954,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: 'kɔ̃sakʀe',
      example: '* consacrer du temps à quelque chose\n* consacrer une église',
      definition: '* employer quelque chose dans un but\n* rendre sacré',
      translation: 'посвяща́ть, дава́ть, освяща́ть, посвящать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JtUyw',
    created: 1736961482505,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: 'ʒystifie',
      example: 'justifier des dépenses',
      definition: 'prouver, expliquer quelque chose',
      translation: 'опра́вдывать, оправдывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'x0DJH',
    created: 1736961484624,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: 'negliʒɑ̃s',
      example:
        '* oublier quelque chose par négligence\n* La panne est due à une négligence.',
      definition:
        '* manque de soin, de vigilance\n* faute commise par manque de soin',
      translation: 'небрежность, халатность',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O52be',
    created: 1736961485600,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: 'pɛʀsɥade',
      example: 'persuader quelqu’un de quelque chose',
      definition: 'convaincre',
      translation: 'убежда́ть, убеждать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VGK-L',
    created: 1736961486588,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: 'pʀɔgʀesivmɑ̃',
      example: 'diminuer progressivement',
      definition: 'petit à petit',
      translation: 'постепе́нно, постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C4HBu',
    created: 1736961489847,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: 'ɛ̃plisitmɑ̃',
      example: 'Il a implicitement reconnu son erreur.',
      definition: 'de façon implicite, sans le dire',
      translation: 'неявно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gTqj9',
    created: 1736961490745,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: 'nɔtamɑ̃',
      example: '',
      definition: 'en particulier',
      translation: 'и́менно, осо́бенно, в частности',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZQnGM',
    created: 1736961491840,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: 'ʀapidmɑ̃',
      example: 'faire quelque chose rapidement',
      definition: 'très vite',
      translation: 'бы́стро, быстро',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c5ojW',
    created: 1736961492688,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'примерно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dX7dt',
    created: 1736961493778,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: 'syfizamɑ̃',
      example: 'avoir suffisamment de place',
      definition: 'assez',
      translation: 'доста́точно, достаточно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-u73I',
    created: 1736961495527,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: 'pɛʀsistɑ̃',
      example: 'une inquiétude persistante',
      definition: 'qui dure toujours',
      translation: 'постоянный, упорный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JIGNA',
    created: 1736961496341,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: 'kɔ̃plɛ',
      example: '* une liste complète\n* hôtel complet',
      definition: "* entier, total\n* où il n'y a plus de place",
      translation: 'по́лный, запо́лненный, полный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VihB0',
    created: 1736961497690,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: 'delisjø',
      example: 'un repas délicieux',
      definition: 'qui est très bon, très agréable',
      translation: 'восхити́тельный, ди́вный, отме́нный, вкусный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aaG81',
    created: 1736961498494,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: 'pʀydɑ̃',
      example: '* une conduite prudente\n* un choix prudent',
      definition:
        "* qui a pour but d'éviter les dangers\n* provoqué, déterminé par la prudence",
      translation: 'осторо́жный, благоразу́мный, осторожный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NBBSX',
    created: 1736961499729,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: 'ʀetisɑ̃',
      example: 'Il était réticent concernant ce mariage.',
      definition: 'qui hésite à faire quelque chose',
      translation: 'нереши́тельный, неуве́ренный, неохотный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_PJkq',
    created: 1736961500584,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: 'siɲifikatif',
      example: 'un geste significatif',
      definition: 'qui indique ou exprime quelque chose',
      translation: 'значи́тельный, многозначи́тельный, значительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
