import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'BDnYP',
    created: 1736962168648,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: 'ɛ̃tegʀite',
      example: "* l'intégrité d'un juge\n* l'intégrité des biens",
      definition: "* grande honnêteté\n* fait d'être entier",
      translation: 'цілісність, чесність',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zzKEZ',
    created: 1736962169913,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: 'резилієнція',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7bX-g',
    created: 1736962171674,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: 'sœj',
      example:
        "* attendre sur le seuil\n* au seuil de l'année\n* le seuil de la douleur",
      definition: "* entrée d'une maison\n* commencement\n* limite",
      translation: 'поріг, початок, межа',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v-S5T',
    created: 1736962174274,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: 'dispozisjɔ̃',
      example:
        "* changer la disposition d'une chambre\n* avoir des dispositions pour les langues",
      definition:
        '* façon dont sont placées les choses\n* capacité, qualité nécessaire pour faire quelque chose',
      translation: 'розташування, здатність, диспозиція',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WtRRp',
    created: 1736962175882,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: 'ʀepɛʀkysjɔ̃',
      example:
        "* répercussion d'un bruit\n* avoir des répercussions sur quelque chose",
      definition: "* renvoi d'un son\n* conséquence",
      translation: 'відлуння, наслідок, реперкусія',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N4oxT',
    created: 1736962177661,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: 'ʀezylta',
      example:
        "* C'est le résultat qui compte !\n* les résultats d'un sondage\n* le résultat d'une addition",
      definition:
        "* ce qui se produit, ce que l'on obtient\n* information donnée par quelque chose\n* solution d'un calcul",
      translation: 'результат, висновок, відповідь',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RNHbk',
    created: 1736962179748,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: 'ʀəkɔnɛtʀ',
      example:
        "* reconnaître un morceau de musique\n* reconnaître ses torts\n* reconnaître l'autorité d'un souverain",
      definition:
        "* identifier quelqu’un ou quelque chose que l'on connaît\n* avouer\n* admettre comme légitime",
      translation: 'визнати, визначити, прийняти',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DCBZF',
    created: 1736962180478,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: 'kɔ̃sideʀe',
      example: '',
      definition: '',
      translation: 'розглядати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sDopH',
    created: 1736962182453,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: 'kɔ̃sakʀe',
      example: '* consacrer du temps à quelque chose\n* consacrer une église',
      definition: '* employer quelque chose dans un but\n* rendre sacré',
      translation: 'присвятити, освятити, присвячувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MKb1L',
    created: 1736962184357,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: 'ʒystifie',
      example: 'justifier des dépenses',
      definition: 'prouver, expliquer quelque chose',
      translation: 'обґрунтувати, пояснити',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AHPcr',
    created: 1736962186073,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: 'negliʒɑ̃s',
      example:
        '* oublier quelque chose par négligence\n* La panne est due à une négligence.',
      definition:
        '* manque de soin, de vigilance\n* faute commise par manque de soin',
      translation: 'недбалість, недогляд',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jd5Sy',
    created: 1736962187384,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: 'pɛʀsɥade',
      example: 'persuader quelqu’un de quelque chose',
      definition: 'convaincre',
      translation: 'переконати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zbWzK',
    created: 1736962191402,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: 'pʀɔgʀesivmɑ̃',
      example: 'diminuer progressivement',
      definition: 'petit à petit',
      translation: 'поступово',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ss5cX',
    created: 1736962192780,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: 'ɛ̃plisitmɑ̃',
      example: 'Il a implicitement reconnu son erreur.',
      definition: 'de façon implicite, sans le dire',
      translation: 'неявно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tP_h5',
    created: 1736962194345,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: 'nɔtamɑ̃',
      example: '',
      definition: 'en particulier',
      translation: 'зокрема',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vtB2y',
    created: 1736962196230,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: 'ʀapidmɑ̃',
      example: 'faire quelque chose rapidement',
      definition: 'très vite',
      translation: 'швидко',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QQJOA',
    created: 1736962196932,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приблизно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pMDdC',
    created: 1736962198234,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: 'syfizamɑ̃',
      example: 'avoir suffisamment de place',
      definition: 'assez',
      translation: 'досить, достатньо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kQG9r',
    created: 1736962199888,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: 'pɛʀsistɑ̃',
      example: 'une inquiétude persistante',
      definition: 'qui dure toujours',
      translation: 'постійний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5BVv0',
    created: 1736962201713,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: 'kɔ̃plɛ',
      example: '* une liste complète\n* hôtel complet',
      definition: "* entier, total\n* où il n'y a plus de place",
      translation: 'повний, заповнений',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i9q4M',
    created: 1736962204300,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: 'delisjø',
      example: 'un repas délicieux',
      definition: 'qui est très bon, très agréable',
      translation: 'смачний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vAoje',
    created: 1736962207317,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: 'pʀydɑ̃',
      example: '* une conduite prudente\n* un choix prudent',
      definition:
        "* qui a pour but d'éviter les dangers\n* provoqué, déterminé par la prudence",
      translation: 'обережний, поміркований',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-pxwp',
    created: 1736962209209,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: 'ʀetisɑ̃',
      example: 'Il était réticent concernant ce mariage.',
      definition: 'qui hésite à faire quelque chose',
      translation: 'неохочий, недовірливий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tFnUN',
    created: 1736962210961,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: 'siɲifikatif',
      example: 'un geste significatif',
      definition: 'qui indique ou exprime quelque chose',
      translation: 'значущий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
