import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'mpIyk',
    created: 1736961377998,
    data: {
      language: 'fr',
      source: 'intégrité',
      ipa: 'ɛ̃tegʀite',
      example: "* l'intégrité d'un juge\n* l'intégrité des biens",
      definition: "* grande honnêteté\n* fait d'être entier",
      translation: '廉洁,正直, 完整,完整性',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eSWHo',
    created: 1736961378914,
    data: {
      language: 'fr',
      source: 'résilience',
      ipa: '',
      example: '',
      definition: '',
      translation: '韧性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cj7al',
    created: 1736961379841,
    data: {
      language: 'fr',
      source: 'seuil',
      ipa: 'sœj',
      example:
        "* attendre sur le seuil\n* au seuil de l'année\n* le seuil de la douleur",
      definition: "* entrée d'une maison\n* commencement\n* limite",
      translation: '门槛, (动作等的)开端, 边界, 界限',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KUFS2',
    created: 1736961381817,
    data: {
      language: 'fr',
      source: 'disposition',
      ipa: 'dispozisjɔ̃',
      example:
        "* changer la disposition d'une chambre\n* avoir des dispositions pour les langues",
      definition:
        '* façon dont sont placées les choses\n* capacité, qualité nécessaire pour faire quelque chose',
      translation: '安排,布置,布局, 能力,才干, 处置',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-abrd',
    created: 1736961382980,
    data: {
      language: 'fr',
      source: 'répercussion',
      ipa: 'ʀepɛʀkysjɔ̃',
      example:
        "* répercussion d'un bruit\n* avoir des répercussions sur quelque chose",
      definition: "* renvoi d'un son\n* conséquence",
      translation: '回响,反射, 后果,反响 ;影响',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vTfLI',
    created: 1736961384219,
    data: {
      language: 'fr',
      source: 'résultat',
      ipa: 'ʀezylta',
      example:
        "* C'est le résultat qui compte !\n* les résultats d'un sondage\n* le résultat d'une addition",
      definition:
        "* ce qui se produit, ce que l'on obtient\n* information donnée par quelque chose\n* solution d'un calcul",
      translation: '成果 ;效果, 结果,答案, 盈亏差额, 成绩 ;比赛结果',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uMKSN',
    created: 1736961384964,
    data: {
      language: 'fr',
      source: 'reconnaître',
      ipa: 'ʀəkɔnɛtʀ',
      example:
        "* reconnaître un morceau de musique\n* reconnaître ses torts\n* reconnaître l'autorité d'un souverain",
      definition:
        "* identifier quelqu’un ou quelque chose que l'on connaît\n* avouer\n* admettre comme légitime",
      translation: '认出,辨认出, 承认,确认, 勘查清楚 ;勘测',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd1IjS',
    created: 1736961385773,
    data: {
      language: 'fr',
      source: 'considérer',
      ipa: 'kɔ̃sideʀe',
      example: '',
      definition: '',
      translation: '考虑',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MkM8z',
    created: 1736961387113,
    data: {
      language: 'fr',
      source: 'consacrer',
      ipa: 'kɔ̃sakʀe',
      example: '* consacrer du temps à quelque chose\n* consacrer une église',
      definition: '* employer quelque chose dans un but\n* rendre sacré',
      translation: '让, 让出, (宗)祝圣;奉献',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RKRXl',
    created: 1736961387771,
    data: {
      language: 'fr',
      source: 'justifier',
      ipa: 'ʒystifie',
      example: 'justifier des dépenses',
      definition: 'prouver, expliquer quelque chose',
      translation: '说明理由,解释, 证明',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Mj9sQ',
    created: 1736961389389,
    data: {
      language: 'fr',
      source: 'négligence',
      ipa: 'negliʒɑ̃s',
      example:
        '* oublier quelque chose par négligence\n* La panne est due à une négligence.',
      definition:
        '* manque de soin, de vigilance\n* faute commise par manque de soin',
      translation: '疏忽, 失职',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_i-a_',
    created: 1736961390351,
    data: {
      language: 'fr',
      source: 'persuader',
      ipa: 'pɛʀsɥade',
      example: 'persuader quelqu’un de quelque chose',
      definition: 'convaincre',
      translation: '说服,使信服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qjoMB',
    created: 1736961391304,
    data: {
      language: 'fr',
      source: 'progressivement',
      ipa: 'pʀɔgʀesivmɑ̃',
      example: 'diminuer progressivement',
      definition: 'petit à petit',
      translation: '渐渐地,逐渐地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'R0NU6',
    created: 1736961393489,
    data: {
      language: 'fr',
      source: 'implicitement',
      ipa: 'ɛ̃plisitmɑ̃',
      example: 'Il a implicitement reconnu son erreur.',
      definition: 'de façon implicite, sans le dire',
      translation: '隐含地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6B5TM',
    created: 1736961394467,
    data: {
      language: 'fr',
      source: 'notamment',
      ipa: 'nɔtamɑ̃',
      example: '',
      definition: 'en particulier',
      translation: '特别是,尤其',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UnAkC',
    created: 1736961395390,
    data: {
      language: 'fr',
      source: 'rapidement',
      ipa: 'ʀapidmɑ̃',
      example: 'faire quelque chose rapidement',
      definition: 'très vite',
      translation: '转眼间, 迅速地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Xo74m',
    created: 1736961396047,
    data: {
      language: 'fr',
      source: 'à peu près',
      ipa: '',
      example: '',
      definition: '',
      translation: '大约',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EF7q0',
    created: 1736961396950,
    data: {
      language: 'fr',
      source: 'suffisamment',
      ipa: 'syfizamɑ̃',
      example: 'avoir suffisamment de place',
      definition: 'assez',
      translation: '够了 !, 足够地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'w22G4',
    created: 1736961398382,
    data: {
      language: 'fr',
      source: 'persistant',
      ipa: 'pɛʀsistɑ̃',
      example: 'une inquiétude persistante',
      definition: 'qui dure toujours',
      translation: '持久的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9ry_e',
    created: 1736961399274,
    data: {
      language: 'fr',
      source: 'complet',
      ipa: 'kɔ̃plɛ',
      example: '* une liste complète\n* hôtel complet',
      definition: "* entier, total\n* où il n'y a plus de place",
      translation: '完全的,完整的,十足的, 满满的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ec8I5',
    created: 1736961400220,
    data: {
      language: 'fr',
      source: 'délicieux',
      ipa: 'delisjø',
      example: 'un repas délicieux',
      definition: 'qui est très bon, très agréable',
      translation: '可口的,美味的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NsAlm',
    created: 1736961401020,
    data: {
      language: 'fr',
      source: 'prudent',
      ipa: 'pʀydɑ̃',
      example: '* une conduite prudente\n* un choix prudent',
      definition:
        "* qui a pour but d'éviter les dangers\n* provoqué, déterminé par la prudence",
      translation: '谨慎的,慎重的, 审慎的,慎重的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GTR1G',
    created: 1736961401850,
    data: {
      language: 'fr',
      source: 'réticent',
      ipa: 'ʀetisɑ̃',
      example: 'Il était réticent concernant ce mariage.',
      definition: 'qui hésite à faire quelque chose',
      translation: '有所保留的,迟疑不决的, 犹豫的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '75OWE',
    created: 1736961402702,
    data: {
      language: 'fr',
      source: 'significatif',
      ipa: 'siɲifikatif',
      example: 'un geste significatif',
      definition: 'qui indique ou exprime quelque chose',
      translation: '有意义的,有含义的, 显著的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
