import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8YThm',
    created: 1737103202726,
    data: {
      language: 'he',
      source: 'שְׁלֵמוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'completeness',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Rb664',
    created: 1737103203860,
    data: {
      language: 'he',
      source: 'כּוֹשֵׁר הִתאוֹשְׁשׁוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resilience',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ImcaB',
    created: 1737103205133,
    data: {
      language: 'he',
      source: 'סף',
      ipa: 'saf',
      example: '',
      definition:
        '* החלק התחתון של פתח הכניסה\n* תחילת דבר מה\n* נקודת התגובה לגירוי',
      translation: 'threshold, verge',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4vjdz',
    created: 1737103206294,
    data: {
      language: 'he',
      source: 'מזג',
      ipa: 'ˈmezeg',
      example: '',
      definition: '',
      translation: 'temper',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nG7A6',
    created: 1737103207237,
    data: {
      language: 'he',
      source: 'הַשְּׁלָכָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implication',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'MfUBQ',
    created: 1737103208191,
    data: {
      language: 'he',
      source: 'תוֹצָאָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'output',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-XDBa',
    created: 1737103209017,
    data: {
      language: 'he',
      source: 'לְהוֹדוֹת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to give thanks',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9408B',
    created: 1737103209825,
    data: {
      language: 'he',
      source: 'לִשְׁקוֹל',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to weigh',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'E7-nf',
    created: 1737103211183,
    data: {
      language: 'he',
      source: 'לְהַקְדִישׁ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to dedicate',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'lf6-N',
    created: 1737103212336,
    data: {
      language: 'he',
      source: 'לְהַצְדִיק',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to justify',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zJWdz',
    created: 1737103213330,
    data: {
      language: 'he',
      source: 'הזנחה',
      ipa: 'haznaˈxa',
      example: 'הזנחת ילדים',
      definition: 'אי-טיפול במישהו או במשהו',
      translation: 'neglect, neglecting',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'VIdN-',
    created: 1737103214496,
    data: {
      language: 'he',
      source: 'לְשַׁכְנֵעַ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'to persuade',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5Nf4E',
    created: 1737103215465,
    data: {
      language: 'he',
      source: 'בְּהַדְרָגָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'in stages',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BkJOZ',
    created: 1737103216409,
    data: {
      language: 'he',
      source: 'באופן מרומז',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicitly',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'bfyui',
    created: 1737103217683,
    data: {
      language: 'he',
      source: 'בְּמִיּוּחָד',
      ipa: '',
      example: '',
      definition: '',
      translation: 'especially',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qQKdV',
    created: 1737103218909,
    data: {
      language: 'he',
      source: 'באופן מיידי',
      ipa: '',
      example: '',
      definition: '',
      translation: 'immediately',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pg2N-',
    created: 1737103219900,
    data: {
      language: 'he',
      source: 'בערך',
      ipa: 'beˈʔeʁex',
      example: 'לפני 20 שנה בערך',
      definition: 'בהערכה משוערת',
      translation: 'about, approximately, around',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pWos6',
    created: 1737103221630,
    data: {
      language: 'he',
      source: 'בְּמִדָּה מַסְפִּיקָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sufficiently',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qot_x',
    created: 1737103222682,
    data: {
      language: 'he',
      source: 'מתמיד',
      ipa: 'matˈmid',
      example: '',
      definition: '',
      translation: 'steady, constant, studious',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uGTcs',
    created: 1737103223751,
    data: {
      language: 'he',
      source: 'מַקִיף',
      ipa: '',
      example: '',
      definition: '',
      translation: 'comprehensive',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rtHfG',
    created: 1737103224489,
    data: {
      language: 'he',
      source: 'מְהַנֶּה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'pleasing',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'RlKiV',
    created: 1737103225299,
    data: {
      language: 'he',
      source: 'זהיר',
      ipa: 'zaˈhiʁ',
      example: '* נהג זהיר\n* צעד זהיר',
      definition: '* מקפיד היטב כדי להימנע מטעות\n* שיש בו מחשבה ושיקול דעת',
      translation: 'careful, cautious',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Swok2',
    created: 1737103226138,
    data: {
      language: 'he',
      source: 'סרבן',
      ipa: 'saʁˈvan',
      example: '',
      definition: 'מתנגד לדבר מה',
      translation: 'objector',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ojkri',
    created: 1737103227145,
    data: {
      language: 'he',
      source: 'חשוב',
      ipa: 'xaˈʃuv',
      example:
        '* עניין חשוב\n* אנשים חשובים\n* ניקיון חשוב מאוד לאדם ולסביבתו.',
      definition: '* בעל ערך ממשי\n* בעל מעמד, כוח וחשיבות\n* נחוץ ביותר',
      translation:
        'important, significant, eminent, influential, crucial, vital, essential',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
