import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ZOpCV',
    created: 1737105048950,
    data: {
      language: 'he',
      source: 'שְׁלֵמוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'целостность',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7OwfY',
    created: 1737105059504,
    data: {
      language: 'he',
      source: 'כּוֹשֵׁר הִתאוֹשְׁשׁוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'способность к восстановлению',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'vcTdQ',
    created: 1737105078955,
    data: {
      language: 'he',
      source: 'סף',
      ipa: 'saf',
      example: '',
      definition:
        '* החלק התחתון של פתח הכניסה\n* תחילת דבר מה\n* נקודת התגובה לגירוי',
      translation: 'порог, начало, точка реакции',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'XE_AD',
    created: 1737105079980,
    data: {
      language: 'he',
      source: 'מזג',
      ipa: 'ˈmezeg',
      example: '',
      definition: '',
      translation: 'характер',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'p8wYM',
    created: 1737105089831,
    data: {
      language: 'he',
      source: 'הַשְׁלָכָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'бросание',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uZ5rJ',
    created: 1737105099561,
    data: {
      language: 'he',
      source: 'תוֹצָאָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'выход',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 's-hav',
    created: 1737105109333,
    data: {
      language: 'he',
      source: 'לְהוֹדוֹת',
      ipa: '',
      example: '',
      definition: '',
      translation: 'благодарить',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Q5h7A',
    created: 1737105119148,
    data: {
      language: 'he',
      source: 'לִשְׁקוֹל',
      ipa: '',
      example: '',
      definition: '',
      translation: 'взвешивать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nYc__',
    created: 1737105138311,
    data: {
      language: 'he',
      source: 'הקדיש',
      ipa: 'hikˈdiʃ',
      example: 'הקדיש את עצמו לעזרה לנזקקים',
      definition: 'הועיד למטרה מסוימת',
      translation: 'посвятил',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'mRpdE',
    created: 1737105148085,
    data: {
      language: 'he',
      source: 'לְהַצְדִיק',
      ipa: '',
      example: '',
      definition: '',
      translation: 'оправдывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'thKom',
    created: 1737105160526,
    data: {
      language: 'he',
      source: 'הזנחה',
      ipa: 'haznaˈxa',
      example: 'הזנחת ילדים',
      definition: 'אי-טיפול במישהו או במשהו',
      translation: 'пренебрежение',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nRQoj',
    created: 1737105170384,
    data: {
      language: 'he',
      source: 'לְשַׁכְנֵעַ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'убеждать',
      partOfSpeech: 'глагол',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '14ROs',
    created: 1737105180136,
    data: {
      language: 'he',
      source: 'בְּהַדרָגָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'в порядке',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ytcIh',
    created: 1737105189985,
    data: {
      language: 'he',
      source: 'באופן מרומז',
      ipa: '',
      example: '',
      definition: '',
      translation: 'в подразумевающем смысле',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HBAex',
    created: 1737105199779,
    data: {
      language: 'he',
      source: 'בְּמִיּוּחָד',
      ipa: '',
      example: '',
      definition: '',
      translation: 'особенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'q402G',
    created: 1737105210277,
    data: {
      language: 'he',
      source: 'באופן מיידי',
      ipa: '',
      example: '',
      definition: '',
      translation: 'немедленно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'TfmD1',
    created: 1737105220996,
    data: {
      language: 'he',
      source: 'בערך',
      ipa: 'beˈʔeʁex',
      example: 'לפני 20 שנה בערך',
      definition: 'בהערכה משוערת',
      translation: 'примерно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jXWHl',
    created: 1737105231049,
    data: {
      language: 'he',
      source: 'בְּמִדָּה מַסְפִּיקָה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'в достаточной мере',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '4LDxt',
    created: 1737105241359,
    data: {
      language: 'he',
      source: 'מתמיד',
      ipa: 'matˈmid',
      example: '',
      definition: '',
      translation: 'вечный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '1njrZ',
    created: 1737105251013,
    data: {
      language: 'he',
      source: 'מַקִיף',
      ipa: '',
      example: '',
      definition: '',
      translation: 'окружающий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rBPU9',
    created: 1737105260994,
    data: {
      language: 'he',
      source: 'מְהַנֶה',
      ipa: '',
      example: '',
      definition: '',
      translation: 'вдохновляющий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'mvV22',
    created: 1737105271792,
    data: {
      language: 'he',
      source: 'זהיר',
      ipa: 'zaˈhiʁ',
      example: '* נהג זהיר\n* צעד זהיר',
      definition: '* מקפיד היטב כדי להימנע מטעות\n* שיש בו מחשבה ושיקול דעת',
      translation: 'осторожный, внимательный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qjSv3',
    created: 1737105290985,
    data: {
      language: 'he',
      source: 'סרבן',
      ipa: 'saʁˈvan',
      example: '',
      definition: 'מתנגד לדבר מה',
      translation: 'упрямец',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'IRGYk',
    created: 1737105310195,
    data: {
      language: 'he',
      source: 'חשוב',
      ipa: 'xaˈʃuv',
      example:
        '* עניין חשוב\n* אנשים חשובים\n* ניקיון חשוב מאוד לאדם ולסביבתו.',
      definition: '* בעל ערך ממשי\n* בעל מעמד, כוח וחשיבות\n* נחוץ ביותר',
      translation: 'важный, значимый, необходимый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
