import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'AWgGW',
    created: 1737104439052,
    data: {
      language: 'he',
      source: 'שלמות',
      ipa: 'ʃleˈmut',
      example: '',
      definition: '* המכלול כולו ללא חיסרון או פגם\n* דבר מושלם',
      translation: '正直',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'bJCi6',
    created: 1737104449292,
    data: {
      language: 'he',
      source: 'כּוֹשֵׁר הִתאוֹשְׁשׁוּת',
      ipa: '',
      example: '',
      definition: '',
      translation: '恢復能力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7zNNT',
    created: 1737104469563,
    data: {
      language: 'he',
      source: 'סף',
      ipa: 'saf',
      example: '',
      definition:
        '* החלק התחתון של פתח הכניסה\n* תחילת דבר מה\n* נקודת התגובה לגירוי',
      translation: '門檻, 開始, 反應點',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gR7ci',
    created: 1737104488500,
    data: {
      language: 'he',
      source: 'מזג',
      ipa: 'ˈmezeg',
      example: '',
      definition: '',
      translation: '脾氣',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uSv5-',
    created: 1737104498309,
    data: {
      language: 'he',
      source: 'הַשְׁלָכָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '投射',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'e8JFl',
    created: 1737104507970,
    data: {
      language: 'he',
      source: 'תוֹצָאָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '產出',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hSrl4',
    created: 1737104509060,
    data: {
      language: 'he',
      source: 'לְהוֹדוֹת',
      ipa: '',
      example: '',
      definition: '',
      translation: '感謝',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HCICd',
    created: 1737104518696,
    data: {
      language: 'he',
      source: 'לִשְׁקוֹל',
      ipa: '',
      example: '',
      definition: '',
      translation: '稱量',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'HFmCz',
    created: 1737104546948,
    data: {
      language: 'he',
      source: 'הקדיש',
      ipa: 'hikˈdiʃ',
      example: 'הקדיש את עצמו לעזרה לנזקקים',
      definition: 'הועיד למטרה מסוימת',
      translation: '奉獻',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'le58f',
    created: 1737104565530,
    data: {
      language: 'he',
      source: 'לְהַצְדִיק',
      ipa: '',
      example: '',
      definition: '',
      translation: '使正當化',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'De0YF',
    created: 1737104575612,
    data: {
      language: 'he',
      source: 'הַזנָחָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '忽視',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'KNfJR',
    created: 1737104585512,
    data: {
      language: 'he',
      source: 'לְשַׁכְנֵעַ',
      ipa: '',
      example: '',
      definition: '',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '32FL2',
    created: 1737104595303,
    data: {
      language: 'he',
      source: 'בְּהַדרָגָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '分級',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'GGBv7',
    created: 1737104596101,
    data: {
      language: 'he',
      source: 'באופן מרומז',
      ipa: '',
      example: '',
      definition: '',
      translation: '暗示地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AG3_B',
    created: 1737104606099,
    data: {
      language: 'he',
      source: 'בְּמִיּוּחָד',
      ipa: '',
      example: '',
      definition: '',
      translation: '特別',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BB9Gh',
    created: 1737104615685,
    data: {
      language: 'he',
      source: 'באופן מיידי',
      ipa: '',
      example: '',
      definition: '',
      translation: '立即',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7A37l',
    created: 1737104635119,
    data: {
      language: 'he',
      source: 'בערך',
      ipa: 'beˈʔeʁex',
      example: 'לפני 20 שנה בערך',
      definition: 'בהערכה משוערת',
      translation: '大約',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '51MO7',
    created: 1737104645290,
    data: {
      language: 'he',
      source: 'בְּמִדָּה מַסְפִּיקָה',
      ipa: '',
      example: '',
      definition: '',
      translation: '足夠地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rZnpt',
    created: 1737104655157,
    data: {
      language: 'he',
      source: 'מתמיד',
      ipa: 'matˈmid',
      example: '',
      definition: '',
      translation: '永久',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'KI0I5',
    created: 1737104655983,
    data: {
      language: 'he',
      source: 'מַקִיף',
      ipa: '',
      example: '',
      definition: '',
      translation: '環繞的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A4ibV',
    created: 1737104665949,
    data: {
      language: 'he',
      source: 'מְהַנֶה',
      ipa: '',
      example: '',
      definition: '',
      translation: '使人愉快的事物',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'JQ1SI',
    created: 1737104685947,
    data: {
      language: 'he',
      source: 'זהיר',
      ipa: 'zaˈhiʁ',
      example: '* נהג זהיר\n* צעד זהיר',
      definition: '* מקפיד היטב כדי להימנע מטעות\n* שיש בו מחשבה ושיקול דעת',
      translation: '小心, 謹慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PUG8q',
    created: 1737104705460,
    data: {
      language: 'he',
      source: 'סרבן',
      ipa: 'saʁˈvan',
      example: '',
      definition: 'מתנגד לדבר מה',
      translation: '反抗者',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CebSl',
    created: 1737104725191,
    data: {
      language: 'he',
      source: 'חשוב',
      ipa: 'xaˈʃuv',
      example:
        '* עניין חשוב\n* אנשים חשובים\n* ניקיון חשוב מאוד לאדם ולסביבתו.',
      definition: '* בעל ערך ממשי\n* בעל מעמד, כוח וחשיבות\n* נחוץ ביותר',
      translation: '重要, 有價值, 必要',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
