import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'HPWN7',
    created: 1736967671010,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: 'integriˈta',
      example: "* integrità fisica\n* esempio d'integrità",
      definition:
        '* stato di ciò che è fisicamente intero, intatto, incolume\n* condizione di chi è moralmente integro',
      translation: '',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FPRb9',
    created: 1736967671147,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resilienza',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fyqv4',
    created: 1736967671281,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: 'ˈsɔʎa',
      example:
        "* varcare la soglia\n* L'autunno è alle soglie.\n* soglia di udibilità",
      definition:
        '* parte inferiore del vano della porta e la porta stessa\n* momento iniziale di un fenomeno o evento\n* il valore minimo perché una grandezza risulti apprezzabile',
      translation: '',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '91l1z',
    created: 1736967671652,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: 'dispoziˈtsjone',
      example:
        '* per disposizione di legge\n* disposizione delle truppe\n* essere nella disposizione adatta',
      definition:
        "* decisione presa da chi ha l'autorità per farlo\n* sistemazione secondo un criterio\n* stato d'animo",
      translation: '',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0gdzv',
    created: 1736967671792,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: 'riperkusˈsjone',
      example: 'Il terrorismo ha avuto ripercussioni sul turismo.',
      definition: 'effetto negativo',
      translation: '',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gPGew',
    created: 1736967671975,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: 'risulˈtato',
      example:
        '* il risultato di un esame\n* Questo è il risultato di tanti anni di odio.\n* risultato finale',
      definition:
        '* esito conclusivo\n* ciò che consegue\n* punteggio di una partita',
      translation: '',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6FHPQ',
    created: 1736967672128,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: 'rikoˈnoʃere',
      example:
        "* L'ho riconosciuto dalla voce.\n* riconoscere il vero dal falso\n* Ha riconosciuto d'aver sbagliato.",
      definition:
        '* identificare cosa o persona nota\n* percepire la differenza\n* dare atto',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XrKHX',
    created: 1736967672297,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: 'konsideˈrare',
      example:
        '* considerare i pro e i contro\n* Considera che una volta eravamo poveri.\n* Tutti lo considerano un comico.',
      definition:
        '* esaminare attentamente\n* tenere presente, tenere in conto\n* ritenere che qualcosa o qualcuno sia in un certo modo',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Scp00',
    created: 1736967672465,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: 'dediˈkare',
      example:
        '* chiesa dedicata alla Madonna\n* dedicare un libro alla propria figlia\n* piazza dedicata ai caduti',
      definition:
        "* consacrare a una divinità\n* offrire un'opera artistica in segno di omaggio a qualcuno\n* chiamare con il nome di qualcuno in sua memoria",
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6bMuu',
    created: 1736967672608,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: 'dʒustifiˈkare',
      example:
        '* il fine giustifica i mezzi\n* giustificare una spesa\n* Nulla può giustificare la sua cattiveria.',
      definition:
        '* rendere legittimo\n* rendere conto o ragione di qualcosa, eventualmente con documentazione\n* rendere ammissibile',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6V62S',
    created: 1736967672763,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: 'traskuˈrare',
      example: '* trascurare la casa\n* trascurare un particolare importante',
      definition: '* non prendersi cura\n* non tenere conto',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CgQUY',
    created: 1736967672938,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: 'perswaˈdere',
      example: "L'ho persuaso a non partire.",
      definition: 'indurre qualcuno a fare o a credere qualcosa',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Rj2N0',
    created: 1736967673064,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradualmente',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'X-RlG',
    created: 1736967673222,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicitamente',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aS1y6',
    created: 1736967673382,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'in particolare',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bQg-8',
    created: 1736967673522,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: 'prontaˈmente',
      example: 'Ha risposto prontamente a tutte le domande.',
      definition: 'in maniera rapida e risoluta',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SyUUp',
    created: 1736967673692,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: 'allinˈtʃirka',
      example: "Mancano all'incirca due settimane al suo arrivo.",
      definition: 'più o meno, a occhio e croce',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BDUxJ',
    created: 1736967673835,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sufficientemente',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XCR4k',
    created: 1736967673993,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: 'persisˈtɛnte',
      example: 'un dolore persistente',
      definition: 'che continua',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4M-4e',
    created: 1736967674199,
    data: {
      language: 'it',
      source: 'completo',
      ipa: 'komˈplɛto',
      example:
        '* teatro completo\n* lista completa\n* Ho completa fiducia in te.',
      definition:
        '* senza posti liberi, occupato interamente\n* che non è privo di alcuna delle sue parti\n* a livello massimo',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2kIqh',
    created: 1736967674348,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: 'deliˈtsjoso',
      example:
        '* Ha preparato una cena deliziosa.\n* ragazza deliziosa\n* Abbiamo trascorso una deliziosa serata.',
      definition:
        '* dal sapore delicato e gradevole\n* dai modi gentili, graziosi\n* che suscita piacere',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hCFtG',
    created: 1736967674512,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: 'ˈkauto',
      example: 'essere cauto nelle spese',
      definition: 'che agisce con prudenza',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SfUc6',
    created: 1736967674686,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: "rilut'tante",
      example: "Si è mostrato riluttante ad accettare l'incarico.",
      definition: 'poco propenso',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JyUxa',
    created: 1736967674848,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: 'siɲifikaˈtivo',
      example: '* gesto significativo\n* un dato significativo',
      definition:
        '* che esprime molto bene qualcosa\n* che ha particolare importanza',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
