import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'lqq4J',
    created: 1736973829077,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: 'integriˈta',
      example: "* integrità fisica\n* esempio d'integrità",
      definition:
        '* stato di ciò che è fisicamente intero, intatto, incolume\n* condizione di chi è moralmente integro',
      translation: 'integritas, keutuhan',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cG2cb',
    created: 1736973839020,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliensi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W-SeA',
    created: 1736973849866,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: 'ˈsɔʎa',
      example:
        "* varcare la soglia\n* L'autunno è alle soglie.\n* soglia di udibilità",
      definition:
        '* parte inferiore del vano della porta e la porta stessa\n* momento iniziale di un fenomeno o evento\n* il valore minimo perché una grandezza risulti apprezzabile',
      translation: 'ambang, tahap awal, batas minimum',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ptFZM',
    created: 1736973869382,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: 'dispoziˈtsjone',
      example:
        '* per disposizione di legge\n* disposizione delle truppe\n* essere nella disposizione adatta',
      definition:
        "* decisione presa da chi ha l'autorità per farlo\n* sistemazione secondo un criterio\n* stato d'animo",
      translation: 'keputusan, penataan, suasana hati',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vzc-A',
    created: 1736973888534,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: 'riperkusˈsjone',
      example: 'Il terrorismo ha avuto ripercussioni sul turismo.',
      definition: 'effetto negativo',
      translation: 'dampak',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'daBaK',
    created: 1736973916729,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: 'risulˈtato',
      example:
        '* il risultato di un esame\n* Questo è il risultato di tanti anni di odio.\n* risultato finale',
      definition:
        '* esito conclusivo\n* ciò che consegue\n* punteggio di una partita',
      translation: 'hasil, skor',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aUT0D',
    created: 1736973927095,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: 'rikoˈnoʃere',
      example:
        "* L'ho riconosciuto dalla voce.\n* riconoscere il vero dal falso\n* Ha riconosciuto d'aver sbagliato.",
      definition:
        '* identificare cosa o persona nota\n* percepire la differenza\n* dare atto',
      translation: 'mengidentifikasi, membedakan, mengakui, mengenali',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZoQ64',
    created: 1736973946127,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: 'konsideˈrare',
      example:
        '* considerare i pro e i contro\n* Considera che una volta eravamo poveri.\n* Tutti lo considerano un comico.',
      definition:
        '* esaminare attentamente\n* tenere presente, tenere in conto\n* ritenere che qualcosa o qualcuno sia in un certo modo',
      translation: 'mempertimbangkan, menganggap',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tXD5X',
    created: 1736973966194,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: 'dediˈkare',
      example:
        '* chiesa dedicata alla Madonna\n* dedicare un libro alla propria figlia\n* piazza dedicata ai caduti',
      definition:
        "* consacrare a una divinità\n* offrire un'opera artistica in segno di omaggio a qualcuno\n* chiamare con il nome di qualcuno in sua memoria",
      translation: 'mengabdikan, mendedikasikan, mempersembahkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C1wH9',
    created: 1736973985443,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: 'dʒustifiˈkare',
      example:
        '* il fine giustifica i mezzi\n* giustificare una spesa\n* Nulla può giustificare la sua cattiveria.',
      definition:
        '* rendere legittimo\n* rendere conto o ragione di qualcosa, eventualmente con documentazione\n* rendere ammissibile',
      translation: 'membenarkan, menjelaskan, mengizinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4SvyL',
    created: 1736973995569,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: 'traskuˈrare',
      example: '* trascurare la casa\n* trascurare un particolare importante',
      definition: '* non prendersi cura\n* non tenere conto',
      translation: 'mengabaikan, mengacuhkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zrA_J',
    created: 1736974018106,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: 'perswaˈdere',
      example: "L'ho persuaso a non partire.",
      definition: 'indurre qualcuno a fare o a credere qualcosa',
      translation: 'membujuk',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xVFuX',
    created: 1736974029633,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: 'gradwalˈmente',
      example: '',
      definition: '',
      translation: 'secara bertahap',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tXNhT',
    created: 1736974030992,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: 'implitʃitaˈmente',
      example: '',
      definition: '',
      translation: 'secara implisit',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iwF1E',
    created: 1736974040696,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara khusus',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v1SYb',
    created: 1736974059888,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: 'prontaˈmente',
      example: 'Ha risposto prontamente a tutte le domande.',
      definition: 'in maniera rapida e risoluta',
      translation: 'segera',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SmAt4',
    created: 1736974079343,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: 'allinˈtʃirka',
      example: "Mancano all'incirca due settimane al suo arrivo.",
      definition: 'più o meno, a occhio e croce',
      translation: 'sekitar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tdh7z',
    created: 1736974089030,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: 'suffitʃɛnteˈmente',
      example: '',
      definition: '',
      translation: 'cukup',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U2Hg-',
    created: 1736974099306,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: 'persisˈtɛnte',
      example: 'un dolore persistente',
      definition: 'che continua',
      translation: 'persisten',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U_hOH',
    created: 1736974127980,
    data: {
      language: 'it',
      source: 'completo',
      ipa: 'komˈplɛto',
      example:
        '* teatro completo\n* lista completa\n* Ho completa fiducia in te.',
      definition:
        '* senza posti liberi, occupato interamente\n* che non è privo di alcuna delle sue parti\n* a livello massimo',
      translation: 'lengkap, penuh',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oRarZ',
    created: 1736974147066,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: 'deliˈtsjoso',
      example:
        '* Ha preparato una cena deliziosa.\n* ragazza deliziosa\n* Abbiamo trascorso una deliziosa serata.',
      definition:
        '* dal sapore delicato e gradevole\n* dai modi gentili, graziosi\n* che suscita piacere',
      translation: 'lezat, menyenangkan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sz0hU',
    created: 1736974166181,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: 'ˈkauto',
      example: 'essere cauto nelle spese',
      definition: 'che agisce con prudenza',
      translation: 'hati-hati',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Y04SV',
    created: 1736974176524,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: "rilut'tante",
      example: "Si è mostrato riluttante ad accettare l'incarico.",
      definition: 'poco propenso',
      translation: 'enggan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U6baV',
    created: 1736974195865,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: 'siɲifikaˈtivo',
      example: '* gesto significativo\n* un dato significativo',
      definition:
        '* che esprime molto bene qualcosa\n* che ha particolare importanza',
      translation: 'bermakna, signifikan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
