import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'mHQlJ',
    created: 1736975188181,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: 'integriˈta',
      example: "* integrità fisica\n* esempio d'integrità",
      definition:
        '* stato di ciò che è fisicamente intero, intatto, incolume\n* condizione di chi è moralmente integro',
      translation: 'ინტეგრიტეტი',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '25Ty9',
    created: 1736975197828,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'რეზილიანცია',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ybkCD',
    created: 1736975207449,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: 'ˈsɔʎa',
      example:
        "* varcare la soglia\n* L'autunno è alle soglie.\n* soglia di udibilità",
      definition:
        '* parte inferiore del vano della porta e la porta stessa\n* momento iniziale di un fenomeno o evento\n* il valore minimo perché una grandezza risulti apprezzabile',
      translation: 'საგზაო',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EYKqc',
    created: 1736975217440,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: 'dispoziˈtsjone',
      example:
        '* per disposizione di legge\n* disposizione delle truppe\n* essere nella disposizione adatta',
      definition:
        "* decisione presa da chi ha l'autorità per farlo\n* sistemazione secondo un criterio\n* stato d'animo",
      translation: 'დაწყება',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5G628',
    created: 1736975227346,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: 'riperkusˈsjone',
      example: 'Il terrorismo ha avuto ripercussioni sul turismo.',
      definition: 'effetto negativo',
      translation: 'გავლენა',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'alhpT',
    created: 1736975237314,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: 'risulˈtato',
      example:
        '* il risultato di un esame\n* Questo è il risultato di tanti anni di odio.\n* risultato finale',
      definition:
        '* esito conclusivo\n* ciò che consegue\n* punteggio di una partita',
      translation: 'შედეგი',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SiLSX',
    created: 1736975247156,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: 'rikoˈnoʃere',
      example:
        "* L'ho riconosciuto dalla voce.\n* riconoscere il vero dal falso\n* Ha riconosciuto d'aver sbagliato.",
      definition:
        '* identificare cosa o persona nota\n* percepire la differenza\n* dare atto',
      translation: 'ცნობიერება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oWXoo',
    created: 1736975248208,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: 'konsideˈrare',
      example:
        '* considerare i pro e i contro\n* Considera che una volta eravamo poveri.\n* Tutti lo considerano un comico.',
      definition:
        '* esaminare attentamente\n* tenere presente, tenere in conto\n* ritenere che qualcosa o qualcuno sia in un certo modo',
      translation: 'გააზრება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jEDif',
    created: 1736975258009,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: 'dediˈkare',
      example:
        '* chiesa dedicata alla Madonna\n* dedicare un libro alla propria figlia\n* piazza dedicata ai caduti',
      definition:
        "* consacrare a una divinità\n* offrire un'opera artistica in segno di omaggio a qualcuno\n* chiamare con il nome di qualcuno in sua memoria",
      translation: 'მოძღვნა',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KG7OL',
    created: 1736975267904,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: 'dʒustifiˈkare',
      example:
        '* il fine giustifica i mezzi\n* giustificare una spesa\n* Nulla può giustificare la sua cattiveria.',
      definition:
        '* rendere legittimo\n* rendere conto o ragione di qualcosa, eventualmente con documentazione\n* rendere ammissibile',
      translation: 'მართლება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IUIuY',
    created: 1736975277877,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: 'traskuˈrare',
      example: '* trascurare la casa\n* trascurare un particolare importante',
      definition: '* non prendersi cura\n* non tenere conto',
      translation: 'გაუფრთხილება',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'johpI',
    created: 1736975296142,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: 'perswaˈdere',
      example: "L'ho persuaso a non partire.",
      definition: 'indurre qualcuno a fare o a credere qualcosa',
      translation: 'დაარწმუნოს',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Lw7Jh',
    created: 1736975305976,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: 'gradwalˈmente',
      example: '',
      definition: '',
      translation: 'ნაგულისხმევად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-bKfW',
    created: 1736975324134,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: 'implitʃitaˈmente',
      example: '',
      definition: '',
      translation: 'ირიბად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N2mzh',
    created: 1736975343928,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خصوصულად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Kxaju',
    created: 1736975344688,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: 'prontaˈmente',
      example: 'Ha risposto prontamente a tutte le domande.',
      definition: 'in maniera rapida e risoluta',
      translation: 'მალევე',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'e0UqM',
    created: 1736975354844,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: 'allinˈtʃirka',
      example: "Mancano all'incirca due settimane al suo arrivo.",
      definition: 'più o meno, a occhio e croce',
      translation: 'შესახებ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hJ0Wd',
    created: 1736975364853,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: 'suffitʃɛnteˈmente',
      example: '',
      definition: '',
      translation: 'საკმარისად',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0MARn',
    created: 1736975374622,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: 'persisˈtɛnte',
      example: 'un dolore persistente',
      definition: 'che continua',
      translation: 'მუდმივი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Fdmzt',
    created: 1736975385001,
    data: {
      language: 'it',
      source: 'completo',
      ipa: 'komˈplɛto',
      example:
        '* teatro completo\n* lista completa\n* Ho completa fiducia in te.',
      definition:
        '* senza posti liberi, occupato interamente\n* che non è privo di alcuna delle sue parti\n* a livello massimo',
      translation: 'მთლიანად',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EHKlm',
    created: 1736975394744,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: 'deliˈtsjoso',
      example:
        '* Ha preparato una cena deliziosa.\n* ragazza deliziosa\n* Abbiamo trascorso una deliziosa serata.',
      definition:
        '* dal sapore delicato e gradevole\n* dai modi gentili, graziosi\n* che suscita piacere',
      translation: 'დელიზიოზო',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xkSMw',
    created: 1736975395728,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: 'ˈkauto',
      example: 'essere cauto nelle spese',
      definition: 'che agisce con prudenza',
      translation: 'დაბალი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'E1R_1',
    created: 1736975405513,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: "rilut'tante",
      example: "Si è mostrato riluttante ad accettare l'incarico.",
      definition: 'poco propenso',
      translation: 'მოუწვდელი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SDphX',
    created: 1736975415243,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: 'siɲifikaˈtivo',
      example: '* gesto significativo\n* un dato significativo',
      definition:
        '* che esprime molto bene qualcosa\n* che ha particolare importanza',
      translation: 'მნიშვნელოვანი',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
