import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'x_WI2',
    created: 1736967186633,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: 'integriˈta',
      example: "* integrità fisica\n* esempio d'integrità",
      definition:
        '* stato di ciò che è fisicamente intero, intatto, incolume\n* condizione di chi è moralmente integro',
      translation: 'целостность, нравственная чистота',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AqabF',
    created: 1736967196952,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'резилиентность',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ENdKL',
    created: 1736967225116,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: 'ˈsɔʎa',
      example:
        "* varcare la soglia\n* L'autunno è alle soglie.\n* soglia di udibilità",
      definition:
        '* parte inferiore del vano della porta e la porta stessa\n* momento iniziale di un fenomeno o evento\n* il valore minimo perché una grandezza risulti apprezzabile',
      translation: 'порог, начало, пороговое значение',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eY_XS',
    created: 1736967261692,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: 'dispoziˈtsjone',
      example:
        '* per disposizione di legge\n* disposizione delle truppe\n* essere nella disposizione adatta',
      definition:
        "* decisione presa da chi ha l'autorità per farlo\n* sistemazione secondo un criterio\n* stato d'animo",
      translation: 'распоряжение, расположение, настроение',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MAtsP',
    created: 1736967289681,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: 'riperkusˈsjone',
      example: 'Il terrorismo ha avuto ripercussioni sul turismo.',
      definition: 'effetto negativo',
      translation: 'последствие',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XVtOe',
    created: 1736967308846,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: 'risulˈtato',
      example:
        '* il risultato di un esame\n* Questo è il risultato di tanti anni di odio.\n* risultato finale',
      definition:
        '* esito conclusivo\n* ciò che consegue\n* punteggio di una partita',
      translation: 'результат, итог',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9NiUz',
    created: 1736967337169,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: 'rikoˈnoʃere',
      example:
        "* L'ho riconosciuto dalla voce.\n* riconoscere il vero dal falso\n* Ha riconosciuto d'aver sbagliato.",
      definition:
        '* identificare cosa o persona nota\n* percepire la differenza\n* dare atto',
      translation: 'узнавать, распознавать, признавать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'adQfR',
    created: 1736967357004,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: 'konsideˈrare',
      example:
        '* considerare i pro e i contro\n* Considera che una volta eravamo poveri.\n* Tutti lo considerano un comico.',
      definition:
        '* esaminare attentamente\n* tenere presente, tenere in conto\n* ritenere che qualcosa o qualcuno sia in un certo modo',
      translation: 'рассматривать, учитывать, считать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n28PA',
    created: 1736967376356,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: 'dediˈkare',
      example:
        '* chiesa dedicata alla Madonna\n* dedicare un libro alla propria figlia\n* piazza dedicata ai caduti',
      definition:
        "* consacrare a una divinità\n* offrire un'opera artistica in segno di omaggio a qualcuno\n* chiamare con il nome di qualcuno in sua memoria",
      translation: 'посвящать, уделять, называть в честь',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'B2_b9',
    created: 1736967396109,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: 'dʒustifiˈkare',
      example:
        '* il fine giustifica i mezzi\n* giustificare una spesa\n* Nulla può giustificare la sua cattiveria.',
      definition:
        '* rendere legittimo\n* rendere conto o ragione di qualcosa, eventualmente con documentazione\n* rendere ammissibile',
      translation: 'оправдывать, обосновывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ui9TL',
    created: 1736967424223,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: 'traskuˈrare',
      example: '* trascurare la casa\n* trascurare un particolare importante',
      definition: '* non prendersi cura\n* non tenere conto',
      translation: 'игнорировать, не обращать внимания, пренебрегать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OIVaT',
    created: 1736967451708,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: 'perswaˈdere',
      example: "L'ho persuaso a non partire.",
      definition: 'indurre qualcuno a fare o a credere qualcosa',
      translation: 'убеждать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f7hAT',
    created: 1736967461953,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: 'gradwalˈmente',
      example: '',
      definition: '',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'y4IHb',
    created: 1736967471899,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: 'implitʃitaˈmente',
      example: '',
      definition: '',
      translation: 'неявно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BrvXD',
    created: 1736967472681,
    data: {
      language: 'it',
      source: 'в частности',
      ipa: '',
      example: '',
      definition: '',
      translation: 'в частности',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cmRFA',
    created: 1736967482489,
    data: {
      language: 'it',
      source: 'пронтаменте',
      ipa: '',
      example: '',
      definition: '',
      translation: 'незамедлительно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cZu2O',
    created: 1736967510274,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: 'allinˈtʃirka',
      example: "Mancano all'incirca due settimane al suo arrivo.",
      definition: 'più o meno, a occhio e croce',
      translation: 'примерно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IVbI6',
    created: 1736967529145,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: 'suffitʃɛnteˈmente',
      example: '',
      definition: '',
      translation: 'достаточно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sxReW',
    created: 1736967556971,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: 'persisˈtɛnte',
      example: 'un dolore persistente',
      definition: 'che continua',
      translation: 'постоянный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MRpeV',
    created: 1736967585534,
    data: {
      language: 'it',
      source: 'completo',
      ipa: 'komˈplɛto',
      example:
        '* teatro completo\n* lista completa\n* Ho completa fiducia in te.',
      definition:
        '* senza posti liberi, occupato interamente\n* che non è privo di alcuna delle sue parti\n* a livello massimo',
      translation: 'полный, завершённый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EKp6g',
    created: 1736967604842,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: 'deliˈtsjoso',
      example:
        '* Ha preparato una cena deliziosa.\n* ragazza deliziosa\n* Abbiamo trascorso una deliziosa serata.',
      definition:
        '* dal sapore delicato e gradevole\n* dai modi gentili, graziosi\n* che suscita piacere',
      translation: 'вкусный, прекрасный, приятный, восхитительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lkoPz',
    created: 1736967632796,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: 'ˈkauto',
      example: 'essere cauto nelle spese',
      definition: 'che agisce con prudenza',
      translation: 'осторожный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_KEqg',
    created: 1736967651508,
    data: {
      language: 'it',
      source: 'рилуттанте',
      ipa: '',
      example: '',
      definition: '',
      translation: 'неохотный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Kx4CE',
    created: 1736967670821,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: 'siɲifikaˈtivo',
      example: '* gesto significativo\n* un dato significativo',
      definition:
        '* che esprime molto bene qualcosa\n* che ha particolare importanza',
      translation: 'значительный, существенный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
