import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'X_m1S',
    created: 1736969665729,
    data: {
      language: 'it',
      source: "l'integrità",
      ipa: 'integriˈta',
      example: "* integrità fisica\n* esempio d'integrità",
      definition:
        '* stato di ciò che è fisicamente intero, intatto, incolume\n* condizione di chi è moralmente integro',
      translation: 'bütünlük, dürüstlük',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DzVve',
    created: 1736969666766,
    data: {
      language: 'it',
      source: 'resilienza',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dayanıklılık',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CDUpE',
    created: 1736969686527,
    data: {
      language: 'it',
      source: 'la soglia',
      ipa: 'ˈsɔʎa',
      example:
        "* varcare la soglia\n* L'autunno è alle soglie.\n* soglia di udibilità",
      definition:
        '* parte inferiore del vano della porta e la porta stessa\n* momento iniziale di un fenomeno o evento\n* il valore minimo perché una grandezza risulti apprezzabile',
      translation: 'eşik, başlangıç noktası, eşik değeri',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_Xq-d',
    created: 1736969705902,
    data: {
      language: 'it',
      source: 'la disposizione',
      ipa: 'dispoziˈtsjone',
      example:
        '* per disposizione di legge\n* disposizione delle truppe\n* essere nella disposizione adatta',
      definition:
        "* decisione presa da chi ha l'autorità per farlo\n* sistemazione secondo un criterio\n* stato d'animo",
      translation: 'karar, düzenleme, ruh hali',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'REQmI',
    created: 1736969725123,
    data: {
      language: 'it',
      source: 'la ripercussione',
      ipa: 'riperkusˈsjone',
      example: 'Il terrorismo ha avuto ripercussioni sul turismo.',
      definition: 'effetto negativo',
      translation: 'yansıma',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v_GCU',
    created: 1736969744616,
    data: {
      language: 'it',
      source: 'il risultato',
      ipa: 'risulˈtato',
      example:
        '* il risultato di un esame\n* Questo è il risultato di tanti anni di odio.\n* risultato finale',
      definition:
        '* esito conclusivo\n* ciò che consegue\n* punteggio di una partita',
      translation: 'sonuç, netice, skor',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mWJBc',
    created: 1736969764355,
    data: {
      language: 'it',
      source: 'riconoscere',
      ipa: 'rikoˈnoʃere',
      example:
        "* L'ho riconosciuto dalla voce.\n* riconoscere il vero dal falso\n* Ha riconosciuto d'aver sbagliato.",
      definition:
        '* identificare cosa o persona nota\n* percepire la differenza\n* dare atto',
      translation: 'tanımak, fark etmek, kabul etmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5MzCa',
    created: 1736969784047,
    data: {
      language: 'it',
      source: 'considerare',
      ipa: 'konsideˈrare',
      example:
        '* considerare i pro e i contro\n* Considera che una volta eravamo poveri.\n* Tutti lo considerano un comico.',
      definition:
        '* esaminare attentamente\n* tenere presente, tenere in conto\n* ritenere che qualcosa o qualcuno sia in un certo modo',
      translation: 'değerlendirmek, göz önünde bulundurmak, saymak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd09kq',
    created: 1736969803468,
    data: {
      language: 'it',
      source: 'dedicare',
      ipa: 'dediˈkare',
      example:
        '* chiesa dedicata alla Madonna\n* dedicare un libro alla propria figlia\n* piazza dedicata ai caduti',
      definition:
        "* consacrare a una divinità\n* offrire un'opera artistica in segno di omaggio a qualcuno\n* chiamare con il nome di qualcuno in sua memoria",
      translation: 'adamak, ithaf etmek, anmak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mncrZ',
    created: 1736969814609,
    data: {
      language: 'it',
      source: 'giustificare',
      ipa: 'dʒustifiˈkare',
      example:
        '* il fine giustifica i mezzi\n* giustificare una spesa\n* Nulla può giustificare la sua cattiveria.',
      definition:
        '* rendere legittimo\n* rendere conto o ragione di qualcosa, eventualmente con documentazione\n* rendere ammissibile',
      translation: 'haklı çıkarmak, gerekçelendirmek, meşrulaştırmak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fCokC',
    created: 1736969833785,
    data: {
      language: 'it',
      source: 'trascurare',
      ipa: 'traskuˈrare',
      example: '* trascurare la casa\n* trascurare un particolare importante',
      definition: '* non prendersi cura\n* non tenere conto',
      translation: 'ihmal etmek, önemsememek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1xOAt',
    created: 1736969853545,
    data: {
      language: 'it',
      source: 'persuadere',
      ipa: 'perswaˈdere',
      example: "L'ho persuaso a non partire.",
      definition: 'indurre qualcuno a fare o a credere qualcosa',
      translation: 'ikna etmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lHXMY',
    created: 1736969863534,
    data: {
      language: 'it',
      source: 'gradualmente',
      ipa: 'gradwalˈmente',
      example: '',
      definition: '',
      translation: 'aşamalı olarak',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NwNt9',
    created: 1736969877472,
    data: {
      language: 'it',
      source: 'implicitamente',
      ipa: 'implitʃitaˈmente',
      example: '',
      definition: '',
      translation: 'dolaylı olarak',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hYfFr',
    created: 1736969878251,
    data: {
      language: 'it',
      source: 'in particolare',
      ipa: '',
      example: '',
      definition: '',
      translation: 'özellikle',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P3XVw',
    created: 1736969897377,
    data: {
      language: 'it',
      source: 'prontamente',
      ipa: 'prontaˈmente',
      example: 'Ha risposto prontamente a tutte le domande.',
      definition: 'in maniera rapida e risoluta',
      translation: 'hızla, hemen',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-6Xf3',
    created: 1736969907990,
    data: {
      language: 'it',
      source: 'incirca',
      ipa: 'allinˈtʃirka',
      example: "Mancano all'incirca due settimane al suo arrivo.",
      definition: 'più o meno, a occhio e croce',
      translation: 'yaklaşık',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LBeQK',
    created: 1736969917553,
    data: {
      language: 'it',
      source: 'sufficientemente',
      ipa: 'suffitʃɛnteˈmente',
      example: '',
      definition: '',
      translation: 'yeterince',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MzAbo',
    created: 1736969936693,
    data: {
      language: 'it',
      source: 'persistente',
      ipa: 'persisˈtɛnte',
      example: 'un dolore persistente',
      definition: 'che continua',
      translation: 'sürekli, kalıcı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c01JC',
    created: 1736969964748,
    data: {
      language: 'it',
      source: 'completo',
      ipa: 'komˈplɛto',
      example:
        '* teatro completo\n* lista completa\n* Ho completa fiducia in te.',
      definition:
        '* senza posti liberi, occupato interamente\n* che non è privo di alcuna delle sue parti\n* a livello massimo',
      translation: 'tam, bütün, eksiksiz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tmlLb',
    created: 1736969983901,
    data: {
      language: 'it',
      source: 'delizioso',
      ipa: 'deliˈtsjoso',
      example:
        '* Ha preparato una cena deliziosa.\n* ragazza deliziosa\n* Abbiamo trascorso una deliziosa serata.',
      definition:
        '* dal sapore delicato e gradevole\n* dai modi gentili, graziosi\n* che suscita piacere',
      translation: 'leziz, hoş',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Oz-xw',
    created: 1736970003148,
    data: {
      language: 'it',
      source: 'cauto',
      ipa: 'ˈkauto',
      example: 'essere cauto nelle spese',
      definition: 'che agisce con prudenza',
      translation: 'temkinli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Q1zgT',
    created: 1736970013688,
    data: {
      language: 'it',
      source: 'riluttante',
      ipa: "rilut'tante",
      example: "Si è mostrato riluttante ad accettare l'incarico.",
      definition: 'poco propenso',
      translation: 'isteksiz',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'I__tR',
    created: 1736970032718,
    data: {
      language: 'it',
      source: 'significativo',
      ipa: 'siɲifikaˈtivo',
      example: '* gesto significativo\n* un dato significativo',
      definition:
        '* che esprime molto bene qualcosa\n* che ha particolare importanza',
      translation: 'anlamlı, önemli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
