import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'xPpam',
    created: 1736966031981,
    data: {
      language: 'ja',
      source: '誠実さ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'الصدق',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G6bn7',
    created: 1736966032803,
    data: {
      language: 'ja',
      source: '回復力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'قوة التعافي',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-RdRy',
    created: 1736966033693,
    data: {
      language: 'ja',
      source: 'しきい値',
      ipa: '',
      example: '',
      definition: '',
      translation: 'عتبة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9JDPD',
    created: 1736966034764,
    data: {
      language: 'ja',
      source: '配置',
      ipa: '',
      example: '',
      definition: '* [ はいち ]\n* [ haichi ]',
      translation: 'ترتيب',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Iz50a',
    created: 1736966035881,
    data: {
      language: 'ja',
      source: '反響',
      ipa: '',
      example: '',
      definition: '* [ はんきょう ]\n* [ hankyoo ]',
      translation: 'رد فعل',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8vOzm',
    created: 1736966037092,
    data: {
      language: 'ja',
      source: '結果',
      ipa: '',
      example: '',
      definition: '* [ けっか ]\n* [ kekka ]',
      translation: 'نتيجة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hApfP',
    created: 1736966038815,
    data: {
      language: 'ja',
      source: '認める',
      ipa: '',
      example: '',
      definition: '* [ みとめる ]\n* [ mitomeru ]',
      translation: 'يعترف',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3giSv',
    created: 1736966039795,
    data: {
      language: 'ja',
      source: '考慮する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'يأخذ بعين الاعتبار',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DlvRj',
    created: 1736966040709,
    data: {
      language: 'ja',
      source: '献身する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'التفاني',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd4eD7',
    created: 1736966041561,
    data: {
      language: 'ja',
      source: '正当化する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تبرير',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QGp3F',
    created: 1736966042894,
    data: {
      language: 'ja',
      source: '無視',
      ipa: '',
      example: '',
      definition: '* [ むし ]\n* [ mushi ]',
      translation: 'يتجاهل',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '45c3s',
    created: 1736966043689,
    data: {
      language: 'ja',
      source: '説得する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إقناع',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Juocb',
    created: 1736966044659,
    data: {
      language: 'ja',
      source: '徐々に',
      ipa: '',
      example: '',
      definition: '* [ じょじょに ]\n* [ jojoni ]',
      translation: 'تدريجياً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'I5sqF',
    created: 1736966045718,
    data: {
      language: 'ja',
      source: '暗黙的に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ضمنيًا',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LqI3M',
    created: 1736966048785,
    data: {
      language: 'ja',
      source: '特に',
      ipa: '',
      example: '',
      definition: '* [ とくに ]\n* [ tokuni ]',
      translation: 'خصوصاً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'g15L4',
    created: 1736966049606,
    data: {
      language: 'ja',
      source: '速やかに',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بسرعة',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2cbGf',
    created: 1736966050815,
    data: {
      language: 'ja',
      source: '大体',
      ipa: '',
      example: '',
      definition: '* [ だいたい ]\n* [ daitai ]',
      translation: 'تقريبا',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pu-PZ',
    created: 1736966051762,
    data: {
      language: 'ja',
      source: '十分に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بشكل كافٍ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'R0J80',
    created: 1736966052657,
    data: {
      language: 'ja',
      source: '持続的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مستدام',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0aSkT',
    created: 1736966053504,
    data: {
      language: 'ja',
      source: '包括的な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'شامل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kyvHa',
    created: 1736966054668,
    data: {
      language: 'ja',
      source: '楽しい',
      ipa: '',
      example: '',
      definition: '* [ たのしい ]\n* [ tanoshii ]',
      translation: 'هزار',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'k_WRk',
    created: 1736966055975,
    data: {
      language: 'ja',
      source: '用心深い',
      ipa: '',
      example: '',
      definition: '* [ ようじんぶかい ]\n* [ yoojinbukai ]',
      translation: 'حذر',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uhrnW',
    created: 1736966057077,
    data: {
      language: 'ja',
      source: '気が進まない',
      ipa: '',
      example: '',
      definition: '',
      translation: 'لا أشعر بالرغبة',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OtgnF',
    created: 1736966058352,
    data: {
      language: 'ja',
      source: '重要な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'مهم',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
