import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'd6da-',
    created: 1736966533808,
    data: {
      language: 'ja',
      source: '誠実さ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անվերապահություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WHfnN',
    created: 1736966534679,
    data: {
      language: 'ja',
      source: 'կայունություն',
      ipa: '',
      example: '',
      definition: '',
      translation: 'կայունություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '77KW0',
    created: 1736966536138,
    data: {
      language: 'ja',
      source: 'շիկիխ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'շիկիխ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wYFWr',
    created: 1736966537047,
    data: {
      language: 'ja',
      source: 'հայեցակարգ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հայեցակարգ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dVQ-o',
    created: 1736966537996,
    data: {
      language: 'ja',
      source: 'հանգիստ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հանգիստ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lFXbD',
    created: 1736966538843,
    data: {
      language: 'ja',
      source: 'արդյունք',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդյունք',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MYo_j',
    created: 1736966539790,
    data: {
      language: 'ja',
      source: '認める',
      ipa: '',
      example: '',
      definition: '* [ みとめる ]\n* [ mitomeru ]',
      translation: 'խոստովանել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2oTDx',
    created: 1736966540949,
    data: {
      language: 'ja',
      source: 'կողմնորոշել',
      ipa: '',
      example: '',
      definition: '',
      translation: 'կողմնորոշել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BoZN-',
    created: 1736966542455,
    data: {
      language: 'ja',
      source: '献身する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'նվիրվել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'R_7BB',
    created: 1736966543285,
    data: {
      language: 'ja',
      source: '正当化する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդարացնել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c1eyx',
    created: 1736966544010,
    data: {
      language: 'ja',
      source: 'մերժում',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մերժում',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kNqZm',
    created: 1736966545390,
    data: {
      language: 'ja',
      source: '説得する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համոզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'POqS_',
    created: 1736966546343,
    data: {
      language: 'ja',
      source: 'ժողովուրդ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հետզհետե',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Wqmy2',
    created: 1736966547283,
    data: {
      language: 'ja',
      source: '暗黙的に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անհայտորեն',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fEuwI',
    created: 1736966548385,
    data: {
      language: 'ja',
      source: '特に',
      ipa: '',
      example: '',
      definition: '* [ とくに ]\n* [ tokuni ]',
      translation: 'հատկապես',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ApN4U',
    created: 1736966549478,
    data: {
      language: 'ja',
      source: '速やかに',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արագ',
      partOfSpeech: '副詞',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0lXPF',
    created: 1736966550412,
    data: {
      language: 'ja',
      source: 'դայթայ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մոտավորապես',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RnZgu',
    created: 1736966551652,
    data: {
      language: 'ja',
      source: 'ջերմություն',
      ipa: '',
      example: '',
      definition: '',
      translation: 'բավարար',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7ZyoU',
    created: 1736966552625,
    data: {
      language: 'ja',
      source: '持続的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հ持续',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XJnaj',
    created: 1736966553619,
    data: {
      language: 'ja',
      source: 'համապարփակ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համապարփակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nS5rR',
    created: 1736966554457,
    data: {
      language: 'ja',
      source: '楽しい',
      ipa: '',
      example: '',
      definition: '* [ たのしい ]\n* [ tanoshii ]',
      translation: 'զվարճանք',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yQ1Ke',
    created: 1736966555474,
    data: {
      language: 'ja',
      source: '用心深い',
      ipa: '',
      example: '',
      definition: '* [ ようじんぶかい ]\n* [ yoojinbukai ]',
      translation: 'զգուշավոր',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xCqNj',
    created: 1736966556512,
    data: {
      language: 'ja',
      source: 'կարծես',
      ipa: '',
      example: '',
      definition: '',
      translation: 'չուզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9nt-r',
    created: 1736966557326,
    data: {
      language: 'ja',
      source: 'անհրաժեշտ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անհրաժեշտ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
