import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'VVKz5',
    created: 1736966187535,
    data: {
      language: 'ja',
      source: '誠実さ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ærlighet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Wg1X6',
    created: 1736966188450,
    data: {
      language: 'ja',
      source: '回復力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motstandskraft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mWIzP',
    created: 1736966189378,
    data: {
      language: 'ja',
      source: 'しきい値',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terskelverdi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HVJiY',
    created: 1736966190191,
    data: {
      language: 'ja',
      source: '配置',
      ipa: '',
      example: '',
      definition: '* [ はいち ]\n* [ haichi ]',
      translation: 'arrangement',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D6UqS',
    created: 1736966191164,
    data: {
      language: 'ja',
      source: '反響',
      ipa: '',
      example: '',
      definition: '* [ はんきょう ]\n* [ hankyoo ]',
      translation: 'Reaksjon',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kNkz2',
    created: 1736966192021,
    data: {
      language: 'ja',
      source: '結果',
      ipa: '',
      example: '',
      definition: '* [ けっか ]\n* [ kekka ]',
      translation: 'resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4gEtn',
    created: 1736966193272,
    data: {
      language: 'ja',
      source: '認める',
      ipa: '',
      example: '',
      definition: '* [ みとめる ]\n* [ mitomeru ]',
      translation: 'innrømme',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wxY9B',
    created: 1736966194429,
    data: {
      language: 'ja',
      source: '考慮する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'vurdere',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rtJ5N',
    created: 1736966195114,
    data: {
      language: 'ja',
      source: '献身する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'å vie seg',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rJl0S',
    created: 1736966196117,
    data: {
      language: 'ja',
      source: '正当化する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rettferdiggjøre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'y5ZFx',
    created: 1736966196947,
    data: {
      language: 'ja',
      source: '無視',
      ipa: '',
      example: '',
      definition: '* [ むし ]\n* [ mushi ]',
      translation: 'overse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'b6E4r',
    created: 1736966197965,
    data: {
      language: 'ja',
      source: '説得する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'overbevise',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gpvqV',
    created: 1736966199024,
    data: {
      language: 'ja',
      source: '徐々に',
      ipa: '',
      example: '',
      definition: '* [ じょじょに ]\n* [ jojoni ]',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2CcsK',
    created: 1736966199735,
    data: {
      language: 'ja',
      source: '暗黙的に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implisitt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oiBjC',
    created: 1736966200690,
    data: {
      language: 'ja',
      source: '特に',
      ipa: '',
      example: '',
      definition: '* [ とくに ]\n* [ tokuni ]',
      translation: 'særlig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CwqRm',
    created: 1736966201505,
    data: {
      language: 'ja',
      source: '速やかに',
      ipa: '',
      example: '',
      definition: '',
      translation: 'snart',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RXe9y',
    created: 1736966202512,
    data: {
      language: 'ja',
      source: '大体',
      ipa: '',
      example: '',
      definition: '* [ だいたい ]\n* [ daitai ]',
      translation: 'omtrent',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_e4_0',
    created: 1736966203263,
    data: {
      language: 'ja',
      source: '十分に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tilstrekkelig',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Gq9sm',
    created: 1736966204036,
    data: {
      language: 'ja',
      source: '持続的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bærekraftig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SxnAr',
    created: 1736966204925,
    data: {
      language: 'ja',
      source: '包括的な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omfattende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4nS4m',
    created: 1736966205860,
    data: {
      language: 'ja',
      source: '楽しい',
      ipa: '',
      example: '',
      definition: '* [ たのしい ]\n* [ tanoshii ]',
      translation: 'moro',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ezTBM',
    created: 1736966206813,
    data: {
      language: 'ja',
      source: '用心深い',
      ipa: '',
      example: '',
      definition: '* [ ようじんぶかい ]\n* [ yoojinbukai ]',
      translation: 'forsiktig',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Uc4V2',
    created: 1736966207781,
    data: {
      language: 'ja',
      source: '気が進まない',
      ipa: '',
      example: '',
      definition: '',
      translation: 'uvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ym3dl',
    created: 1736966208558,
    data: {
      language: 'ja',
      source: '重要な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'viktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
