import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'ElFQX',
    created: 1736966372704,
    data: {
      language: 'ja',
      source: '誠実さ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความซื่อสัตย์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9cwrW',
    created: 1736966373749,
    data: {
      language: 'ja',
      source: '回復力',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความสามารถในการฟื้นตัว',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lna9L',
    created: 1736966374644,
    data: {
      language: 'ja',
      source: 'しきい値',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ค่าขีดจำกัด',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wOOPT',
    created: 1736966375591,
    data: {
      language: 'ja',
      source: '配置',
      ipa: '',
      example: '',
      definition: '* [ はいち ]\n* [ haichi ]',
      translation: 'การจัดเตรียม',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tZwuM',
    created: 1736966376540,
    data: {
      language: 'ja',
      source: '反響',
      ipa: '',
      example: '',
      definition: '* [ はんきょう ]\n* [ hankyoo ]',
      translation: 'ปฏิกิริยา',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_2FCu',
    created: 1736966377584,
    data: {
      language: 'ja',
      source: '結果',
      ipa: '',
      example: '',
      definition: '* [ けっか ]\n* [ kekka ]',
      translation: 'ผลลัพธ์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rArC8',
    created: 1736966382911,
    data: {
      language: 'ja',
      source: '認める',
      ipa: '',
      example: '',
      definition: '* [ みとめる ]\n* [ mitomeru ]',
      translation: 'ยอมรับ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '78pak',
    created: 1736966383832,
    data: {
      language: 'ja',
      source: '考慮する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'พิจารณา',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jY8VW',
    created: 1736966384835,
    data: {
      language: 'ja',
      source: '献身する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อุทิศตน',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Yl9Fq',
    created: 1736966386108,
    data: {
      language: 'ja',
      source: '正当化する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ทำให้ถูกต้อง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M175-',
    created: 1736966387291,
    data: {
      language: 'ja',
      source: '無視',
      ipa: '',
      example: '',
      definition: '* [ むし ]\n* [ mushi ]',
      translation: 'ไม่สนใจ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BRyVl',
    created: 1736966388051,
    data: {
      language: 'ja',
      source: '説得する',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ชักชวน',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aTHnj',
    created: 1736966389080,
    data: {
      language: 'ja',
      source: '徐々に',
      ipa: '',
      example: '',
      definition: '* [ じょじょに ]\n* [ jojoni ]',
      translation: 'ค่อยๆ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'T15zs',
    created: 1736966390734,
    data: {
      language: 'ja',
      source: '暗黙的に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยปริยาย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SkCdP',
    created: 1736966391709,
    data: {
      language: 'ja',
      source: '特に',
      ipa: '',
      example: '',
      definition: '* [ とくに ]\n* [ tokuni ]',
      translation: 'โดยเฉพาะ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ie2wr',
    created: 1736966392870,
    data: {
      language: 'ja',
      source: '速やかに',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อย่างรวดเร็ว',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LK-Yv',
    created: 1736966393858,
    data: {
      language: 'ja',
      source: '大体',
      ipa: '',
      example: '',
      definition: '* [ だいたい ]\n* [ daitai ]',
      translation: 'ประมาณ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JxQd5',
    created: 1736966396050,
    data: {
      language: 'ja',
      source: '十分に',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อย่างเพียงพอ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RkBqC',
    created: 1736966396803,
    data: {
      language: 'ja',
      source: '持続的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อย่างยั่งยืน',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-Fqy9',
    created: 1736966397548,
    data: {
      language: 'ja',
      source: '包括的な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ครอบคลุม',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3_mad',
    created: 1736966398412,
    data: {
      language: 'ja',
      source: '楽しい',
      ipa: '',
      example: '',
      definition: '* [ たのしい ]\n* [ tanoshii ]',
      translation: 'สนุก',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Cxi4E',
    created: 1736966399476,
    data: {
      language: 'ja',
      source: '用心深い',
      ipa: '',
      example: '',
      definition: '* [ ようじんぶかい ]\n* [ yoojinbukai ]',
      translation: 'ระมัดระวัง',
      partOfSpeech: 'i-adj',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VcciF',
    created: 1736966400467,
    data: {
      language: 'ja',
      source: '気が進まない',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ไม่อยากทำ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8wuaT',
    created: 1736966401243,
    data: {
      language: 'ja',
      source: '重要な',
      ipa: '',
      example: '',
      definition: '',
      translation: 'สำคัญ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
