import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'sdrm0',
    created: 1737044504194,
    data: {
      language: 'ko',
      source: '실성',
      ipa: 'ʃilsʌŋ',
      example: '실성을 했나?',
      definition: '정신에 이상이 생김',
      translation: 'mielenterveysongelma',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'x4Ud6',
    created: 1737044505304,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elvytysvoima',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LbhuG',
    created: 1737044506199,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'raja',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H10ne',
    created: 1737044508019,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: 'ʧʌbun',
      example: '* 음식 쓰레기 처분\n* 주식 처분\n* 무기정학 처분을 받다',
      definition: '* 처리하여 치움\n* 판매\n* 조처',
      translation: 'käsittely, myynti, toimenpide',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VILYO',
    created: 1737044509054,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kaiku',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7kYVz',
    created: 1737044511683,
    data: {
      language: 'ko',
      source: '결과',
      ipa: 'gjʌlgwa',
      example: '원인과 결과',
      definition: '어떤 원인으로 인해 생긴 결말',
      translation: 'tulos',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NTpl_',
    created: 1737044516320,
    data: {
      language: 'ko',
      source: '인정',
      ipa: 'inʤʌŋ',
      example: '소유권 인정',
      definition: '* 시인함\n* 남을 생각하는 따뜻한 마음',
      translation: 'myöntäminen, myötätunto',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ibJO7',
    created: 1737044518195,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'edistyminen',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'V8vIJ',
    created: 1737044521256,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: 'baʧida',
      example: '* 뇌물을 바치다\n* 목숨을 바치다\n* 세금을 바치다',
      definition:
        '* 윗사람에게 물건을 드리다\n* 귀중한 것을 내주다\n* 세금 따위를 바치다',
      translation: 'antaa, maksaa, uhrata',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MF1z-',
    created: 1737044522114,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'jumala sanoo olevan oikein',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2Q13_',
    created: 1737044524876,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'huolehtia välinpitämättömästi',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XsUjG',
    created: 1737044526941,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'edistyminen',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-HaeM',
    created: 1737044527883,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'hiljalleen',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'u_sCL',
    created: 1737044529829,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: 'guʧeʤʌk ̚',
      example: '구체적 증거',
      definition: '실제적이고 세밀한',
      translation: 'konkreettinen',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ccolL',
    created: 1737044531440,
    data: {
      language: 'ko',
      source: '특히',
      ipa: 'tʰɨkʰi',
      example: '오늘은 특히 더 피곤하다.',
      definition: '보통과는 다르게',
      translation: 'erityisesti',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GIEdG',
    created: 1737044532736,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: "ʤɨk ̚ʃ'i",
      example: '즉시 시정하다',
      definition: '당장',
      translation: 'välittömästi',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vD_XW',
    created: 1737044533481,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'suurin piirtein',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'M-YX6',
    created: 1737044534587,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: 'ʧuŋbunʰi',
      example: '충분히 쉬다',
      definition: '',
      translation: 'riittävästi',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'l1qO_',
    created: 1737044535854,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kestävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EeOg1',
    created: 1737044537677,
    data: {
      language: 'ko',
      source: '잠재적',
      ipa: 'ʤamʤεʤʌk ̚',
      example: '잠재적 욕구',
      definition: '숨어 있는',
      translation: 'potentiaalinen',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IWITQ',
    created: 1737044538446,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erittäin iloinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lFyyo',
    created: 1737044539440,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'varovainen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PjgUT',
    created: 1737044541375,
    data: {
      language: 'ko',
      source: '의존',
      ipa: 'ɰiʤon',
      example: '지나친 의존',
      definition: '다른 것에 의지함',
      translation: 'riippuvuus',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'V9P_L',
    created: 1737044543204,
    data: {
      language: 'ko',
      source: '한',
      ipa: 'han',
      example:
        '* 밥 한 그릇만 더 주시오.\n* 옛날 한 마을에\n* 한 오십 명 가량이 모였다.',
      definition: "* 수량이 하나임을 나타내는 말\n* '어떤'의 뜻\n* '대략'의 뜻",
      translation: 'yksi, eräs, noin',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
