import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '9q7N8',
    created: 1737024720840,
    data: {
      language: 'ko',
      source: '실성',
      ipa: 'ʃilsʌŋ',
      example: '실성을 했나?',
      definition: '정신에 이상이 생김',
      translation: 'वास्तविकता',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rClyc',
    created: 1737024730720,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लचीलापन',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eAn_b',
    created: 1737024740431,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सीमा बिंदु',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QOw91',
    created: 1737024760047,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: 'ʧʌbun',
      example: '* 음식 쓰레기 처분\n* 주식 처분\n* 무기정학 처분을 받다',
      definition: '* 처리하여 치움\n* 판매\n* 조처',
      translation: 'प्रबंधन, बिक्री, कार्रवाई',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JFBqZ',
    created: 1737024769807,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'प्रतिध्वनि',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'xDPYl',
    created: 1737024797868,
    data: {
      language: 'ko',
      source: '결과',
      ipa: 'gjʌlgwa',
      example: '원인과 결과',
      definition: '어떤 원인으로 인해 생긴 결말',
      translation: 'परिणाम',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0I4WZ',
    created: 1737024827114,
    data: {
      language: 'ko',
      source: '인정',
      ipa: 'inʤʌŋ',
      example: '소유권 인정',
      definition: '* 시인함\n* 남을 생각하는 따뜻한 마음',
      translation: 'स्वीकृति, सहानुभूति',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rPUh6',
    created: 1737024855315,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'आगे बढ़ना',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pR7Qd',
    created: 1737024883476,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: 'baʧida',
      example: '* 뇌물을 바치다\n* 목숨을 바치다\n* 세금을 바치다',
      definition:
        '* 윗사람에게 물건을 드리다\n* 귀중한 것을 내주다\n* 세금 따위를 바치다',
      translation: 'अर्पित करना, समर्पित करना, कर चुकाना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'q7oCA',
    created: 1737024893083,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ईश्वर ने कहा कि यह सही है',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'w-FyL',
    created: 1737024894034,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लापरवाही करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gl1pA',
    created: 1737024922307,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'आगे बढ़ना',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VFZhs',
    created: 1737024932419,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'धीरे-धीरे',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XcN_U',
    created: 1737024960563,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: 'guʧeʤʌk ̚',
      example: '구체적 증거',
      definition: '실제적이고 세밀한',
      translation: 'विशिष्ट',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'apgvu',
    created: 1737024971268,
    data: {
      language: 'ko',
      source: '특히',
      ipa: 'tʰɨkʰi',
      example: '오늘은 특히 더 피곤하다.',
      definition: '보통과는 다르게',
      translation: 'विशेष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lUGPE',
    created: 1737024990349,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: "ʤɨk ̚ʃ'i",
      example: '즉시 시정하다',
      definition: '당장',
      translation: 'तुरंत',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZhCTX',
    created: 1737025000013,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लगभग',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oegbk',
    created: 1737025009703,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: 'ʧuŋbunʰi',
      example: '충분히 쉬다',
      definition: '',
      translation: 'पर्याप्त रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eXWjX',
    created: 1737025020085,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'स्थायी',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ds--I',
    created: 1737025056341,
    data: {
      language: 'ko',
      source: '포괄적',
      ipa: "pʰogwalʤ'ʌk",
      example: '포괄적 개념',
      definition: '하나의 범위 안에 포함시키는',
      translation: 'विस्तृत',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2zj_l',
    created: 1737025066102,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'बहुत खुश',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Iv2er',
    created: 1737025075987,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'सावधान',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lnJGc',
    created: 1737025104415,
    data: {
      language: 'ko',
      source: '주저하다',
      ipa: 'ʤuʤʌʰada',
      example: '대답을 주저하다',
      definition: '망설이다',
      translation: 'संकोच करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'J4d_F',
    created: 1737025144180,
    data: {
      language: 'ko',
      source: '한',
      ipa: 'han',
      example:
        '* 밥 한 그릇만 더 주시오.\n* 옛날 한 마을에\n* 한 오십 명 가량이 모였다.',
      definition: "* 수량이 하나임을 나타내는 말\n* '어떤'의 뜻\n* '대략'의 뜻",
      translation: 'एक, किसी, लगभग',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
