import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'UKqzS',
    created: 1737044992461,
    data: {
      language: 'ko',
      source: 'жүзеге асыру',
      ipa: '',
      example: '',
      definition: '',
      translation: 'шындық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JBR02',
    created: 1737044993418,
    data: {
      language: 'ko',
      source: 'қалпына келу',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қалпына келу',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5RMOf',
    created: 1737044994408,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'шекара нүктесі',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dUluo',
    created: 1737044995607,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: 'ʧʌbun',
      example: '* 음식 쓰레기 처분\n* 주식 처분\n* 무기정학 처분을 받다',
      definition: '* 처리하여 치움\n* 판매\n* 조처',
      translation: 'кәдеге жарату',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0bCa4',
    created: 1737044996529,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жаңғырық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qVEzB',
    created: 1737044997325,
    data: {
      language: 'ko',
      source: 'нәтиже',
      ipa: '',
      example: '',
      definition: '',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '017lI',
    created: 1737044998158,
    data: {
      language: 'ko',
      source: 'инжеката',
      ipa: '',
      example: '',
      definition: '',
      translation: 'мойындау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'en8nt',
    created: 1737044999003,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'алдын ала',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3srnr',
    created: 1737044999898,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: 'baʧida',
      example: '* 뇌물을 바치다\n* 목숨을 바치다\n* 세금을 바치다',
      definition:
        '* 윗사람에게 물건을 드리다\n* 귀중한 것을 내주다\n* 세금 따위를 바치다',
      translation: 'арнау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AXVGi',
    created: 1737045000643,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Құдай дұрыс дейді',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3vwFb',
    created: 1737045001692,
    data: {
      language: 'ko',
      source: 'соһолхи хада',
      ipa: '',
      example: '',
      definition: '',
      translation: 'бос қалдыру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cEPPP',
    created: 1737045003196,
    data: {
      language: 'ko',
      source: '설득',
      ipa: "sʌlt'ɨk ̚",
      example: '설득을 당하다',
      definition: '이해시킴',
      translation: 'сендіру',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lnElr',
    created: 1737045004342,
    data: {
      language: 'ko',
      source: 'себепсіз',
      ipa: '',
      example: '',
      definition: '',
      translation: 'баяу',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tixQ6',
    created: 1737045005731,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: 'guʧeʤʌk ̚',
      example: '구체적 증거',
      definition: '실제적이고 세밀한',
      translation: 'нақты',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TTDcK',
    created: 1737045006997,
    data: {
      language: 'ko',
      source: '특히',
      ipa: 'tʰɨkʰi',
      example: '오늘은 특히 더 피곤하다.',
      definition: '보통과는 다르게',
      translation: 'әсіресе',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RHsOY',
    created: 1737045008112,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: "ʤɨk ̚ʃ'i",
      example: '즉시 시정하다',
      definition: '당장',
      translation: 'дереу',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4Ctz9',
    created: 1737045009034,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жартылай',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aVqxh',
    created: 1737045009967,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: 'ʧuŋbunʰi',
      example: '충분히 쉬다',
      definition: '',
      translation: 'жеткілікті',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'crCsT',
    created: 1737045011515,
    data: {
      language: 'ko',
      source: 'жүйелі',
      ipa: '',
      example: '',
      definition: '',
      translation: 'тұрақты',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pqdS5',
    created: 1737045012952,
    data: {
      language: 'ko',
      source: '잠재적',
      ipa: 'ʤamʤεʤʌk ̚',
      example: '잠재적 욕구',
      definition: '숨어 있는',
      translation: 'потенциал',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mTyy4',
    created: 1737045014058,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'өте қуанышты',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cDAC4',
    created: 1737045015140,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сақ боларлық',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XjGMs',
    created: 1737045016355,
    data: {
      language: 'ko',
      source: '의존',
      ipa: 'ɰiʤon',
      example: '지나친 의존',
      definition: '다른 것에 의지함',
      translation: 'тәуелділік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'm-7gm',
    created: 1737045017255,
    data: {
      language: 'ko',
      source: 'маңызды',
      ipa: '',
      example: '',
      definition: '',
      translation: 'маңызды',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
