import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'BULJ1',
    created: 1737044855981,
    data: {
      language: 'ko',
      source: '실성',
      ipa: 'ʃilsʌŋ',
      example: '실성을 했나?',
      definition: '정신에 이상이 생김',
      translation: 'gangguan mental',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ihN0g',
    created: 1737044857035,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'daya tahan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wlBg1',
    created: 1737044857937,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'titik had',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2oBdI',
    created: 1737044859614,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: 'ʧʌbun',
      example: '* 음식 쓰레기 처분\n* 주식 처분\n* 무기정학 처분을 받다',
      definition: '* 처리하여 치움\n* 판매\n* 조처',
      translation: 'penyelesaian, penjualan, tindakan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5mLbt',
    created: 1737044860728,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'reaksi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'L2fKL',
    created: 1737044862786,
    data: {
      language: 'ko',
      source: '결과',
      ipa: 'gjʌlgwa',
      example: '원인과 결과',
      definition: '어떤 원인으로 인해 생긴 결말',
      translation: 'hasil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'fGMDa',
    created: 1737044864369,
    data: {
      language: 'ko',
      source: '인정',
      ipa: 'inʤʌŋ',
      example: '소유권 인정',
      definition: '* 시인함\n* 남을 생각하는 따뜻한 마음',
      translation: 'pengakuan, kasih sayang',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ajfbp',
    created: 1737044869671,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'kemajuan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mhmSV',
    created: 1737044871632,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: 'baʧida',
      example: '* 뇌물을 바치다\n* 목숨을 바치다\n* 세금을 바치다',
      definition:
        '* 윗사람에게 물건을 드리다\n* 귀중한 것을 내주다\n* 세금 따위를 바치다',
      translation: 'memberi, menyerahkan, membayar, menyampaikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KbSsk',
    created: 1737044875059,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Tuhan berkata benar',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'F4MZK',
    created: 1737044876287,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'mengabaikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sVnPY',
    created: 1737044878081,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'kemajuan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yp_nA',
    created: 1737044878909,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'perlahan-lahan',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5c1FB',
    created: 1737044881485,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: 'guʧeʤʌk ̚',
      example: '구체적 증거',
      definition: '실제적이고 세밀한',
      translation: 'spesifik, terperinci',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_LU37',
    created: 1737044883188,
    data: {
      language: 'ko',
      source: '특히',
      ipa: 'tʰɨkʰi',
      example: '오늘은 특히 더 피곤하다.',
      definition: '보통과는 다르게',
      translation: 'terutama',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'h5XS-',
    created: 1737044884675,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: "ʤɨk ̚ʃ'i",
      example: '즉시 시정하다',
      definition: '당장',
      translation: 'segera',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'g-Hhm',
    created: 1737044885712,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'secara kasar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2LW_U',
    created: 1737044886578,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: 'ʧuŋbunʰi',
      example: '충분히 쉬다',
      definition: '',
      translation: 'secukupnya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'c94oP',
    created: 1737044887403,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berterusan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oJh1e',
    created: 1737044888906,
    data: {
      language: 'ko',
      source: '포괄적',
      ipa: "pʰogwalʤ'ʌk",
      example: '포괄적 개념',
      definition: '하나의 범위 안에 포함시키는',
      translation: 'menyeluruh',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mQElS',
    created: 1737044889744,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sangat gembira',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eEXxO',
    created: 1737044891037,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'berhati-hati',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bWhkQ',
    created: 1737044892884,
    data: {
      language: 'ko',
      source: '의존',
      ipa: 'ɰiʤon',
      example: '지나친 의존',
      definition: '다른 것에 의지함',
      translation: 'bergantung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'YxMG1',
    created: 1737044894968,
    data: {
      language: 'ko',
      source: '한',
      ipa: 'han',
      example:
        '* 밥 한 그릇만 더 주시오.\n* 옛날 한 마을에\n* 한 오십 명 가량이 모였다.',
      definition: "* 수량이 하나임을 나타내는 말\n* '어떤'의 뜻\n* '대략'의 뜻",
      translation: 'satu, sebuah, lebih kurang',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
