import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'AVyjW',
    created: 1737025163577,
    data: {
      language: 'ko',
      source: '실성',
      ipa: 'ʃilsʌŋ',
      example: '실성을 했나?',
      definition: '정신에 이상이 생김',
      translation: 'Gerçeklik',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UFQTs',
    created: 1737025174297,
    data: {
      language: 'ko',
      source: '회복력',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dayanıklılık',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nyq7Z',
    created: 1737025184024,
    data: {
      language: 'ko',
      source: '한계점',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sınır noktası',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tUuNz',
    created: 1737025203013,
    data: {
      language: 'ko',
      source: '처ː분',
      ipa: 'ʧʌbun',
      example: '* 음식 쓰레기 처분\n* 주식 처분\n* 무기정학 처분을 받다',
      definition: '* 처리하여 치움\n* 판매\n* 조처',
      translation: 'işlem, satış, önlem',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0JMHW',
    created: 1737025212773,
    data: {
      language: 'ko',
      source: '반향',
      ipa: '',
      example: '',
      definition: '',
      translation: 'yankı',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CnukG',
    created: 1737025232469,
    data: {
      language: 'ko',
      source: '결과',
      ipa: 'gjʌlgwa',
      example: '원인과 결과',
      definition: '어떤 원인으로 인해 생긴 결말',
      translation: 'sonuç',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0rL8G',
    created: 1737025269876,
    data: {
      language: 'ko',
      source: '인정',
      ipa: 'inʤʌŋ',
      example: '소유권 인정',
      definition: '* 시인함\n* 남을 생각하는 따뜻한 마음',
      translation: 'kabul, itiraf etmek',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3zDNt',
    created: 1737025306151,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'ilerleme',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Mtbns',
    created: 1737025334257,
    data: {
      language: 'ko',
      source: '바치다',
      ipa: 'baʧida',
      example: '* 뇌물을 바치다\n* 목숨을 바치다\n* 세금을 바치다',
      definition:
        '* 윗사람에게 물건을 드리다\n* 귀중한 것을 내주다\n* 세금 따위를 바치다',
      translation: 'sunmak, vermek, ödemek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7ZYPi',
    created: 1737025343853,
    data: {
      language: 'ko',
      source: '신이 옳다고 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Tanrı doğru diyor',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RjXce',
    created: 1737025355597,
    data: {
      language: 'ko',
      source: '소홀히 하다',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ihmal etmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'q3uGH',
    created: 1737025383817,
    data: {
      language: 'ko',
      source: '전진',
      ipa: 'ʤʌnʤin',
      example: '전진을 계속하다',
      definition: '앞으로 나아감',
      translation: 'ilerleme',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yqUPM',
    created: 1737025393849,
    data: {
      language: 'ko',
      source: '서서히',
      ipa: '',
      example: '',
      definition: '',
      translation: 'yavaş yavaş',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CBymc',
    created: 1737025413138,
    data: {
      language: 'ko',
      source: '구체적',
      ipa: 'guʧeʤʌk ̚',
      example: '구체적 증거',
      definition: '실제적이고 세밀한',
      translation: 'somut, detaylı',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vnUqD',
    created: 1737025432382,
    data: {
      language: 'ko',
      source: '특히',
      ipa: 'tʰɨkʰi',
      example: '오늘은 특히 더 피곤하다.',
      definition: '보통과는 다르게',
      translation: 'özellikle',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wCc_V',
    created: 1737025451675,
    data: {
      language: 'ko',
      source: '즉시',
      ipa: "ʤɨk ̚ʃ'i",
      example: '즉시 시정하다',
      definition: '당장',
      translation: 'hemen',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NfERq',
    created: 1737025461891,
    data: {
      language: 'ko',
      source: '대충',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rastgele',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MNzn8',
    created: 1737025471632,
    data: {
      language: 'ko',
      source: '충분히',
      ipa: 'ʧuŋbunʰi',
      example: '충분히 쉬다',
      definition: '',
      translation: 'yeterince',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QZ6Qm',
    created: 1737025473705,
    data: {
      language: 'ko',
      source: '지속성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sürekli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'U3Lag',
    created: 1737025501910,
    data: {
      language: 'ko',
      source: '포괄적',
      ipa: "pʰogwalʤ'ʌk",
      example: '포괄적 개념',
      definition: '하나의 범위 안에 포함시키는',
      translation: 'kapsayıcı',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1rwk-',
    created: 1737025511676,
    data: {
      language: 'ko',
      source: '매우 기쁜',
      ipa: '',
      example: '',
      definition: '',
      translation: 'çok mutlu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RVzs3',
    created: 1737025521484,
    data: {
      language: 'ko',
      source: '조심성 있는',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dikkatli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8NM9g',
    created: 1737025549314,
    data: {
      language: 'ko',
      source: '의존',
      ipa: 'ɰiʤon',
      example: '지나친 의존',
      definition: '다른 것에 의지함',
      translation: 'bağımlılık',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ml65p',
    created: 1737025586633,
    data: {
      language: 'ko',
      source: '한',
      ipa: 'han',
      example:
        '* 밥 한 그릇만 더 주시오.\n* 옛날 한 마을에\n* 한 오십 명 가량이 모였다.',
      definition: "* 수량이 하나임을 나타내는 말\n* '어떤'의 뜻\n* '대략'의 뜻",
      translation: 'bir, bir tane, yaklaşık',
      partOfSpeech: 'determiner',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
