import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'F80gU',
    created: 1737012254730,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: "ɪntexri'tɛit",
      example:
        'Integriteit staat volop in de belangstelling bij bedrijfsleven en overheid.',
      definition: 'eigenschap dat je eerlijk en betrouwbaar bent',
      translation: 'rehellisyys, integraatio',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oPZfA',
    created: 1737012274015,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: "'werstɑnt",
      example: '* weerstand bieden\n* weerstand opbouwen',
      definition:
        '* keer dat je je verzet tegen iets of iemand\n* mate waarin je lichaam kan voorkomen dat je ziek wordt',
      translation: 'vastustus, resistanssi',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_NzGg',
    created: 1737012293128,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: "'drɛmpəlwardə",
      example: 'de drempelwaarde wordt steeds vaker overschreden',
      definition: 'waarde die een onder- of bovengrens aangeeft',
      translation: 'kynnysarvo',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4uCf6',
    created: 1737012312366,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: "dɪspo'zi(t)si",
      example:
        'Disposities van orgels zijn verschillend door het doel, de tijdgeest en muzikale stromingen.',
      definition:
        '* (van een orgel) alle registers en andere onderdelen samen\n* het opnemen van geld bij een bank',
      translation: 'rekisterit, talletus, dispositio',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cCRNP',
    created: 1737012322585,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: "repɛr'kʏsi",
      example: 'de repercussies van de financiële crisis',
      definition: 'nadelig gevolg van iets',
      translation: 'seuraus, reperkuio',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZahLQ',
    created: 1737012341671,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: 'rezʏlˈtat',
      example: 'bedrijfsresultaat',
      definition: 'wat je bereikt nadat je iets hebt gedaan of gemaakt',
      translation: 'tulos',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_euf3',
    created: 1737012378026,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: 'ɛrˈkɛnə(n)',
      example: 'je fouten erkennen',
      definition: '(iets) inzien en ook toegeven',
      translation: 'myöntää, tunnustaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mCdcK',
    created: 1737012406156,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: 'ovərˈwexə(n)',
      example: 'overwegen je te laten omscholen tot meubelmaker',
      definition: 'nadenken of je iets wilt doen of niet',
      translation: 'pohdiskella, punnita',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'imh0G',
    created: 1737012425475,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: 'ˈwɛidə(n)',
      example: 'iemand tot priester wijden',
      definition: 'met religieuze handelingen zegenen',
      translation: 'vihkiä, laajentaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'z4opr',
    created: 1737012467726,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: 'vərˈɑntwordə(n)',
      example: 'je keuze verantwoorden',
      definition: 'vertellen waarom iets verantwoord is',
      translation: 'perustella, vastata',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4gWn0',
    created: 1737012478179,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: "vər'warlozə(n)",
      example: 'je gezondheid verwaarlozen',
      definition: 'te weinig aandacht besteden aan',
      translation: 'huomiotta jättää, laiminlyödä',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KKrgx',
    created: 1737012505850,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: 'ovərˈtœyxə(n)',
      example: 'overtuigend bewijs',
      definition:
        'met argumenten bereiken dat (iemand) gelooft dat iets is zoals je het voorstelt',
      translation: 'vakuuttaa',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'e68iH',
    created: 1737012533736,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: 'xəˈlɛidələk',
      example: 'Geleidelijk aan is hij grijs geworden.',
      definition: 'langzaam steeds meer',
      translation: 'asteittain',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6On7e',
    created: 1737012561355,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: 'ɪmpliˈsit',
      example:
        'door extra aardig te zijn impliciet toegeven dat je daarnet onaardig was',
      definition: 'als iets zo is maar niet gezegd wordt',
      translation: 'epäsuora, implisiittinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wauPH',
    created: 1737012589275,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: 'ɔpˈmɛrkələk',
      example:
        'De snel groeiende belangstelling voor de golfsport is een opmerkelijk verschijnsel.',
      definition: 'opvallend',
      translation: 'huomionarvoinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ncnu_',
    created: 1737012608754,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: 'prɔmt',
      example: '',
      definition:
        'teken of tekenreeks op een beeldscherm dat aangeeft dat de gebruiker iets moet doen',
      translation: 'kehotus',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'k10p_',
    created: 1737012627980,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: 'ɔnxəˈver',
      example: 'ongeveer een meter',
      definition: 'niet precies',
      translation: 'noin',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'i-44N',
    created: 1737012656348,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: "vɔl'dundə",
      example: 'We hebben je voldoende gewaarschuwd.',
      definition: 'zo veel, zo goed enz. als nodig is',
      translation: 'riittävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cPh3P',
    created: 1737012684515,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: "vɔl'hɑrdɪŋ",
      example:
        'Hij heeft zijn succes te danken aan zijn enthousiasme en volhardendheid.',
      definition: 'het standvastig of koppig volhouden wat je begonnen bent',
      translation: 'kestävyys',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vwjZD',
    created: 1737012703963,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: "'œytxəbrɛit",
      example: 'een uitgebreid weerbericht',
      definition: 'met een grote omvang of duur',
      translation: 'laaja',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IsMOS',
    created: 1737012722860,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: 'vərˈʏkələk',
      example: 'een verrukkelijke smaak',
      definition: 'heel erg lekker',
      translation: 'herkullinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HOs1m',
    created: 1737012742138,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: "vor'zɪxtəx",
      example: 'Wees voorzichtig!',
      definition:
        'waarbij je goed oplet en ervoor zorgt dat er geen onaangename dingen gebeuren',
      translation: 'varovainen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gA1dx',
    created: 1737012779341,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: 'ˈhœyvərəx',
      example: 'Veel consumenten zijn nog huiverig om kunstvlees te kopen.',
      definition: 'als je een beetje bang bent om iets te doen',
      translation: 'epävarma, epäluuloinen',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hrj3Z',
    created: 1737012789545,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: "'sɪxnifikɑnt",
      example:
        '* Bij een meetwaarde is het eerste cijfer van het getal het meest significant.\n* Uit een statistische toets blijkt dat het resultaat significant is.',
      definition: '* van groot belang\n* statistisch niet op toeval berustend',
      translation: 'merkittävä, tilastollisesti merkittävä',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
