import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'U8DWl',
    created: 1737016089861,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: "ɪntexri'tɛit",
      example:
        'Integriteit staat volop in de belangstelling bij bedrijfsleven en overheid.',
      definition: 'eigenschap dat je eerlijk en betrouwbaar bent',
      translation: 'integritas',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'fukb3',
    created: 1737016109793,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: "'werstɑnt",
      example: '* weerstand bieden\n* weerstand opbouwen',
      definition:
        '* keer dat je je verzet tegen iets of iemand\n* mate waarin je lichaam kan voorkomen dat je ziek wordt',
      translation: 'perlawanan, ketahanan',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qLE54',
    created: 1737016130303,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: "'drɛmpəlwardə",
      example: 'de drempelwaarde wordt steeds vaker overschreden',
      definition: 'waarde die een onder- of bovengrens aangeeft',
      translation: 'ambang nilai, nilai ambang',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ogrw7',
    created: 1737016140701,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: "dɪspo'zi(t)si",
      example:
        'Disposities van orgels zijn verschillend door het doel, de tijdgeest en muzikale stromingen.',
      definition:
        '* (van een orgel) alle registers en andere onderdelen samen\n* het opnemen van geld bij een bank',
      translation: 'disposisi, penarikan',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lnPBD',
    created: 1737016161025,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: "repɛr'kʏsi",
      example: 'de repercussies van de financiële crisis',
      definition: 'nadelig gevolg van iets',
      translation: 'damp, konsekuensi, dampak',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tFzgB',
    created: 1737016188586,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: 'rezʏlˈtat',
      example: 'bedrijfsresultaat',
      definition: 'wat je bereikt nadat je iets hebt gedaan of gemaakt',
      translation: 'hasil',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RPqEo',
    created: 1737016216687,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: 'ɛrˈkɛnə(n)',
      example: 'je fouten erkennen',
      definition: '(iets) inzien en ook toegeven',
      translation: 'mengakui',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5xWeg',
    created: 1737016244529,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: 'ovərˈwexə(n)',
      example: 'overwegen je te laten omscholen tot meubelmaker',
      definition: 'nadenken of je iets wilt doen of niet',
      translation: 'mempertimbangkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dfjKJ',
    created: 1737016272410,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: 'ˈwɛidə(n)',
      example: 'iemand tot priester wijden',
      definition: 'met religieuze handelingen zegenen',
      translation: 'menguduskan, memperluas',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'fn3aV',
    created: 1737016308647,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: 'vərˈɑntwordə(n)',
      example: 'je keuze verantwoorden',
      definition: 'vertellen waarom iets verantwoord is',
      translation: 'untuk membenarkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'uD_XV',
    created: 1737016336714,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: "vər'warlozə(n)",
      example: 'je gezondheid verwaarlozen',
      definition: 'te weinig aandacht besteden aan',
      translation: 'mengabaikan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hmnJX',
    created: 1737016373062,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: 'ovərˈtœyxə(n)',
      example: 'overtuigend bewijs',
      definition:
        'met argumenten bereiken dat (iemand) gelooft dat iets is zoals je het voorstelt',
      translation: 'meyakinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5sCsL',
    created: 1737016392205,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: 'xəˈlɛidələk',
      example: 'Geleidelijk aan is hij grijs geworden.',
      definition: 'langzaam steeds meer',
      translation: 'perlahan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'uFLYH',
    created: 1737016420053,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: 'ɪmpliˈsit',
      example:
        'door extra aardig te zijn impliciet toegeven dat je daarnet onaardig was',
      definition: 'als iets zo is maar niet gezegd wordt',
      translation: 'implisit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oVvft',
    created: 1737016448602,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: 'ɔpˈmɛrkələk',
      example:
        'De snel groeiende belangstelling voor de golfsport is een opmerkelijk verschijnsel.',
      definition: 'opvallend',
      translation: 'menarik, mencolok',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jg87l',
    created: 1737016476854,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: 'prɔmt',
      example: '',
      definition:
        'teken of tekenreeks op een beeldscherm dat aangeeft dat de gebruiker iets moet doen',
      translation: 'perintah',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-mAl2',
    created: 1737016487193,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: 'ɔnxəˈver',
      example: 'ongeveer een meter',
      definition: 'niet precies',
      translation: 'sekitar',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NMfdt',
    created: 1737016515578,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: "vɔl'dundə",
      example: 'We hebben je voldoende gewaarschuwd.',
      definition: 'zo veel, zo goed enz. als nodig is',
      translation: 'cukup',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IuGQp',
    created: 1737016552094,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: "vɔl'hɑrdɪŋ",
      example:
        'Hij heeft zijn succes te danken aan zijn enthousiasme en volhardendheid.',
      definition: 'het standvastig of koppig volhouden wat je begonnen bent',
      translation: 'ketekunan',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0Oiy-',
    created: 1737016579630,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: "'œytxəbrɛit",
      example: 'een uitgebreid weerbericht',
      definition: 'met een grote omvang of duur',
      translation: 'luas',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VQ-Eo',
    created: 1737016598738,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: 'vərˈʏkələk',
      example: 'een verrukkelijke smaak',
      definition: 'heel erg lekker',
      translation: 'lezat, enak',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZZvs-',
    created: 1737016618102,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: "vor'zɪxtəx",
      example: 'Wees voorzichtig!',
      definition:
        'waarbij je goed oplet en ervoor zorgt dat er geen onaangename dingen gebeuren',
      translation: 'hati-hati',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-pXBV',
    created: 1737016646361,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: 'ˈhœyvərəx',
      example: 'Veel consumenten zijn nog huiverig om kunstvlees te kopen.',
      definition: 'als je een beetje bang bent om iets te doen',
      translation: 'ragu, ragu-ragu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7HeHq',
    created: 1737016665764,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: "'sɪxnifikɑnt",
      example:
        '* Bij een meetwaarde is het eerste cijfer van het getal het meest significant.\n* Uit een statistische toets blijkt dat het resultaat significant is.',
      definition: '* van groot belang\n* statistisch niet op toeval berustend',
      translation: 'signifikan, berarti besar',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
