import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'PRF9q',
    created: 1737005797633,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: "ɪntexri'tɛit",
      example:
        'Integriteit staat volop in de belangstelling bij bedrijfsleven en overheid.',
      definition: 'eigenschap dat je eerlijk en betrouwbaar bent',
      translation: 'целостность',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EA7hQ',
    created: 1737005807963,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: "'werstɑnt",
      example: '* weerstand bieden\n* weerstand opbouwen',
      definition:
        '* keer dat je je verzet tegen iets of iemand\n* mate waarin je lichaam kan voorkomen dat je ziek wordt',
      translation: 'сопротивление, иммунитет',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0nts5',
    created: 1737005827624,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: "'drɛmpəlwardə",
      example: 'de drempelwaarde wordt steeds vaker overschreden',
      definition: 'waarde die een onder- of bovengrens aangeeft',
      translation: 'пороговое значение',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bsGlC',
    created: 1737005846676,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: "dɪspo'zi(t)si",
      example:
        'Disposities van orgels zijn verschillend door het doel, de tijdgeest en muzikale stromingen.',
      definition:
        '* (van een orgel) alle registers en andere onderdelen samen\n* het opnemen van geld bij een bank',
      translation: 'регистры органа, депозит, диспозиция',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 't24BR',
    created: 1737005865933,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: "repɛr'kʏsi",
      example: 'de repercussies van de financiële crisis',
      definition: 'nadelig gevolg van iets',
      translation: 'последствие, реперкуссия',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ddYUS',
    created: 1737005876158,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: 'rezʏlˈtat',
      example: 'bedrijfsresultaat',
      definition: 'wat je bereikt nadat je iets hebt gedaan of gemaakt',
      translation: 'результат',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'YwvLM',
    created: 1737005904433,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: 'ɛrˈkɛnə(n)',
      example: 'je fouten erkennen',
      definition: '(iets) inzien en ook toegeven',
      translation: 'признавать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZE0u5',
    created: 1737005961212,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: 'ovərˈwexə(n)',
      example: 'overwegen je te laten omscholen tot meubelmaker',
      definition: 'nadenken of je iets wilt doen of niet',
      translation: 'обдумывать, рассматривать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ELZtQ',
    created: 1737005962687,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: 'ˈwɛidə(n)',
      example: 'iemand tot priester wijden',
      definition: 'met religieuze handelingen zegenen',
      translation: 'освящать, расширять',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wjx7l',
    created: 1737005982194,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: 'vərˈɑntwordə(n)',
      example: 'je keuze verantwoorden',
      definition: 'vertellen waarom iets verantwoord is',
      translation: 'обосновать, обосновывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qkLKO',
    created: 1737006001255,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: "vər'warlozə(n)",
      example: 'je gezondheid verwaarlozen',
      definition: 'te weinig aandacht besteden aan',
      translation: 'игнорировать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'R8uyc',
    created: 1737006029459,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: 'ovərˈtœyxə(n)',
      example: 'overtuigend bewijs',
      definition:
        'met argumenten bereiken dat (iemand) gelooft dat iets is zoals je het voorstelt',
      translation: 'убеждать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'U3ckQ',
    created: 1737006057378,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: 'xəˈlɛidələk',
      example: 'Geleidelijk aan is hij grijs geworden.',
      definition: 'langzaam steeds meer',
      translation: 'постепенный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CFjYL',
    created: 1737006067520,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: 'ɪmpliˈsit',
      example:
        'door extra aardig te zijn impliciet toegeven dat je daarnet onaardig was',
      definition: 'als iets zo is maar niet gezegd wordt',
      translation: 'неявный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lWJsl',
    created: 1737006121494,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: 'ɔpˈmɛrkələk',
      example:
        'De snel groeiende belangstelling voor de golfsport is een opmerkelijk verschijnsel.',
      definition: 'opvallend',
      translation: 'заметный, замечательный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FfjqM',
    created: 1737006131862,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: 'prɔmt',
      example: '',
      definition:
        'teken of tekenreeks op een beeldscherm dat aangeeft dat de gebruiker iets moet doen',
      translation: 'подсказка',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vc5Hw',
    created: 1737006151224,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: 'ɔnxəˈver',
      example: 'ongeveer een meter',
      definition: 'niet precies',
      translation: 'примерно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '94FBM',
    created: 1737006170362,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: "vɔl'dundə",
      example: 'We hebben je voldoende gewaarschuwd.',
      definition: 'zo veel, zo goed enz. als nodig is',
      translation: 'достаточно',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'A_WiS',
    created: 1737006198316,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: "vɔl'hɑrdɪŋ",
      example:
        'Hij heeft zijn succes te danken aan zijn enthousiasme en volhardendheid.',
      definition: 'het standvastig of koppig volhouden wat je begonnen bent',
      translation: 'упорство',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8kC5m',
    created: 1737006226575,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: "'œytxəbrɛit",
      example: 'een uitgebreid weerbericht',
      definition: 'met een grote omvang of duur',
      translation: 'обширный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5Jn_y',
    created: 1737006245660,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: 'vərˈʏkələk',
      example: 'een verrukkelijke smaak',
      definition: 'heel erg lekker',
      translation: 'восхитительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UGNCH',
    created: 1737006267483,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: "vor'zɪxtəx",
      example: 'Wees voorzichtig!',
      definition:
        'waarbij je goed oplet en ervoor zorgt dat er geen onaangename dingen gebeuren',
      translation: 'осторожный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nIDQh',
    created: 1737006286804,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: 'ˈhœyvərəx',
      example: 'Veel consumenten zijn nog huiverig om kunstvlees te kopen.',
      definition: 'als je een beetje bang bent om iets te doen',
      translation: 'опасливый, робкий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TgMr6',
    created: 1737006306146,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: "'sɪxnifikɑnt",
      example:
        '* Bij een meetwaarde is het eerste cijfer van het getal het meest significant.\n* Uit een statistische toets blijkt dat het resultaat significant is.',
      definition: '* van groot belang\n* statistisch niet op toeval berustend',
      translation: 'значительный, существенный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
