import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'F36Fk',
    created: 1737015042588,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: "ɪntexri'tɛit",
      example:
        'Integriteit staat volop in de belangstelling bij bedrijfsleven en overheid.',
      definition: 'eigenschap dat je eerlijk en betrouwbaar bent',
      translation: 'ความซื่อสัตย์',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QJVp6',
    created: 1737015053144,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: "'werstɑnt",
      example: '* weerstand bieden\n* weerstand opbouwen',
      definition:
        '* keer dat je je verzet tegen iets of iemand\n* mate waarin je lichaam kan voorkomen dat je ziek wordt',
      translation: 'การต่อต้าน, ภูมิคุ้มกัน, ความต้านทาน',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-_kXz',
    created: 1737015072205,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: "'drɛmpəlwardə",
      example: 'de drempelwaarde wordt steeds vaker overschreden',
      definition: 'waarde die een onder- of bovengrens aangeeft',
      translation: 'เกณฑ์, ค่าขั้นต่ำ',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2IWLi',
    created: 1737015091267,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: "dɪspo'zi(t)si",
      example:
        'Disposities van orgels zijn verschillend door het doel, de tijdgeest en muzikale stromingen.',
      definition:
        '* (van een orgel) alle registers en andere onderdelen samen\n* het opnemen van geld bij een bank',
      translation: 'การจัดเรียง, การฝากเงิน, การจัดการ',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mLrDU',
    created: 1737015110451,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: "repɛr'kʏsi",
      example: 'de repercussies van de financiële crisis',
      definition: 'nadelig gevolg van iets',
      translation: 'ผลกระทบ',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '550xj',
    created: 1737015120918,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: 'rezʏlˈtat',
      example: 'bedrijfsresultaat',
      definition: 'wat je bereikt nadat je iets hebt gedaan of gemaakt',
      translation: 'ผลลัพธ์',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SAQj6',
    created: 1737015148873,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: 'ɛrˈkɛnə(n)',
      example: 'je fouten erkennen',
      definition: '(iets) inzien en ook toegeven',
      translation: 'ยอมรับ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tDe_F',
    created: 1737015177329,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: 'ovərˈwexə(n)',
      example: 'overwegen je te laten omscholen tot meubelmaker',
      definition: 'nadenken of je iets wilt doen of niet',
      translation: 'พิจารณา',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XnCyE',
    created: 1737015205155,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: 'ˈwɛidə(n)',
      example: 'iemand tot priester wijden',
      definition: 'met religieuze handelingen zegenen',
      translation: 'อุทิศ, ขยาย',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4qhHd',
    created: 1737015233130,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: 'vərˈɑntwordə(n)',
      example: 'je keuze verantwoorden',
      definition: 'vertellen waarom iets verantwoord is',
      translation: 'ชี้แจง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IeA1U',
    created: 1737015243572,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: "vər'warlozə(n)",
      example: 'je gezondheid verwaarlozen',
      definition: 'te weinig aandacht besteden aan',
      translation: 'ละเลย',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UuXs3',
    created: 1737015272017,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: 'ovərˈtœyxə(n)',
      example: 'overtuigend bewijs',
      definition:
        'met argumenten bereiken dat (iemand) gelooft dat iets is zoals je het voorstelt',
      translation: 'ทำให้เชื่อ, ชักจูง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_xhvA',
    created: 1737015299946,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: 'xəˈlɛidələk',
      example: 'Geleidelijk aan is hij grijs geworden.',
      definition: 'langzaam steeds meer',
      translation: 'ค่อยๆ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LLx7B',
    created: 1737015319076,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: 'ɪmpliˈsit',
      example:
        'door extra aardig te zijn impliciet toegeven dat je daarnet onaardig was',
      definition: 'als iets zo is maar niet gezegd wordt',
      translation: 'โดยนัย',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'R848i',
    created: 1737015347190,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: 'ɔpˈmɛrkələk',
      example:
        'De snel groeiende belangstelling voor de golfsport is een opmerkelijk verschijnsel.',
      definition: 'opvallend',
      translation: 'น่าสังเกต, น่าทึ่ง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3DK56',
    created: 1737015375326,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: 'prɔmt',
      example: '',
      definition:
        'teken of tekenreeks op een beeldscherm dat aangeeft dat de gebruiker iets moet doen',
      translation: 'คำสั่ง',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6IiJ0',
    created: 1737015394604,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: 'ɔnxəˈver',
      example: 'ongeveer een meter',
      definition: 'niet precies',
      translation: 'ประมาณ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FQPdI',
    created: 1737015422554,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: "vɔl'dundə",
      example: 'We hebben je voldoende gewaarschuwd.',
      definition: 'zo veel, zo goed enz. als nodig is',
      translation: 'เพียงพอ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MkREE',
    created: 1737015442095,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: "vɔl'hɑrdɪŋ",
      example:
        'Hij heeft zijn succes te danken aan zijn enthousiasme en volhardendheid.',
      definition: 'het standvastig of koppig volhouden wat je begonnen bent',
      translation: 'ความมุ่งมั่น',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dioZO',
    created: 1737015470288,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: "'œytxəbrɛit",
      example: 'een uitgebreid weerbericht',
      definition: 'met een grote omvang of duur',
      translation: 'กว้างขวาง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'shjMN',
    created: 1737015490775,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: 'vərˈʏkələk',
      example: 'een verrukkelijke smaak',
      definition: 'heel erg lekker',
      translation: 'อร่อยมาก',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ME9Wt',
    created: 1737015501308,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: "vor'zɪxtəx",
      example: 'Wees voorzichtig!',
      definition:
        'waarbij je goed oplet en ervoor zorgt dat er geen onaangename dingen gebeuren',
      translation: 'ระมัดระวัง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ozrRI',
    created: 1737015529494,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: 'ˈhœyvərəx',
      example: 'Veel consumenten zijn nog huiverig om kunstvlees te kopen.',
      definition: 'als je een beetje bang bent om iets te doen',
      translation: 'กลัว, หวาดกลัว',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'gLm91',
    created: 1737015548863,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: "'sɪxnifikɑnt",
      example:
        '* Bij een meetwaarde is het eerste cijfer van het getal het meest significant.\n* Uit een statistische toets blijkt dat het resultaat significant is.',
      definition: '* van groot belang\n* statistisch niet op toeval berustend',
      translation: 'สำคัญ, มีนัยสำคัญ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
