import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'xatAt',
    created: 1737017408874,
    data: {
      language: 'nl',
      source: 'de integriteit',
      ipa: "ɪntexri'tɛit",
      example:
        'Integriteit staat volop in de belangstelling bij bedrijfsleven en overheid.',
      definition: 'eigenschap dat je eerlijk en betrouwbaar bent',
      translation: 'цілісність',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6Hlgv',
    created: 1737017444755,
    data: {
      language: 'nl',
      source: 'de weerstand',
      ipa: "'werstɑnt",
      example: '* weerstand bieden\n* weerstand opbouwen',
      definition:
        '* keer dat je je verzet tegen iets of iemand\n* mate waarin je lichaam kan voorkomen dat je ziek wordt',
      translation: 'опір',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zqDdG',
    created: 1737017480820,
    data: {
      language: 'nl',
      source: 'de drempelwaarde',
      ipa: "'drɛmpəlwardə",
      example: 'de drempelwaarde wordt steeds vaker overschreden',
      definition: 'waarde die een onder- of bovengrens aangeeft',
      translation: 'порогове значення',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sa_81',
    created: 1737017516894,
    data: {
      language: 'nl',
      source: 'de dispositie',
      ipa: "dɪspo'zi(t)si",
      example:
        'Disposities van orgels zijn verschillend door het doel, de tijdgeest en muzikale stromingen.',
      definition:
        '* (van een orgel) alle registers en andere onderdelen samen\n* het opnemen van geld bij een bank',
      translation: 'розташування',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XwSZ8',
    created: 1737017552976,
    data: {
      language: 'nl',
      source: 'de repercussie',
      ipa: "repɛr'kʏsi",
      example: 'de repercussies van de financiële crisis',
      definition: 'nadelig gevolg van iets',
      translation: 'реперкусія',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'd5Z7S',
    created: 1737017588891,
    data: {
      language: 'nl',
      source: 'het resultaat',
      ipa: 'rezʏlˈtat',
      example: 'bedrijfsresultaat',
      definition: 'wat je bereikt nadat je iets hebt gedaan of gemaakt',
      translation: 'результат',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8DZyw',
    created: 1737017624932,
    data: {
      language: 'nl',
      source: 'erkennen',
      ipa: 'ɛrˈkɛnə(n)',
      example: 'je fouten erkennen',
      definition: '(iets) inzien en ook toegeven',
      translation: 'визнати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4O3Zp',
    created: 1737017661003,
    data: {
      language: 'nl',
      source: 'overwegen',
      ipa: 'ovərˈwexə(n)',
      example: 'overwegen je te laten omscholen tot meubelmaker',
      definition: 'nadenken of je iets wilt doen of niet',
      translation: 'розглянути',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aZ22i',
    created: 1737017697297,
    data: {
      language: 'nl',
      source: 'wijden',
      ipa: 'ˈwɛidə(n)',
      example: 'iemand tot priester wijden',
      definition: 'met religieuze handelingen zegenen',
      translation: 'освячувати, присвятити',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '0czbk',
    created: 1737017725556,
    data: {
      language: 'nl',
      source: 'verantwoorden',
      ipa: 'vərˈɑntwordə(n)',
      example: 'je keuze verantwoorden',
      definition: 'vertellen waarom iets verantwoord is',
      translation: 'виправдовувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wIanw',
    created: 1737017753607,
    data: {
      language: 'nl',
      source: 'verwaarlozen',
      ipa: "vər'warlozə(n)",
      example: 'je gezondheid verwaarlozen',
      definition: 'te weinig aandacht besteden aan',
      translation: 'ігнорувати, не звертати уваги',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tsGDA',
    created: 1737017781982,
    data: {
      language: 'nl',
      source: 'overtuigen',
      ipa: 'ovərˈtœyxə(n)',
      example: 'overtuigend bewijs',
      definition:
        'met argumenten bereiken dat (iemand) gelooft dat iets is zoals je het voorstelt',
      translation: 'переконати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PsKDe',
    created: 1737017801152,
    data: {
      language: 'nl',
      source: 'geleidelijk',
      ipa: 'xəˈlɛidələk',
      example: 'Geleidelijk aan is hij grijs geworden.',
      definition: 'langzaam steeds meer',
      translation: 'поступово',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ke8Zr',
    created: 1737017837091,
    data: {
      language: 'nl',
      source: 'impliciet',
      ipa: 'ɪmpliˈsit',
      example:
        'door extra aardig te zijn impliciet toegeven dat je daarnet onaardig was',
      definition: 'als iets zo is maar niet gezegd wordt',
      translation: 'неявний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JSqmu',
    created: 1737017873473,
    data: {
      language: 'nl',
      source: 'opmerkelijk',
      ipa: 'ɔpˈmɛrkələk',
      example:
        'De snel groeiende belangstelling voor de golfsport is een opmerkelijk verschijnsel.',
      definition: 'opvallend',
      translation: 'Чудово',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'S8UMW',
    created: 1737017901382,
    data: {
      language: 'nl',
      source: 'de prompt',
      ipa: 'prɔmt',
      example: '',
      definition:
        'teken of tekenreeks op een beeldscherm dat aangeeft dat de gebruiker iets moet doen',
      translation: 'підказка',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8Ay6O',
    created: 1737017911731,
    data: {
      language: 'nl',
      source: 'ongeveer',
      ipa: 'ɔnxəˈver',
      example: 'ongeveer een meter',
      definition: 'niet precies',
      translation: 'приблизно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GX4pU',
    created: 1737017939622,
    data: {
      language: 'nl',
      source: 'voldoende',
      ipa: "vɔl'dundə",
      example: 'We hebben je voldoende gewaarschuwd.',
      definition: 'zo veel, zo goed enz. als nodig is',
      translation: 'достатньо',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7VWW5',
    created: 1737017967393,
    data: {
      language: 'nl',
      source: 'de volharding',
      ipa: "vɔl'hɑrdɪŋ",
      example:
        'Hij heeft zijn succes te danken aan zijn enthousiasme en volhardendheid.',
      definition: 'het standvastig of koppig volhouden wat je begonnen bent',
      translation: 'наполегливість',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cpY4S',
    created: 1737018003878,
    data: {
      language: 'nl',
      source: 'uitgebreid',
      ipa: "'œytxəbrɛit",
      example: 'een uitgebreid weerbericht',
      definition: 'met een grote omvang of duur',
      translation: 'широкий, розширений, екстенсивний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'u8i0Q',
    created: 1737018017500,
    data: {
      language: 'nl',
      source: 'verrukkelijk',
      ipa: 'vərˈʏkələk',
      example: 'een verrukkelijke smaak',
      definition: 'heel erg lekker',
      translation: 'смачний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9LzRi',
    created: 1737018045091,
    data: {
      language: 'nl',
      source: 'voorzichtig',
      ipa: "vor'zɪxtəx",
      example: 'Wees voorzichtig!',
      definition:
        'waarbij je goed oplet en ervoor zorgt dat er geen onaangename dingen gebeuren',
      translation: 'обережний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lg8zv',
    created: 1737018073815,
    data: {
      language: 'nl',
      source: 'huiverig',
      ipa: 'ˈhœyvərəx',
      example: 'Veel consumenten zijn nog huiverig om kunstvlees te kopen.',
      definition: 'als je een beetje bang bent om iets te doen',
      translation: 'обережний, тремтячий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mDU17',
    created: 1737018088258,
    data: {
      language: 'nl',
      source: 'significant',
      ipa: "'sɪxnifikɑnt",
      example:
        '* Bij een meetwaarde is het eerste cijfer van het getal het meest significant.\n* Uit een statistische toets blijkt dat het resultaat significant is.',
      definition: '* van groot belang\n* statistisch niet op toeval berustend',
      translation: 'значний, істотний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
