import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'xlEC9',
    created: 1737076672647,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: 'ɪntəgɾɪˈteːt',
      example: 'Han har stor integritet i fagmiljøet.',
      definition: 'selvstendighet, ukrenkelighet, anseelse',
      translation: 'Integrität, Ansehen',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'vnXVO',
    created: 1737076673561,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'Widerstandskraft',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'R-MXA',
    created: 1737076683194,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: "'tæʃkəl",
      example:
        '* Leiligheten har ingen høye terskler.\n* heve terskelen for noe\n* terskelen ved Drøbak',
      definition:
        '* tre i bunnen av dørkarm, dørstokk\n* grense, overgang\n* forhøyning under vann',
      translation: 'Schwelle, Türschwelle, Fjordschwelle',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '8wQwR',
    created: 1737076692806,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: 'dɪspusɪˈʃuːn',
      example:
        '* sette opp en disposisjon\n* ha midler til disposisjon\n* ha disposisjon for visse sykdommer',
      definition:
        '* plan for ordning av innhold i en skriftlig fremstilling\n* rådighet\n* mottakelighet, anlegg',
      translation: 'Gliederung, Verfügung, Anfälligkeit',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0PaEY',
    created: 1737076702477,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nachwirkung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iLxxQ',
    created: 1737076712211,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: "'ʉːtfɑl",
      example: '* gjøre et utfall\n* Hva ble utfallet av diskusjonen?',
      definition: '* rask bevegelse; angrep\n* resultat',
      translation: 'Ausfall, Angriff, Ausgang, Ergebnis',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-y7q-',
    created: 1737076722241,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: 'bəˈkɾeftə',
      example: 'bekrefte et rykte',
      definition: 'gi svaret ja på',
      translation: 'bestätigen, bekräftigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ifVeo',
    created: 1737076732134,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: 'ʋʉɾˈdeːɾə',
      example: '* vurdere situasjonen\n* vurdere å gjøre noe',
      definition: '* bedømme; klassifisere\n* overveie',
      translation:
        'beurteilen, bewerten, (ein)schätzen, in Erwägung ziehen, erwägen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Gb87l',
    created: 1737076741873,
    data: {
      language: 'no',
      source: 'vie',
      ipa: "'ʋiːə",
      example: '* vie noen til prest\n* vie livet sitt til noe\n* vie et par',
      definition:
        '* innvie\n* bruke; konsentrere; vise, ofre\n* forene i ekteskap',
      translation: 'weihen, widmen, trauen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'gyvQ9',
    created: 1737076742866,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtfertigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NKeSj',
    created: 1737076752575,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: 'ˈfɔɾsɔməɾ',
      example: '',
      definition: 'når våren går over til sommer',
      translation: '@@@@@',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'frdSE',
    created: 1737076762327,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: "'oːʋəɾtɑːlə",
      example: 'Hun ble overtalt til å bli med.',
      definition: 'snakke noen til en annen mening',
      translation: 'überreden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WYiyl',
    created: 1737076771959,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: "'gɾɑːdʋiːs",
      example: 'en gradvis tilvenning',
      definition: 'som endres litt etter litt',
      translation: 'schrittweise, allmählich',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LZL8n',
    created: 1737076781765,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: 'ɪmplɪˈsit',
      example: 'Kommentaren var en implisitt kritikk.',
      definition: 'indirekte uttrykt, underforstått, mots. eksplisitt',
      translation: 'implizit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dYO2y',
    created: 1737076791456,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: 'spəsɪˈelt',
      example: 'Jeg husker spesielt vårt første møte.',
      definition: 'som skiller seg ut, særlig',
      translation: 'besonders, vor allem',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'o5Wru',
    created: 1737076801615,
    data: {
      language: 'no',
      source: 'rask',
      ipa: 'ɾɑsk',
      example: '* en rask bil\n* Han er rask tross alderen.',
      definition: '* hurtig, snar\n* sunn, frisk',
      translation: 'schnell, gesund',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pjNvB',
    created: 1737076802514,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: "ɔm'tɾent",
      example: 'Vi kom omtrent samtidig.',
      definition: 'om lag, cirka, nesten',
      translation: 'ungefähr, etwa',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CscdE',
    created: 1737076812309,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: "tɪl'stɾekəlɪ",
      example: 'ha tilstrekkelig mengde av noe',
      definition: 'nok, så mye en trenger',
      translation: 'hinreichend, ausreichend, genügend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'g8Rss',
    created: 1737076822056,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: "'ʋeːdʋɑːɾə",
      example: 'en vedvarende kiming',
      definition: 'vare ved, fortsette',
      translation: 'anhaltend, andauernd',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tvCux',
    created: 1737076831838,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: "'ɔmfɑtənə",
      example: 'omfattende skader',
      definition: 'betydelig, grundig',
      translation: 'umfassend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'BdfPH',
    created: 1737076841668,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: 'ˈhæːɾlɪ',
      example: '* en herlig dag\n* en herlig blanding av ulike mennesker',
      definition: '* fortreffelig, glimrende\n* skikkelig, ordentlig',
      translation: 'herrlich, großartig, wunderbar',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'VSwBY',
    created: 1737076852559,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: 'fɔɾˈsiktɪ',
      example: 'komme med noen forsiktige påstander',
      definition: 'varsom, skånsom',
      translation: 'vorsichtig, zurückhaltend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kdXz4',
    created: 1737076862264,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: "'muːtʋilɪ",
      example: 'komme med en motvillig innrømmelse',
      definition: 'uten lyst, motstrebende',
      translation: 'widerwillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ivZ9s',
    created: 1737076863470,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: "bə'tyːdəlɪ",
      example: 'et betydelig beløp',
      definition: 'som er av en viss størrelse',
      translation: 'bedeutend, beachtlich',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
