import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Yu2rL',
    created: 1737076016190,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: 'ɪntəgɾɪˈteːt',
      example: 'Han har stor integritet i fagmiljøet.',
      definition: 'selvstendighet, ukrenkelighet, anseelse',
      translation: 'integrity',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'rY7O5',
    created: 1737076026045,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resilience',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nxTcp',
    created: 1737076035702,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: "'tæʃkəl",
      example:
        '* Leiligheten har ingen høye terskler.\n* heve terskelen for noe\n* terskelen ved Drøbak',
      definition:
        '* tre i bunnen av dørkarm, dørstokk\n* grense, overgang\n* forhøyning under vann',
      translation: 'threshold, shelf',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2YOKi',
    created: 1737076045608,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: 'dɪspusɪˈʃuːn',
      example:
        '* sette opp en disposisjon\n* ha midler til disposisjon\n* ha disposisjon for visse sykdommer',
      definition:
        '* plan for ordning av innhold i en skriftlig fremstilling\n* rådighet\n* mottakelighet, anlegg',
      translation: 'outline, plan, disposal, disposition, susceptible',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DqRkB',
    created: 1737076055283,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aftereffect',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PPvpc',
    created: 1737076064915,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: "'ʉːtfɑl",
      example: '* gjøre et utfall\n* Hva ble utfallet av diskusjonen?',
      definition: '* rask bevegelse; angrep\n* resultat',
      translation: 'lunge, attack, result, outcome',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '76yb2',
    created: 1737076075475,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: 'bəˈkɾeftə',
      example: 'bekrefte et rykte',
      definition: 'gi svaret ja på',
      translation: 'to confirm',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-7Sxm',
    created: 1737076085136,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: 'ʋʉɾˈdeːɾə',
      example: '* vurdere situasjonen\n* vurdere å gjøre noe',
      definition: '* bedømme; klassifisere\n* overveie',
      translation: 'to evaluate, to assess, to consider',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-z6jv',
    created: 1737076086066,
    data: {
      language: 'no',
      source: 'vie',
      ipa: "'ʋiːə",
      example: '* vie noen til prest\n* vie livet sitt til noe\n* vie et par',
      definition:
        '* innvie\n* bruke; konsentrere; vise, ofre\n* forene i ekteskap',
      translation: 'to consecrate, to dedicate, to devote, to marry, to wed',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fc3fc',
    created: 1737076095838,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'justify',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7bhRM',
    created: 1737076105804,
    data: {
      language: 'no',
      source: 'forsømme',
      ipa: 'fɔɾˈsœmə',
      example: 'forsømme sine plikter',
      definition: 'unnlate å gjøre el. ta seg av',
      translation: 'to neglect',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hdoKn',
    created: 1737076115539,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: "'oːʋəɾtɑːlə",
      example: 'Hun ble overtalt til å bli med.',
      definition: 'snakke noen til en annen mening',
      translation: 'to convince, persuade',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'VbFHk',
    created: 1737076126382,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: "'gɾɑːdʋiːs",
      example: 'en gradvis tilvenning',
      definition: 'som endres litt etter litt',
      translation: 'gradual, gradually',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'kjvMn',
    created: 1737076136316,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: 'ɪmplɪˈsit',
      example: 'Kommentaren var en implisitt kritikk.',
      definition: 'indirekte uttrykt, underforstått, mots. eksplisitt',
      translation: 'implicit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ekobk',
    created: 1737076137314,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: 'spəsɪˈelt',
      example: 'Jeg husker spesielt vårt første møte.',
      definition: 'som skiller seg ut, særlig',
      translation: 'especially, particularly',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ERLzA',
    created: 1737076147137,
    data: {
      language: 'no',
      source: 'rask',
      ipa: 'ɾɑsk',
      example: '* en rask bil\n* Han er rask tross alderen.',
      definition: '* hurtig, snar\n* sunn, frisk',
      translation: 'quick, fast, healthy, fit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'u9YH0',
    created: 1737076157587,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: "ɔm'tɾent",
      example: 'Vi kom omtrent samtidig.',
      definition: 'om lag, cirka, nesten',
      translation: 'about, around, approximately',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0tACZ',
    created: 1737076167612,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: "tɪl'stɾekəlɪ",
      example: 'ha tilstrekkelig mengde av noe',
      definition: 'nok, så mye en trenger',
      translation: 'adequate, sufficient',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'AUOdi',
    created: 1737076179097,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: "'ʋeːdʋɑːɾə",
      example: 'en vedvarende kiming',
      definition: 'vare ved, fortsette',
      translation: 'to last, to continue',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WbTi_',
    created: 1737076188869,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: "'ɔmfɑtənə",
      example: 'omfattende skader',
      definition: 'betydelig, grundig',
      translation: 'comprehensive, extensive',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '81eS5',
    created: 1737076189779,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: 'ˈhæːɾlɪ',
      example: '* en herlig dag\n* en herlig blanding av ulike mennesker',
      definition: '* fortreffelig, glimrende\n* skikkelig, ordentlig',
      translation: 'wonderful, excellent, lovely, good',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hL0lU',
    created: 1737076199675,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: 'fɔɾˈsiktɪ',
      example: 'komme med noen forsiktige påstander',
      definition: 'varsom, skånsom',
      translation: 'careful',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jB_H7',
    created: 1737076209460,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: "'muːtʋilɪ",
      example: 'komme med en motvillig innrømmelse',
      definition: 'uten lyst, motstrebende',
      translation: 'reluctant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'OnKHk',
    created: 1737076221217,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: "bə'tyːdəlɪ",
      example: 'et betydelig beløp',
      definition: 'som er av en viss størrelse',
      translation: 'significant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
