import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '06d7A',
    created: 1737088345957,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: 'ɪntəgɾɪˈteːt',
      example: 'Han har stor integritet i fagmiljøet.',
      definition: 'selvstendighet, ukrenkelighet, anseelse',
      translation: 'интегритет',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'G4WoC',
    created: 1737088355581,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қарсылық күші',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'FhQSA',
    created: 1737088365314,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: "'tæʃkəl",
      example:
        '* Leiligheten har ingen høye terskler.\n* heve terskelen for noe\n* terskelen ved Drøbak',
      definition:
        '* tre i bunnen av dørkarm, dørstokk\n* grense, overgang\n* forhøyning under vann',
      translation: 'шек',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dI_ew',
    created: 1737088374936,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: 'dɪspusɪˈʃuːn',
      example:
        '* sette opp en disposisjon\n* ha midler til disposisjon\n* ha disposisjon for visse sykdommer',
      definition:
        '* plan for ordning av innhold i en skriftlig fremstilling\n* rådighet\n* mottakelighet, anlegg',
      translation: 'тұжырымдама',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '94yZj',
    created: 1737088384559,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'салдар',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'axZx_',
    created: 1737088402913,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: "'ʉːtfɑl",
      example: '* gjøre et utfall\n* Hva ble utfallet av diskusjonen?',
      definition: '* rask bevegelse; angrep\n* resultat',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zFNjA',
    created: 1737088421182,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: 'bəˈkɾeftə',
      example: 'bekrefte et rykte',
      definition: 'gi svaret ja på',
      translation: 'растау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'v6m28',
    created: 1737088431656,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: 'ʋʉɾˈdeːɾə',
      example: '* vurdere situasjonen\n* vurdere å gjøre noe',
      definition: '* bedømme; klassifisere\n* overveie',
      translation: 'бағалау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qmAkJ',
    created: 1737088432811,
    data: {
      language: 'no',
      source: 'vie',
      ipa: "'ʋiːə",
      example: '* vie noen til prest\n* vie livet sitt til noe\n* vie et par',
      definition:
        '* innvie\n* bruke; konsentrere; vise, ofre\n* forene i ekteskap',
      translation: 'неке',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ss2Yg',
    created: 1737088443003,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'әділеттілікпен түсіндіру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fKaJa',
    created: 1737088453084,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: 'ˈfɔɾsɔməɾ',
      example: '',
      definition: 'når våren går over til sommer',
      translation: 'жаздың басы',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LO-tY',
    created: 1737088471510,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: "'oːʋəɾtɑːlə",
      example: 'Hun ble overtalt til å bli med.',
      definition: 'snakke noen til en annen mening',
      translation: 'сендіру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'UOvL4',
    created: 1737088481150,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: "'gɾɑːdʋiːs",
      example: 'en gradvis tilvenning',
      definition: 'som endres litt etter litt',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'fOhIg',
    created: 1737088491032,
    data: {
      language: 'no',
      source: 'имплицитті',
      ipa: '',
      example: '',
      definition: '',
      translation: 'имплицитті',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_afmY',
    created: 1737088501311,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: 'spəsɪˈelt',
      example: 'Jeg husker spesielt vårt første møte.',
      definition: 'som skiller seg ut, særlig',
      translation: 'ерекше',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'u6W6h',
    created: 1737088502615,
    data: {
      language: 'no',
      source: 'rask',
      ipa: 'ɾɑsk',
      example: '* en rask bil\n* Han er rask tross alderen.',
      definition: '* hurtig, snar\n* sunn, frisk',
      translation: 'жылдам',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Z35s1',
    created: 1737088512430,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: "ɔm'tɾent",
      example: 'Vi kom omtrent samtidig.',
      definition: 'om lag, cirka, nesten',
      translation: 'шамамен',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'z-YiU',
    created: 1737088522345,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: "tɪl'stɾekəlɪ",
      example: 'ha tilstrekkelig mengde av noe',
      definition: 'nok, så mye en trenger',
      translation: 'жеткілікті',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jt8Jk',
    created: 1737088532460,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: "'ʋeːdʋɑːɾə",
      example: 'en vedvarende kiming',
      definition: 'vare ved, fortsette',
      translation: 'сақтау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'V9pNI',
    created: 1737088542432,
    data: {
      language: 'no',
      source: 'омфaттeнде',
      ipa: '',
      example: '',
      definition: '',
      translation: 'кең ауқымды',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'r4y2b',
    created: 1737088552293,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: 'ˈhæːɾlɪ',
      example: '* en herlig dag\n* en herlig blanding av ulike mennesker',
      definition: '* fortreffelig, glimrende\n* skikkelig, ordentlig',
      translation: 'керемет',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'azn9Z',
    created: 1737088553292,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: 'fɔɾˈsiktɪ',
      example: 'komme med noen forsiktige påstander',
      definition: 'varsom, skånsom',
      translation: 'сақ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'o3wOw',
    created: 1737088563013,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: "'muːtʋilɪ",
      example: 'komme med en motvillig innrømmelse',
      definition: 'uten lyst, motstrebende',
      translation: 'қарсылық білдіретін',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'IawoI',
    created: 1737088572777,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: "bə'tyːdəlɪ",
      example: 'et betydelig beløp',
      definition: 'som er av en viss størrelse',
      translation: 'маңызды',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
