import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'SS4tg',
    created: 1737080403241,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: 'ɪntəgɾɪˈteːt',
      example: 'Han har stor integritet i fagmiljøet.',
      definition: 'selvstendighet, ukrenkelighet, anseelse',
      translation: 'integriteit',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9n3Ls',
    created: 1737080413286,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'weerstandskracht',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'DDrNq',
    created: 1737080423887,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: "'tæʃkəl",
      example:
        '* Leiligheten har ingen høye terskler.\n* heve terskelen for noe\n* terskelen ved Drøbak',
      definition:
        '* tre i bunnen av dørkarm, dørstokk\n* grense, overgang\n* forhøyning under vann',
      translation: 'drempel, grens, verhoging',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NNOi8',
    created: 1737080443556,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: 'dɪspusɪˈʃuːn',
      example:
        '* sette opp en disposisjon\n* ha midler til disposisjon\n* ha disposisjon for visse sykdommer',
      definition:
        '* plan for ordning av innhold i en skriftlig fremstilling\n* rådighet\n* mottakelighet, anlegg',
      translation: 'opzet, beschikking, ontvankelijkheid',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '-eKo7',
    created: 1737080453085,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nasleep',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zVF0j',
    created: 1737080472751,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: "'ʉːtfɑl",
      example: '* gjøre et utfall\n* Hva ble utfallet av diskusjonen?',
      definition: '* rask bevegelse; angrep\n* resultat',
      translation: 'aanval, resultaat',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'hcC7C',
    created: 1737080492438,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: 'bəˈkɾeftə',
      example: 'bekrefte et rykte',
      definition: 'gi svaret ja på',
      translation: 'bevestigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qAWWe',
    created: 1737080511579,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: 'ʋʉɾˈdeːɾə',
      example: '* vurdere situasjonen\n* vurdere å gjøre noe',
      definition: '* bedømme; klassifisere\n* overveie',
      translation: 'beoordelen, overwegen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LlVzl',
    created: 1737080531769,
    data: {
      language: 'no',
      source: 'vie',
      ipa: "'ʋiːə",
      example: '* vie noen til prest\n* vie livet sitt til noe\n* vie et par',
      definition:
        '* innvie\n* bruke; konsentrere; vise, ofre\n* forene i ekteskap',
      translation: 'wijden, huwen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uyOtS',
    created: 1737080541744,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'rechtvaardigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'qpcWK',
    created: 1737080561841,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: 'ˈfɔɾsɔməɾ',
      example: '',
      definition: 'når våren går over til sommer',
      translation: 'vroege zomer',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'R9dKy',
    created: 1737080581208,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: "'oːʋəɾtɑːlə",
      example: 'Hun ble overtalt til å bli med.',
      definition: 'snakke noen til en annen mening',
      translation: 'overtuigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iXTO8',
    created: 1737080600548,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: "'gɾɑːdʋiːs",
      example: 'en gradvis tilvenning',
      definition: 'som endres litt etter litt',
      translation: 'geleidelijk',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'uA9U9',
    created: 1737080636802,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: 'ɪmplɪˈsit',
      example: 'Kommentaren var en implisitt kritikk.',
      definition: 'indirekte uttrykt, underforstått, mots. eksplisitt',
      translation: 'impliciet',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Wnj75',
    created: 1737080672929,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: 'spəsɪˈelt',
      example: 'Jeg husker spesielt vårt første møte.',
      definition: 'som skiller seg ut, særlig',
      translation: 'bijzonder, speciaal',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'auO6K',
    created: 1737080692458,
    data: {
      language: 'no',
      source: 'rask',
      ipa: 'ɾɑsk',
      example: '* en rask bil\n* Han er rask tross alderen.',
      definition: '* hurtig, snar\n* sunn, frisk',
      translation: 'snel, gezond',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'bJ81j',
    created: 1737080720675,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: "ɔm'tɾent",
      example: 'Vi kom omtrent samtidig.',
      definition: 'om lag, cirka, nesten',
      translation: 'ongeveer',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WdZCb',
    created: 1737080739719,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: "tɪl'stɾekəlɪ",
      example: 'ha tilstrekkelig mengde av noe',
      definition: 'nok, så mye en trenger',
      translation: 'voldoende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'xSF61',
    created: 1737080759179,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: "'ʋeːdʋɑːɾə",
      example: 'en vedvarende kiming',
      definition: 'vare ved, fortsette',
      translation: 'voortduren',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2Uu7n',
    created: 1737080778519,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: "'ɔmfɑtənə",
      example: 'omfattende skader',
      definition: 'betydelig, grundig',
      translation: 'omvattend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5uiz4',
    created: 1737080806793,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: 'ˈhæːɾlɪ',
      example: '* en herlig dag\n* en herlig blanding av ulike mennesker',
      definition: '* fortreffelig, glimrende\n* skikkelig, ordentlig',
      translation: 'heerlijk, prachtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'O6Au4',
    created: 1737080834936,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: 'fɔɾˈsiktɪ',
      example: 'komme med noen forsiktige påstander',
      definition: 'varsom, skånsom',
      translation: 'voorzichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '37rzw',
    created: 1737080851478,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: "'muːtʋilɪ",
      example: 'komme med en motvillig innrømmelse',
      definition: 'uten lyst, motstrebende',
      translation: 'tegenstribbelend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'V0HQ6',
    created: 1737080870590,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: "bə'tyːdəlɪ",
      example: 'et betydelig beløp',
      definition: 'som er av en viss størrelse',
      translation: 'aanzienlijk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
