import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8xlR5',
    created: 1737078645045,
    data: {
      language: 'no',
      source: 'en integritet',
      ipa: 'ɪntəgɾɪˈteːt',
      example: 'Han har stor integritet i fagmiljøet.',
      definition: 'selvstendighet, ukrenkelighet, anseelse',
      translation: 'целостность, независимость',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'dPYRa',
    created: 1737078655084,
    data: {
      language: 'no',
      source: 'motstandskraft',
      ipa: '',
      example: '',
      definition: '',
      translation: 'устойчивость',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jtSwz',
    created: 1737078683386,
    data: {
      language: 'no',
      source: 'en terskel',
      ipa: "'tæʃkəl",
      example:
        '* Leiligheten har ingen høye terskler.\n* heve terskelen for noe\n* terskelen ved Drøbak',
      definition:
        '* tre i bunnen av dørkarm, dørstokk\n* grense, overgang\n* forhøyning under vann',
      translation: 'порог, граница, подъем',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5yTj0',
    created: 1737078711343,
    data: {
      language: 'no',
      source: 'en disposisjon',
      ipa: 'dɪspusɪˈʃuːn',
      example:
        '* sette opp en disposisjon\n* ha midler til disposisjon\n* ha disposisjon for visse sykdommer',
      definition:
        '* plan for ordning av innhold i en skriftlig fremstilling\n* rådighet\n* mottakelighet, anlegg',
      translation: 'план, распоряжение, восприятие',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SzhyG',
    created: 1737078712323,
    data: {
      language: 'no',
      source: 'ettervirkning',
      ipa: '',
      example: '',
      definition: '',
      translation: 'последствие',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CV0zR',
    created: 1737078731421,
    data: {
      language: 'no',
      source: 'et utfall',
      ipa: "'ʉːtfɑl",
      example: '* gjøre et utfall\n* Hva ble utfallet av diskusjonen?',
      definition: '* rask bevegelse; angrep\n* resultat',
      translation: 'атакующее движение, результат',
      partOfSpeech: 'noun',
      g: 'n',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'keVUE',
    created: 1737078759452,
    data: {
      language: 'no',
      source: 'bekrefte',
      ipa: 'bəˈkɾeftə',
      example: 'bekrefte et rykte',
      definition: 'gi svaret ja på',
      translation: 'подтверждать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '5seeQ',
    created: 1737078796274,
    data: {
      language: 'no',
      source: 'vurdere',
      ipa: 'ʋʉɾˈdeːɾə',
      example: '* vurdere situasjonen\n* vurdere å gjøre noe',
      definition: '* bedømme; klassifisere\n* overveie',
      translation: 'оценивать, рассматривать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'S03S3',
    created: 1737078806983,
    data: {
      language: 'no',
      source: 'vie',
      ipa: "'ʋiːə",
      example: '* vie noen til prest\n* vie livet sitt til noe\n* vie et par',
      definition:
        '* innvie\n* bruke; konsentrere; vise, ofre\n* forene i ekteskap',
      translation: 'освятить, обручить, женить',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iZ9-i',
    created: 1737078816777,
    data: {
      language: 'no',
      source: 'rettferdiggjøre',
      ipa: '',
      example: '',
      definition: '',
      translation: 'оправдывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'YAwZb',
    created: 1737078844467,
    data: {
      language: 'no',
      source: 'en forsommer',
      ipa: 'ˈfɔɾsɔməɾ',
      example: '',
      definition: 'når våren går over til sommer',
      translation: 'начало лета',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'iNz_d',
    created: 1737078863613,
    data: {
      language: 'no',
      source: 'overtale',
      ipa: "'oːʋəɾtɑːlə",
      example: 'Hun ble overtalt til å bli med.',
      definition: 'snakke noen til en annen mening',
      translation: 'уговорить',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '2mZFw',
    created: 1737078900563,
    data: {
      language: 'no',
      source: 'gradvis',
      ipa: "'gɾɑːdʋiːs",
      example: 'en gradvis tilvenning',
      definition: 'som endres litt etter litt',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '9x3fL',
    created: 1737078911115,
    data: {
      language: 'no',
      source: 'implisitt',
      ipa: 'ɪmplɪˈsit',
      example: 'Kommentaren var en implisitt kritikk.',
      definition: 'indirekte uttrykt, underforstått, mots. eksplisitt',
      translation: 'неявный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'A_cPY',
    created: 1737078947913,
    data: {
      language: 'no',
      source: 'spesielt',
      ipa: 'spəsɪˈelt',
      example: 'Jeg husker spesielt vårt første møte.',
      definition: 'som skiller seg ut, særlig',
      translation: 'особенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'cIdyj',
    created: 1737078967106,
    data: {
      language: 'no',
      source: 'rask',
      ipa: 'ɾɑsk',
      example: '* en rask bil\n* Han er rask tross alderen.',
      definition: '* hurtig, snar\n* sunn, frisk',
      translation: 'быстрый, здоровый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '3sdDB',
    created: 1737078995510,
    data: {
      language: 'no',
      source: 'omtrent',
      ipa: "ɔm'tɾent",
      example: 'Vi kom omtrent samtidig.',
      definition: 'om lag, cirka, nesten',
      translation: 'примерно, около',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'H884o',
    created: 1737079006056,
    data: {
      language: 'no',
      source: 'tilstrekkelig',
      ipa: "tɪl'stɾekəlɪ",
      example: 'ha tilstrekkelig mengde av noe',
      definition: 'nok, så mye en trenger',
      translation: 'достаточный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7LQf8',
    created: 1737079034316,
    data: {
      language: 'no',
      source: 'vedvare',
      ipa: "'ʋeːdʋɑːɾə",
      example: 'en vedvarende kiming',
      definition: 'vare ved, fortsette',
      translation: 'продолжать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'sBiIU',
    created: 1737079062681,
    data: {
      language: 'no',
      source: 'omfattende',
      ipa: "'ɔmfɑtənə",
      example: 'omfattende skader',
      definition: 'betydelig, grundig',
      translation: 'обширный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'jRBYC',
    created: 1737079090604,
    data: {
      language: 'no',
      source: 'herlig',
      ipa: 'ˈhæːɾlɪ',
      example: '* en herlig dag\n* en herlig blanding av ulike mennesker',
      definition: '* fortreffelig, glimrende\n* skikkelig, ordentlig',
      translation: 'прекрасный, замечательный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'R460y',
    created: 1737079118629,
    data: {
      language: 'no',
      source: 'forsiktig',
      ipa: 'fɔɾˈsiktɪ',
      example: 'smile forsiktig til hverandre',
      definition: 'på en varsom måte, tilbakeholdent',
      translation: 'осторожно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '7iZkt',
    created: 1737079142337,
    data: {
      language: 'no',
      source: 'motvillig',
      ipa: "'muːtʋilɪ",
      example: 'komme med en motvillig innrømmelse',
      definition: 'uten lyst, motstrebende',
      translation: 'неохотно',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '6fx5z',
    created: 1737079152691,
    data: {
      language: 'no',
      source: 'betydelig',
      ipa: "bə'tyːdəlɪ",
      example: 'et betydelig beløp',
      definition: 'som er av en viss størrelse',
      translation: 'значительный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
