import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'XjSOA',
    created: 1736977372261,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: "ĩtəgri'dadə",
      example: 'a integridade dos juízes',
      definition: 'honestidade, rectidão',
      translation: 'integridad',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VqKi0',
    created: 1736977373271,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resiliencia',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AhZi3',
    created: 1736977375313,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: "li'mitə",
      example:
        '* os limites de um território\n* É o prazo limite para entrega do trabalho.\n* A paciência tem limites.',
      definition:
        '* linha que separa dois países, terrenos\n* termo de tempo\n* ponto que não se deve ultrapassar',
      translation: 'límite, plazo, punto de no retorno',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KT3mt',
    created: 1736977376599,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: "dəʃpuzi'sɐ̃w",
      example:
        '* a disposição dos móveis\n* estar comboa /má disposição\n* estar na disposição de fazer algo',
      definition: '* arranjo\n* estado de espírito\n* aceitar fazer algo',
      translation: 'disposición, estado de ánimo, disposición a hacer algo',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3tdPl',
    created: 1736977378535,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: "ʀəpərku'sɐ̃w",
      example:
        '* a repercussão de um som pelo eco\n* A subida dos preços tem repercussões sobre a economia.',
      definition: '* acto de reflectir, um som ou luz\n* efeito, consequência',
      translation: 'repercusión, efecto',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Q2Mjy',
    created: 1736977380558,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: "ʀəzul'tadu",
      example:
        '* o resultado de uma acção\n* o resultado do jogo\n* o resultado da soma',
      definition:
        '* consequência, efeito\n* situação final de uma competição\n* solução de um cálculo',
      translation: 'resultado, consecuencia, solución',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vMKE_',
    created: 1736977382946,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: "ʀəkuɲə'ser",
      example:
        '* reconhecer um antigo amigo\n* reconhecer os seus erros\n* reconhecer a autoridade dos pais',
      definition:
        '* identificar algo ou alguém que se conhece\n* admitir, confessar\n* admitir, aceitar',
      translation: 'reconocer, admitir, aceptar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wQvIL',
    created: 1736977384152,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: "kõsidə'rar",
      example: 'considerar os prós e os contras',
      definition: 'pensar, julgar',
      translation: 'considerar, pensar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S4hHS',
    created: 1736977385607,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: "dədi'kar",
      example: 'dedicar um poema aos pais',
      definition: 'oferecer',
      translation: 'dedicar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vxubG',
    created: 1736977387070,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: "ʒuʃtifi'kar",
      example: 'justificar os seus actos',
      definition: 'apresentar um motivo ou explicação',
      translation: 'justificar, dar razón',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0Mpr5',
    created: 1736977388298,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: "nəgli'ʒẽsjɐ",
      example: '',
      definition: 'falta de cuidado',
      translation: 'negligencia',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Su3_i',
    created: 1736977389550,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: "pərsuɐ'dir",
      example: 'persuadir alguém de algo',
      definition: 'convencer',
      translation: 'persuadir, convencer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9kb8D',
    created: 1736977390873,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: "grɐdwal'mẽtə",
      example: 'deixar de fumar gradualmente',
      definition: 'progressivamente',
      translation: 'gradualmente, progresivamente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fBZAg',
    created: 1736977391714,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implícitamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd9WsC',
    created: 1736977392560,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'notablemente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FtCFs',
    created: 1736977394100,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: "'prõtɐ",
      example: '* O almoço está pronto.\n* uma resposta pronta',
      definition: '* acabado, terminado\n* rápido, imediato',
      translation: 'listo, preparado',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-tiQP',
    created: 1736977395444,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: "ɐprɔsimadɐ'mẽtə",
      example: 'uma população de aproximadamente dez milhões',
      definition: 'cerca de',
      translation: 'aproximadamente, cerca de',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vwIt0',
    created: 1736977397129,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: "sufi'sjẽtə",
      example: '* Ter dinheiro suficiente.\n* ter uma nota suficiente',
      definition: '* que basta\n* médio, razoável',
      translation: 'suficiente, razonable',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4HeEl',
    created: 1736977398585,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: "pərsiʃ'tẽtə",
      example: '* uma pessoa persistente\n* dores persistentes',
      definition: '* que não desiste facilmente\n* que dura, não acaba',
      translation: 'persistente, tenaz',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yIUTU',
    created: 1736977399548,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'abarcador',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zxW6X',
    created: 1736977401974,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: "dəli'sjozu",
      example: 'um prato delicioso',
      definition: 'muito agradável ou saboroso',
      translation: 'delicioso',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GhDn4',
    created: 1736977403881,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: "kaw'tɛlɐ",
      example: '* ter cautela com os perigos\n* comprar uma cautela',
      definition: '* cuidado\n* fracção de bilhete da lotaria',
      translation: 'cuidado, fracción de billete de lotería',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Mx7tF',
    created: 1736977405753,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: "ʀəlu'tɐ̃tə",
      example: '',
      definition: 'que resiste, hesita',
      translation: 'reacio, reticente',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4y4UG',
    created: 1736977408175,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: "signifikɐ'tivu",
      example: 'uma atitude significativa',
      definition: 'que exprime ou indica algo',
      translation: 'significativo',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
