import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'BerMz',
    created: 1736978545403,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: "ĩtəgri'dadə",
      example: 'a integridade dos juízes',
      definition: 'honestidade, rectidão',
      translation: '誠実, 正直',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UDlsE',
    created: 1736978555010,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'レジリエンス',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_H-7Z',
    created: 1736978583405,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: "li'mitə",
      example:
        '* os limites de um território\n* É o prazo limite para entrega do trabalho.\n* A paciência tem limites.',
      definition:
        '* linha que separa dois países, terrenos\n* termo de tempo\n* ponto que não se deve ultrapassar',
      translation: '境界, 期限, 限界',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'GMsUC',
    created: 1736978607164,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: "dəʃpuzi'sɐ̃w",
      example:
        '* a disposição dos móveis\n* estar comboa /má disposição\n* estar na disposição de fazer algo',
      definition: '* arranjo\n* estado de espírito\n* aceitar fazer algo',
      translation: '配置, 気分, 受け入れる',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XeFk8',
    created: 1736978617546,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: "ʀəpərku'sɐ̃w",
      example:
        '* a repercussão de um som pelo eco\n* A subida dos preços tem repercussões sobre a economia.',
      definition: '* acto de reflectir, um som ou luz\n* efeito, consequência',
      translation: '反響, 影響',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FGQJ7',
    created: 1736978646588,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: "ʀəzul'tadu",
      example:
        '* o resultado de uma acção\n* o resultado do jogo\n* o resultado da soma',
      definition:
        '* consequência, efeito\n* situação final de uma competição\n* solução de um cálculo',
      translation: '結果, 成績, 計算結果',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6Swhg',
    created: 1736978675153,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: "ʀəkuɲə'ser",
      example:
        '* reconhecer um antigo amigo\n* reconhecer os seus erros\n* reconhecer a autoridade dos pais',
      definition:
        '* identificar algo ou alguém que se conhece\n* admitir, confessar\n* admitir, aceitar',
      translation: '認識する, 認める, 受け入れる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lyOKO',
    created: 1736978688792,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: "kõsidə'rar",
      example: 'considerar os prós e os contras',
      definition: 'pensar, julgar',
      translation: '考える, 判断する, 考慮する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FreN_',
    created: 1736978708683,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: "dədi'kar",
      example: 'dedicar um poema aos pais',
      definition: 'oferecer',
      translation: '捧げる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dZCZj',
    created: 1736978727872,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: "ʒuʃtifi'kar",
      example: 'justificar os seus actos',
      definition: 'apresentar um motivo ou explicação',
      translation: '正当化する, 理由を述べる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lurU3',
    created: 1736979670948,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: "nəgli'ʒẽsjɐ",
      example: '',
      definition: 'falta de cuidado',
      translation: '怠慢, 無関心',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0Uy4y',
    created: 1736979672719,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: "pərsuɐ'dir",
      example: 'persuadir alguém de algo',
      definition: 'convencer',
      translation: '説得する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jn0cc',
    created: 1736979674469,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: "grɐdwal'mẽtə",
      example: 'deixar de fumar gradualmente',
      definition: 'progressivamente',
      translation: '徐々に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'H001G',
    created: 1736979675603,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '暗黙的に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8NII-',
    created: 1736979676324,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '顕著に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'J6ELh',
    created: 1736979678238,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: "'prõtɐ",
      example: '* O almoço está pronto.\n* uma resposta pronta',
      definition: '* acabado, terminado\n* rápido, imediato',
      translation: '完成した, 即座の',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P-VWt',
    created: 1736979679697,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: "ɐprɔsimadɐ'mẽtə",
      example: 'uma população de aproximadamente dez milhões',
      definition: 'cerca de',
      translation: '約, おおよそ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'H01UU',
    created: 1736979681196,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: "sufi'sjẽtə",
      example: '* Ter dinheiro suficiente.\n* ter uma nota suficiente',
      definition: '* que basta\n* médio, razoável',
      translation: '十分な, 適度な',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Andur',
    created: 1736979682581,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: "pərsiʃ'tẽtə",
      example: '* uma pessoa persistente\n* dores persistentes',
      definition: '* que não desiste facilmente\n* que dura, não acaba',
      translation: 'しつこい, 持続的な',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'by0G9',
    created: 1736979683321,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: '包括的な',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zb6mx',
    created: 1736979684882,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: "dəli'sjozu",
      example: 'um prato delicioso',
      definition: 'muito agradável ou saboroso',
      translation: '美味しい, おいしい',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7JYpG',
    created: 1736979686392,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: "kaw'tɛlɐ",
      example: '* ter cautela com os perigos\n* comprar uma cautela',
      definition: '* cuidado\n* fracção de bilhete da lotaria',
      translation: '注意, 宝くじの券の一部',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NLzrY',
    created: 1736979687875,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: "ʀəlu'tɐ̃tə",
      example: '',
      definition: 'que resiste, hesita',
      translation: 'ためらいがち, ためらっている',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P29EM',
    created: 1736979689800,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: "signifikɐ'tivu",
      example: 'uma atitude significativa',
      definition: 'que exprime ou indica algo',
      translation: '意味のある, 重要な',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
