import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '_NymB',
    created: 1736981901031,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: "ĩtəgri'dadə",
      example: 'a integridade dos juízes',
      definition: 'honestidade, rectidão',
      translation: '정직, 청렴',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'URuRZ',
    created: 1736981901952,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: '회복력',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dytB8',
    created: 1736981904014,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: "li'mitə",
      example:
        '* os limites de um território\n* É o prazo limite para entrega do trabalho.\n* A paciência tem limites.',
      definition:
        '* linha que separa dois países, terrenos\n* termo de tempo\n* ponto que não se deve ultrapassar',
      translation: '경계, 기한, 한계',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zPtjV',
    created: 1736981909651,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: "dəʃpuzi'sɐ̃w",
      example:
        '* a disposição dos móveis\n* estar comboa /má disposição\n* estar na disposição de fazer algo',
      definition: '* arranjo\n* estado de espírito\n* aceitar fazer algo',
      translation: '배치, 기분, 수용',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2ytqf',
    created: 1736981911578,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: "ʀəpərku'sɐ̃w",
      example:
        '* a repercussão de um som pelo eco\n* A subida dos preços tem repercussões sobre a economia.',
      definition: '* acto de reflectir, um som ou luz\n* efeito, consequência',
      translation: '반향, 영향, 파장',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tXWgt',
    created: 1736981912884,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: "ʀəzul'tadu",
      example:
        '* o resultado de uma acção\n* o resultado do jogo\n* o resultado da soma',
      definition:
        '* consequência, efeito\n* situação final de uma competição\n* solução de um cálculo',
      translation: '결과, 경기 결과, 계산 결과',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gKpbv',
    created: 1736981914392,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: "ʀəkuɲə'ser",
      example:
        '* reconhecer um antigo amigo\n* reconhecer os seus erros\n* reconhecer a autoridade dos pais',
      definition:
        '* identificar algo ou alguém que se conhece\n* admitir, confessar\n* admitir, aceitar',
      translation: '인식하다, 인정하다, 수용하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'bZN0H',
    created: 1736981916149,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: "kõsidə'rar",
      example: 'considerar os prós e os contras',
      definition: 'pensar, julgar',
      translation: '생각하다, 판단하다, 고려하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j4wOo',
    created: 1736981917799,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: "dədi'kar",
      example: 'dedicar um poema aos pais',
      definition: 'oferecer',
      translation: '바치다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j8TTG',
    created: 1736981919372,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: "ʒuʃtifi'kar",
      example: 'justificar os seus actos',
      definition: 'apresentar um motivo ou explicação',
      translation: '정당화하다, 이유를 설명하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mEUVd',
    created: 1736981921180,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: "nəgli'ʒẽsjɐ",
      example: '',
      definition: 'falta de cuidado',
      translation: '태만, 부주의',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K48W3',
    created: 1736981922818,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: "pərsuɐ'dir",
      example: 'persuadir alguém de algo',
      definition: 'convencer',
      translation: '설득하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Mx7Yh',
    created: 1736981924100,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: "grɐdwal'mẽtə",
      example: 'deixar de fumar gradualmente',
      definition: 'progressivamente',
      translation: '점진적으로',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uJQn6',
    created: 1736981928724,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: '암묵적으로',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G5tCz',
    created: 1736982831282,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: '눈에 띄게',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Y8iq4',
    created: 1736982833000,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: "'prõtɐ",
      example: '* O almoço está pronto.\n* uma resposta pronta',
      definition: '* acabado, terminado\n* rápido, imediato',
      translation: '완료된, 즉각적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8zBoU',
    created: 1736982834359,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: "ɐprɔsimadɐ'mẽtə",
      example: 'uma população de aproximadamente dez milhões',
      definition: 'cerca de',
      translation: '약, 대략',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tt8ix',
    created: 1736982835754,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: "sufi'sjẽtə",
      example: '* Ter dinheiro suficiente.\n* ter uma nota suficiente',
      definition: '* que basta\n* médio, razoável',
      translation: '충분한, 적당한',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dBxrl',
    created: 1736982837680,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: "pərsiʃ'tẽtə",
      example: '* uma pessoa persistente\n* dores persistentes',
      definition: '* que não desiste facilmente\n* que dura, não acaba',
      translation: '끈질긴, 지속적인',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'P65QA',
    created: 1736982839036,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: '포괄적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CHJ6i',
    created: 1736982840725,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: "dəli'sjozu",
      example: 'um prato delicioso',
      definition: 'muito agradável ou saboroso',
      translation: '맛있는',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8n_Ru',
    created: 1736982842149,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: "kaw'tɛlɐ",
      example: '* ter cautela com os perigos\n* comprar uma cautela',
      definition: '* cuidado\n* fracção de bilhete da lotaria',
      translation: '주의, 복권의 일부',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ULbqC',
    created: 1736982843608,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: "ʀəlu'tɐ̃tə",
      example: '',
      definition: 'que resiste, hesita',
      translation: '주저하는, 망설이는',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'U-I9v',
    created: 1736982845441,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: "signifikɐ'tivu",
      example: 'uma atitude significativa',
      definition: 'que exprime ou indica algo',
      translation: '의미 있는',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
