import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'EH53g',
    created: 1736988337110,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: "ĩtəgri'dadə",
      example: 'a integridade dos juízes',
      definition: 'honestidade, rectidão',
      translation: 'ความซื่อสัตย์',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4I8gj',
    created: 1736988338159,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความยืดหยุ่น',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MHNza',
    created: 1736988340209,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: "li'mitə",
      example:
        '* os limites de um território\n* É o prazo limite para entrega do trabalho.\n* A paciência tem limites.',
      definition:
        '* linha que separa dois países, terrenos\n* termo de tempo\n* ponto que não se deve ultrapassar',
      translation: 'เส้นแบ่ง, กำหนดเวลา, จุดที่ไม่ควรข้าม, ขีดจำกัด',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LDCIG',
    created: 1736988342008,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: "dəʃpuzi'sɐ̃w",
      example:
        '* a disposição dos móveis\n* estar comboa /má disposição\n* estar na disposição de fazer algo',
      definition: '* arranjo\n* estado de espírito\n* aceitar fazer algo',
      translation: 'การจัดเรียง, อารมณ์, ยินดี, การจัดเตรียม',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NTVrU',
    created: 1736988343828,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: "ʀəpərku'sɐ̃w",
      example:
        '* a repercussão de um som pelo eco\n* A subida dos preços tem repercussões sobre a economia.',
      definition: '* acto de reflectir, um som ou luz\n* efeito, consequência',
      translation: 'การสะท้อน, ผลกระทบ',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-xAhk',
    created: 1736988347547,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: "ʀəzul'tadu",
      example:
        '* o resultado de uma acção\n* o resultado do jogo\n* o resultado da soma',
      definition:
        '* consequência, efeito\n* situação final de uma competição\n* solução de um cálculo',
      translation: 'ผลลัพธ์, ผลการแข่งขัน, ผลการคำนวณ',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JHKdZ',
    created: 1736988349407,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: "ʀəkuɲə'ser",
      example:
        '* reconhecer um antigo amigo\n* reconhecer os seus erros\n* reconhecer a autoridade dos pais',
      definition:
        '* identificar algo ou alguém que se conhece\n* admitir, confessar\n* admitir, aceitar',
      translation: 'ระบุ, ยอมรับ, รับรู้',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'C4xzG',
    created: 1736988350710,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: "kõsidə'rar",
      example: 'considerar os prós e os contras',
      definition: 'pensar, julgar',
      translation: 'พิจารณา',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4qlfc',
    created: 1736988352087,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: "dədi'kar",
      example: 'dedicar um poema aos pais',
      definition: 'oferecer',
      translation: 'มอบให้, อุทิศ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vV0_C',
    created: 1736988354646,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: "ʒuʃtifi'kar",
      example: 'justificar os seus actos',
      definition: 'apresentar um motivo ou explicação',
      translation: 'ชี้แจง, อธิบาย',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TjF6f',
    created: 1736988356500,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: "nəgli'ʒẽsjɐ",
      example: '',
      definition: 'falta de cuidado',
      translation: 'การละเลย, ความประมาท',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QNb0E',
    created: 1736988357902,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: "pərsuɐ'dir",
      example: 'persuadir alguém de algo',
      definition: 'convencer',
      translation: 'ชักชวน, ชักจูง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TyniL',
    created: 1736988359809,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: "grɐdwal'mẽtə",
      example: 'deixar de fumar gradualmente',
      definition: 'progressivamente',
      translation: 'ทีละน้อย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ksBFC',
    created: 1736988360770,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยนัย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Wg_C3',
    created: 1736988362219,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อย่างเห็นได้ชัด',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KePYj',
    created: 1736988364467,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: "'prõtɐ",
      example: '* O almoço está pronto.\n* uma resposta pronta',
      definition: '* acabado, terminado\n* rápido, imediato',
      translation: 'เสร็จ, พร้อม',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jm33l',
    created: 1736988365913,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: "ɐprɔsimadɐ'mẽtə",
      example: 'uma população de aproximadamente dez milhões',
      definition: 'cerca de',
      translation: 'ประมาณ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XeKR9',
    created: 1736988369117,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: "sufi'sjẽtə",
      example: '* Ter dinheiro suficiente.\n* ter uma nota suficiente',
      definition: '* que basta\n* médio, razoável',
      translation: 'เพียงพอ, พอสมควร',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8tF8w',
    created: 1736988370919,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: "pərsiʃ'tẽtə",
      example: '* uma pessoa persistente\n* dores persistentes',
      definition: '* que não desiste facilmente\n* que dura, não acaba',
      translation: 'ดื้อรั้น, คงทน',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'vSrO5',
    created: 1736988371999,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ครอบคลุม',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bRAJA',
    created: 1736988373515,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: "dəli'sjozu",
      example: 'um prato delicioso',
      definition: 'muito agradável ou saboroso',
      translation: 'อร่อย',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DsEOi',
    created: 1736988376085,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: "kaw'tɛlɐ",
      example: '* ter cautela com os perigos\n* comprar uma cautela',
      definition: '* cuidado\n* fracção de bilhete da lotaria',
      translation: 'ความระมัดระวัง, ตั๋วลอตเตอรี่',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1Uw66',
    created: 1736988377311,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: "ʀəlu'tɐ̃tə",
      example: '',
      definition: 'que resiste, hesita',
      translation: 'ลังเล',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pAvTv',
    created: 1736988378956,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: "signifikɐ'tivu",
      example: 'uma atitude significativa',
      definition: 'que exprime ou indica algo',
      translation: 'มีความหมาย',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
