import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '6FY6p',
    created: 1736983842288,
    data: {
      language: 'pt',
      source: 'integridade',
      ipa: "ĩtəgri'dadə",
      example: 'a integridade dos juízes',
      definition: 'honestidade, rectidão',
      translation: 'bütünlük',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9nLvX',
    created: 1736983843171,
    data: {
      language: 'pt',
      source: 'resiliência',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dayanıklılık',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S8xbV',
    created: 1736983844988,
    data: {
      language: 'pt',
      source: 'limite',
      ipa: "li'mitə",
      example:
        '* os limites de um território\n* É o prazo limite para entrega do trabalho.\n* A paciência tem limites.',
      definition:
        '* linha que separa dois países, terrenos\n* termo de tempo\n* ponto que não se deve ultrapassar',
      translation: 'sınır, son, aşılmaması gereken nokta',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6-XCw',
    created: 1736983846681,
    data: {
      language: 'pt',
      source: 'disposição',
      ipa: "dəʃpuzi'sɐ̃w",
      example:
        '* a disposição dos móveis\n* estar comboa /má disposição\n* estar na disposição de fazer algo',
      definition: '* arranjo\n* estado de espírito\n* aceitar fazer algo',
      translation: 'düzen, ruh hali, kabul etmek, hazır olma',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Jn6Zj',
    created: 1736983848389,
    data: {
      language: 'pt',
      source: 'repercussão',
      ipa: "ʀəpərku'sɐ̃w",
      example:
        '* a repercussão de um som pelo eco\n* A subida dos preços tem repercussões sobre a economia.',
      definition: '* acto de reflectir, um som ou luz\n* efeito, consequência',
      translation: 'yansıma, etki',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '12dkq',
    created: 1736983851243,
    data: {
      language: 'pt',
      source: 'resultado',
      ipa: "ʀəzul'tadu",
      example:
        '* o resultado de uma acção\n* o resultado do jogo\n* o resultado da soma',
      definition:
        '* consequência, efeito\n* situação final de uma competição\n* solução de um cálculo',
      translation: 'sonuç, netice, hesap sonucu',
      partOfSpeech: 'noun',
      g: 'm',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QZmRF',
    created: 1736983853037,
    data: {
      language: 'pt',
      source: 'reconhecer',
      ipa: "ʀəkuɲə'ser",
      example:
        '* reconhecer um antigo amigo\n* reconhecer os seus erros\n* reconhecer a autoridade dos pais',
      definition:
        '* identificar algo ou alguém que se conhece\n* admitir, confessar\n* admitir, aceitar',
      translation: 'tanımak, kabul etmek, itiraf etmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '77yrx',
    created: 1736983854508,
    data: {
      language: 'pt',
      source: 'considerar',
      ipa: "kõsidə'rar",
      example: 'considerar os prós e os contras',
      definition: 'pensar, julgar',
      translation: 'düşünmek, değerlendirmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LbAfL',
    created: 1736983855695,
    data: {
      language: 'pt',
      source: 'dedicar',
      ipa: "dədi'kar",
      example: 'dedicar um poema aos pais',
      definition: 'oferecer',
      translation: 'sunmak, adamak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0VPZ4',
    created: 1736983857185,
    data: {
      language: 'pt',
      source: 'justificar',
      ipa: "ʒuʃtifi'kar",
      example: 'justificar os seus actos',
      definition: 'apresentar um motivo ou explicação',
      translation: 'gerekçe göstermek, haklı çıkarmak',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_ufuX',
    created: 1736983859163,
    data: {
      language: 'pt',
      source: 'negligência',
      ipa: "nəgli'ʒẽsjɐ",
      example: '',
      definition: 'falta de cuidado',
      translation: 'ihmal',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uw1rw',
    created: 1736983860844,
    data: {
      language: 'pt',
      source: 'persuadir',
      ipa: "pərsuɐ'dir",
      example: 'persuadir alguém de algo',
      definition: 'convencer',
      translation: 'ikna etmek',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'larhB',
    created: 1736983862749,
    data: {
      language: 'pt',
      source: 'gradualmente',
      ipa: "grɐdwal'mẽtə",
      example: 'deixar de fumar gradualmente',
      definition: 'progressivamente',
      translation: 'aşamalı, aşamalı olarak',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hClRK',
    created: 1736983863675,
    data: {
      language: 'pt',
      source: 'implicitamente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dolaylı olarak',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-nefe',
    created: 1736983864379,
    data: {
      language: 'pt',
      source: 'notavelmente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dikkate değer bir şekilde',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DQsb2',
    created: 1736983865847,
    data: {
      language: 'pt',
      source: 'pronta',
      ipa: "'prõtɐ",
      example: '* O almoço está pronto.\n* uma resposta pronta',
      definition: '* acabado, terminado\n* rápido, imediato',
      translation: 'hazır, çabuk',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O1Z6h',
    created: 1736983868276,
    data: {
      language: 'pt',
      source: 'aproximadamente',
      ipa: "ɐprɔsimadɐ'mẽtə",
      example: 'uma população de aproximadamente dez milhões',
      definition: 'cerca de',
      translation: 'yaklaşık, yaklaşık olarak',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'LKbUl',
    created: 1736983869864,
    data: {
      language: 'pt',
      source: 'suficiente',
      ipa: "sufi'sjẽtə",
      example: '* Ter dinheiro suficiente.\n* ter uma nota suficiente',
      definition: '* que basta\n* médio, razoável',
      translation: 'yeterli, orta',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Hg_g1',
    created: 1736983871210,
    data: {
      language: 'pt',
      source: 'persistente',
      ipa: "pərsiʃ'tẽtə",
      example: '* uma pessoa persistente\n* dores persistentes',
      definition: '* que não desiste facilmente\n* que dura, não acaba',
      translation: 'inatçı, sürekli, ısrarcı',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2-8rB',
    created: 1736984646535,
    data: {
      language: 'pt',
      source: 'abrangente',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kapsayıcı',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'm9TpF',
    created: 1736984648051,
    data: {
      language: 'pt',
      source: 'delicioso',
      ipa: "dəli'sjozu",
      example: 'um prato delicioso',
      definition: 'muito agradável ou saboroso',
      translation: 'lezzetli',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ETlen',
    created: 1736984649548,
    data: {
      language: 'pt',
      source: 'cautela',
      ipa: "kaw'tɛlɐ",
      example: '* ter cautela com os perigos\n* comprar uma cautela',
      definition: '* cuidado\n* fracção de bilhete da lotaria',
      translation: 'dikkat, lotarya kuponu',
      partOfSpeech: 'noun',
      g: 'f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'saiXm',
    created: 1736984650958,
    data: {
      language: 'pt',
      source: 'relutante',
      ipa: "ʀəlu'tɐ̃tə",
      example: '',
      definition: 'que resiste, hesita',
      translation: 'isteksiz, tereddütlü',
      partOfSpeech: 'adjective',
      g: 'm-f',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zd3xe',
    created: 1736984652720,
    data: {
      language: 'pt',
      source: 'significativo',
      ipa: "signifikɐ'tivu",
      example: 'uma atitude significativa',
      definition: 'que exprime ou indica algo',
      translation: 'anlamlı',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
