import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'iaGMj',
    created: 1737063012103,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: 'integritẹ:t',
      example:
        '* Den personliga integriteten kan hotas av FRA-lagen.\n* Klubbens ledare måste ha hög personlig integritet.',
      definition:
        '* rätt att inte bli kränkt (särskilt av myndigheter)\n* hederlighet',
      translation: 'Integrität, Achtung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WDbLR',
    created: 1737063013174,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elastizität',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JsyV-',
    created: 1737063023004,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '²trọ̈s:kel',
      example:
        '* Han stod på tröskeln in till rummet.\n* Nyåret 2010, på tröskeln till ett nytt decennium.\n* Min tröskel för smärta är ganska låg.',
      definition:
        '* upphöjd bräda på golvet i dörröppning\n* början\n* nedre gräns (för en viss effekt)',
      translation: 'Türschwelle, Beginn, Grenze, Hürde',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yJA19',
    created: 1737063032805,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: 'disposiʃọ:n',
      example:
        '* Jag behöver inte bilen på fredag, så den står till din disposition!\n* Hon skulle skriva en artikel och började med att göra en disposition.\n* Han har disposition för infektioner.',
      definition:
        '* förfogande(rätt)\n* planläggning (av skrift eller tal)\n* anlag, mottaglighet',
      translation:
        'Disposition, Verfügung, Einteilung, Gliederung, Veranlagung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yn9Sw',
    created: 1737063042564,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '²ạ̊:tervär:kniŋ',
      example: 'Beslutet fick betydande återverkningar på företagets ekonomi.',
      definition: 'återverkan',
      translation: 'Konsequenz',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6CNlx',
    created: 1737063052531,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: 'resultạ:t',
      example: 'Ansträngningarna har lett till resultat.',
      definition: 'följd (1) som värderas; prestation',
      translation: 'Resultat, ergebnis',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MbIi4',
    created: 1737063062503,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '²ẹ:rçen:er‿²ạ̈a',
      example:
        '* Han erkände sitt misstag.\n* Den åtalade erkände.\n* en erkänd konstnär',
      definition:
        '* håller med om, medger\n* tillstå\n* accepterar, uppskattar',
      translation: 'zugegen, gestehen, anerkannt, anerkennen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QbF2o',
    created: 1737063072515,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '²ọ̈:vervä:ga',
      example:
        '* Hon överväger att tacka ja till jobbet.\n* fördelarna med förslaget överväger nackdelarna',
      definition:
        '* tänka igenom (noga), fundera på\n* vara viktigare än, dominera över',
      translation: 'nachdenken, überwiegen, überlegen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H6sgO',
    created: 1737063091766,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '²ẹŋ:na',
      example:
        '* Många föräldrar ägnar för lite tid åt barnen.\n* Hans uppträdande är inte ägnat att skapa förtroende.',
      definition: '* avsätta (3), reservera; tilldela\n* vara lämplig för',
      translation: 'widmen, zuwenden',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'B9kJ3',
    created: 1737063101502,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '²rẹt:fä:r‿diga',
      example:
        'Han var djupt kränkt, men det rättfärdigar inte hans våldsamma reaktion.',
      definition: 'försvarar viss handling',
      translation: 'rechtfertigen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LMP_M',
    created: 1737063130135,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: 'för‿sụm:else',
      example: 'Det skedde för många försummelser på sistone.',
      definition: 'det att försumma något, underlåtenhet',
      translation: 'Vernachlässigung',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'J49JA',
    created: 1737063139874,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '²ọ̈:ver‿ty:ga',
      example: 'De lyckades övertyga honom om att han borde ta en försäkring.',
      definition: 'få någon att tro eller bli säker på',
      translation: 'überzeugen',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'JBOmx',
    created: 1737063149482,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '²grạ:dvi:s',
      example: 'Han bröts gradvis ner av sjukdomen.',
      definition: 'steg för steg, så småningom, successivt',
      translation: 'schrittweise',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3J6s_',
    created: 1737063159957,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implizit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '3YOJ-',
    created: 1737063160792,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'insbesondere',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mDTi6',
    created: 1737063170368,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '²ọ:me:delba:r‿t',
      example: 'Sluta omedelbart med de där dumheterna!',
      definition: 'genast, med detsamma',
      translation: 'unmittelbar, sofort',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nfgyN',
    created: 1737063180096,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: 'unjefạ̈:r',
      example: 'Han kommer hem ungefär klockan 3.',
      definition: 'omkring (1), cirka',
      translation: 'ungefähr',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'H16FB',
    created: 1737063189828,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '²tịl:rek:lig',
      example: 'De hade tillräckligt med bensin för 10 mil.',
      definition: 'som räcker till',
      translation: 'ausreichend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9Vvd3',
    created: 1737063209093,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: 'bestẹn:dig',
      example: 'Vätskan är beständig.',
      definition: 'som bevarar sina väsentliga egenskaper',
      translation: 'beständig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PkR8l',
    created: 1737063228550,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '²ạ̊m:fat:ande',
      example: 'Branden orsakade omfattande skador.',
      definition: 'stor, betydande',
      translation: 'umfassend',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tczme',
    created: 1737063247775,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '²hạ̈:r‿lig',
      example: 'ett härligt bad',
      definition: 'mycket behaglig, ljuvlig',
      translation: 'herrlich',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'VqCpk',
    created: 1737063266290,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: 'för‿sịk:tig',
      example: 'Var försiktig när du går över gatan!',
      definition: 'aktsam, varsam',
      translation: 'vorsichtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ceJD8',
    created: 1737063276166,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '²mọ:tvil:ig',
      example: 'Facket gick motvilligt med på permitteringarna.',
      definition: 'ovillig, motsträvig',
      translation: 'widerwillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'la7GE',
    created: 1737063286161,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: 'siŋnifikạn:t',
      example:
        '* Det finns signifikanta skillnader mellan städerna.\n* En signifikant ökning av väljarstödet för Moderaterna.',
      definition:
        '* som är ett mycket tydligt tecken (på något)\n* som med stor sannolikhet inte beror på en slump',
      translation: 'signifikant',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
