import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'pHMhm',
    created: 1737069576085,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: 'integritẹ:t',
      example:
        '* Den personliga integriteten kan hotas av FRA-lagen.\n* Klubbens ledare måste ha hög personlig integritet.',
      definition:
        '* rätt att inte bli kränkt (särskilt av myndigheter)\n* hederlighet',
      translation: 'integritet, ære',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'm3yqs',
    created: 1737069585781,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elasticitet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_BNbI',
    created: 1737069597036,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '²trọ̈s:kel',
      example:
        '* Han stod på tröskeln in till rummet.\n* Nyåret 2010, på tröskeln till ett nytt decennium.\n* Min tröskel för smärta är ganska låg.',
      definition:
        '* upphöjd bräda på golvet i dörröppning\n* början\n* nedre gräns (för en viss effekt)',
      translation: 'dørtrin, begyndelse, grænse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nqYis',
    created: 1737069616362,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: 'disposiʃọ:n',
      example:
        '* Jag behöver inte bilen på fredag, så den står till din disposition!\n* Hon skulle skriva en artikel och började med att göra en disposition.\n* Han har disposition för infektioner.',
      definition:
        '* förfogande(rätt)\n* planläggning (av skrift eller tal)\n* anlag, mottaglighet',
      translation: 'disposition, planlægning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ykmsf',
    created: 1737069645293,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '²ạ̊:tervär:kniŋ',
      example: 'Beslutet fick betydande återverkningar på företagets ekonomi.',
      definition: 'återverkan',
      translation: 'eftervirkning',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '74apg',
    created: 1737069664494,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: 'resultạ:t',
      example: 'Ansträngningarna har lett till resultat.',
      definition: 'följd (1) som värderas; prestation',
      translation: 'resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TFuNB',
    created: 1737069684061,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '²ẹ:rçen:er‿²ạ̈a',
      example:
        '* Han erkände sitt misstag.\n* Den åtalade erkände.\n* en erkänd konstnär',
      definition:
        '* håller med om, medger\n* tillstå\n* accepterar, uppskattar',
      translation: 'erkende, anerkende, tilstå',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'n8kY2',
    created: 1737069712053,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '²ọ̈:vervä:ga',
      example:
        '* Hon överväger att tacka ja till jobbet.\n* fördelarna med förslaget överväger nackdelarna',
      definition:
        '* tänka igenom (noga), fundera på\n* vara viktigare än, dominera över',
      translation: 'overveje, veje tungt',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TXgDT',
    created: 1737069740040,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '²ẹŋ:na',
      example:
        '* Många föräldrar ägnar för lite tid åt barnen.\n* Hans uppträdande är inte ägnat att skapa förtroende.',
      definition: '* avsätta (3), reservera; tilldela\n* vara lämplig för',
      translation: 'afse, dedikere, vige',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'J0X5W',
    created: 1737069768230,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '²rẹt:fä:r‿diga',
      example:
        'Han var djupt kränkt, men det rättfärdigar inte hans våldsamma reaktion.',
      definition: 'försvarar viss handling',
      translation: 'retfærdiggøre',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'S4NgJ',
    created: 1737069787425,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: 'för‿sụm:else',
      example: 'Det skedde för många försummelser på sistone.',
      definition: 'det att försumma något, underlåtenhet',
      translation: 'forsømmelse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WL8jw',
    created: 1737069816094,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '²ọ̈:ver‿ty:ga',
      example: 'De lyckades övertyga honom om att han borde ta en försäkring.',
      definition: 'få någon att tro eller bli säker på',
      translation: 'overbevise',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HaTKl',
    created: 1737069835350,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '²grạ:dvi:s',
      example: 'Han bröts gradvis ner av sjukdomen.',
      definition: 'steg för steg, så småningom, successivt',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9XQRQ',
    created: 1737069845375,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'implicit',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KtCSk',
    created: 1737069855217,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'især',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '35lY5',
    created: 1737069874566,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '²ọ:me:delba:r‿t',
      example: 'Sluta omedelbart med de där dumheterna!',
      definition: 'genast, med detsamma',
      translation: 'straks, øjeblikkeligt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ype2y',
    created: 1737069902717,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: 'unjefạ̈:r',
      example: 'Han kommer hem ungefär klockan 3.',
      definition: 'omkring (1), cirka',
      translation: 'omkring, cirka, omtrent',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'n4Ln9',
    created: 1737069922288,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '²tịl:rek:lig',
      example: 'De hade tillräckligt med bensin för 10 mil.',
      definition: 'som räcker till',
      translation: 'tilstrækkelig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '8A6Q6',
    created: 1737069950350,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: 'bestẹn:dig',
      example: 'Vätskan är beständig.',
      definition: 'som bevarar sina väsentliga egenskaper',
      translation: 'bestandig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sHnsJ',
    created: 1737069951255,
    data: {
      language: 'sv',
      source: 'omfattende',
      ipa: '',
      example: '',
      definition: '',
      translation: 'omfattende',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZjY0U',
    created: 1737069979080,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '²hạ̈:r‿lig',
      example: 'ett härligt bad',
      definition: 'mycket behaglig, ljuvlig',
      translation: 'herlig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9cLeN',
    created: 1737070007206,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: 'för‿sịk:tig',
      example: 'Var försiktig när du går över gatan!',
      definition: 'aktsam, varsam',
      translation: 'forsigtig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'F4vV1',
    created: 1737070025670,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '²mọ:tvil:ig',
      example: 'Facket gick motvilligt med på permitteringarna.',
      definition: 'ovillig, motsträvig',
      translation: 'modvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_CCSO',
    created: 1737070044773,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: 'siŋnifikạn:t',
      example:
        '* Det finns signifikanta skillnader mellan städerna.\n* En signifikant ökning av väljarstödet för Moderaterna.',
      definition:
        '* som är ett mycket tydligt tecken (på något)\n* som med stor sannolikhet inte beror på en slump',
      translation: 'signifikant, betydningsfuld',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
