import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'pc90F',
    created: 1737068042236,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: 'integritẹ:t',
      example:
        '* Den personliga integriteten kan hotas av FRA-lagen.\n* Klubbens ledare måste ha hög personlig integritet.',
      definition:
        '* rätt att inte bli kränkt (särskilt av myndigheter)\n* hederlighet',
      translation: 'गोपनीयता, ईमानदारी, अखंडता',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'pNv9w',
    created: 1737068051992,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'लचीलापन',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ejz_6',
    created: 1737068071286,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '²trọ̈s:kel',
      example:
        '* Han stod på tröskeln in till rummet.\n* Nyåret 2010, på tröskeln till ett nytt decennium.\n* Min tröskel för smärta är ganska låg.',
      definition:
        '* upphöjd bräda på golvet i dörröppning\n* början\n* nedre gräns (för en viss effekt)',
      translation: 'दरवाजे की चौखट, शुरुआत, न्यूनतम सीमा, कदम',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QHOUB',
    created: 1737068090385,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: 'disposiʃọ:n',
      example:
        '* Jag behöver inte bilen på fredag, så den står till din disposition!\n* Hon skulle skriva en artikel och började med att göra en disposition.\n* Han har disposition för infektioner.',
      definition:
        '* förfogande(rätt)\n* planläggning (av skrift eller tal)\n* anlag, mottaglighet',
      translation: 'अधिकार, योजना, स्वभाव, विन्यास',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zu4ER',
    created: 1737068118725,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '²ạ̊:tervär:kniŋ',
      example: 'Beslutet fick betydande återverkningar på företagets ekonomi.',
      definition: 'återverkan',
      translation: 'परिणाम',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'St-z3',
    created: 1737068129274,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: 'resultạ:t',
      example: 'Ansträngningarna har lett till resultat.',
      definition: 'följd (1) som värderas; prestation',
      translation: 'परिणाम',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '2EyeN',
    created: 1737068157317,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '²ẹ:rçen:er‿²ạ̈a',
      example:
        '* Han erkände sitt misstag.\n* Den åtalade erkände.\n* en erkänd konstnär',
      definition:
        '* håller med om, medger\n* tillstå\n* accepterar, uppskattar',
      translation: 'स्वीकृत करना, मान लेना, स्वीकार करना, स्वीकृति देना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6bcSq',
    created: 1737068185598,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '²ọ̈:vervä:ga',
      example:
        '* Hon överväger att tacka ja till jobbet.\n* fördelarna med förslaget överväger nackdelarna',
      definition:
        '* tänka igenom (noga), fundera på\n* vara viktigare än, dominera över',
      translation: 'विचार करना, प्रमुख होना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'tO9wD',
    created: 1737068213598,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '²ẹŋ:na',
      example:
        '* Många föräldrar ägnar för lite tid åt barnen.\n* Hans uppträdande är inte ägnat att skapa förtroende.',
      definition: '* avsätta (3), reservera; tilldela\n* vara lämplig för',
      translation: 'समर्पित करना, उपयुक्त होना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TaKnv',
    created: 1737068232917,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '²rẹt:fä:r‿diga',
      example:
        'Han var djupt kränkt, men det rättfärdigar inte hans våldsamma reaktion.',
      definition: 'försvarar viss handling',
      translation: 'सत्यापित करना, न्यायसंगत करना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IpaL8',
    created: 1737068261267,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: 'för‿sụm:else',
      example: 'Det skedde för många försummelser på sistone.',
      definition: 'det att försumma något, underlåtenhet',
      translation: 'अवहेलना',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'K-E9L',
    created: 1737068289227,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '²ọ̈:ver‿ty:ga',
      example: 'De lyckades övertyga honom om att han borde ta en försäkring.',
      definition: 'få någon att tro eller bli säker på',
      translation: 'विश्वास दिलाना, मनाना',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bQFDh',
    created: 1737068308434,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '²grạ:dvi:s',
      example: 'Han bröts gradvis ner av sjukdomen.',
      definition: 'steg för steg, så småningom, successivt',
      translation: 'धीरे-धीरे',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oI5Uz',
    created: 1737068310192,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'अप्रत्यक्ष',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hkXOK',
    created: 1737068320143,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'विशेष रूप से',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GCDk7',
    created: 1737068348125,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '²ọ:me:delba:r‿t',
      example: 'Sluta omedelbart med de där dumheterna!',
      definition: 'genast, med detsamma',
      translation: 'तुरंत',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'l98Ae',
    created: 1737068376191,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: 'unjefạ̈:r',
      example: 'Han kommer hem ungefär klockan 3.',
      definition: 'omkring (1), cirka',
      translation: 'लगभग',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'o3o1x',
    created: 1737068395232,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '²tịl:rek:lig',
      example: 'De hade tillräckligt med bensin för 10 mil.',
      definition: 'som räcker till',
      translation: 'पर्याप्त',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Eqad4',
    created: 1737068414872,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: 'bestẹn:dig',
      example: 'Vätskan är beständig.',
      definition: 'som bevarar sina väsentliga egenskaper',
      translation: 'स्थायी',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 's6dU7',
    created: 1737068442851,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '²ạ̊m:fat:ande',
      example: 'Branden orsakade omfattande skador.',
      definition: 'stor, betydande',
      translation: 'व्यापक, विशाल',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'o4xxC',
    created: 1737068470836,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '²hạ̈:r‿lig',
      example: 'ett härligt bad',
      definition: 'mycket behaglig, ljuvlig',
      translation: 'सुंदर, आकर्षक',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_AYd8',
    created: 1737068498864,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: 'för‿sịk:tig',
      example: 'Var försiktig när du går över gatan!',
      definition: 'aktsam, varsam',
      translation: 'सावधान, विचारशील',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'fFhmN',
    created: 1737068509338,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '²mọ:tvil:ig',
      example: 'Facket gick motvilligt med på permitteringarna.',
      definition: 'ovillig, motsträvig',
      translation: 'अनिच्छुक, विरोधी',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WAPXY',
    created: 1737068528852,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: 'siŋnifikạn:t',
      example:
        '* Det finns signifikanta skillnader mellan städerna.\n* En signifikant ökning av väljarstödet för Moderaterna.',
      definition:
        '* som är ett mycket tydligt tecken (på något)\n* som med stor sannolikhet inte beror på en slump',
      translation: 'महत्वपूर्ण, संगत',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
