import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: '8JGds',
    created: 1737074130862,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: 'integritẹ:t',
      example:
        '* Den personliga integriteten kan hotas av FRA-lagen.\n* Klubbens ledare måste ha hög personlig integritet.',
      definition:
        '* rätt att inte bli kränkt (särskilt av myndigheter)\n* hederlighet',
      translation: 'integriti, kehormatan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '_bbFY',
    created: 1737074132904,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'elastik',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'OLnpj',
    created: 1737074152375,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '²trọ̈s:kel',
      example:
        '* Han stod på tröskeln in till rummet.\n* Nyåret 2010, på tröskeln till ett nytt decennium.\n* Min tröskel för smärta är ganska låg.',
      definition:
        '* upphöjd bräda på golvet i dörröppning\n* början\n* nedre gräns (för en viss effekt)',
      translation: 'ambang, permulaan, had bawah',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'B9tBZ',
    created: 1737074171942,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: 'disposiʃọ:n',
      example:
        '* Jag behöver inte bilen på fredag, så den står till din disposition!\n* Hon skulle skriva en artikel och började med att göra en disposition.\n* Han har disposition för infektioner.',
      definition:
        '* förfogande(rätt)\n* planläggning (av skrift eller tal)\n* anlag, mottaglighet',
      translation: 'hak penguasaan, perancangan, kecenderungan, disposisi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ucKX_',
    created: 1737074199884,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '²ạ̊:tervär:kniŋ',
      example: 'Beslutet fick betydande återverkningar på företagets ekonomi.',
      definition: 'återverkan',
      translation: 'kesan',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'Nzy9K',
    created: 1737074210177,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: 'resultạ:t',
      example: 'Ansträngningarna har lett till resultat.',
      definition: 'följd (1) som värderas; prestation',
      translation: 'hasil',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'pn0vz',
    created: 1737074238223,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '²ẹ:rçen:er‿²ạ̈a',
      example:
        '* Han erkände sitt misstag.\n* Den åtalade erkände.\n* en erkänd konstnär',
      definition:
        '* håller med om, medger\n* tillstå\n* accepterar, uppskattar',
      translation: 'mengakui, mengizinkan, menerima',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'CM1S4',
    created: 1737074266624,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '²ọ̈:vervä:ga',
      example:
        '* Hon överväger att tacka ja till jobbet.\n* fördelarna med förslaget överväger nackdelarna',
      definition:
        '* tänka igenom (noga), fundera på\n* vara viktigare än, dominera över',
      translation: 'mempertimbangkan, mengutamakan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'ckSgk',
    created: 1737074294643,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '²ẹŋ:na',
      example:
        '* Många föräldrar ägnar för lite tid åt barnen.\n* Hans uppträdande är inte ägnat att skapa förtroende.',
      definition: '* avsätta (3), reservera; tilldela\n* vara lämplig för',
      translation: 'peruntukkan, sesuai untuk, dedikasi',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'PgEXk',
    created: 1737074313746,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '²rẹt:fä:r‿diga',
      example:
        'Han var djupt kränkt, men det rättfärdigar inte hans våldsamma reaktion.',
      definition: 'försvarar viss handling',
      translation: 'membenarkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'LQJK_',
    created: 1737074341845,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: 'för‿sụm:else',
      example: 'Det skedde för många försummelser på sistone.',
      definition: 'det att försumma något, underlåtenhet',
      translation: 'pengabaian',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'B5lEL',
    created: 1737074369610,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '²ọ̈:ver‿ty:ga',
      example: 'De lyckades övertyga honom om att han borde ta en försäkring.',
      definition: 'få någon att tro eller bli säker på',
      translation: 'meyakinkan',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '0F59l',
    created: 1737074389016,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '²grạ:dvi:s',
      example: 'Han bröts gradvis ner av sjukdomen.',
      definition: 'steg för steg, så småningom, successivt',
      translation: 'secara beransur, secara beransur-ansur',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'zU9-b',
    created: 1737074398622,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tersirat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '1Uxgo',
    created: 1737074409201,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'terutamanya',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'wWLkp',
    created: 1737074428542,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '²ọ:me:delba:r‿t',
      example: 'Sluta omedelbart med de där dumheterna!',
      definition: 'genast, med detsamma',
      translation: 'segera',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'MCcWD',
    created: 1737074456631,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: 'unjefạ̈:r',
      example: 'Han kommer hem ungefär klockan 3.',
      definition: 'omkring (1), cirka',
      translation: 'kira-kira, lebih kurang',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'nSdU4',
    created: 1737074476078,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '²tịl:rek:lig',
      example: 'De hade tillräckligt med bensin för 10 mil.',
      definition: 'som räcker till',
      translation: 'cukup',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'tivpv',
    created: 1737074504054,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: 'bestẹn:dig',
      example: 'Vätskan är beständig.',
      definition: 'som bevarar sina väsentliga egenskaper',
      translation: 'tahan lama',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: '58vzZ',
    created: 1737074532579,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '²ạ̊m:fat:ande',
      example: 'Branden orsakade omfattande skador.',
      definition: 'stor, betydande',
      translation: 'meluas',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'SC4Ga',
    created: 1737074560715,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '²hạ̈:r‿lig',
      example: 'ett härligt bad',
      definition: 'mycket behaglig, ljuvlig',
      translation: 'indah, menyenangkan',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'NFMXL',
    created: 1737074588784,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: 'för‿sịk:tig',
      example: 'Var försiktig när du går över gatan!',
      definition: 'aktsam, varsam',
      translation: 'berhati-hati, cermat',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'eg-v6',
    created: 1737074599093,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '²mọ:tvil:ig',
      example: 'Facket gick motvilligt med på permitteringarna.',
      definition: 'ovillig, motsträvig',
      translation: 'enggan, ragu',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
  {
    id: 'WF7bk',
    created: 1737074618705,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: 'siŋnifikạn:t',
      example:
        '* Det finns signifikanta skillnader mellan städerna.\n* En signifikant ökning av väljarstödet för Moderaterna.',
      definition:
        '* som är ett mycket tydligt tecken (på något)\n* som med stor sannolikhet inte beror på en slump',
      translation: 'signifikan, penting',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1737072000000,
    },
  },
];
