import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'NRboB',
    created: 1737063864554,
    data: {
      language: 'sv',
      source: 'integritet',
      ipa: 'integritẹ:t',
      example:
        '* Den personliga integriteten kan hotas av FRA-lagen.\n* Klubbens ledare måste ha hög personlig integritet.',
      definition:
        '* rätt att inte bli kränkt (särskilt av myndigheter)\n* hederlighet',
      translation: '隱私, 正直, 完整性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'o_t9C',
    created: 1737063874430,
    data: {
      language: 'sv',
      source: 'elasticitet',
      ipa: '',
      example: '',
      definition: '',
      translation: '彈性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'heNGn',
    created: 1737063893742,
    data: {
      language: 'sv',
      source: 'tröskel',
      ipa: '²trọ̈s:kel',
      example:
        '* Han stod på tröskeln in till rummet.\n* Nyåret 2010, på tröskeln till ett nytt decennium.\n* Min tröskel för smärta är ganska låg.',
      definition:
        '* upphöjd bräda på golvet i dörröppning\n* början\n* nedre gräns (för en viss effekt)',
      translation: '門檻, 開始, 下限',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EXy7e',
    created: 1737063904490,
    data: {
      language: 'sv',
      source: 'disposition',
      ipa: 'disposiʃọ:n',
      example:
        '* Jag behöver inte bilen på fredag, så den står till din disposition!\n* Hon skulle skriva en artikel och började med att göra en disposition.\n* Han har disposition för infektioner.',
      definition:
        '* förfogande(rätt)\n* planläggning (av skrift eller tal)\n* anlag, mottaglighet',
      translation: '處置權, 安排, 天賦',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TtAkk',
    created: 1737063932766,
    data: {
      language: 'sv',
      source: 'återverkning',
      ipa: '²ạ̊:tervär:kniŋ',
      example: 'Beslutet fick betydande återverkningar på företagets ekonomi.',
      definition: 'återverkan',
      translation: '影響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '6Pp0i',
    created: 1737063951904,
    data: {
      language: 'sv',
      source: 'resultat',
      ipa: 'resultạ:t',
      example: 'Ansträngningarna har lett till resultat.',
      definition: 'följd (1) som värderas; prestation',
      translation: '結果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4WIwP',
    created: 1737063979930,
    data: {
      language: 'sv',
      source: 'erkänna',
      ipa: '²ẹ:rçen:er‿²ạ̈a',
      example:
        '* Han erkände sitt misstag.\n* Den åtalade erkände.\n* en erkänd konstnär',
      definition:
        '* håller med om, medger\n* tillstå\n* accepterar, uppskattar',
      translation: '承認, 認可, 接受',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-UmXN',
    created: 1737063998985,
    data: {
      language: 'sv',
      source: 'överväga',
      ipa: '²ọ̈:vervä:ga',
      example:
        '* Hon överväger att tacka ja till jobbet.\n* fördelarna med förslaget överväger nackdelarna',
      definition:
        '* tänka igenom (noga), fundera på\n* vara viktigare än, dominera över',
      translation: '考慮',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'chhW7',
    created: 1737064027044,
    data: {
      language: 'sv',
      source: 'ägna',
      ipa: '²ẹŋ:na',
      example:
        '* Många föräldrar ägnar för lite tid åt barnen.\n* Hans uppträdande är inte ägnat att skapa förtroende.',
      definition: '* avsätta (3), reservera; tilldela\n* vara lämplig för',
      translation: '專注, 適合, 專心於',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'NmMvW',
    created: 1737064055118,
    data: {
      language: 'sv',
      source: 'rättfärdiga',
      ipa: '²rẹt:fä:r‿diga',
      example:
        'Han var djupt kränkt, men det rättfärdigar inte hans våldsamma reaktion.',
      definition: 'försvarar viss handling',
      translation: '辯護, 辯解',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wapD3',
    created: 1737064083283,
    data: {
      language: 'sv',
      source: 'försummelse',
      ipa: 'för‿sụm:else',
      example: 'Det skedde för många försummelser på sistone.',
      definition: 'det att försumma något, underlåtenhet',
      translation: '忽視, 疏忽',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hu_xy',
    created: 1737064102427,
    data: {
      language: 'sv',
      source: 'övertyga',
      ipa: '²ọ̈:ver‿ty:ga',
      example: 'De lyckades övertyga honom om att han borde ta en försäkring.',
      definition: 'få någon att tro eller bli säker på',
      translation: '說服',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1jp-x',
    created: 1737064121996,
    data: {
      language: 'sv',
      source: 'gradvis',
      ipa: '²grạ:dvi:s',
      example: 'Han bröts gradvis ner av sjukdomen.',
      definition: 'steg för steg, så småningom, successivt',
      translation: '逐漸',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mSMuX',
    created: 1737064132255,
    data: {
      language: 'sv',
      source: 'implicit',
      ipa: '',
      example: '',
      definition: '',
      translation: '隱含的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'a_HZH',
    created: 1737064141856,
    data: {
      language: 'sv',
      source: 'i synnerhet',
      ipa: '',
      example: '',
      definition: '',
      translation: '特別是',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '7rYZ7',
    created: 1737064174313,
    data: {
      language: 'sv',
      source: 'omedelbart',
      ipa: '²ọ:me:delba:r‿t',
      example: 'Sluta omedelbart med de där dumheterna!',
      definition: 'genast, med detsamma',
      translation: '立即',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jH9gE',
    created: 1737064193381,
    data: {
      language: 'sv',
      source: 'ungefär',
      ipa: 'unjefạ̈:r',
      example: 'Han kommer hem ungefär klockan 3.',
      definition: 'omkring (1), cirka',
      translation: '大約',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'U7sUf',
    created: 1737064212974,
    data: {
      language: 'sv',
      source: 'tillräcklig',
      ipa: '²tịl:rek:lig',
      example: 'De hade tillräckligt med bensin för 10 mil.',
      definition: 'som räcker till',
      translation: '足夠的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QROpf',
    created: 1737064232499,
    data: {
      language: 'sv',
      source: 'beständig',
      ipa: 'bestẹn:dig',
      example: 'Vätskan är beständig.',
      definition: 'som bevarar sina väsentliga egenskaper',
      translation: '持久的, 穩定的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'P_dsV',
    created: 1737064260619,
    data: {
      language: 'sv',
      source: 'omfattande',
      ipa: '²ạ̊m:fat:ande',
      example: 'Branden orsakade omfattande skador.',
      definition: 'stor, betydande',
      translation: '廣泛的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '66T30',
    created: 1737064289106,
    data: {
      language: 'sv',
      source: 'härlig',
      ipa: '²hạ̈:r‿lig',
      example: 'ett härligt bad',
      definition: 'mycket behaglig, ljuvlig',
      translation: '愉快, 美好',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'XBk3m',
    created: 1737064317062,
    data: {
      language: 'sv',
      source: 'försiktig',
      ipa: 'för‿sịk:tig',
      example: 'Var försiktig när du går över gatan!',
      definition: 'aktsam, varsam',
      translation: '小心, 謹慎, 小心的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oLraQ',
    created: 1737064327673,
    data: {
      language: 'sv',
      source: 'motvillig',
      ipa: '²mọ:tvil:ig',
      example: 'Facket gick motvilligt med på permitteringarna.',
      definition: 'ovillig, motsträvig',
      translation: '不情願, 不情願的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'i_mbg',
    created: 1737064347076,
    data: {
      language: 'sv',
      source: 'signifikant',
      ipa: 'siŋnifikạn:t',
      example:
        '* Det finns signifikanta skillnader mellan städerna.\n* En signifikant ökning av väljarstödet för Moderaterna.',
      definition:
        '* som är ett mycket tydligt tecken (på något)\n* som med stor sannolikhet inte beror på en slump',
      translation: '顯著, 重要, 顯著的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
