import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'oZRii',
    created: 1737054587101,
    data: {
      language: 'tr',
      source: 'bütünlük',
      ipa: '',
      example: '',
      definition: '',
      translation: 'الكلية',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iFDQk',
    created: 1737054605269,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: 'متانة',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'sX8Nh',
    created: 1737054615595,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: "e'ʃic",
      example: '* eşikten geçmek\n* savaşın eşiğinde olmak',
      definition:
        '* kapı boşluğunun altındaki alçak basamak\n* başlangıç noktası',
      translation: 'عتبة, نقطة البداية',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'e4OpC',
    created: 1737054634944,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: "ei'lim",
      example: 'gençlerin bu konuya eğilimi',
      definition: 'meyil',
      translation: 'ميل',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-5aPO',
    created: 1737054671396,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: "jan'kɯ",
      example: '* Kendi sesinin yankısını duydu.\n* gazete haberinin yankısı',
      definition:
        '* sesin bir yere çarpıp geri dönmesiyle duyulan ikinci ses\n* bir haber veya olayın uyandırdığı duygu, düşünce ya da tepki',
      translation: 'صدى, رد فعل',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ckMDq',
    created: 1737054708563,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: "so'nuʧ",
      example:
        '* başarılı bir sonuç\n* çalışmanın sonucu\n* metnin sonuç bölümü',
      definition:
        '* bir olayın doğurduğu başka bir olay veya durum\n* bir girişimden elde edilen şey\n* yazının veya sözün bittiği bölümü',
      translation: 'نتيجة, خاتمة, النتيجة',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Tg14D',
    created: 1737054718193,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'القبول',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EPdtb',
    created: 1737054719173,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'أخذ بعين الاعتبار',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'czv_f',
    created: 1737054729042,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'التضحية',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'clfSa',
    created: 1737054738828,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'الدفاع',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aR_r-',
    created: 1737054748664,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إهمال',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cgBC0',
    created: 1737054758297,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'إقناع',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hx9C-',
    created: 1737054777729,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: "'ɟitɟide",
      example: 'Gitgide alışıyor.',
      definition: 'zaman ilerledikçe',
      translation: 'تدريجياً, بالتدريج',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5t3Ae',
    created: 1737054787575,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'بشكل غير مباشر',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'fQC4T',
    created: 1737054810155,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: "œzel'licle",
      example: 'Özellikle erken geldik.',
      definition: 'özel olarak, her şeyden önce',
      translation: 'خصوصاً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'g0cvW',
    created: 1737054823773,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: "'deɾhal",
      example: 'Yemek derhal geldi.',
      definition: 'çabucak, hemen',
      translation: 'فوراً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '1ent_',
    created: 1737054863377,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '* Dilimleri kabaca kesti.\n* Konuyu kabaca anladı.',
      definition: '* kaba bir biçimde\n* yaklaşık olarak\n* irice, büyükçe',
      translation: 'بشكل خشن, تقريباً, بشكل تقريبي',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-XTi-',
    created: 1737054882840,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: "jete'ɾinʤe",
      example: 'Yeterince parası yok.',
      definition: 'yeterli miktarda',
      translation: 'كافٍ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qHFUb',
    created: 1737054902717,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: "kaɫɯ'ʤɯ",
      example:
        '* kalıcı bir hasar\n* kalıcı bir çözüm\n* Misafirlerimiz kalıcı.',
      definition:
        '* sürekli olan; geçici karşıtı\n* gerçerliliği sürekli olan\n* bir müddet belli bir yerde kalan',
      translation: 'دائم, مستمر',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QxBk6',
    created: 1737054912730,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'شامل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9Dq0o',
    created: 1737054941163,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: 'hoʃ',
      example: 'hoş biri',
      definition: 'beğenilen',
      translation: 'مُعْجَب, جميل',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'D0G1U',
    created: 1737054950868,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'حذر',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9mksk',
    created: 1737054969846,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: "istec'siz",
      example: 'isteksiz işçi',
      definition: 'bir işi yapmaya isteği olmayan',
      translation: 'غير راغب',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zvYHH',
    created: 1737055000670,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: "œnem'li",
      example: 'önemli bir karar',
      definition: 'önemi olan',
      translation: 'مهم',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
