import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'CJBgb',
    created: 1737051538558,
    data: {
      language: 'tr',
      source: 'bütünlük',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integridad',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cnd3w',
    created: 1737051539525,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: 'resistencia',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'eObk6',
    created: 1737051567169,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: "e'ʃic",
      example: '* eşikten geçmek\n* savaşın eşiğinde olmak',
      definition:
        '* kapı boşluğunun altındaki alçak basamak\n* başlangıç noktası',
      translation: 'umbral',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'dBNpb',
    created: 1737051594891,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: "ei'lim",
      example: 'gençlerin bu konuya eğilimi',
      definition: 'meyil',
      translation: 'tendencia, disposición',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jo-IW',
    created: 1737051614152,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: "jan'kɯ",
      example: '* Kendi sesinin yankısını duydu.\n* gazete haberinin yankısı',
      definition:
        '* sesin bir yere çarpıp geri dönmesiyle duyulan ikinci ses\n* bir haber veya olayın uyandırdığı duygu, düşünce ya da tepki',
      translation: 'eco, reacción',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'v6ITM',
    created: 1737051633433,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: "so'nuʧ",
      example:
        '* başarılı bir sonuç\n* çalışmanın sonucu\n* metnin sonuç bölümü',
      definition:
        '* bir olayın doğurduğu başka bir olay veya durum\n* bir girişimden elde edilen şey\n* yazının veya sözün bittiği bölümü',
      translation: 'resultado, consecuencia, conclusión',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'snr9U',
    created: 1737051634443,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aceptar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 't6oU9',
    created: 1737051644257,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tomar en cuenta',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kHpNA',
    created: 1737051654179,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'dedicar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'iRISo',
    created: 1737051665674,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'defender',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4m76d',
    created: 1737051675588,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'negar',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'QaoLE',
    created: 1737051685366,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'convencer',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'MbFlf',
    created: 1737051695753,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: "'ɟitɟide",
      example: 'Gitgide alışıyor.',
      definition: 'zaman ilerledikçe',
      translation: 'cada vez más',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'anSnG',
    created: 1737051705413,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'indirectamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Ma4us',
    created: 1737051733665,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: "œzel'licle",
      example: 'Özellikle erken geldik.',
      definition: 'özel olarak, her şeyden önce',
      translation: 'especialmente',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'WgEBc',
    created: 1737051752969,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: "'deɾhal",
      example: 'Yemek derhal geldi.',
      definition: 'çabucak, hemen',
      translation: 'inmediatamente, de inmediato',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '-p_xQ',
    created: 1737051772425,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '',
      definition: '',
      translation: 'aproximadamente',
      partOfSpeech: 'adverbio',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CBThE',
    created: 1737051800663,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: "jete'ɾinʤe",
      example: 'Yeterince parası yok.',
      definition: 'yeterli miktarda',
      translation: 'suficiente',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'lwpUQ',
    created: 1737051819996,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: "kaɫɯ'ʤɯ",
      example:
        '* kalıcı bir hasar\n* kalıcı bir çözüm\n* Misafirlerimiz kalıcı.',
      definition:
        '* sürekli olan; geçici karşıtı\n* gerçerliliği sürekli olan\n* bir müddet belli bir yerde kalan',
      translation: 'permanente, duradero',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'im4Kr',
    created: 1737051829985,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'inclusivo',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'kQfL9',
    created: 1737051858614,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: 'hoʃ',
      example: 'hoş biri',
      definition: 'beğenilen',
      translation: 'agradable, bonito',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Cm3cz',
    created: 1737051859640,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'cuidadoso',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TP-QV',
    created: 1737051887923,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: "istec'siz",
      example: 'isteksiz işçi',
      definition: 'bir işi yapmaya isteği olmayan',
      translation: 'reacio, desinteresado',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'mAPbu',
    created: 1737051907065,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: "œnem'li",
      example: 'önemli bir karar',
      definition: 'önemi olan',
      translation: 'importante',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
