import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'FZf2N',
    created: 1737061227742,
    data: {
      language: 'tr',
      source: 'բարեկեցություն',
      ipa: '',
      example: '',
      definition: '',
      translation: 'բարեկեցություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'aEfQN',
    created: 1737061237699,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: 'դիմադրություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ivnP1',
    created: 1737061247377,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: "e'ʃic",
      example: '* eşikten geçmek\n* savaşın eşiğinde olmak',
      definition:
        '* kapı boşluğunun altındaki alçak basamak\n* başlangıç noktası',
      translation: 'շեմ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nR4o1',
    created: 1737061257430,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: "ei'lim",
      example: 'gençlerin bu konuya eğilimi',
      definition: 'meyil',
      translation: 'տենդենց',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '06kPZ',
    created: 1737061267270,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: "jan'kɯ",
      example: '* Kendi sesinin yankısını duydu.\n* gazete haberinin yankısı',
      definition:
        '* sesin bir yere çarpıp geri dönmesiyle duyulan ikinci ses\n* bir haber veya olayın uyandırdığı duygu, düşünce ya da tepki',
      translation: 'հնչյուն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'EG30Y',
    created: 1737061268970,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: "so'nuʧ",
      example:
        '* başarılı bir sonuç\n* çalışmanın sonucu\n* metnin sonuç bölümü',
      definition:
        '* bir olayın doğurduğu başka bir olay veya durum\n* bir girişimden elde edilen şey\n* yazının veya sözün bittiği bölümü',
      translation: 'արդյունք',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'RjqlG',
    created: 1737061287118,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ընդունել',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '81-Km',
    created: 1737061297028,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հաշվի առնել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'bVWyK',
    created: 1737061307594,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'նվիրվել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_Szs3',
    created: 1737061317169,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'պաշտպանել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IF8tU',
    created: 1737061326917,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'անտեսել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'jpLdD',
    created: 1737061336626,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'համոզել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SSEb_',
    created: 1737061337711,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: "'ɟitɟide",
      example: 'Gitgide alışıyor.',
      definition: 'zaman ilerledikçe',
      translation: 'հաճախակի',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Nrs5G',
    created: 1737061347411,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ուղղակի կերպով',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'x7SDQ',
    created: 1737061357239,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: "œzel'licle",
      example: 'Özellikle erken geldik.',
      definition: 'özel olarak, her şeyden önce',
      translation: '特别是',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'POcMh',
    created: 1737061366958,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: "'deɾhal",
      example: 'Yemek derhal geldi.',
      definition: 'çabucak, hemen',
      translation: 'միանգամից',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '85UL3',
    created: 1737061376715,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '* Dilimleri kabaca kesti.\n* Konuyu kabaca anladı.',
      definition: '* kaba bir biçimde\n* yaklaşık olarak\n* irice, büyükçe',
      translation: 'մոտավոր',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'qaEDD',
    created: 1737061387083,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: "jete'ɾinʤe",
      example: 'Yeterince parası yok.',
      definition: 'yeterli miktarda',
      translation: 'բավարար',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'KEfId',
    created: 1737061396774,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: "kaɫɯ'ʤɯ",
      example:
        '* kalıcı bir hasar\n* kalıcı bir çözüm\n* Misafirlerimiz kalıcı.',
      definition:
        '* sürekli olan; geçici karşıtı\n* gerçerliliği sürekli olan\n* bir müddet belli bir yerde kalan',
      translation: 'մշտական',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zXLHB',
    created: 1737061397767,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ընդգրկող',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'yxC4t',
    created: 1737061407373,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: 'hoʃ',
      example: 'hoş biri',
      definition: 'beğenilen',
      translation: 'հաճելի',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'muQ3Z',
    created: 1737061417019,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ուշադիր',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Pkv1n',
    created: 1737061426749,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: "istec'siz",
      example: 'isteksiz işçi',
      definition: 'bir işi yapmaya isteği olmayan',
      translation: 'չափազանց',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'AMpx4',
    created: 1737061436599,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: "œnem'li",
      example: 'önemli bir karar',
      definition: 'önemi olan',
      translation: ' կարևոր',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
