import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'avICP',
    created: 1737055455909,
    data: {
      language: 'tr',
      source: 'bütünlük',
      ipa: '',
      example: '',
      definition: '',
      translation: '전체성',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'oz0o9',
    created: 1737055465790,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: '내구성',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'CKynA',
    created: 1737055484923,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: "e'ʃic",
      example: '* eşikten geçmek\n* savaşın eşiğinde olmak',
      definition:
        '* kapı boşluğunun altındaki alçak basamak\n* başlangıç noktası',
      translation: '문턱, 시작점',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZTx28',
    created: 1737055503923,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: "ei'lim",
      example: 'gençlerin bu konuya eğilimi',
      definition: 'meyil',
      translation: '경향',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BORQv',
    created: 1737055514415,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: "jan'kɯ",
      example: '* Kendi sesinin yankısını duydu.\n* gazete haberinin yankısı',
      definition:
        '* sesin bir yere çarpıp geri dönmesiyle duyulan ikinci ses\n* bir haber veya olayın uyandırdığı duygu, düşünce ya da tepki',
      translation: '메아리, 반향',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FrdM1',
    created: 1737055533871,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: "so'nuʧ",
      example:
        '* başarılı bir sonuç\n* çalışmanın sonucu\n* metnin sonuç bölümü',
      definition:
        '* bir olayın doğurduğu başka bir olay veya durum\n* bir girişimden elde edilen şey\n* yazının veya sözün bittiği bölümü',
      translation: '결과, 결말',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'g9AC0',
    created: 1737055543731,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: '받아들이다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'FZ1lY',
    created: 1737055554649,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: '고려하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'M9eta',
    created: 1737055564326,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: '바치다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Q6mDo',
    created: 1737055565282,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: '방어하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'PCKXe',
    created: 1737055575812,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: '무시하다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nA0Rb',
    created: 1737055585521,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: '납득시키다',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'cRCYK',
    created: 1737055604637,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: "'ɟitɟide",
      example: 'Gitgide alışıyor.',
      definition: 'zaman ilerledikçe',
      translation: '점점',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'SIcd2',
    created: 1737055614484,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: '간접적으로',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'b3qtn',
    created: 1737055642317,
    data: {
      language: 'tr',
      source: 'özellikle',
      ipa: "œzel'licle",
      example: 'Özellikle erken geldik.',
      definition: 'özel olarak, her şeyden önce',
      translation: '특히',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5HB9a',
    created: 1737055652652,
    data: {
      language: 'tr',
      source: 'derhal',
      ipa: "'deɾhal",
      example: 'Yemek derhal geldi.',
      definition: 'çabucak, hemen',
      translation: '즉시',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GPK7H',
    created: 1737055680487,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '* Dilimleri kabaca kesti.\n* Konuyu kabaca anladı.',
      definition: '* kaba bir biçimde\n* yaklaşık olarak\n* irice, büyükçe',
      translation: '대략적으로, 거칠게, 대략',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'u2i0G',
    created: 1737055708615,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: "jete'ɾinʤe",
      example: 'Yeterince parası yok.',
      definition: 'yeterli miktarda',
      translation: '충분히',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ohFq0',
    created: 1737055728327,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: "kaɫɯ'ʤɯ",
      example:
        '* kalıcı bir hasar\n* kalıcı bir çözüm\n* Misafirlerimiz kalıcı.',
      definition:
        '* sürekli olan; geçici karşıtı\n* gerçerliliği sürekli olan\n* bir müddet belli bir yerde kalan',
      translation: '영구적인, 지속적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '5tIrJ',
    created: 1737055738151,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: '포괄적인',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'Aj0jM',
    created: 1737055757782,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: 'hoʃ',
      example: 'hoş biri',
      definition: 'beğenilen',
      translation: '아름다운',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '4hSbQ',
    created: 1737055767734,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: '주의 깊은',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'UZGir',
    created: 1737055795876,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: "istec'siz",
      example: 'isteksiz işçi',
      definition: 'bir işi yapmaya isteği olmayan',
      translation: '내키지 않는',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'a5DoQ',
    created: 1737055815328,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: "œnem'li",
      example: 'önemli bir karar',
      definition: 'önemi olan',
      translation: '중요한',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
