import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'TCtTx',
    created: 1737061648874,
    data: {
      language: 'tr',
      source: 'бүтіндік',
      ipa: '',
      example: '',
      definition: '',
      translation: 'бүтіндік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_caOU',
    created: 1737061658783,
    data: {
      language: 'tr',
      source: 'dayanıklılık',
      ipa: '',
      example: '',
      definition: '',
      translation: 'төзімділік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'xJpx4',
    created: 1737061668770,
    data: {
      language: 'tr',
      source: 'eşik',
      ipa: "e'ʃic",
      example: '* eşikten geçmek\n* savaşın eşiğinde olmak',
      definition:
        '* kapı boşluğunun altındaki alçak basamak\n* başlangıç noktası',
      translation: 'есік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BMEOY',
    created: 1737061678564,
    data: {
      language: 'tr',
      source: 'eğilim',
      ipa: "ei'lim",
      example: 'gençlerin bu konuya eğilimi',
      definition: 'meyil',
      translation: 'бейімділік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HTydu',
    created: 1737061688332,
    data: {
      language: 'tr',
      source: 'yankı',
      ipa: "jan'kɯ",
      example: '* Kendi sesinin yankısını duydu.\n* gazete haberinin yankısı',
      definition:
        '* sesin bir yere çarpıp geri dönmesiyle duyulan ikinci ses\n* bir haber veya olayın uyandırdığı duygu, düşünce ya da tepki',
      translation: 'жаңғырық',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'zxCaB',
    created: 1737061698034,
    data: {
      language: 'tr',
      source: 'sonuç',
      ipa: "so'nuʧ",
      example:
        '* başarılı bir sonuç\n* çalışmanın sonucu\n* metnin sonuç bölümü',
      definition:
        '* bir olayın doğurduğu başka bir olay veya durum\n* bir girişimden elde edilen şey\n* yazının veya sözün bittiği bölümü',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'hG5yQ',
    created: 1737061707661,
    data: {
      language: 'tr',
      source: 'kabullenmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қабылдау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'GwEhh',
    created: 1737061708756,
    data: {
      language: 'tr',
      source: 'dikkate almak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ескеру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '59p5y',
    created: 1737061718382,
    data: {
      language: 'tr',
      source: 'adamak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'арнау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'BogoP',
    created: 1737061728205,
    data: {
      language: 'tr',
      source: 'savunmak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қорғау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '9f1p_',
    created: 1737061738063,
    data: {
      language: 'tr',
      source: 'ihmal etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ескермеу',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'HK4VQ',
    created: 1737061747833,
    data: {
      language: 'tr',
      source: 'ikna etmek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сендіру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'TM0xc',
    created: 1737061757656,
    data: {
      language: 'tr',
      source: 'gitgide',
      ipa: "'ɟitɟide",
      example: 'Gitgide alışıyor.',
      definition: 'zaman ilerledikçe',
      translation: 'кезең-кезеңімен',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ysA7u',
    created: 1737061769906,
    data: {
      language: 'tr',
      source: 'dolaylı olarak',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жанама түрде',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ACL9L',
    created: 1737061770683,
    data: {
      language: 'tr',
      source: 'особенно',
      ipa: '',
      example: '',
      definition: '',
      translation: 'әсіресе',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'LhRRX',
    created: 1737061780346,
    data: {
      language: 'tr',
      source: 'дерхал',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дереу',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'IB4dC',
    created: 1737061790010,
    data: {
      language: 'tr',
      source: 'kabaca',
      ipa: '',
      example: '* Dilimleri kabaca kesti.\n* Konuyu kabaca anladı.',
      definition: '* kaba bir biçimde\n* yaklaşık olarak\n* irice, büyükçe',
      translation: 'шамамен',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '_IgDg',
    created: 1737061800031,
    data: {
      language: 'tr',
      source: 'yeterince',
      ipa: "jete'ɾinʤe",
      example: 'Yeterince parası yok.',
      definition: 'yeterli miktarda',
      translation: 'жеткілікті',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: '11UMs',
    created: 1737061810183,
    data: {
      language: 'tr',
      source: 'kalıcı',
      ipa: "kaɫɯ'ʤɯ",
      example:
        '* kalıcı bir hasar\n* kalıcı bir çözüm\n* Misafirlerimiz kalıcı.',
      definition:
        '* sürekli olan; geçici karşıtı\n* gerçerliliği sürekli olan\n* bir müddet belli bir yerde kalan',
      translation: 'тұрақты',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'ZSJMd',
    created: 1737061820120,
    data: {
      language: 'tr',
      source: 'kapsayıcı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қамтушы',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'rxnhF',
    created: 1737061820860,
    data: {
      language: 'tr',
      source: 'hoş',
      ipa: 'hoʃ',
      example: 'hoş biri',
      definition: 'beğenilen',
      translation: 'ұнақты',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'nY1jX',
    created: 1737061830727,
    data: {
      language: 'tr',
      source: 'dikkatli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'сақ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'wwOPr',
    created: 1737061840415,
    data: {
      language: 'tr',
      source: 'isteksiz',
      ipa: "istec'siz",
      example: 'isteksiz işçi',
      definition: 'bir işi yapmaya isteği olmayan',
      translation: 'қалаусыз',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
  {
    id: 'DFSeM',
    created: 1737061850121,
    data: {
      language: 'tr',
      source: 'önemli',
      ipa: "œnem'li",
      example: 'önemli bir karar',
      definition: 'önemi olan',
      translation: 'маңызды',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736985600000,
    },
  },
];
