import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'APKER',
    created: 1736964636020,
    data: {
      language: 'zh',
      source: '粗略',
      ipa: 'cūlüè',
      example: '粗略的估算',
      definition: '大略的、大概的',
      translation: 'kobud',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZjwM8',
    created: 1736964636797,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: 'elastiklik',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kWv9o',
    created: 1736964638138,
    data: {
      language: 'zh',
      source: 'limiti nöqtəsi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'limiti nöqtəsi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EtAH-',
    created: 1736964639173,
    data: {
      language: 'zh',
      source: '战略',
      ipa: 'zhànlüè',
      example: '战略管理',
      definition: '作战的谋略',
      translation: 'strategiya',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZSUKh',
    created: 1736964640506,
    data: {
      language: 'zh',
      source: '模特儿',
      ipa: 'mótèr',
      example: '时装模特儿',
      definition: '展示艺术、时尚产品、广告等媒体的人',
      translation: 'model',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'z6Lle',
    created: 1736964641502,
    data: {
      language: 'zh',
      source: '奶粉',
      ipa: 'nǎifěn',
      example: '冲一杯奶粉',
      definition: '将牛奶脱水后制成的一种食品',
      translation: 'süd tozu',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kZnLP',
    created: 1736964642741,
    data: {
      language: 'zh',
      source: 'çəkirdek',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tanımaq',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zf1ux',
    created: 1736964643826,
    data: {
      language: 'zh',
      source: 'konsiderasiya',
      ipa: '',
      example: '',
      definition: '',
      translation: 'konsiderasiya',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qff2M',
    created: 1736964645022,
    data: {
      language: 'zh',
      source: '副',
      ipa: 'fù',
      example: '一副象棋',
      definition: '量词，计算成套成组物品的单位',
      translation: 'vitse',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'onJU3',
    created: 1736964646027,
    data: {
      language: 'zh',
      source: 'sübut etmək',
      ipa: '',
      example: '',
      definition: '',
      translation: 'qanuni',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mg7Pm',
    created: 1736964647074,
    data: {
      language: 'zh',
      source: 'ignoring',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gözardı etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vNCv6',
    created: 1736964648222,
    data: {
      language: 'zh',
      source: '体态',
      ipa: 'tǐtài',
      example: '体态轻盈',
      definition: '身体的姿态',
      translation: 'duruş',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YuLUh',
    created: 1736964649310,
    data: {
      language: 'zh',
      source: '试探',
      ipa: 'shìtàn',
      example: '试探底限',
      definition: '试着探索',
      translation: 'test',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'p2Sj_',
    created: 1736964650502,
    data: {
      language: 'zh',
      source: 'gizli şəkildə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gizli şəkildə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'w1MYR',
    created: 1736964651898,
    data: {
      language: 'zh',
      source: '戏谑',
      ipa: 'xìnüè',
      example: '言语戏谑',
      definition: '开玩笑',
      translation: 'zarafat',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KTxiK',
    created: 1736964652819,
    data: {
      language: 'zh',
      source: '一次',
      ipa: 'yīcì',
      example: '再相信我一次',
      definition: '曾经、一遍',
      translation: 'bir dəfə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f2uZk',
    created: 1736964653740,
    data: {
      language: 'zh',
      source: '得当',
      ipa: 'dédàng',
      example: '处理得当',
      definition: '（言行或举止）恰当、合适',
      translation: 'uyğun',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iZDCz',
    created: 1736964654630,
    data: {
      language: 'zh',
      source: 'yeterli',
      ipa: '',
      example: '',
      definition: '',
      translation: '足够',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HRvJu',
    created: 1736964655510,
    data: {
      language: 'zh',
      source: 'izləyici',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tutqun',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KDkHA',
    created: 1736964656532,
    data: {
      language: 'zh',
      source: '绵',
      ipa: 'mián',
      example: '绵延的山脉',
      definition: '连续延长',
      translation: 'pambıq',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A6ex7',
    created: 1736964658082,
    data: {
      language: 'zh',
      source: 'yaxşı',
      ipa: '',
      example: '',
      definition: '',
      translation: '愉快',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UCX72',
    created: 1736964659234,
    data: {
      language: 'zh',
      source: '才',
      ipa: 'cái',
      example: '德才兼备',
      definition: '才能、天赋',
      translation: 'istedad',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JHrt6',
    created: 1736964660610,
    data: {
      language: 'zh',
      source: 'istəksiz',
      ipa: '',
      example: '',
      definition: '',
      translation: '不情愿的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rsyPc',
    created: 1736964661860,
    data: {
      language: 'zh',
      source: '难',
      ipa: 'nàn',
      example: '难民',
      definition: '遭遇灾难的',
      translation: 'Fəlakət',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
