import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'zko48',
    created: 1736964182565,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: 'راستگو',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WaEsH',
    created: 1736964184193,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: 'کشسانی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'F8iUr',
    created: 1736964184994,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'نقطه بحرانی',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C8E4h',
    created: 1736964186726,
    data: {
      language: 'zh',
      source: '处置',
      ipa: 'chǔzhì',
      example: '处置不当',
      definition: '治理、安置',
      translation: 'تدبیر، مدیریت',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mNcuh',
    created: 1736964187753,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'واکنش',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ovU31',
    created: 1736964189419,
    data: {
      language: 'zh',
      source: '结果',
      ipa: 'jiéguǒ',
      example: '不好的结果',
      definition: '植物长出果实；指事物最后的结局或归宿',
      translation: 'نتیجه',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YIoX6',
    created: 1736964192369,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: 'تأیید کردن، تأیید',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MLl86',
    created: 1736964194251,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: 'kǎolǜ',
      example: '考虑问题',
      definition: '仔细思索',
      translation: 'اندیشیدن، تفکر',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'G-6U_',
    created: 1736964195343,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'فداکاری',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yCEg0',
    created: 1736964196831,
    data: {
      language: 'zh',
      source: '合法',
      ipa: 'héfǎ',
      example: '合法利益',
      definition: '符合法律规定',
      translation: 'قانونی',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OnAmC',
    created: 1736964198366,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: 'نادیده گرفتن',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_yknV',
    created: 1736964199730,
    data: {
      language: 'zh',
      source: '说服',
      ipa: 'shuìfú',
      example: '说服别人',
      definition: '以言词游说，使人采纳',
      translation: 'قانع کردن',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zffjZ',
    created: 1736964201579,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: 'به تدریج',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tzL9j',
    created: 1736964203327,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: 'در همه جا',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EtinO',
    created: 1736964206348,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: 'yóuqí',
      example: '他喜欢图画，尤其喜欢国画。',
      definition: '特别的、更加',
      translation: 'به‌ویژه، به ویژه',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5756y',
    created: 1736964207682,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: 'به موقع',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IH-Oi',
    created: 1736964208679,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'تقریباً',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1Vsxm',
    created: 1736964209815,
    data: {
      language: 'zh',
      source: '足够',
      ipa: 'zúgòu',
      example: '足够勇敢',
      definition: '充足不缺',
      translation: 'کافی',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sBII7',
    created: 1736964212043,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: 'پافشاری، مصرّ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O8Mu3',
    created: 1736964213590,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: 'jiànzhèng',
      example: '见证人',
      definition: '当场目睹而可以作证',
      translation: 'آزمون استخدامی',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OUOJZ',
    created: 1736964214365,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خوشحال',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'E7i62',
    created: 1736964215254,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'احتیاط',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nOv3P',
    created: 1736964217300,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: 'ناهمسان',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pw1Co',
    created: 1736964218871,
    data: {
      language: 'zh',
      source: '重要',
      ipa: 'zhòngyào',
      example: '重要问题',
      definition: '重大而且要紧',
      translation: 'مهم',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
