import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'S3rmQ',
    created: 1736964551267,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: 'իրավիճակ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fzMjk',
    created: 1736964551994,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: '弹力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qA0-N',
    created: 1736964553857,
    data: {
      language: 'zh',
      source: 'լիմիտային կետ',
      ipa: '',
      example: '',
      definition: '',
      translation: 'լիմիտային կետ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WHus2',
    created: 1736964555731,
    data: {
      language: 'zh',
      source: '产',
      ipa: 'chǎn',
      example: '',
      definition: '* 房地财物\n* 出自人工或天然的物品',
      translation: 'Արտադրել',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uoDet',
    created: 1736964557251,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'հնչյուն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9_XWA',
    created: 1736964558572,
    data: {
      language: 'zh',
      source: 'result',
      ipa: '',
      example: '',
      definition: '',
      translation: 'արդյունք',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VzgDS',
    created: 1736964559334,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: 'ճանաչել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ofiHo',
    created: 1736964560565,
    data: {
      language: 'zh',
      source: '开',
      ipa: 'kāi',
      example: '对开',
      definition:
        '量词，计算纸张大小尺寸的单位，切割一大张纸为若干分之一称为“开”',
      translation: 'բացել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HgxBZ',
    created: 1736964561639,
    data: {
      language: 'zh',
      source: 'վճռականություն',
      ipa: '',
      example: '',
      definition: '',
      translation: 'նվիրում',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wtvNl',
    created: 1736964562841,
    data: {
      language: 'zh',
      source: '证明',
      ipa: 'zhèngmíng',
      example: '充分证明',
      definition: '用证据或事实来表明真相，使人相信',
      translation: 'ապացուցել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'f4ebD',
    created: 1736964563746,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: 'անտեսում',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'jlzks',
    created: 1736964564784,
    data: {
      language: 'zh',
      source: 'շահագրգռել',
      ipa: '',
      example: '',
      definition: '',
      translation: 'շահագրգռել',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fb8O4',
    created: 1736964565761,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: 'աստիճանաբար',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZN7dd',
    created: 1736964566800,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: 'ամենուր',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_3smh',
    created: 1736964567632,
    data: {
      language: 'zh',
      source: '尤为',
      ipa: '',
      example: '',
      definition: '',
      translation: 'خصوصապես',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RMd7q',
    created: 1736964568680,
    data: {
      language: 'zh',
      source: 'timely',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ժամանակին',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'HSZw7',
    created: 1736964569596,
    data: {
      language: 'zh',
      source: 'dazhe',
      ipa: '',
      example: '',
      definition: '',
      translation: 'մոտավոր',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZoGcR',
    created: 1736964570357,
    data: {
      language: 'zh',
      source: '足够',
      ipa: 'zúgòu',
      example: '足够勇敢',
      definition: '充足不缺',
      translation: 'բավարար',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PMgxh',
    created: 1736964571701,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: 'Համառություն',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Rm4HN',
    created: 1736964572524,
    data: {
      language: 'zh',
      source: 'զանգվածային',
      ipa: '',
      example: '',
      definition: '',
      translation: 'զանգվածային',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FbO7d',
    created: 1736964573261,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ուրախություն',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fSSQD',
    created: 1736964574659,
    data: {
      language: 'zh',
      source: '头脑',
      ipa: 'tóunǎo',
      example: '头脑清醒',
      definition: '思维、条理',
      translation: 'միտք',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wq8c5',
    created: 1736964575667,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: 'Ոչ մի սպասեք',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9xyrL',
    created: 1736964576482,
    data: {
      language: 'zh',
      source: 'zhongyaode',
      ipa: '',
      example: '',
      definition: '',
      translation: ' կարևոր',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
