import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'sBfkj',
    created: 1736963697393,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: '正直(しょうじき)である',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ns9Th',
    created: 1736963698749,
    data: {
      language: 'zh',
      source: '力',
      ipa: 'lì',
      example: '体力',
      definition: '* 人和动物筋肉的效能\n* 姓氏',
      translation: '力(ちから), 力(りき),姓(せい)の一種(いっしゅ)',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Zy4J8',
    created: 1736963699597,
    data: {
      language: 'zh',
      source: '点',
      ipa: 'diǎn',
      example: '第三点规定',
      definition:
        '* 量词，计算条文项目的单位\n* 小的水滴、小的痕迹\n* 小数点\n* （事物的）方面、重点',
      translation:
        '条文(じょうぶん)の項目(こうもく)を数(かぞ)える, 小(ちい)さなしずく, しみ, 小数点(しょうすうてん), (物事(ものごと)の)面(めん), 個所(かしょ), 象徴的(しょうちょうてき)な意味(いみ)のある位置(いち)や程度(ていど)',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'maCi-',
    created: 1736963700483,
    data: {
      language: 'zh',
      source: '置疑',
      ipa: 'zhìyí',
      example: '不容置疑',
      definition: '怀疑',
      translation: '疑(うたが)う',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1AOj-',
    created: 1736963701366,
    data: {
      language: 'zh',
      source: '反',
      ipa: 'fǎn',
      example: '衬衫穿反了。',
      definition: '* 翻转、相反的\n* 回',
      translation: '逆(ぎゃく)の,反対(はんたい)の, 逆(ぎゃく)にする',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rpqP_',
    created: 1736963702329,
    data: {
      language: 'zh',
      source: '结果',
      ipa: 'jiéguǒ',
      example: '不好的结果',
      definition: '植物长出果实；指事物最后的结局或归宿',
      translation: '結果(けっか)',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tBn4Q',
    created: 1736963703066,
    data: {
      language: 'zh',
      source: '承',
      ipa: 'chéng',
      example: '* 这把椅子无法承担你的重量。\n* 承先启后',
      definition: '* 担当，应允\n* 托、支持\n* 继续、承接',
      translation:
        '担当(たんとう)する,引(ひ)き受(う)ける, 支(ささ)える, 引(ひ)きつぐ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'UXjoz',
    created: 1736963703807,
    data: {
      language: 'zh',
      source: '考',
      ipa: 'kǎo',
      example: '考问',
      definition: '提出问题让对方回答',
      translation: '試験(しけん)する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cbPVk',
    created: 1736963704566,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉仕',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tMx6h',
    created: 1736963705649,
    data: {
      language: 'zh',
      source: '证明',
      ipa: 'zhèngmíng',
      example: '充分证明',
      definition: '用证据或事实来表明真相，使人相信',
      translation: '証明(しょうめい)する',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6ADfG',
    created: 1736963706793,
    data: {
      language: 'zh',
      source: '忽',
      ipa: 'hū',
      example: '忽小姐',
      definition: '姓氏',
      translation: '忽(こつ),姓(せい)の一種(いっしゅ)',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'e5eFS',
    created: 1736963707692,
    data: {
      language: 'zh',
      source: '得',
      ipa: 'de',
      example: '我还吃得下。',
      definition: '* 用在动词后面（表示可能性）\n* 得到、获得',
      translation:
        '動詞(どうし)と結果補語(けっかほご)、方向補語(ほうこうほご)の間(あいだ)において可能補語(かのうほご)を構成(こうせい)する, 得(え)る, 手(て)に入(い)れる',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XyKPY',
    created: 1736963709245,
    data: {
      language: 'zh',
      source: 'じょじょに',
      ipa: '',
      example: '',
      definition: '',
      translation: '徐々に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1Mvs1',
    created: 1736963710103,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: 'あらゆる場所(ばしょ)',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'X7dAd',
    created: 1736963710983,
    data: {
      language: 'zh',
      source: '尤',
      ipa: 'yóu',
      example: '',
      definition: '姓',
      translation: '尤(ゆう),姓(せい)の一種(いっしゅ)',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ffErK',
    created: 1736963711713,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: 'いつでも',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AxLBj',
    created: 1736963713574,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'おおよそ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '2aQtI',
    created: 1736963714422,
    data: {
      language: 'zh',
      source: '足够',
      ipa: 'zúgòu',
      example: '足够勇敢',
      definition: '充足不缺',
      translation: '十分(じゅうぶん)に',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Vf66d',
    created: 1736963715394,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: '執着(しゅうちゃく)している',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i0p2I',
    created: 1736963716361,
    data: {
      language: 'zh',
      source: '合',
      ipa: 'hé',
      example: '合家欢',
      definition: '全部、整个',
      translation: '全(すべ)ての',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OjyBz',
    created: 1736963717361,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: '愉快',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fpleB',
    created: 1736963718217,
    data: {
      language: 'zh',
      source: '慎重',
      ipa: 'shènzhòng',
      example: '慎重考虑',
      definition: '谨慎认真',
      translation: '慎重(しんちょう)である',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NRhkl',
    created: 1736963719348,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: '同(おな)じでない',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M2hpN',
    created: 1736963720271,
    data: {
      language: 'zh',
      source: '重要',
      ipa: 'zhòngyào',
      example: '重要问题',
      definition: '重大而且要紧',
      translation: '重要(じゅうよう)である',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
