import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'OXdbp',
    created: 1736964604533,
    data: {
      language: 'zh',
      source: 'zhen zhi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'адал',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '7-NfQ',
    created: 1736964605487,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: 'серпімділік',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sbt5H',
    created: 1736964606478,
    data: {
      language: 'zh',
      source: 'limjiet',
      ipa: '',
      example: '',
      definition: '',
      translation: 'шекті нүкте',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rHBII',
    created: 1736964607584,
    data: {
      language: 'zh',
      source: 'chuzhi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жою',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IaafS',
    created: 1736964608477,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'реакция',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9owE5',
    created: 1736964609472,
    data: {
      language: 'zh',
      source: 'нәтиже',
      ipa: '',
      example: '',
      definition: '',
      translation: 'нәтиже',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ADXqt',
    created: 1736964611027,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: 'мойындау',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'D-UjJ',
    created: 1736964611765,
    data: {
      language: 'zh',
      source: 'қарастыру',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қарастыру',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SCnJU',
    created: 1736964612855,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'арнау',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oik13',
    created: 1736964614156,
    data: {
      language: 'zh',
      source: 'дәлелдеу заңды',
      ipa: '',
      example: '',
      definition: '',
      translation: 'дәлелдеу заңды',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'YJ9s4',
    created: 1736964615032,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: 'ескермеу',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'A0-kG',
    created: 1736964615947,
    data: {
      language: 'zh',
      source: '说服',
      ipa: 'shuìfú',
      example: '说服别人',
      definition: '以言词游说，使人采纳',
      translation: 'сендіру',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PQH0G',
    created: 1736964620095,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: 'біртіндеп',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'sYzE3',
    created: 1736964622181,
    data: {
      language: 'zh',
      source: 'yinhande',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жасырын түрде',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lNFZh',
    created: 1736964623233,
    data: {
      language: 'zh',
      source: '尤为',
      ipa: '',
      example: '',
      definition: '',
      translation: 'әсіресе',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SWhb1',
    created: 1736964623998,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: 'уақытында',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '13A-L',
    created: 1736964624856,
    data: {
      language: 'zh',
      source: 'dazhi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'шамамен',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AQFxl',
    created: 1736964626838,
    data: {
      language: 'zh',
      source: '勃勃',
      ipa: 'bóbó',
      example: '生机勃勃',
      definition: '形容兴隆旺盛的样子',
      translation: 'жігерлі',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JDpgz',
    created: 1736964628258,
    data: {
      language: 'zh',
      source: 'zharqyn',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жарқын',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RNAYQ',
    created: 1736964629572,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: 'jiànzhèng',
      example: '见证人',
      definition: '当场目睹而可以作证',
      translation: 'Ресми жұмысқа орналасу алдындағы тағылымдамадан өту кезеңі',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hITWR',
    created: 1736964630514,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'қуаныш',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OxRKG',
    created: 1736964631637,
    data: {
      language: 'zh',
      source: '基金',
      ipa: 'jījīn',
      example: '教育基金',
      definition: '为兴办、维持或发展某种事业而储备的资金或专门拨款',
      translation: 'қор',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gPxAw',
    created: 1736964633687,
    data: {
      language: 'zh',
      source: '必备',
      ipa: 'bìbèi',
      example: '必备条件',
      definition: '不可少的',
      translation: 'Маңызды',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n825G',
    created: 1736964634652,
    data: {
      language: 'zh',
      source: '吗',
      ipa: 'ma',
      example: '你明天来吗？',
      definition: '用在句末，表示疑问或反诘的语气',
      translation: '?',
      partOfSpeech: 'particle',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
