import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'SxpZO',
    created: 1736963721918,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: 'честный, прямой',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fvtHZ',
    created: 1736963723256,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: 'упругость',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Cb2l7',
    created: 1736963724288,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'критическая точка',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'MoYqf',
    created: 1736963725487,
    data: {
      language: 'zh',
      source: '处置',
      ipa: 'chǔzhì',
      example: '处置不当',
      definition: '治理、安置',
      translation: 'управление, размещение',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lqyiK',
    created: 1736963726895,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'отклик',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'txyNB',
    created: 1736963729223,
    data: {
      language: 'zh',
      source: '结果',
      ipa: 'jiéguǒ',
      example: '不好的结果',
      definition: '植物长出果实；指事物最后的结局或归宿',
      translation: 'результат',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DXLEJ',
    created: 1736963730901,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: 'признавать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'uDbBk',
    created: 1736963732639,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: 'kǎolǜ',
      example: '考虑问题',
      definition: '仔细思索',
      translation: 'рассматривать, обдумывать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'O6hvB',
    created: 1736963733499,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жертва',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9sbeM',
    created: 1736963735405,
    data: {
      language: 'zh',
      source: '证明',
      ipa: 'zhèngmíng',
      example: '充分证明',
      definition: '用证据或事实来表明真相，使人相信',
      translation: 'доказать',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ihsRs',
    created: 1736963736941,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: 'игнорировать, не обращать внимание',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TKEbS',
    created: 1736963738360,
    data: {
      language: 'zh',
      source: '说服',
      ipa: 'shuìfú',
      example: '说服别人',
      definition: '以言词游说，使人采纳',
      translation: 'убеждение',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8XuOd',
    created: 1736963740483,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: 'постепенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'n9kfw',
    created: 1736963742182,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: 'повсюду',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lZELe',
    created: 1736963743555,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: 'yóuqí',
      example: '他喜欢图画，尤其喜欢国画。',
      definition: '特别的、更加',
      translation: 'особенно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9oQMq',
    created: 1736963744935,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: 'вовремя, своевременно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zdZSD',
    created: 1736963745998,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'в общем',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5dbLD',
    created: 1736963747439,
    data: {
      language: 'zh',
      source: '足够',
      ipa: 'zúgòu',
      example: '足够勇敢',
      definition: '充足不缺',
      translation: 'достаточно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'frQsF',
    created: 1736963750241,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: 'упорный, настойчивый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-joOS',
    created: 1736963751913,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: 'jiànzhèng',
      example: '见证人',
      definition: '当场目睹而可以作证',
      translation: 'стажировка',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j6d0F',
    created: 1736963752637,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'радость',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AlO5r',
    created: 1736963753552,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'осторожность',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '5Ymdr',
    created: 1736963755393,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: 'неравный, неодинаковый',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eovGd',
    created: 1736963757098,
    data: {
      language: 'zh',
      source: '重要',
      ipa: 'zhòngyào',
      example: '重要问题',
      definition: '重大而且要紧',
      translation: 'важный',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
