import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'XoNss',
    created: 1736965492600,
    data: {
      language: 'zh-TW',
      source: '正直',
      ipa: '',
      example: '正直的人',
      definition: '公正坦率',
      translation: 'ซื่อสัตย์',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ntOGl',
    created: 1736965494035,
    data: {
      language: 'zh-TW',
      source: '彈性',
      ipa: '',
      example: '* 橡皮筋的彈性\n* 彈性措施',
      definition:
        '* 物體受外力作用時，會改變形體，而當外力除去後隨即恢復原狀的性質\n* 比喻事情無絕對的標準、形式等，可以隨狀況調整',
      translation: 'ความยืดหยุ่น, ความยืด',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'NaRSd',
    created: 1736965495206,
    data: {
      language: 'zh-TW',
      source: '臨界點',
      ipa: '',
      example: '',
      definition: '',
      translation: 'จุดวิกฤต',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yXdbV',
    created: 1736965496583,
    data: {
      language: 'zh-TW',
      source: '性格',
      ipa: '',
      example: '',
      definition: '',
      translation: 'บุคลิกภาพ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oBG7I',
    created: 1736965497433,
    data: {
      language: 'zh-TW',
      source: '迴響',
      ipa: '',
      example: '',
      definition: '',
      translation: 'เสียงสะท้อน',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v2U-Z',
    created: 1736965498843,
    data: {
      language: 'zh-TW',
      source: '結果',
      ipa: '',
      example: '不好的結果',
      definition: '後果',
      translation: 'ผลลัพธ์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '79xzp',
    created: 1736965500137,
    data: {
      language: 'zh-TW',
      source: '承認',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การยอมรับ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KOq3n',
    created: 1736965501403,
    data: {
      language: 'zh-TW',
      source: '考慮',
      ipa: '',
      example: '考慮問題',
      definition: '仔細思索',
      translation: 'พิจารณา',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's7dC8',
    created: 1736965502617,
    data: {
      language: 'zh-TW',
      source: '奉獻',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การถวาย',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FQrW2',
    created: 1736965504786,
    data: {
      language: 'zh-TW',
      source: '證明合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'พิสูจน์ความถูกต้อง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'c9SNp',
    created: 1736965506411,
    data: {
      language: 'zh-TW',
      source: '忽視',
      ipa: '',
      example: '忽視他人的意見',
      definition: '不注意、不重視',
      translation: 'มองข้าม',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wqE24',
    created: 1736965507835,
    data: {
      language: 'zh-TW',
      source: '說服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ชักจูง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M9Mpn',
    created: 1736965509344,
    data: {
      language: 'zh-TW',
      source: '逐步地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ทีละขั้น',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'C3Llv',
    created: 1736965510422,
    data: {
      language: 'zh-TW',
      source: '隱含地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยนัย',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OQVvm',
    created: 1736965513182,
    data: {
      language: 'zh-TW',
      source: '尤其',
      ipa: '',
      example: '他喜歡圖畫，尤其喜歡國畫。',
      definition: '特別的、 更加',
      translation: 'โดยเฉพาะ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gjDmd',
    created: 1736965514824,
    data: {
      language: 'zh-TW',
      source: '及時',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ทันเวลา',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KRGJh',
    created: 1736965515693,
    data: {
      language: 'zh-TW',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยประมาณ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W616M',
    created: 1736965517725,
    data: {
      language: 'zh-TW',
      source: '充分地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'อย่างเต็มที่',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-5W3r',
    created: 1736965519450,
    data: {
      language: 'zh-TW',
      source: '執著的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ยึดมั่น',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IPdeB',
    created: 1736965520368,
    data: {
      language: 'zh-TW',
      source: '綜合的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'รวมกัน',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pt0s6',
    created: 1736965527199,
    data: {
      language: 'zh-TW',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความสุข',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iWEKe',
    created: 1736965528108,
    data: {
      language: 'zh-TW',
      source: '謹慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ระมัดระวัง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0YqkM',
    created: 1736965529771,
    data: {
      language: 'zh-TW',
      source: '不情願的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ไม่เต็มใจ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'k9jW6',
    created: 1736965531517,
    data: {
      language: 'zh-TW',
      source: '重要的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'สำคัญ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
