import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'Z1spK',
    created: 1736964851049,
    data: {
      language: 'zh-TW',
      source: '正直',
      ipa: '',
      example: '正直的人',
      definition: '公正坦率',
      translation: '',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1ksrg',
    created: 1736964851333,
    data: {
      language: 'zh-TW',
      source: '彈性',
      ipa: '',
      example: '* 橡皮筋的彈性\n* 彈性措施',
      definition:
        '* 物體受外力作用時，會改變形體，而當外力除去後隨即恢復原狀的性質\n* 比喻事情無絕對的標準、形式等，可以隨狀況調整',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r6dtW',
    created: 1736964851520,
    data: {
      language: 'zh-TW',
      source: '臨界點',
      ipa: '',
      example: '',
      definition: '',
      translation: '臨界點',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'N-P9l',
    created: 1736964851663,
    data: {
      language: 'zh-TW',
      source: '性格',
      ipa: '',
      example: '',
      definition: '',
      translation: '性格',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ZHaX7',
    created: 1736964851807,
    data: {
      language: 'zh-TW',
      source: '迴響',
      ipa: '',
      example: '',
      definition: '',
      translation: '迴響',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W2H0L',
    created: 1736964851959,
    data: {
      language: 'zh-TW',
      source: '結果',
      ipa: '',
      example: '不好的結果',
      definition: '後果',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JaCEX',
    created: 1736964852101,
    data: {
      language: 'zh-TW',
      source: '承認',
      ipa: '',
      example: '承認錯誤',
      definition: '對某件事表示認可或不隱瞞',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RpUpZ',
    created: 1736964852251,
    data: {
      language: 'zh-TW',
      source: '考慮',
      ipa: '',
      example: '考慮問題',
      definition: '仔細思索',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RLahd',
    created: 1736964852389,
    data: {
      language: 'zh-TW',
      source: '奉獻',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉獻',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dmOGW',
    created: 1736964852525,
    data: {
      language: 'zh-TW',
      source: '證明合法',
      ipa: '',
      example: '',
      definition: '',
      translation: '證明合法',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_ZaRU',
    created: 1736964852667,
    data: {
      language: 'zh-TW',
      source: '忽視',
      ipa: '',
      example: '忽視他人的意見',
      definition: '不注意、不重視',
      translation: '',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TNEux',
    created: 1736964852807,
    data: {
      language: 'zh-TW',
      source: '說服',
      ipa: '',
      example: '說服別人',
      definition: '以言詞遊說，使人採納',
      translation: '',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '9qjIU',
    created: 1736964852972,
    data: {
      language: 'zh-TW',
      source: '逐步地',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐步地',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aPwaY',
    created: 1736964853131,
    data: {
      language: 'zh-TW',
      source: '隱含地',
      ipa: '',
      example: '',
      definition: '',
      translation: '隱含地',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'kKACj',
    created: 1736964853261,
    data: {
      language: 'zh-TW',
      source: '尤其',
      ipa: '',
      example: '他喜歡圖畫，尤其喜歡國畫。',
      definition: '特別的、 更加',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xiOd5',
    created: 1736964853403,
    data: {
      language: 'zh-TW',
      source: '及時',
      ipa: '',
      example: '及時到來',
      definition: '正好趕上、適合需要',
      translation: '',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JiJsD',
    created: 1736964853550,
    data: {
      language: 'zh-TW',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: '大致',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-zxCy',
    created: 1736964853701,
    data: {
      language: 'zh-TW',
      source: '充分地',
      ipa: '',
      example: '',
      definition: '',
      translation: '充分地',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ASm5l',
    created: 1736964853846,
    data: {
      language: 'zh-TW',
      source: '執著的',
      ipa: '',
      example: '',
      definition: '',
      translation: '執著的',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'beid3',
    created: 1736964854008,
    data: {
      language: 'zh-TW',
      source: '綜合的',
      ipa: '',
      example: '',
      definition: '',
      translation: '綜合的',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'JJrr8',
    created: 1736964854188,
    data: {
      language: 'zh-TW',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: '愉快',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8jF22',
    created: 1736964854332,
    data: {
      language: 'zh-TW',
      source: '謹慎',
      ipa: '',
      example: '',
      definition: '',
      translation: '謹慎',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qVFeZ',
    created: 1736964854515,
    data: {
      language: 'zh-TW',
      source: '不情願的',
      ipa: '',
      example: '',
      definition: '',
      translation: '不情願的',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-48b1',
    created: 1736964854661,
    data: {
      language: 'zh-TW',
      source: '重要的',
      ipa: '',
      example: '',
      definition: '',
      translation: '重要的',
      partOfSpeech: '',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
