import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'MSSPH',
    created: 1736964342303,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: 'ซื่อสัตย์',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'XmWkO',
    created: 1736964344608,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: 'ความยืดหยุ่น',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vGXzz',
    created: 1736964345513,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'จุดวิกฤต',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QfirH',
    created: 1736964347126,
    data: {
      language: 'zh',
      source: '处置',
      ipa: 'chǔzhì',
      example: '处置不当',
      definition: '治理、安置',
      translation: 'จัดการ, จัดตั้ง',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dKSj8',
    created: 1736964348092,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การตอบสนอง',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nJxKP',
    created: 1736964349606,
    data: {
      language: 'zh',
      source: '结果',
      ipa: 'jiéguǒ',
      example: '不好的结果',
      definition: '植物长出果实；指事物最后的结局或归宿',
      translation: 'ผลลัพธ์',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tIIF4',
    created: 1736964351145,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: 'ยอมรับ',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Lp59z',
    created: 1736964352787,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: 'kǎolǜ',
      example: '考虑问题',
      definition: '仔细思索',
      translation: 'พิจารณา',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-23kf',
    created: 1736964353652,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'การอุทิศ',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'vQMnu',
    created: 1736964355430,
    data: {
      language: 'zh',
      source: '证明',
      ipa: 'zhèngmíng',
      example: '充分证明',
      definition: '用证据或事实来表明真相，使人相信',
      translation: 'พิสูจน์',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'QCD4O',
    created: 1736964357485,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: 'มองข้าม',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aaVDX',
    created: 1736964359356,
    data: {
      language: 'zh',
      source: '说服',
      ipa: 'shuìfú',
      example: '说服别人',
      definition: '以言词游说，使人采纳',
      translation: 'ชักชวน',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '1QD_A',
    created: 1736964361278,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: 'ทีละขั้น',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'b89n_',
    created: 1736964363607,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: 'ทั่ว',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SauBD',
    created: 1736964365307,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: 'yóuqí',
      example: '他喜欢图画，尤其喜欢国画。',
      definition: '特别的、更加',
      translation: 'โดยเฉพาะ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OxEzU',
    created: 1736964366822,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: 'ทันเวลา',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'I7JqA',
    created: 1736964367673,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'โดยประมาณ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oAThs',
    created: 1736964369615,
    data: {
      language: 'zh',
      source: '足够',
      ipa: 'zúgòu',
      example: '足够勇敢',
      definition: '充足不缺',
      translation: 'เพียงพอ',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'WpLOy',
    created: 1736964371335,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: 'มุ่งมั่น',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'CQ_1j',
    created: 1736964376735,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: 'jiànzhèng',
      example: '见证人',
      definition: '当场目睹而可以作证',
      translation: 'การฝึกงาน',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'hlc26',
    created: 1736964377610,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ความสุข',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SnRYy',
    created: 1736964378578,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ระมัดระวัง',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'REaIJ',
    created: 1736964381004,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: 'ไม่เท่ากัน',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'iUia3',
    created: 1736964385449,
    data: {
      language: 'zh',
      source: '重要',
      ipa: 'zhòngyào',
      example: '重要问题',
      definition: '重大而且要紧',
      translation: 'สำคัญ',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
