import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'j3LlH',
    created: 1736965190164,
    data: {
      language: 'zh-TW',
      source: '正直',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ärlighet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'L_Qn3',
    created: 1736965191911,
    data: {
      language: 'zh-TW',
      source: '彈性',
      ipa: '',
      example: '* 橡皮筋的彈性\n* 彈性措施',
      definition:
        '* 物體受外力作用時，會改變形體，而當外力除去後隨即恢復原狀的性質\n* 比喻事情無絕對的標準、形式等，可以隨狀況調整',
      translation: 'elasticitet, flexibilitet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gXwOq',
    created: 1736965192789,
    data: {
      language: 'zh-TW',
      source: '臨界點',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gränspunkt',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'taORm',
    created: 1736965193643,
    data: {
      language: 'zh-TW',
      source: '性格',
      ipa: '',
      example: '',
      definition: '',
      translation: 'karaktär',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'fjTYb',
    created: 1736965194684,
    data: {
      language: 'zh-TW',
      source: '迴響',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ekon',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qJJVa',
    created: 1736965196256,
    data: {
      language: 'zh-TW',
      source: '結果',
      ipa: '',
      example: '不好的結果',
      definition: '後果',
      translation: 'konsekvens, resultat',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aLeP6',
    created: 1736965197582,
    data: {
      language: 'zh-TW',
      source: '承認',
      ipa: '',
      example: '',
      definition: '',
      translation: 'erkännande',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4MLfr',
    created: 1736965199029,
    data: {
      language: 'zh-TW',
      source: '考慮',
      ipa: '',
      example: '',
      definition: '',
      translation: 'övervägande',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'OMtPH',
    created: 1736965199789,
    data: {
      language: 'zh-TW',
      source: '奉獻',
      ipa: '',
      example: '',
      definition: '',
      translation: 'offra',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cle19',
    created: 1736965201836,
    data: {
      language: 'zh-TW',
      source: '證明合法',
      ipa: '',
      example: '',
      definition: '',
      translation: 'bevisa laglighet',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's2XCF',
    created: 1736965203931,
    data: {
      language: 'zh-TW',
      source: '忽視',
      ipa: '',
      example: '忽視他人的意見',
      definition: '不注意、不重視',
      translation: 'förbise, ignorera',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tk0QJ',
    created: 1736965205464,
    data: {
      language: 'zh-TW',
      source: '說服',
      ipa: '',
      example: '',
      definition: '',
      translation: 'övertala',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'J6hBH',
    created: 1736965207311,
    data: {
      language: 'zh-TW',
      source: '逐步地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gradvis',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FpRQ9',
    created: 1736965208428,
    data: {
      language: 'zh-TW',
      source: '隱含地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'underförstått',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tc6SB',
    created: 1736965209842,
    data: {
      language: 'zh-TW',
      source: '尤其',
      ipa: '',
      example: '他喜歡圖畫，尤其喜歡國畫。',
      definition: '特別的、 更加',
      translation: 'särskilt, speciellt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'tI_hM',
    created: 1736965212268,
    data: {
      language: 'zh-TW',
      source: '及時',
      ipa: '',
      example: '及時到來',
      definition: '正好趕上、適合需要',
      translation: 'i tid',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's1SSe',
    created: 1736965214764,
    data: {
      language: 'zh-TW',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ungefär',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qPyys',
    created: 1736965216423,
    data: {
      language: 'zh-TW',
      source: '充分地',
      ipa: '',
      example: '',
      definition: '',
      translation: 'tillräckligt',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3cM68',
    created: 1736965218145,
    data: {
      language: 'zh-TW',
      source: '執著的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'besatt',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mF9Z4',
    created: 1736965219062,
    data: {
      language: 'zh-TW',
      source: '綜合的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'integrerad',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Pw5SY',
    created: 1736965220065,
    data: {
      language: 'zh-TW',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'glad',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'nhaE6',
    created: 1736965221085,
    data: {
      language: 'zh-TW',
      source: '謹慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'försiktighet',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cxpjx',
    created: 1736965222622,
    data: {
      language: 'zh-TW',
      source: '不情願的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'motvillig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'wWnQE',
    created: 1736965224108,
    data: {
      language: 'zh-TW',
      source: '重要的',
      ipa: '',
      example: '',
      definition: '',
      translation: 'viktig',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
