import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'MPTN4',
    created: 1736965753078,
    data: {
      language: 'zh-TW',
      source: 'düzgün',
      ipa: '',
      example: '',
      definition: '',
      translation: '正直',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VoZF4',
    created: 1736965753882,
    data: {
      language: 'zh-TW',
      source: 'elastiklik',
      ipa: '',
      example: '',
      definition: '',
      translation: '弹性',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'dkw4d',
    created: 1736965754814,
    data: {
      language: 'zh-TW',
      source: 'limiti nöqtəsi',
      ipa: '',
      example: '',
      definition: '',
      translation: 'limiti nöqtəsi',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'v9Bf2',
    created: 1736965755529,
    data: {
      language: 'zh-TW',
      source: 'xarakter',
      ipa: '',
      example: '',
      definition: '',
      translation: 'xarakter',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SxTNN',
    created: 1736965756709,
    data: {
      language: 'zh-TW',
      source: 'əks-səda',
      ipa: '',
      example: '',
      definition: '',
      translation: 'əks-səda',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_bk-2',
    created: 1736965757532,
    data: {
      language: 'zh-TW',
      source: 'nəticə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'nəticə',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Qnk1E',
    created: 1736965758583,
    data: {
      language: 'zh-TW',
      source: 'tanımaq',
      ipa: '',
      example: '',
      definition: '',
      translation: '承認',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DHgz5',
    created: 1736965759499,
    data: {
      language: 'zh-TW',
      source: 'konsiderasiya',
      ipa: '',
      example: '',
      definition: '',
      translation: '考慮',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pZgeB',
    created: 1736965760528,
    data: {
      language: 'zh-TW',
      source: 'fəda',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉獻',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'RrPG6',
    created: 1736965761295,
    data: {
      language: 'zh-TW',
      source: 'sübut etmək qanuni',
      ipa: '',
      example: '',
      definition: '',
      translation: 'sübut etmək qanuni',
      partOfSpeech: 'verb phrase',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'H4Syt',
    created: 1736965762078,
    data: {
      language: 'zh-TW',
      source: 'ignora',
      ipa: '',
      example: '',
      definition: '',
      translation: 'göz ardı etmək',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PLpni',
    created: 1736965763128,
    data: {
      language: 'zh-TW',
      source: 'şöhrət',
      ipa: '',
      example: '',
      definition: '',
      translation: 'persuasion',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'j6O-h',
    created: 1736965763935,
    data: {
      language: 'zh-TW',
      source: 'tədricən',
      ipa: '',
      example: '',
      definition: '',
      translation: '逐步地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rNwwT',
    created: 1736965764743,
    data: {
      language: 'zh-TW',
      source: 'gizli şəkildə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'gizli şəkildə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3oJNo',
    created: 1736965765654,
    data: {
      language: 'zh-TW',
      source: 'xüsusilə',
      ipa: '',
      example: '',
      definition: '',
      translation: 'xüsusilə',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '21egs',
    created: 1736965766567,
    data: {
      language: 'zh-TW',
      source: 'cəld',
      ipa: '',
      example: '',
      definition: '',
      translation: '及时',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'x4VLz',
    created: 1736965767452,
    data: {
      language: 'zh-TW',
      source: 'düzgün',
      ipa: '',
      example: '',
      definition: '',
      translation: 'təxminən',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'SBazb',
    created: 1736965768411,
    data: {
      language: 'zh-TW',
      source: 'kifayət qədər',
      ipa: '',
      example: '',
      definition: '',
      translation: 'kifayət qədər',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '6EyNG',
    created: 1736965769346,
    data: {
      language: 'zh-TW',
      source: 'ziddiyyətli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'ziddiyyətli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 's7XfS',
    created: 1736965770519,
    data: {
      language: 'zh-TW',
      source: 'müxtəlif',
      ipa: '',
      example: '',
      definition: '',
      translation: 'müxtəlif',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'KQe_J',
    created: 1736965771470,
    data: {
      language: 'zh-TW',
      source: 'yaxşı',
      ipa: '',
      example: '',
      definition: '',
      translation: 'xoşbəxt',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'd5_uz',
    created: 1736965772302,
    data: {
      language: 'zh-TW',
      source: 'cəhd',
      ipa: '',
      example: '',
      definition: '',
      translation: 'təvazökar',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PPNiz',
    created: 1736965773543,
    data: {
      language: 'zh-TW',
      source: 'istəksiz',
      ipa: '',
      example: '',
      definition: '',
      translation: '不情願的',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'z6YnG',
    created: 1736965775041,
    data: {
      language: 'zh-TW',
      source: 'önəmli',
      ipa: '',
      example: '',
      definition: '',
      translation: 'önəmli',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
