import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'xaA8k',
    created: 1736964515463,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: 'чесний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'gdZs4',
    created: 1736964516837,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: 'еластичність',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'oYu4r',
    created: 1736964517698,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: 'критична точка',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VI6xL',
    created: 1736964519292,
    data: {
      language: 'zh',
      source: '处置',
      ipa: 'chǔzhì',
      example: '处置不当',
      definition: '治理、安置',
      translation: 'управління, розміщення',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Tlmcy',
    created: 1736964520034,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: 'відгук',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'PLI2E',
    created: 1736964522812,
    data: {
      language: 'zh',
      source: '结果',
      ipa: 'jiéguǒ',
      example: '不好的结果',
      definition: '植物长出果实；指事物最后的结局或归宿',
      translation: 'результат',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'lmooI',
    created: 1736964524134,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: 'визнати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'EKbUG',
    created: 1736964525554,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: 'kǎolǜ',
      example: '考虑问题',
      definition: '仔细思索',
      translation: 'розглядати, обмірковувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'DiMhW',
    created: 1736964526635,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: 'жертва',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FgMc_',
    created: 1736964528547,
    data: {
      language: 'zh',
      source: '证明',
      ipa: 'zhèngmíng',
      example: '充分证明',
      definition: '用证据或事实来表明真相，使人相信',
      translation: 'доводити',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '4k-yj',
    created: 1736964529956,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: 'ігнорувати',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ai0mh',
    created: 1736964531772,
    data: {
      language: 'zh',
      source: '说服',
      ipa: 'shuìfú',
      example: '说服别人',
      definition: '以言词游说，使人采纳',
      translation: 'переконання',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Ndpah',
    created: 1736964533278,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: 'поступово',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '0w-zb',
    created: 1736964534775,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: 'скрізь',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'AhY4y',
    created: 1736964536257,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: 'yóuqí',
      example: '他喜欢图画，尤其喜欢国画。',
      definition: '特别的、更加',
      translation: 'особливо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cPqi2',
    created: 1736964537713,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: 'вчасно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'yMkdv',
    created: 1736964538991,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приблизно',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'rqaTF',
    created: 1736964540585,
    data: {
      language: 'zh',
      source: '足够',
      ipa: 'zúgòu',
      example: '足够勇敢',
      definition: '充足不缺',
      translation: 'достатньо',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'pRtEq',
    created: 1736964543636,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: 'упертий, настійний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'i2_rU',
    created: 1736964545094,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: 'jiànzhèng',
      example: '见证人',
      definition: '当场目睹而可以作证',
      translation: 'стажування',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'zteYE',
    created: 1736964546098,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: 'приємний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3hXrJ',
    created: 1736964546964,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: 'обережність',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'eBced',
    created: 1736964549097,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: 'нерівний',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_i0LL',
    created: 1736964550429,
    data: {
      language: 'zh',
      source: '重要',
      ipa: 'zhòngyào',
      example: '重要问题',
      definition: '重大而且要紧',
      translation: 'важливий',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
