import { CardItem } from '@vocably/model';

export const predefinedMultiChoiceOptions: CardItem[] = [
  {
    id: 'LrjYt',
    created: 1736963664920,
    data: {
      language: 'zh',
      source: '正直',
      ipa: 'zhèngzhí',
      example: '正直的人',
      definition: '公正坦率',
      translation: '正直',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'Hrb-u',
    created: 1736963666196,
    data: {
      language: 'zh',
      source: '弹力',
      ipa: 'tánlì',
      example: '弹力球',
      definition: '物体受外力压迫后，回复原状的力量',
      translation: '彈力',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'TEaQo',
    created: 1736963667047,
    data: {
      language: 'zh',
      source: '临界点',
      ipa: '',
      example: '',
      definition: '',
      translation: '臨界點',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'qYVmw',
    created: 1736963668377,
    data: {
      language: 'zh',
      source: '处置',
      ipa: 'chǔzhì',
      example: '处置不当',
      definition: '治理、安置',
      translation: '處置, 治理',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'mZRAh',
    created: 1736963669310,
    data: {
      language: 'zh',
      source: '反响',
      ipa: '',
      example: '',
      definition: '',
      translation: '反響',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '78Txx',
    created: 1736963670568,
    data: {
      language: 'zh',
      source: '结果',
      ipa: 'jiéguǒ',
      example: '不好的结果',
      definition: '植物长出果实；指事物最后的结局或归宿',
      translation: '結果',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'S5qUo',
    created: 1736963672025,
    data: {
      language: 'zh',
      source: '承认',
      ipa: 'chéngrèn',
      example: '承认错误',
      definition: '对某件事表示认可或不隐瞒',
      translation: '承認',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'cfa5g',
    created: 1736963673448,
    data: {
      language: 'zh',
      source: '考虑',
      ipa: 'kǎolǜ',
      example: '考虑问题',
      definition: '仔细思索',
      translation: '考慮',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'BeaPQ',
    created: 1736963674200,
    data: {
      language: 'zh',
      source: '奉献',
      ipa: '',
      example: '',
      definition: '',
      translation: '奉獻',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'W8LUP',
    created: 1736963675637,
    data: {
      language: 'zh',
      source: '合法',
      ipa: 'héfǎ',
      example: '合法利益',
      definition: '符合法律规定',
      translation: '合法',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '3TBiv',
    created: 1736963676845,
    data: {
      language: 'zh',
      source: '忽视',
      ipa: 'hūshì',
      example: '忽视他人的意见',
      definition: '不注意、不重视',
      translation: '忽視',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'M7g__',
    created: 1736963678478,
    data: {
      language: 'zh',
      source: '说服',
      ipa: 'shuìfú',
      example: '说服别人',
      definition: '以言词游说，使人采纳',
      translation: '說服',
      partOfSpeech: 'noun',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'VY_hJ',
    created: 1736963680576,
    data: {
      language: 'zh',
      source: '逐步',
      ipa: 'zhúbù',
      example: '逐步深入',
      definition: '依照先后次序，一一挨着',
      translation: '逐步',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '_vZhI',
    created: 1736963682206,
    data: {
      language: 'zh',
      source: '遍地',
      ipa: 'biàndì',
      example: '黄花遍地',
      definition: '到处',
      translation: '遍地',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'aQKVh',
    created: 1736963683687,
    data: {
      language: 'zh',
      source: '尤其',
      ipa: 'yóuqí',
      example: '他喜欢图画，尤其喜欢国画。',
      definition: '特别的、更加',
      translation: '尤其',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'J9vIq',
    created: 1736963685201,
    data: {
      language: 'zh',
      source: '及时',
      ipa: 'jíshí',
      example: '及时到来',
      definition: '正好赶上、适合需要',
      translation: '及時',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'FfBh2',
    created: 1736963685944,
    data: {
      language: 'zh',
      source: '大致',
      ipa: '',
      example: '',
      definition: '',
      translation: '大致',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'IcGEP',
    created: 1736963687412,
    data: {
      language: 'zh',
      source: '足',
      ipa: 'zú',
      example: '不足为奇',
      definition: '* 充足、足够\n* 足以（多用于否定式）',
      translation: '足夠, 足以',
      partOfSpeech: 'adverb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '8OkNQ',
    created: 1736963689477,
    data: {
      language: 'zh',
      source: '执着',
      ipa: 'zhízhuó',
      example: '性情执着',
      definition: '指固执或拘泥，也指坚持不懈',
      translation: '執著',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'ONsuo',
    created: 1736963691121,
    data: {
      language: 'zh',
      source: '正式聘用前的实习阶段',
      ipa: 'jiànzhèng',
      example: '见证人',
      definition: '当场目睹而可以作证',
      translation: '實習階段',
      partOfSpeech: 'verb',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'r8oYt',
    created: 1736963691954,
    data: {
      language: 'zh',
      source: '愉快',
      ipa: '',
      example: '',
      definition: '',
      translation: '愉快',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: '-Zqx-',
    created: 1736963692867,
    data: {
      language: 'zh',
      source: '谨慎',
      ipa: '',
      example: '',
      definition: '',
      translation: '謹慎',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'xt8OK',
    created: 1736963694758,
    data: {
      language: 'zh',
      source: '不等',
      ipa: 'bùděng',
      example: '价格不等',
      definition: '不一样、不相等',
      translation: '不等',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
  {
    id: 'K73b4',
    created: 1736963696591,
    data: {
      language: 'zh',
      source: '重要',
      ipa: 'zhòngyào',
      example: '重要问题',
      definition: '重大而且要紧',
      translation: '重要',
      partOfSpeech: 'adjective',
      tags: [],
      interval: 0,
      repetition: 0,
      eFactor: 2.5,
      dueDate: 1736899200000,
    },
  },
];
