# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(
      readonly: true,
      app_identifier: [
        "pro.vocably.app",
        "pro.vocably.app.Vocably-for-Safari",
        "pro.vocably.app.VocablyProShare"
      ]
    )
  end

  desc 'Fetch code signing secrets. Build the iOS application.'
  lane :build do
    certificates
    increment_version_number(
      version_number: File.read("../../VERSION")
    )

    increment_build_number(
      xcodeproj: "VocablyPro.xcodeproj",
    )

    gym(
      export_method: ENV["FASTFILE_GYM_EXPORT_METHOD"]
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    # Using default env variable names for fastlane to pick them up.
    app_store_connect_api_key(
      is_key_content_base64: true,
    )
    pilot
  end
end
