import { ChatGPTLanguage } from '@vocably/model';
import { isObject, isString } from 'lodash-es';

export type AiTranslation = {
  fixedSource: string;
  translation: string;
  partOfSpeech: string;
};

export const isAiTranslation = (value: any): value is AiTranslation => {
  return (
    isObject(value) &&
    isString(value['fixedSource']) &&
    isString(value['translation']) &&
    isString(value['partOfSpeech'])
  );
};

export const resultExamples: Record<
  ChatGPTLanguage,
  Record<ChatGPTLanguage, AiTranslation>
> = {
  en: {
    en: {
      fixedSource: 'table',
      translation: 'table',
      partOfSpeech: 'noun',
    },
    es: { fixedSource: 'table', translation: 'mesa', partOfSpeech: 'noun' },
    fr: {
      fixedSource: 'table',
      translation: 'tableau',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'table',
      translation: 'tisch',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'table', translation: '桌子', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'table',
      translation: '桌子',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'table',
      translation: 'テーブル',
      partOfSpeech: 'noun',
    },
    ru: { fixedSource: 'table', translation: 'стол', partOfSpeech: 'noun' },
    it: {
      fixedSource: 'table',
      translation: 'tavolo',
      partOfSpeech: 'noun',
    },
    pt: { fixedSource: 'table', translation: 'mesa', partOfSpeech: 'noun' },
    ar: {
      fixedSource: 'table',
      translation: 'طاولة',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'table',
      translation: 'tafel',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'table',
      translation: '테이블',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'table', translation: 'मेज़', partOfSpeech: 'noun' },
    tr: { fixedSource: 'table', translation: 'masa', partOfSpeech: 'noun' },
    sv: {
      fixedSource: 'table',
      translation: 'tabell',
      partOfSpeech: 'noun',
    },
    no: { fixedSource: 'table', translation: 'bord', partOfSpeech: 'noun' },
    da: {
      fixedSource: 'table',
      translation: 'tabel',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'table',
      translation: 'taulukko',
      partOfSpeech: 'noun',
    },
    fa: { fixedSource: 'table', translation: 'جدول', partOfSpeech: 'noun' },
    pl: {
      fixedSource: 'table',
      translation: 'tabela',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'table',
      translation: 'τραπέζι',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'table',
      translation: 'לוּחַ',
      partOfSpeech: 'noun',
    },
    th: { fixedSource: 'table', translation: 'โต๊ะ', partOfSpeech: 'noun' },
    vi: { fixedSource: 'table', translation: 'bàn', partOfSpeech: 'noun' },
    id: { fixedSource: 'table', translation: 'meja', partOfSpeech: 'noun' },
    ms: { fixedSource: 'table', translation: 'meja', partOfSpeech: 'noun' },
    uk: { fixedSource: 'table', translation: 'стіл', partOfSpeech: 'noun' },
  },
  es: {
    en: {
      fixedSource: 'corazón',
      translation: 'heart',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'corazón',
      translation: 'corazón',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'corazón',
      translation: 'cœur',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'corazón',
      translation: 'herz',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'corazón', translation: '心', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'corazón',
      translation: '心',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'corazón',
      translation: '心臓',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'corazón',
      translation: 'сердце',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'corazón',
      translation: 'cuore',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'corazón',
      translation: 'coração',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'corazón',
      translation: 'قلب',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'corazón',
      translation: 'hart',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'corazón',
      translation: '마음',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'corazón',
      translation: 'दिल',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'corazón',
      translation: 'kalp',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'corazón',
      translation: 'hjärta',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'corazón',
      translation: 'hjerte',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'corazón',
      translation: 'hjerte',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'corazón',
      translation: 'sydän',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'corazón',
      translation: 'قلب',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'corazón',
      translation: 'serce',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'corazón',
      translation: 'καρδιά',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'corazón',
      translation: 'לֵב',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'corazón',
      translation: 'หัวใจ',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'corazón',
      translation: 'trái tim',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'corazón',
      translation: 'jantung',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'corazón',
      translation: 'hati',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'corazón',
      translation: 'серце',
      partOfSpeech: 'noun',
    },
  },
  fr: {
    en: {
      fixedSource: 'légume',
      translation: 'vegetable',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'légume',
      translation: 'verdura',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'légume',
      translation: 'légume',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'légume',
      translation: 'gemüse',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'légume',
      translation: '蔬菜',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'légume',
      translation: '蔬菜',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'légume',
      translation: '野菜',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'légume',
      translation: 'овощной',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'légume',
      translation: 'vegetale',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'légume',
      translation: 'vegetal',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'légume',
      translation: 'نباتي',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'légume',
      translation: 'groente',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'légume',
      translation: '채소',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'légume',
      translation: 'सब्ज़ी',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'légume',
      translation: 'sebze',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'légume',
      translation: 'vegetabilisk',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'légume',
      translation: 'grønnsak',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'légume',
      translation: 'grøntsag',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'légume',
      translation: 'kasvis',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'légume',
      translation: 'سبزی',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'légume',
      translation: 'warzywo',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'légume',
      translation: 'λαχανικό',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'légume',
      translation: 'יֶרֶק',
      partOfSpeech: 'noun',
    },
    th: { fixedSource: 'légume', translation: 'ผัก', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'légume',
      translation: 'rau quả',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'légume',
      translation: 'sayuran',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'légume',
      translation: 'sayur',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'légume',
      translation: 'рослинний',
      partOfSpeech: 'noun',
    },
  },
  de: {
    en: { fixedSource: 'füße', translation: 'feet', partOfSpeech: 'noun' },
    es: { fixedSource: 'füße', translation: 'pies', partOfSpeech: 'noun' },
    fr: { fixedSource: 'füße', translation: 'pieds', partOfSpeech: 'noun' },
    de: { fixedSource: 'füße', translation: 'füße', partOfSpeech: 'noun' },
    zh: { fixedSource: 'füße', translation: '脚', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'füße',
      translation: '腳',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'füße', translation: '足', partOfSpeech: 'noun' },
    ru: { fixedSource: 'füße', translation: 'ноги', partOfSpeech: 'noun' },
    it: { fixedSource: 'füße', translation: 'piedi', partOfSpeech: 'noun' },
    pt: { fixedSource: 'füße', translation: 'pés', partOfSpeech: 'noun' },
    ar: { fixedSource: 'füße', translation: 'قدم', partOfSpeech: 'noun' },
    nl: {
      fixedSource: 'füße',
      translation: 'voeten',
      partOfSpeech: 'noun',
    },
    ko: { fixedSource: 'füße', translation: '피트', partOfSpeech: 'noun' },
    hi: { fixedSource: 'füße', translation: 'पैर', partOfSpeech: 'noun' },
    tr: { fixedSource: 'füße', translation: 'ayak', partOfSpeech: 'noun' },
    sv: {
      fixedSource: 'füße',
      translation: 'fötter',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'füße',
      translation: 'føtter',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'füße',
      translation: 'fødder',
      partOfSpeech: 'noun',
    },
    fi: { fixedSource: 'füße', translation: 'jalat', partOfSpeech: 'noun' },
    fa: { fixedSource: 'füße', translation: 'پا', partOfSpeech: 'noun' },
    pl: { fixedSource: 'füße', translation: 'stopy', partOfSpeech: 'noun' },
    el: { fixedSource: 'füße', translation: 'πόδια', partOfSpeech: 'noun' },
    he: {
      fixedSource: 'füße',
      translation: 'רגליים',
      partOfSpeech: 'noun',
    },
    th: { fixedSource: 'füße', translation: 'เท้า', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'füße',
      translation: 'bàn chân',
      partOfSpeech: 'noun',
    },
    id: { fixedSource: 'füße', translation: 'kaki', partOfSpeech: 'noun' },
    ms: { fixedSource: 'füße', translation: 'kaki', partOfSpeech: 'noun' },
    uk: { fixedSource: 'füße', translation: 'ноги', partOfSpeech: 'noun' },
  },
  zh: {
    en: { fixedSource: '书', translation: 'book', partOfSpeech: 'noun' },
    es: { fixedSource: '书', translation: 'libro', partOfSpeech: 'noun' },
    fr: { fixedSource: '书', translation: 'livre', partOfSpeech: 'noun' },
    de: { fixedSource: '书', translation: 'buch', partOfSpeech: 'noun' },
    zh: { fixedSource: '书', translation: '书', partOfSpeech: 'noun' },
    'zh-TW': { fixedSource: '书', translation: '書', partOfSpeech: 'noun' },
    ja: { fixedSource: '书', translation: '本', partOfSpeech: 'noun' },
    ru: { fixedSource: '书', translation: 'книга', partOfSpeech: 'noun' },
    it: { fixedSource: '书', translation: 'libro', partOfSpeech: 'noun' },
    pt: { fixedSource: '书', translation: 'livro', partOfSpeech: 'noun' },
    ar: { fixedSource: '书', translation: 'كتاب', partOfSpeech: 'noun' },
    nl: { fixedSource: '书', translation: 'boek', partOfSpeech: 'noun' },
    ko: { fixedSource: '书', translation: '책', partOfSpeech: 'noun' },
    hi: { fixedSource: '书', translation: 'किताब', partOfSpeech: 'noun' },
    tr: { fixedSource: '书', translation: 'kitap', partOfSpeech: 'noun' },
    sv: { fixedSource: '书', translation: 'boka', partOfSpeech: 'noun' },
    no: { fixedSource: '书', translation: 'bok', partOfSpeech: 'noun' },
    da: { fixedSource: '书', translation: 'bog', partOfSpeech: 'noun' },
    fi: { fixedSource: '书', translation: 'kirja', partOfSpeech: 'noun' },
    fa: { fixedSource: '书', translation: 'کتاب', partOfSpeech: 'noun' },
    pl: { fixedSource: '书', translation: 'książka', partOfSpeech: 'noun' },
    el: { fixedSource: '书', translation: 'βιβλίο', partOfSpeech: 'noun' },
    he: { fixedSource: '书', translation: 'סֵפֶר', partOfSpeech: 'noun' },
    th: { fixedSource: '书', translation: 'หนังสือ', partOfSpeech: 'noun' },
    vi: { fixedSource: '书', translation: 'sách', partOfSpeech: 'noun' },
    id: { fixedSource: '书', translation: 'buku', partOfSpeech: 'noun' },
    ms: { fixedSource: '书', translation: 'buku', partOfSpeech: 'noun' },
    uk: { fixedSource: '书', translation: 'книга', partOfSpeech: 'noun' },
  },
  'zh-TW': {
    en: {
      fixedSource: '燈籠',
      translation: 'lantern',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: '燈籠',
      translation: 'linterna',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: '燈籠',
      translation: 'lanterne',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: '燈籠',
      translation: 'laterne',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: '燈籠', translation: '灯笼', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: '燈籠',
      translation: '燈籠',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: '燈籠',
      translation: 'ランタン',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: '燈籠',
      translation: 'фонарь',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: '燈籠',
      translation: 'lanterna',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: '燈籠',
      translation: 'lanterna',
      partOfSpeech: 'noun',
    },
    ar: { fixedSource: '燈籠', translation: 'فانوس', partOfSpeech: 'noun' },
    nl: {
      fixedSource: '燈籠',
      translation: 'lantaarn',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: '燈籠',
      translation: '칸델라',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: '燈籠',
      translation: 'लालटेन',
      partOfSpeech: 'noun',
    },
    tr: { fixedSource: '燈籠', translation: 'fener', partOfSpeech: 'noun' },
    sv: { fixedSource: '燈籠', translation: 'lykta', partOfSpeech: 'noun' },
    no: {
      fixedSource: '燈籠',
      translation: 'lanterne',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: '燈籠',
      translation: 'lanterne',
      partOfSpeech: 'noun',
    },
    fi: { fixedSource: '燈籠', translation: 'lyhty', partOfSpeech: 'noun' },
    fa: { fixedSource: '燈籠', translation: 'فانوس', partOfSpeech: 'noun' },
    pl: {
      fixedSource: '燈籠',
      translation: 'latarnia',
      partOfSpeech: 'noun',
    },
    el: { fixedSource: '燈籠', translation: 'φανός', partOfSpeech: 'noun' },
    he: {
      fixedSource: '燈籠',
      translation: 'פָּנָס',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: '燈籠',
      translation: 'ตะเกียง',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: '燈籠',
      translation: 'đèn lồng',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: '燈籠',
      translation: 'lentera',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: '燈籠',
      translation: 'tanglung',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: '燈籠',
      translation: 'ліхтар',
      partOfSpeech: 'noun',
    },
  },
  ja: {
    en: {
      fixedSource: 'お箸',
      translation: 'chopsticks',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'お箸',
      translation: 'palillos',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'お箸',
      translation: 'baguettes',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'お箸',
      translation: 'essstäbchen',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'お箸', translation: '筷子', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'お箸',
      translation: '筷子',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'お箸', translation: 'お箸', partOfSpeech: 'noun' },
    ru: {
      fixedSource: 'お箸',
      translation: 'палочки для еды',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'お箸',
      translation: 'bacchette',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'お箸',
      translation: 'pauzinhos',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'お箸',
      translation: 'عيدان تناول الطعام',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'お箸',
      translation: 'eetstokjes',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'お箸',
      translation: '젓가락',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'お箸',
      translation: 'चीनी काँटा',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'お箸',
      translation: 'yemek çubukları',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'お箸',
      translation: 'ätpinnar',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'お箸',
      translation: 'spisepinner',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'お箸',
      translation: 'spisepinde',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'お箸',
      translation: 'syömäpuikot',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'お箸',
      translation: 'چاپستیک ها',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'お箸',
      translation: 'pałeczki do jedzenia',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'お箸',
      translation: 'ξυλάκια',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'お箸',
      translation: 'מַקלוֹת אֲכִילָה',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'お箸',
      translation: 'ตะเกียบ',
      partOfSpeech: 'noun',
    },
    vi: { fixedSource: 'お箸', translation: 'đũa', partOfSpeech: 'noun' },
    id: {
      fixedSource: 'お箸',
      translation: 'sumpit',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'お箸',
      translation: 'penyepit',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'お箸',
      translation: 'палички для їжі',
      partOfSpeech: 'noun',
    },
  },
  ru: {
    en: {
      fixedSource: 'ёж',
      translation: 'hedgehog',
      partOfSpeech: 'noun',
    },
    es: { fixedSource: 'ёж', translation: 'erizo', partOfSpeech: 'noun' },
    fr: {
      fixedSource: 'ёж',
      translation: 'hérisson',
      partOfSpeech: 'noun',
    },
    de: { fixedSource: 'ёж', translation: 'igel', partOfSpeech: 'noun' },
    zh: { fixedSource: 'ёж', translation: '刺猬', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'ёж',
      translation: '刺蝟',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'ёж',
      translation: 'ハリネズミ',
      partOfSpeech: 'noun',
    },
    ru: { fixedSource: 'ёж', translation: 'ёж', partOfSpeech: 'noun' },
    it: { fixedSource: 'ёж', translation: 'riccio', partOfSpeech: 'noun' },
    pt: { fixedSource: 'ёж', translation: 'ouriço', partOfSpeech: 'noun' },
    ar: { fixedSource: 'ёж', translation: 'القنفذ', partOfSpeech: 'noun' },
    nl: { fixedSource: 'ёж', translation: 'egel', partOfSpeech: 'noun' },
    ko: {
      fixedSource: 'ёж',
      translation: '고슴도치',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'ёж', translation: 'हाथी', partOfSpeech: 'noun' },
    tr: { fixedSource: 'ёж', translation: 'kirpi', partOfSpeech: 'noun' },
    sv: {
      fixedSource: 'ёж',
      translation: 'igelkott',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'ёж',
      translation: 'pinnsvin',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'ёж',
      translation: 'pindsvin',
      partOfSpeech: 'noun',
    },
    fi: { fixedSource: 'ёж', translation: 'siili', partOfSpeech: 'noun' },
    fa: {
      fixedSource: 'ёж',
      translation: 'جوجه تیغی',
      partOfSpeech: 'noun',
    },
    pl: { fixedSource: 'ёж', translation: 'jeż', partOfSpeech: 'noun' },
    el: {
      fixedSource: 'ёж',
      translation: 'σκατζόχοιρος',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'ёж', translation: 'קִפּוֹד', partOfSpeech: 'noun' },
    th: { fixedSource: 'ёж', translation: 'เม่น', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'ёж',
      translation: 'con nhím',
      partOfSpeech: 'noun',
    },
    id: { fixedSource: 'ёж', translation: 'landak', partOfSpeech: 'noun' },
    ms: { fixedSource: 'ёж', translation: 'landak', partOfSpeech: 'noun' },
    uk: { fixedSource: 'ёж', translation: 'їжак', partOfSpeech: 'noun' },
  },
  it: {
    en: { fixedSource: 'città', translation: 'city', partOfSpeech: 'noun' },
    es: {
      fixedSource: 'città',
      translation: 'ciudad',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'città',
      translation: 'ville',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'città',
      translation: 'stadt',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'città', translation: '城市', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'città',
      translation: '城市',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'città', translation: '市', partOfSpeech: 'noun' },
    ru: {
      fixedSource: 'città',
      translation: 'город',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'città',
      translation: 'città',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'città',
      translation: 'cidade',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'città',
      translation: 'مدينة',
      partOfSpeech: 'noun',
    },
    nl: { fixedSource: 'città', translation: 'stad', partOfSpeech: 'noun' },
    ko: { fixedSource: 'città', translation: '도시', partOfSpeech: 'noun' },
    hi: { fixedSource: 'città', translation: 'शहर', partOfSpeech: 'noun' },
    tr: {
      fixedSource: 'città',
      translation: 'şehir',
      partOfSpeech: 'noun',
    },
    sv: { fixedSource: 'città', translation: 'stad', partOfSpeech: 'noun' },
    no: { fixedSource: 'città', translation: 'by', partOfSpeech: 'noun' },
    da: { fixedSource: 'città', translation: 'by', partOfSpeech: 'noun' },
    fi: {
      fixedSource: 'città',
      translation: 'kaupunki',
      partOfSpeech: 'noun',
    },
    fa: { fixedSource: 'città', translation: 'شهر', partOfSpeech: 'noun' },
    pl: {
      fixedSource: 'città',
      translation: 'miasto',
      partOfSpeech: 'noun',
    },
    el: { fixedSource: 'città', translation: 'πόλη', partOfSpeech: 'noun' },
    he: { fixedSource: 'città', translation: 'עִיר', partOfSpeech: 'noun' },
    th: {
      fixedSource: 'città',
      translation: 'เมือง',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'città',
      translation: 'thành phố',
      partOfSpeech: 'noun',
    },
    id: { fixedSource: 'città', translation: 'kota', partOfSpeech: 'noun' },
    ms: {
      fixedSource: 'città',
      translation: 'bandar',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'città',
      translation: 'місто',
      partOfSpeech: 'noun',
    },
  },
  pt: {
    en: {
      fixedSource: 'óculos',
      translation: 'glasses',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'óculos',
      translation: 'anteojos',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'óculos',
      translation: 'lunettes',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'óculos',
      translation: 'gläser',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'óculos',
      translation: '眼镜',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'óculos',
      translation: '眼鏡',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'óculos',
      translation: '眼鏡',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'óculos',
      translation: 'очки',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'óculos',
      translation: 'occhiali',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'óculos',
      translation: 'óculos',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'óculos',
      translation: 'نظارات',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'óculos',
      translation: 'bril',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'óculos',
      translation: '안경',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'óculos',
      translation: 'चश्मा',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'óculos',
      translation: 'gözlük',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'óculos',
      translation: 'glasögon',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'óculos',
      translation: 'briller',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'óculos',
      translation: 'briller',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'óculos',
      translation: 'lasit',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'óculos',
      translation: 'عینک',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'óculos',
      translation: 'okulary',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'óculos',
      translation: 'γυαλιά',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'óculos',
      translation: 'מִשׁקָפַיִם',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'óculos',
      translation: 'แว่นตา',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'óculos',
      translation: 'kính',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'óculos',
      translation: 'kacamata',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'óculos',
      translation: 'cermin mata',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'óculos',
      translation: 'окуляри',
      partOfSpeech: 'noun',
    },
  },
  ar: {
    en: {
      fixedSource: 'مَكتَبَة',
      translation: 'library',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'مَكتَبَة',
      translation: 'biblioteca',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'مَكتَبَة',
      translation: 'bibliothèque',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'مَكتَبَة',
      translation: 'bibliothek',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'مَكتَبَة',
      translation: '图书馆',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'مَكتَبَة',
      translation: '圖書館',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'مَكتَبَة',
      translation: '図書館',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'مَكتَبَة',
      translation: 'библиотека',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'مَكتَبَة',
      translation: 'biblioteca',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'مَكتَبَة',
      translation: 'biblioteca',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'مَكتَبَة',
      translation: 'مَكتَبَة',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'مَكتَبَة',
      translation: 'bibliotheek',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'مَكتَبَة',
      translation: '도서관',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'مَكتَبَة',
      translation: 'पुस्तकालय',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'مَكتَبَة',
      translation: 'kütüphane',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'مَكتَبَة',
      translation: 'bibliotek',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'مَكتَبَة',
      translation: 'bibliotek',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'مَكتَبَة',
      translation: 'bibliotek',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'مَكتَبَة',
      translation: 'kirjasto',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'مَكتَبَة',
      translation: 'کتابخانه',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'مَكتَبَة',
      translation: 'biblioteka',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'مَكتَبَة',
      translation: 'βιβλιοθήκη',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'مَكتَبَة',
      translation: 'סִפְרִיָה',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'مَكتَبَة',
      translation: 'ห้องสมุด',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'مَكتَبَة',
      translation: 'thư viện',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'مَكتَبَة',
      translation: 'perpustakaan',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'مَكتَبَة',
      translation: 'perpustakaan',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'مَكتَبَة',
      translation: 'бібліотека',
      partOfSpeech: 'noun',
    },
  },
  nl: {
    en: {
      fixedSource: 'inspanning',
      translation: 'effort',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'inspanning',
      translation: 'esfuerzo',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'inspanning',
      translation: 'effort',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'inspanning',
      translation: 'bemühung',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'inspanning',
      translation: '努力',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'inspanning',
      translation: '努力',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'inspanning',
      translation: '努力',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'inspanning',
      translation: 'усилие',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'inspanning',
      translation: 'sforzo',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'inspanning',
      translation: 'esforço',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'inspanning',
      translation: 'جهد',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'inspanning',
      translation: 'inspanning',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'inspanning',
      translation: '노력',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'inspanning',
      translation: 'कोशिश',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'inspanning',
      translation: 'çaba',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'inspanning',
      translation: 'ansträngning',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'inspanning',
      translation: 'anstrengelse',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'inspanning',
      translation: 'forsøg',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'inspanning',
      translation: 'vaivaa',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'inspanning',
      translation: 'تلاش',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'inspanning',
      translation: 'wysiłek',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'inspanning',
      translation: 'προσπάθεια',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'inspanning',
      translation: 'מַאֲמָץ',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'inspanning',
      translation: 'ความพยายาม',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'inspanning',
      translation: 'cố gắng',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'inspanning',
      translation: 'upaya',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'inspanning',
      translation: 'usaha',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'inspanning',
      translation: 'зусилля',
      partOfSpeech: 'noun',
    },
  },
  ko: {
    en: {
      fixedSource: '젓가락',
      translation: 'chopsticks',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: '젓가락',
      translation: 'palillos',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: '젓가락',
      translation: 'baguettes',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: '젓가락',
      translation: 'essstäbchen',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: '젓가락',
      translation: '筷子',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: '젓가락',
      translation: '筷子',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: '젓가락', translation: '箸', partOfSpeech: 'noun' },
    ru: {
      fixedSource: '젓가락',
      translation: 'палочки для еды',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: '젓가락',
      translation: 'bacchette',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: '젓가락',
      translation: 'pauzinhos',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: '젓가락',
      translation: 'عيدان تناول الطعام',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: '젓가락',
      translation: 'eetstokjes',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: '젓가락',
      translation: '젓가락',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: '젓가락',
      translation: 'चीनी काँटा',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: '젓가락',
      translation: 'yemek çubukları',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: '젓가락',
      translation: 'ätpinnar',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: '젓가락',
      translation: 'spisepinner',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: '젓가락',
      translation: 'spisepinde',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: '젓가락',
      translation: 'syömäpuikot',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: '젓가락',
      translation: 'چاپستیک ها',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: '젓가락',
      translation: 'pałeczki do jedzenia',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: '젓가락',
      translation: 'ξυλάκια',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: '젓가락',
      translation: 'מַקלוֹת אֲכִילָה',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: '젓가락',
      translation: 'ตะเกียบ',
      partOfSpeech: 'noun',
    },
    vi: { fixedSource: '젓가락', translation: 'đũa', partOfSpeech: 'noun' },
    id: {
      fixedSource: '젓가락',
      translation: 'sumpit',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: '젓가락',
      translation: 'penyepit',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: '젓가락',
      translation: 'палички для їжі',
      partOfSpeech: 'noun',
    },
  },
  hi: {
    en: { fixedSource: 'क़लम', translation: 'pen', partOfSpeech: 'noun' },
    es: {
      fixedSource: 'क़लम',
      translation: 'bolígrafo',
      partOfSpeech: 'noun',
    },
    fr: { fixedSource: 'क़लम', translation: 'stylo', partOfSpeech: 'noun' },
    de: { fixedSource: 'क़लम', translation: 'stift', partOfSpeech: 'noun' },
    zh: { fixedSource: 'क़लम', translation: '笔', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'क़लम',
      translation: '筆',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'क़लम', translation: 'ペン', partOfSpeech: 'noun' },
    ru: { fixedSource: 'क़लम', translation: 'ручка', partOfSpeech: 'noun' },
    it: { fixedSource: 'क़लम', translation: 'penna', partOfSpeech: 'noun' },
    pt: {
      fixedSource: 'क़लम',
      translation: 'caneta',
      partOfSpeech: 'noun',
    },
    ar: { fixedSource: 'क़लम', translation: 'قلم', partOfSpeech: 'noun' },
    nl: { fixedSource: 'क़लम', translation: 'pen', partOfSpeech: 'noun' },
    ko: { fixedSource: 'क़लम', translation: '펜', partOfSpeech: 'noun' },
    hi: { fixedSource: 'क़लम', translation: 'क़लम', partOfSpeech: 'noun' },
    tr: {
      fixedSource: 'क़लम',
      translation: 'dolma kalem',
      partOfSpeech: 'noun',
    },
    sv: { fixedSource: 'क़लम', translation: 'penna', partOfSpeech: 'noun' },
    no: { fixedSource: 'क़लम', translation: 'penn', partOfSpeech: 'noun' },
    da: { fixedSource: 'क़लम', translation: 'pen', partOfSpeech: 'noun' },
    fi: { fixedSource: 'क़लम', translation: 'kynä', partOfSpeech: 'noun' },
    fa: { fixedSource: 'क़लम', translation: 'قلم', partOfSpeech: 'noun' },
    pl: { fixedSource: 'क़लम', translation: 'pióro', partOfSpeech: 'noun' },
    el: { fixedSource: 'क़लम', translation: 'στυλό', partOfSpeech: 'noun' },
    he: { fixedSource: 'क़लम', translation: 'עֵט', partOfSpeech: 'noun' },
    th: { fixedSource: 'क़लम', translation: 'ปากกา', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'क़लम',
      translation: 'cái bút',
      partOfSpeech: 'noun',
    },
    id: { fixedSource: 'क़लम', translation: 'pena', partOfSpeech: 'noun' },
    ms: { fixedSource: 'क़लम', translation: 'pen', partOfSpeech: 'noun' },
    uk: { fixedSource: 'क़लम', translation: 'перо', partOfSpeech: 'noun' },
  },
  tr: {
    en: {
      fixedSource: 'çalışkan',
      translation: 'hard working',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'çalışkan',
      translation: 'trabajo duro',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'çalışkan',
      translation: 'travailler dur',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'çalışkan',
      translation: 'hart arbeiten',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'çalışkan',
      translation: '任劳任怨',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'çalışkan',
      translation: '任勞任怨',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'çalışkan',
      translation: '勤勉な',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'çalışkan',
      translation: 'трудолюбивый',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'çalışkan',
      translation: 'laborioso',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'çalışkan',
      translation: 'trabalha duro',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'çalışkan',
      translation: 'العمل الجاد',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'çalışkan',
      translation: 'hard werken',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'çalışkan',
      translation: '열심히 일하는',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'çalışkan',
      translation: 'मेहनती',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'çalışkan',
      translation: 'çalışkan',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'çalışkan',
      translation: 'hårt arbetande',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'çalışkan',
      translation: 'hardt arbeid',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'çalışkan',
      translation: 'hårdtarbejdende',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'çalışkan',
      translation: 'kovaa työtä',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'çalışkan',
      translation: 'سخت کار کردن',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'çalışkan',
      translation: 'ciężko pracujący',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'çalışkan',
      translation: 'εργατικός',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'çalışkan',
      translation: 'עבודה קשה',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'çalışkan',
      translation: 'ทำงานหนัก',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'çalışkan',
      translation: 'làm việc chăm chỉ',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'çalışkan',
      translation: 'kerja keras',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'çalışkan',
      translation: 'bekerja keras',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'çalışkan',
      translation: 'працьовитий',
      partOfSpeech: 'noun',
    },
  },
  sv: {
    en: {
      fixedSource: 'fjäder',
      translation: 'spring',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'fjäder',
      translation: 'primavera',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'fjäder',
      translation: 'printemps',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'fjäder',
      translation: 'frühling',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'fjäder',
      translation: '春天',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'fjäder',
      translation: '春天',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'fjäder', translation: '春', partOfSpeech: 'noun' },
    ru: {
      fixedSource: 'fjäder',
      translation: 'весна',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'fjäder',
      translation: 'primavera',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'fjäder',
      translation: 'primavera',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'fjäder',
      translation: 'ربيع',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'fjäder',
      translation: 'lente',
      partOfSpeech: 'noun',
    },
    ko: { fixedSource: 'fjäder', translation: '봄', partOfSpeech: 'noun' },
    hi: {
      fixedSource: 'fjäder',
      translation: 'वसंत',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'fjäder',
      translation: 'bahar',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'fjäder',
      translation: 'fjäder',
      partOfSpeech: 'noun',
    },
    no: { fixedSource: 'fjäder', translation: 'vår', partOfSpeech: 'noun' },
    da: {
      fixedSource: 'fjäder',
      translation: 'forår',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'fjäder',
      translation: 'kevät',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'fjäder',
      translation: 'بهار',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'fjäder',
      translation: 'wiosna',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'fjäder',
      translation: 'άνοιξη',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'fjäder',
      translation: 'אָבִיב',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'fjäder',
      translation: 'ฤดูใบไม้ผลิ',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'fjäder',
      translation: 'mùa xuân',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'fjäder',
      translation: 'musim semi',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'fjäder',
      translation: 'musim bunga',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'fjäder',
      translation: 'весна',
      partOfSpeech: 'noun',
    },
  },
  no: {
    en: { fixedSource: 'fjøs', translation: 'barn', partOfSpeech: 'noun' },
    es: {
      fixedSource: 'fjøs',
      translation: 'granero',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'fjøs',
      translation: 'grange',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'fjøs',
      translation: 'scheune',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'fjøs', translation: '谷仓', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'fjøs',
      translation: '穀倉',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'fjøs', translation: '納屋', partOfSpeech: 'noun' },
    ru: { fixedSource: 'fjøs', translation: 'сарай', partOfSpeech: 'noun' },
    it: {
      fixedSource: 'fjøs',
      translation: 'fienile',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'fjøs',
      translation: 'celeiro',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'fjøs',
      translation: 'الحظيرة',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'fjøs',
      translation: 'schuur',
      partOfSpeech: 'noun',
    },
    ko: { fixedSource: 'fjøs', translation: '헛간', partOfSpeech: 'noun' },
    hi: {
      fixedSource: 'fjøs',
      translation: 'खलिहान',
      partOfSpeech: 'noun',
    },
    tr: { fixedSource: 'fjøs', translation: 'ahır', partOfSpeech: 'noun' },
    sv: { fixedSource: 'fjøs', translation: 'barn', partOfSpeech: 'noun' },
    no: { fixedSource: 'fjøs', translation: 'fjøs', partOfSpeech: 'noun' },
    da: { fixedSource: 'fjøs', translation: 'lade', partOfSpeech: 'noun' },
    fi: {
      fixedSource: 'fjøs',
      translation: 'navetta',
      partOfSpeech: 'noun',
    },
    fa: { fixedSource: 'fjøs', translation: 'انبار', partOfSpeech: 'noun' },
    pl: {
      fixedSource: 'fjøs',
      translation: 'stodoła',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'fjøs',
      translation: 'σιταποθήκη',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'fjøs', translation: 'אֹסֶם', partOfSpeech: 'noun' },
    th: { fixedSource: 'fjøs', translation: 'โรงนา', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'fjøs',
      translation: 'chuồng trại',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'fjøs',
      translation: 'lumbung',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'fjøs',
      translation: 'bangsal',
      partOfSpeech: 'noun',
    },
    uk: { fixedSource: 'fjøs', translation: 'сарай', partOfSpeech: 'noun' },
  },
  da: {
    en: { fixedSource: 'sø', translation: 'lake', partOfSpeech: 'noun' },
    es: { fixedSource: 'sø', translation: 'lago', partOfSpeech: 'noun' },
    fr: { fixedSource: 'sø', translation: 'lac', partOfSpeech: 'noun' },
    de: { fixedSource: 'sø', translation: 'see', partOfSpeech: 'noun' },
    zh: { fixedSource: 'sø', translation: '湖', partOfSpeech: 'noun' },
    'zh-TW': { fixedSource: 'sø', translation: '湖', partOfSpeech: 'noun' },
    ja: { fixedSource: 'sø', translation: '湖', partOfSpeech: 'noun' },
    ru: { fixedSource: 'sø', translation: 'озеро', partOfSpeech: 'noun' },
    it: { fixedSource: 'sø', translation: 'lago', partOfSpeech: 'noun' },
    pt: { fixedSource: 'sø', translation: 'lago', partOfSpeech: 'noun' },
    ar: { fixedSource: 'sø', translation: 'بحيرة', partOfSpeech: 'noun' },
    nl: { fixedSource: 'sø', translation: 'meer', partOfSpeech: 'noun' },
    ko: { fixedSource: 'sø', translation: '호수', partOfSpeech: 'noun' },
    hi: { fixedSource: 'sø', translation: 'झील', partOfSpeech: 'noun' },
    tr: { fixedSource: 'sø', translation: 'göl', partOfSpeech: 'noun' },
    sv: { fixedSource: 'sø', translation: 'sjö', partOfSpeech: 'noun' },
    no: { fixedSource: 'sø', translation: 'innsjø', partOfSpeech: 'noun' },
    da: { fixedSource: 'sø', translation: 'sø', partOfSpeech: 'noun' },
    fi: { fixedSource: 'sø', translation: 'järvi', partOfSpeech: 'noun' },
    fa: { fixedSource: 'sø', translation: 'دریاچه', partOfSpeech: 'noun' },
    pl: { fixedSource: 'sø', translation: 'jezioro', partOfSpeech: 'noun' },
    el: { fixedSource: 'sø', translation: 'λίμνη', partOfSpeech: 'noun' },
    he: { fixedSource: 'sø', translation: 'אֲגַם', partOfSpeech: 'noun' },
    th: { fixedSource: 'sø', translation: 'ทะเลสาบ', partOfSpeech: 'noun' },
    vi: { fixedSource: 'sø', translation: 'hồ', partOfSpeech: 'noun' },
    id: { fixedSource: 'sø', translation: 'danau', partOfSpeech: 'noun' },
    ms: { fixedSource: 'sø', translation: 'tasik', partOfSpeech: 'noun' },
    uk: { fixedSource: 'sø', translation: 'озеро', partOfSpeech: 'noun' },
  },
  fi: {
    en: {
      fixedSource: 'käärme',
      translation: 'snake',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'käärme',
      translation: 'serpiente',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'käärme',
      translation: 'serpent',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'käärme',
      translation: 'schlange',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'käärme', translation: '蛇', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'käärme',
      translation: '蛇',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'käärme', translation: '蛇', partOfSpeech: 'noun' },
    ru: {
      fixedSource: 'käärme',
      translation: 'змея',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'käärme',
      translation: 'serpente',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'käärme',
      translation: 'cobra',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'käärme',
      translation: 'ثعبان',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'käärme',
      translation: 'slang',
      partOfSpeech: 'noun',
    },
    ko: { fixedSource: 'käärme', translation: '뱀', partOfSpeech: 'noun' },
    hi: {
      fixedSource: 'käärme',
      translation: 'साँप',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'käärme',
      translation: 'yılan',
      partOfSpeech: 'noun',
    },
    sv: { fixedSource: 'käärme', translation: 'orm', partOfSpeech: 'noun' },
    no: {
      fixedSource: 'käärme',
      translation: 'slange',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'käärme',
      translation: 'slange',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'käärme',
      translation: 'käärme',
      partOfSpeech: 'noun',
    },
    fa: { fixedSource: 'käärme', translation: 'مار', partOfSpeech: 'noun' },
    pl: { fixedSource: 'käärme', translation: 'wąż', partOfSpeech: 'noun' },
    el: {
      fixedSource: 'käärme',
      translation: 'φίδι',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'käärme',
      translation: 'נָחָשׁ',
      partOfSpeech: 'noun',
    },
    th: { fixedSource: 'käärme', translation: 'งู', partOfSpeech: 'noun' },
    vi: { fixedSource: 'käärme', translation: 'rắn', partOfSpeech: 'noun' },
    id: {
      fixedSource: 'käärme',
      translation: 'ular',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'käärme',
      translation: 'ular',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'käärme',
      translation: 'змія',
      partOfSpeech: 'noun',
    },
  },
  fa: {
    en: {
      fixedSource: 'ساختمان',
      translation: 'building',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'ساختمان',
      translation: 'edificio',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'ساختمان',
      translation: 'bâtiment',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'ساختمان',
      translation: 'gebäude',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'ساختمان',
      translation: '建筑',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'ساختمان',
      translation: '大樓',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'ساختمان',
      translation: '建物',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'ساختمان',
      translation: 'здание',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'ساختمان',
      translation: 'edificio',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'ساختمان',
      translation: 'prédio',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'ساختمان',
      translation: 'مبنى',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'ساختمان',
      translation: 'gebouw',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'ساختمان',
      translation: '건물',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'ساختمان',
      translation: 'इमारत',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'ساختمان',
      translation: 'bina',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'ساختمان',
      translation: 'byggnad',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'ساختمان',
      translation: 'bygning',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'ساختمان',
      translation: 'bygning',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'ساختمان',
      translation: 'rakentaminen',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'ساختمان',
      translation: 'ساختمان',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'ساختمان',
      translation: 'budynek',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'ساختمان',
      translation: 'κτίριο',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'ساختمان',
      translation: 'בִּניָן',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'ساختمان',
      translation: 'อาคาร',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'ساختمان',
      translation: 'xây dựng',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'ساختمان',
      translation: 'bangunan',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'ساختمان',
      translation: 'bangunan',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'ساختمان',
      translation: 'будівля',
      partOfSpeech: 'noun',
    },
  },
  pl: {
    en: {
      fixedSource: 'żółw',
      translation: 'turtle',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'żółw',
      translation: 'tortuga',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'żółw',
      translation: 'tortue',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'żółw',
      translation: 'schildkröte',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'żółw', translation: '龟', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'żółw',
      translation: '龜',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'żółw', translation: 'カメ', partOfSpeech: 'noun' },
    ru: {
      fixedSource: 'żółw',
      translation: 'черепаха',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'żółw',
      translation: 'tartaruga',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'żółw',
      translation: 'tartaruga',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'żółw',
      translation: 'سلحفاة',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'żółw',
      translation: 'schildpad',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'żółw',
      translation: '거북이',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'żółw', translation: 'कछुआ', partOfSpeech: 'noun' },
    tr: {
      fixedSource: 'żółw',
      translation: 'kaplumbağa',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'żółw',
      translation: 'sköldpadda',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'żółw',
      translation: 'skilpadde',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'żółw',
      translation: 'skildpadde',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'żółw',
      translation: 'kilpikonna',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'żółw',
      translation: 'لاک پشت',
      partOfSpeech: 'noun',
    },
    pl: { fixedSource: 'żółw', translation: 'żółw', partOfSpeech: 'noun' },
    el: {
      fixedSource: 'żółw',
      translation: 'χελώνα',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'żółw', translation: 'צָב', partOfSpeech: 'noun' },
    th: { fixedSource: 'żółw', translation: 'เต่า', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'żółw',
      translation: 'con rùa',
      partOfSpeech: 'noun',
    },
    id: { fixedSource: 'żółw', translation: 'penyu', partOfSpeech: 'noun' },
    ms: { fixedSource: 'żółw', translation: 'penyu', partOfSpeech: 'noun' },
    uk: {
      fixedSource: 'żółw',
      translation: 'черепаха',
      partOfSpeech: 'noun',
    },
  },
  el: {
    en: {
      fixedSource: 'καρδιά',
      translation: 'heart',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'καρδιά',
      translation: 'corazón',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'καρδιά',
      translation: 'cœur',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'καρδιά',
      translation: 'herz',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'καρδιά', translation: '心', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'καρδιά',
      translation: '心',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'καρδιά',
      translation: '心臓',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'καρδιά',
      translation: 'сердце',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'καρδιά',
      translation: 'cuore',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'καρδιά',
      translation: 'coração',
      partOfSpeech: 'noun',
    },
    ar: { fixedSource: 'καρδιά', translation: 'قلب', partOfSpeech: 'noun' },
    nl: {
      fixedSource: 'καρδιά',
      translation: 'hart',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'καρδιά',
      translation: '마음',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'καρδιά', translation: 'दिल', partOfSpeech: 'noun' },
    tr: {
      fixedSource: 'καρδιά',
      translation: 'kalp',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'καρδιά',
      translation: 'hjärta',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'καρδιά',
      translation: 'hjerte',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'καρδιά',
      translation: 'hjerte',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'καρδιά',
      translation: 'sydän',
      partOfSpeech: 'noun',
    },
    fa: { fixedSource: 'καρδιά', translation: 'قلب', partOfSpeech: 'noun' },
    pl: {
      fixedSource: 'καρδιά',
      translation: 'serce',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'καρδιά',
      translation: 'καρδιά',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'καρδιά', translation: 'לֵב', partOfSpeech: 'noun' },
    th: {
      fixedSource: 'καρδιά',
      translation: 'หัวใจ',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'καρδιά',
      translation: 'trái tim',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'καρδιά',
      translation: 'jantung',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'καρδιά',
      translation: 'hati',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'καρδιά',
      translation: 'серце',
      partOfSpeech: 'noun',
    },
  },
  he: {
    en: {
      fixedSource: 'שָׁלוֹם',
      translation: 'peace',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'שָׁלוֹם',
      translation: 'paz',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'שָׁלוֹם',
      translation: 'paix',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'שָׁלוֹם',
      translation: 'frieden',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'שָׁלוֹם',
      translation: '和平',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'שָׁלוֹם',
      translation: '和平',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'שָׁלוֹם',
      translation: '平和',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'שָׁלוֹם',
      translation: 'мир',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'שָׁלוֹם',
      translation: 'pace',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'שָׁלוֹם',
      translation: 'paz',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'שָׁלוֹם',
      translation: 'سلام',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'שָׁלוֹם',
      translation: 'vrede',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'שָׁלוֹם',
      translation: '평화',
      partOfSpeech: 'noun',
    },
    hi: {
      fixedSource: 'שָׁלוֹם',
      translation: 'शांति',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'שָׁלוֹם',
      translation: 'barış',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'שָׁלוֹם',
      translation: 'fred',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'שָׁלוֹם',
      translation: 'fred',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'שָׁלוֹם',
      translation: 'fred',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'שָׁלוֹם',
      translation: 'rauhaa',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'שָׁלוֹם',
      translation: 'صلح',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'שָׁלוֹם',
      translation: 'pokój',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'שָׁלוֹם',
      translation: 'ειρήνη',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'שָׁלוֹם',
      translation: 'שָׁלוֹם',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'שָׁלוֹם',
      translation: 'ความสงบ',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'שָׁלוֹם',
      translation: 'hòa bình',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'שָׁלוֹם',
      translation: 'perdamaian',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'שָׁלוֹם',
      translation: 'kedamaian',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'שָׁלוֹם',
      translation: 'спокій',
      partOfSpeech: 'noun',
    },
  },
  th: {
    en: {
      fixedSource: 'ช้าง',
      translation: 'elephant',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'ช้าง',
      translation: 'elefante',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'ช้าง',
      translation: 'éléphant',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'ช้าง',
      translation: 'elefant',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'ช้าง', translation: '大象', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'ช้าง',
      translation: '大象',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'ช้าง', translation: '象', partOfSpeech: 'noun' },
    ru: { fixedSource: 'ช้าง', translation: 'слон', partOfSpeech: 'noun' },
    it: {
      fixedSource: 'ช้าง',
      translation: 'elefante',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'ช้าง',
      translation: 'elefante',
      partOfSpeech: 'noun',
    },
    ar: { fixedSource: 'ช้าง', translation: 'فيل', partOfSpeech: 'noun' },
    nl: {
      fixedSource: 'ช้าง',
      translation: 'olifant',
      partOfSpeech: 'noun',
    },
    ko: {
      fixedSource: 'ช้าง',
      translation: '코끼리',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'ช้าง', translation: 'हाथी', partOfSpeech: 'noun' },
    tr: { fixedSource: 'ช้าง', translation: 'fil', partOfSpeech: 'noun' },
    sv: {
      fixedSource: 'ช้าง',
      translation: 'elefant',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'ช้าง',
      translation: 'elefant',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'ช้าง',
      translation: 'elefant',
      partOfSpeech: 'noun',
    },
    fi: { fixedSource: 'ช้าง', translation: 'norsu', partOfSpeech: 'noun' },
    fa: { fixedSource: 'ช้าง', translation: 'فیل', partOfSpeech: 'noun' },
    pl: { fixedSource: 'ช้าง', translation: 'słoń', partOfSpeech: 'noun' },
    el: {
      fixedSource: 'ช้าง',
      translation: 'ελέφαντας',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'ช้าง', translation: 'פִּיל', partOfSpeech: 'noun' },
    th: { fixedSource: 'ช้าง', translation: 'ช้าง', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'ช้าง',
      translation: 'con voi',
      partOfSpeech: 'noun',
    },
    id: { fixedSource: 'ช้าง', translation: 'gajah', partOfSpeech: 'noun' },
    ms: { fixedSource: 'ช้าง', translation: 'gajah', partOfSpeech: 'noun' },
    uk: { fixedSource: 'ช้าง', translation: 'слон', partOfSpeech: 'noun' },
  },
  vi: {
    en: {
      fixedSource: 'bánh mì',
      translation: 'bread',
      partOfSpeech: 'noun',
    },
    es: {
      fixedSource: 'bánh mì',
      translation: 'pan',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'bánh mì',
      translation: 'pain',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'bánh mì',
      translation: 'brot',
      partOfSpeech: 'noun',
    },
    zh: {
      fixedSource: 'bánh mì',
      translation: '面包',
      partOfSpeech: 'noun',
    },
    'zh-TW': {
      fixedSource: 'bánh mì',
      translation: '麵包',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'bánh mì',
      translation: 'パン',
      partOfSpeech: 'noun',
    },
    ru: {
      fixedSource: 'bánh mì',
      translation: 'хлеб',
      partOfSpeech: 'noun',
    },
    it: {
      fixedSource: 'bánh mì',
      translation: 'pane',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'bánh mì',
      translation: 'pão',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'bánh mì',
      translation: 'خبز',
      partOfSpeech: 'noun',
    },
    nl: {
      fixedSource: 'bánh mì',
      translation: 'brood',
      partOfSpeech: 'noun',
    },
    ko: { fixedSource: 'bánh mì', translation: '빵', partOfSpeech: 'noun' },
    hi: {
      fixedSource: 'bánh mì',
      translation: 'रोटी',
      partOfSpeech: 'noun',
    },
    tr: {
      fixedSource: 'bánh mì',
      translation: 'ekmek',
      partOfSpeech: 'noun',
    },
    sv: {
      fixedSource: 'bánh mì',
      translation: 'bröd',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'bánh mì',
      translation: 'brød',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'bánh mì',
      translation: 'brød',
      partOfSpeech: 'noun',
    },
    fi: {
      fixedSource: 'bánh mì',
      translation: 'leipää',
      partOfSpeech: 'noun',
    },
    fa: {
      fixedSource: 'bánh mì',
      translation: 'نان',
      partOfSpeech: 'noun',
    },
    pl: {
      fixedSource: 'bánh mì',
      translation: 'chleb',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'bánh mì',
      translation: 'ψωμί',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'bánh mì',
      translation: 'לֶחֶם',
      partOfSpeech: 'noun',
    },
    th: {
      fixedSource: 'bánh mì',
      translation: 'ขนมปัง',
      partOfSpeech: 'noun',
    },
    vi: {
      fixedSource: 'bánh mì',
      translation: 'bánh mì',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'bánh mì',
      translation: 'roti',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'bánh mì',
      translation: 'roti',
      partOfSpeech: 'noun',
    },
    uk: {
      fixedSource: 'bánh mì',
      translation: 'хліб',
      partOfSpeech: 'noun',
    },
  },
  id: {
    en: { fixedSource: 'meja', translation: 'table', partOfSpeech: 'noun' },
    es: { fixedSource: 'meja', translation: 'mesa', partOfSpeech: 'noun' },
    fr: {
      fixedSource: 'meja',
      translation: 'tableau',
      partOfSpeech: 'noun',
    },
    de: { fixedSource: 'meja', translation: 'tisch', partOfSpeech: 'noun' },
    zh: { fixedSource: 'meja', translation: '桌子', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'meja',
      translation: '桌子',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'meja',
      translation: 'テーブル',
      partOfSpeech: 'noun',
    },
    ru: { fixedSource: 'meja', translation: 'стол', partOfSpeech: 'noun' },
    it: {
      fixedSource: 'meja',
      translation: 'tavolo',
      partOfSpeech: 'noun',
    },
    pt: { fixedSource: 'meja', translation: 'mesa', partOfSpeech: 'noun' },
    ar: { fixedSource: 'meja', translation: 'طاولة', partOfSpeech: 'noun' },
    nl: { fixedSource: 'meja', translation: 'tafel', partOfSpeech: 'noun' },
    ko: {
      fixedSource: 'meja',
      translation: '테이블',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'meja', translation: 'मेज़', partOfSpeech: 'noun' },
    tr: { fixedSource: 'meja', translation: 'masa', partOfSpeech: 'noun' },
    sv: {
      fixedSource: 'meja',
      translation: 'tabell',
      partOfSpeech: 'noun',
    },
    no: { fixedSource: 'meja', translation: 'bord', partOfSpeech: 'noun' },
    da: { fixedSource: 'meja', translation: 'tabel', partOfSpeech: 'noun' },
    fi: {
      fixedSource: 'meja',
      translation: 'taulukko',
      partOfSpeech: 'noun',
    },
    fa: { fixedSource: 'meja', translation: 'جدول', partOfSpeech: 'noun' },
    pl: {
      fixedSource: 'meja',
      translation: 'tabela',
      partOfSpeech: 'noun',
    },
    el: {
      fixedSource: 'meja',
      translation: 'τραπέζι',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'meja', translation: 'לוּחַ', partOfSpeech: 'noun' },
    th: { fixedSource: 'meja', translation: 'โต๊ะ', partOfSpeech: 'noun' },
    vi: { fixedSource: 'meja', translation: 'bàn', partOfSpeech: 'noun' },
    id: { fixedSource: 'meja', translation: 'meja', partOfSpeech: 'noun' },
    ms: { fixedSource: 'meja', translation: 'meja', partOfSpeech: 'noun' },
    uk: { fixedSource: 'meja', translation: 'стіл', partOfSpeech: 'noun' },
  },
  ms: {
    en: { fixedSource: 'laut', translation: 'sea', partOfSpeech: 'noun' },
    es: {
      fixedSource: 'laut',
      translation: 'el mar',
      partOfSpeech: 'noun',
    },
    fr: {
      fixedSource: 'laut',
      translation: 'la mer',
      partOfSpeech: 'noun',
    },
    de: {
      fixedSource: 'laut',
      translation: 'das meer',
      partOfSpeech: 'noun',
    },
    zh: { fixedSource: 'laut', translation: '海', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'laut',
      translation: '海',
      partOfSpeech: 'noun',
    },
    ja: { fixedSource: 'laut', translation: '海', partOfSpeech: 'noun' },
    ru: { fixedSource: 'laut', translation: 'море', partOfSpeech: 'noun' },
    it: {
      fixedSource: 'laut',
      translation: 'il mare',
      partOfSpeech: 'noun',
    },
    pt: { fixedSource: 'laut', translation: 'o mar', partOfSpeech: 'noun' },
    ar: { fixedSource: 'laut', translation: 'البحر', partOfSpeech: 'noun' },
    nl: {
      fixedSource: 'laut',
      translation: 'de zee',
      partOfSpeech: 'noun',
    },
    ko: { fixedSource: 'laut', translation: '바다', partOfSpeech: 'noun' },
    hi: { fixedSource: 'laut', translation: 'ये ए', partOfSpeech: 'noun' },
    tr: { fixedSource: 'laut', translation: 'deniz', partOfSpeech: 'noun' },
    sv: { fixedSource: 'laut', translation: 'havet', partOfSpeech: 'noun' },
    no: { fixedSource: 'laut', translation: 'havet', partOfSpeech: 'noun' },
    da: { fixedSource: 'laut', translation: 'havet', partOfSpeech: 'noun' },
    fi: { fixedSource: 'laut', translation: 'meri', partOfSpeech: 'noun' },
    fa: { fixedSource: 'laut', translation: 'دریا', partOfSpeech: 'noun' },
    pl: { fixedSource: 'laut', translation: 'morze', partOfSpeech: 'noun' },
    el: {
      fixedSource: 'laut',
      translation: 'η θάλασσα',
      partOfSpeech: 'noun',
    },
    he: { fixedSource: 'laut', translation: 'הים', partOfSpeech: 'noun' },
    th: { fixedSource: 'laut', translation: 'ทะเล', partOfSpeech: 'noun' },
    vi: { fixedSource: 'laut', translation: 'biển', partOfSpeech: 'noun' },
    id: { fixedSource: 'laut', translation: 'laut', partOfSpeech: 'noun' },
    ms: { fixedSource: 'laut', translation: 'laut', partOfSpeech: 'noun' },
    uk: { fixedSource: 'laut', translation: 'море', partOfSpeech: 'noun' },
  },
  uk: {
    en: {
      fixedSource: 'їжак',
      translation: 'hedgehog',
      partOfSpeech: 'noun',
    },
    es: { fixedSource: 'їжак', translation: 'erizo', partOfSpeech: 'noun' },
    fr: {
      fixedSource: 'їжак',
      translation: 'hérisson',
      partOfSpeech: 'noun',
    },
    de: { fixedSource: 'їжак', translation: 'igel', partOfSpeech: 'noun' },
    zh: { fixedSource: 'їжак', translation: '刺猬', partOfSpeech: 'noun' },
    'zh-TW': {
      fixedSource: 'їжак',
      translation: '刺蝟',
      partOfSpeech: 'noun',
    },
    ja: {
      fixedSource: 'їжак',
      translation: 'ハリネズミ',
      partOfSpeech: 'noun',
    },
    ru: { fixedSource: 'їжак', translation: 'еж', partOfSpeech: 'noun' },
    it: {
      fixedSource: 'їжак',
      translation: 'riccio',
      partOfSpeech: 'noun',
    },
    pt: {
      fixedSource: 'їжак',
      translation: 'ouriço',
      partOfSpeech: 'noun',
    },
    ar: {
      fixedSource: 'їжак',
      translation: 'القنفذ',
      partOfSpeech: 'noun',
    },
    nl: { fixedSource: 'їжак', translation: 'egel', partOfSpeech: 'noun' },
    ko: {
      fixedSource: 'їжак',
      translation: '고슴도치',
      partOfSpeech: 'noun',
    },
    hi: { fixedSource: 'їжак', translation: 'हाथी', partOfSpeech: 'noun' },
    tr: { fixedSource: 'їжак', translation: 'kirpi', partOfSpeech: 'noun' },
    sv: {
      fixedSource: 'їжак',
      translation: 'igelkott',
      partOfSpeech: 'noun',
    },
    no: {
      fixedSource: 'їжак',
      translation: 'pinnsvin',
      partOfSpeech: 'noun',
    },
    da: {
      fixedSource: 'їжак',
      translation: 'pindsvin',
      partOfSpeech: 'noun',
    },
    fi: { fixedSource: 'їжак', translation: 'siili', partOfSpeech: 'noun' },
    fa: {
      fixedSource: 'їжак',
      translation: 'جوجه تیغی',
      partOfSpeech: 'noun',
    },
    pl: { fixedSource: 'їжак', translation: 'jeż', partOfSpeech: 'noun' },
    el: {
      fixedSource: 'їжак',
      translation: 'σκατζόχοιρος',
      partOfSpeech: 'noun',
    },
    he: {
      fixedSource: 'їжак',
      translation: 'קִפּוֹד',
      partOfSpeech: 'noun',
    },
    th: { fixedSource: 'їжак', translation: 'เม่น', partOfSpeech: 'noun' },
    vi: {
      fixedSource: 'їжак',
      translation: 'con nhím',
      partOfSpeech: 'noun',
    },
    id: {
      fixedSource: 'їжак',
      translation: 'landak',
      partOfSpeech: 'noun',
    },
    ms: {
      fixedSource: 'їжак',
      translation: 'landak',
      partOfSpeech: 'noun',
    },
    uk: { fixedSource: 'їжак', translation: 'їжак', partOfSpeech: 'noun' },
  },
};
