export const Errors = [
  'AS_IS_TRANSLATION_REQUEST_EXCEPTION',
  'AS_IS_TRANSLATION_UNABLE_TO_TRANSLATE',
  'TRANSLATION_REQUEST_MISSING_PHRASE',
  'TRANSLATION_REQUEST_UNAVAILABLE_REQUESTED_LANGUAGE',
  'TRANSLATION_REQUEST_UNAVAILABLE_DETECTED_LANGUAGE',
  'CARD_COLLECTION_UPDATE_MISSING_CARD',
  'CARDS_SAVE_ERROR',
  'CARDS_LOAD_ERROR',
  'LEXICALA_UNSUCCESSFUL_FETCH',
  'LEXICALA_UNCAUGHT_ERROR',
  'HTTP_REQUEST_NOT_OK',
  'HTTP_REQUEST_UNCAUGHT',
] as const;

export type VocablyErrorCode = typeof Errors[number];
